function oi_apply_color_scale(axesHandle, colorbarHandle, colorMap, colorLimits, theme, missingColor)
%OI_APPLY_COLOR_SCALE Apply one validated axes-specific publication scale.
% Input contract: colorMap is a finite real N-by-3 RGB map with N >= 2;
% colorLimits is a finite increasing pair; optional missingColor is one RGB
% triplet. The colorbar and its label are styled from the explicit theme.
arguments
    axesHandle (1,1) matlab.graphics.axis.Axes
    colorbarHandle (1,1)
    colorMap (:,3) double
    colorLimits (1,2) double
    theme (1,1) struct
    missingColor double = []
end
assert(isgraphics(colorbarHandle) && isprop(colorbarHandle, "Label"), ...
    "oi_apply_color_scale:InvalidColorbar", ...
    "colorbarHandle must be a live MATLAB colorbar");
assert(size(colorMap, 1) >= 2 && isreal(colorMap) ...
    && all(isfinite(colorMap), "all") ...
    && all(colorMap >= 0, "all") && all(colorMap <= 1, "all"), ...
    "oi_apply_color_scale:InvalidColormap", ...
    "colorMap must contain at least two finite real RGB rows in [0,1]");
assert(isreal(colorLimits) && all(isfinite(colorLimits)) ...
    && colorLimits(1) < colorLimits(2), ...
    "oi_apply_color_scale:InvalidLimits", ...
    "colorLimits must be a finite real increasing pair");
assert(isempty(missingColor) || (isreal(missingColor) ...
    && isequal(size(missingColor), [1 3]) ...
    && all(isfinite(missingColor)) ...
    && all(missingColor >= 0) && all(missingColor <= 1)), ...
    "oi_apply_color_scale:InvalidMissingColor", ...
    "missingColor must be empty or one finite real RGB triplet in [0,1]");
requiredThemeFields = ["FontName" "FontSize" "LabelSize" "TextColor"];
assert(all(isfield(theme, cellstr(requiredThemeFields))), ...
    "oi_apply_color_scale:InvalidTheme", ...
    "theme must define FontName, FontSize, LabelSize, and TextColor");
fontName = oi_require_text(theme.FontName, ...
    "oi_apply_color_scale:InvalidTheme", "theme.FontName must be nonblank text");
assert(isnumeric(theme.FontSize) && isreal(theme.FontSize) ...
    && isscalar(theme.FontSize) && isfinite(theme.FontSize) && theme.FontSize > 0 ...
    && isnumeric(theme.LabelSize) && isreal(theme.LabelSize) ...
    && isscalar(theme.LabelSize) && isfinite(theme.LabelSize) && theme.LabelSize > 0 ...
    && isnumeric(theme.TextColor) && isreal(theme.TextColor) ...
    && isequal(size(theme.TextColor), [1 3]) ...
    && all(isfinite(theme.TextColor)) && all(theme.TextColor >= 0) ...
    && all(theme.TextColor <= 1), ...
    "oi_apply_color_scale:InvalidTheme", ...
    "theme sizes and TextColor must be finite publication values");
if ~isempty(missingColor)
    axesHandle.Color = missingColor;
end
colormap(axesHandle, colorMap);
if exist("clim", "file") == 2 || exist("clim", "builtin") == 5
    clim(axesHandle, colorLimits);
else
    caxis(axesHandle, colorLimits);
end
colorbarHandle.FontName = fontName;
colorbarHandle.FontSize = theme.FontSize;
colorbarHandle.Color = theme.TextColor;
if isprop(colorbarHandle, "TickLabelInterpreter")
    colorbarHandle.TickLabelInterpreter = "none";
end
colorbarHandle.Label.FontName = fontName;
colorbarHandle.Label.FontSize = theme.LabelSize;
colorbarHandle.Label.Color = theme.TextColor;
colorbarHandle.Label.Interpreter = "none";
setappdata(axesHandle, "OI_ColorScale", struct("limits", colorLimits, ...
    "missing_color", missingColor, "colormap_rows", size(colorMap, 1)));
end
