function figureHandle = oi_figure(widthPixels, heightPixels, visible)
%OI_FIGURE Create a deterministic MATLAB-native export figure.
% Input contract: widthPixels and heightPixels are positive finite pixel
% dimensions. visible is "on" or "off". No current-figure state is used.
arguments
    widthPixels (1,1) double {mustBeInteger,mustBePositive} = 1200
    heightPixels (1,1) double {mustBeInteger,mustBePositive} = 675
    visible (1,1) string {mustBeMember(visible,["on","off"])} = "off"
end
theme = oi_ocean_theme();
figureHandle = figure("Visible", visible, "Color", theme.CanvasColor, ...
    "Units", "pixels", "Position", [80 80 widthPixels heightPixels], ...
    "InvertHardcopy", "off", "PaperPositionMode", "auto");
set(figureHandle, "DefaultAxesColorOrder", theme.LineColors, ...
    "DefaultAxesLineStyleOrder", cellstr(theme.LineStyles), ...
    "DefaultAxesFontName", theme.FontName, ...
    "DefaultAxesFontSize", theme.FontSize, ...
    "DefaultTextFontName", theme.FontName, ...
    "DefaultTextFontSize", theme.FontSize, ...
    "DefaultTextFontUnits", "points", ...
    "DefaultTextInterpreter", "none", ...
    "DefaultLegendInterpreter", "none");
setappdata(figureHandle, "OI_OceanTheme", theme);
setappdata(figureHandle, "OI_RequestedPixelSize", [widthPixels heightPixels]);
end
