function result = oi_plot_vector_field(axesHandle, xValues, yValues, uComponent, vComponent, options)
%OI_PLOT_VECTOR_FIELD Plot paired horizontal vector components.
% Input contract: xValues and yValues are finite strictly increasing
% rectilinear coordinates. uComponent and vComponent are y-by-x, share one
% unit and identical finite/NaN masks. NaN vectors are omitted, never replaced
% by zero, and components are never rotated without a documented transform.
arguments
    axesHandle (1,1) matlab.graphics.axis.Axes
    xValues (1,:) double
    yValues (:,1) double
    uComponent (:,:) double
    vComponent (:,:) double
    options (1,1) struct = struct()
end
assert(numel(xValues) >= 2 && all(isfinite(xValues)) && all(diff(xValues) > 0), ...
    "oi_plot_vector_field:XCoordinate", "xValues must be finite and strictly increasing");
assert(numel(yValues) >= 2 && all(isfinite(yValues)) && all(diff(yValues) > 0), ...
    "oi_plot_vector_field:YCoordinate", "yValues must be finite and strictly increasing");
assert(isequal(size(uComponent),[numel(yValues) numel(xValues)]) ...
    && isequal(size(vComponent),size(uComponent)), ...
    "oi_plot_vector_field:SizeMismatch", "Vector components must be y-by-x");
assert(isreal(uComponent) && isreal(vComponent) ...
    && ~any(isinf(uComponent),"all") && ~any(isinf(vComponent),"all"), ...
    "oi_plot_vector_field:InvalidComponents", ...
    "Vector components may contain NaN but not Inf or complex values");
assert(isequal(isfinite(uComponent),isfinite(vComponent)), ...
    "oi_plot_vector_field:MaskMismatch", ...
    "u/v finite masks must match; incomplete vectors cannot be silently zero-filled");
validMask = isfinite(uComponent) & isfinite(vComponent);
assert(any(validMask,"all"), "oi_plot_vector_field:NoValidVectors", ...
    "At least one complete vector is required");
missingPolicy = string(oi_get_option(options, "MissingPolicy", "preserve"));
assert(missingPolicy == "preserve", "oi_plot_vector_field:MissingPolicy", ...
    "Only MissingPolicy='preserve' is supported");
stride = oi_get_option(options, "Stride", 1);
assert(isnumeric(stride) && isreal(stride) && isscalar(stride) ...
    && isfinite(stride) && stride >= 1 && fix(stride) == stride, ...
    "oi_plot_vector_field:Stride", "Stride must be a positive integer");
xUnit = oi_require_text(oi_get_option(options, "XUnit", ""), ...
    "oi_plot_vector_field:Units", "XUnit must be explicit nonblank text");
yUnit = oi_require_text(oi_get_option(options, "YUnit", ""), ...
    "oi_plot_vector_field:Units", "YUnit must be explicit nonblank text");
vectorUnit = oi_require_text(oi_get_option(options, "VectorUnit", ""), ...
    "oi_plot_vector_field:Units", "VectorUnit must be explicit nonblank text");
componentFrame = oi_require_text(oi_get_option(options, "ComponentFrame", ""), ...
    "oi_plot_vector_field:Units", "ComponentFrame must be explicit nonblank text");
xLabel = oi_require_text(oi_get_option(options, "XLabel", ""), ...
    "oi_plot_vector_field:Units", "XLabel must be explicit nonblank text");
yLabel = oi_require_text(oi_get_option(options, "YLabel", ""), ...
    "oi_plot_vector_field:Units", "YLabel must be explicit nonblank text");
assert(all([isscalar(xUnit) isscalar(yUnit) isscalar(vectorUnit) ...
    isscalar(componentFrame) isscalar(xLabel) isscalar(yLabel)]), ...
    "oi_plot_vector_field:Units", ...
    "Coordinate names/units, vector unit, and component frame must be explicit");
referenceMagnitude = oi_get_option(options, "ReferenceMagnitude", NaN);
assert(isnumeric(referenceMagnitude) && isreal(referenceMagnitude) ...
    && isscalar(referenceMagnitude) && (isnan(referenceMagnitude) ...
    || (isfinite(referenceMagnitude) && referenceMagnitude > 0)), ...
    "oi_plot_vector_field:ReferenceMagnitude", ...
    "ReferenceMagnitude must be positive or NaN when explicitly unavailable");
autoScaleFactor = oi_get_option(options, "AutoScaleFactor", 0.9);
assert(isnumeric(autoScaleFactor) && isreal(autoScaleFactor) ...
    && isscalar(autoScaleFactor) && isfinite(autoScaleFactor) ...
    && autoScaleFactor > 0, "oi_plot_vector_field:AutoScaleFactor", ...
    "AutoScaleFactor must be a positive finite scalar");
componentRotationDegrees = oi_get_option(options, "ComponentRotationDegrees", 0);
assert(isnumeric(componentRotationDegrees) && isreal(componentRotationDegrees) ...
    && (isscalar(componentRotationDegrees) ...
    || isequal(size(componentRotationDegrees), size(uComponent))) ...
    && all(isfinite(componentRotationDegrees), "all") ...
    && all(abs(componentRotationDegrees) <= 360, "all"), ...
    "oi_plot_vector_field:ComponentRotation", ...
    "ComponentRotationDegrees must be a finite scalar or y-by-x array within [-360,360]");
if isscalar(componentRotationDegrees)
    componentRotationDegrees = repmat(componentRotationDegrees, size(uComponent));
end
rotationApplied = any(componentRotationDegrees(validMask) ~= 0);
rotationConvention = string(oi_get_option(options, "RotationConvention", ""));
plotComponentFrame = string(oi_get_option(options, "PlotComponentFrame", componentFrame));
if rotationApplied
    assert(isscalar(rotationConvention) ...
        && rotationConvention == "counterclockwise-input-to-plot", ...
        "oi_plot_vector_field:RotationConvention", ...
        "Nonzero component rotation requires RotationConvention='counterclockwise-input-to-plot'");
    plotComponentFrame = oi_require_text(plotComponentFrame, ...
        "oi_plot_vector_field:PlotComponentFrame", ...
        "Nonzero component rotation requires PlotComponentFrame");
    assert(isscalar(plotComponentFrame), ...
        "oi_plot_vector_field:PlotComponentFrame", ...
        "PlotComponentFrame must be scalar text");
else
    assert(isscalar(rotationConvention) && strlength(rotationConvention) == 0, ...
        "oi_plot_vector_field:UnusedRotationMetadata", ...
        "RotationConvention must be omitted when no component rotation is applied");
end
cosRotation = cosd(componentRotationDegrees);
sinRotation = sind(componentRotationDegrees);
plotU = uComponent .* cosRotation - vComponent .* sinRotation;
plotV = uComponent .* sinRotation + vComponent .* cosRotation;
zeroSpeedMask = validMask & uComponent == 0 & vComponent == 0;
rows = 1:stride:numel(yValues);
columns = 1:stride:numel(xValues);
[xGrid,yGrid] = meshgrid(xValues(columns),yValues(rows));
sampleU = plotU(rows,columns);
sampleV = plotV(rows,columns);
theme = oi_get_option(options, "Theme", struct());
if isempty(fieldnames(theme))
    theme = oi_ocean_theme();
end
titleText = oi_require_text(oi_get_option(options, "Title", "Ocean vector field"), ...
    "oi_plot_vector_field:Title", "Title must be explicit nonblank text");
quiverHandle = quiver(axesHandle,xGrid,yGrid,sampleU,sampleV, ...
    "AutoScale","on","AutoScaleFactor",autoScaleFactor, ...
    "Color",theme.NegativeColor,"LineWidth",0.9,"MaxHeadSize",0.8);
xlabel(axesHandle,xLabel + " (" + xUnit + ")", ...
    "Interpreter","none");
ylabel(axesHandle,yLabel + " (" + yUnit + ")", ...
    "Interpreter","none");
title(axesHandle,titleText ...
    + "; " + plotComponentFrame + "; vector unit: " + vectorUnit, ...
    "FontWeight","normal","Interpreter","none");
if isfinite(referenceMagnitude)
    text(axesHandle,0.02,0.03,"Reference magnitude: " + string(referenceMagnitude) ...
        + " " + vectorUnit,"Units","normalized","Interpreter","none", ...
        "VerticalAlignment","bottom","FontName",theme.FontName, ...
        "FontSize",theme.FontSize,"Color",theme.TextColor);
end
oi_apply_axes(axesHandle,theme);
result = struct("Axes",axesHandle,"Quiver",quiverHandle,"ValidMask",validMask, ...
    "MissingCount",sum(~validMask,"all"),"ValidCount",sum(validMask,"all"), ...
    "MissingPolicy",missingPolicy,"Stride",stride,"VectorUnit",vectorUnit, ...
    "ComponentFrame",componentFrame,"ReferenceMagnitude",referenceMagnitude, ...
    "PlotComponentFrame",plotComponentFrame, ...
    "ComponentRotationDegrees",componentRotationDegrees, ...
    "RotationConvention",rotationConvention,"RotationApplied",rotationApplied, ...
    "PlotU",plotU,"PlotV",plotV,"ZeroSpeedMask",zeroSpeedMask, ...
    "ZeroSpeedCount",sum(zeroSpeedMask,"all"), ...
    "Speed",hypot(uComponent,vComponent), "valid_count", ...
    sum(validMask, "all"), "missing_count", sum(~validMask, "all"));
end
