function result = oi_plot_ts_diagram(axesHandle, salinityValues, temperatureValues, colorValues, options)
%OI_PLOT_TS_DIAGRAM Plot validated temperature-salinity relationships.
% Input contract: numeric inputs are aligned vectors; table/timetable input
% uses explicit variable names. NaN, QC rejection, and incomplete uncertainty
% are omitted as complete tuples and counted. Density is always caller-supplied.
arguments
    axesHandle (1,1) matlab.graphics.axis.Axes
    salinityValues
    temperatureValues
    colorValues
    options (1,1) struct = struct()
end

missingPolicy = string(oi_get_option(options,"MissingPolicy","preserve"));
assert(missingPolicy == "preserve","oi_plot_ts_diagram:MissingPolicy", ...
    "Only MissingPolicy='preserve' is supported");
[data,source] = resolve_input(salinityValues,temperatureValues,colorValues,options);
salinity = data.Salinity;
temperature = data.Temperature;
colorData = data.Color;
assert(isnumeric(salinity) && isnumeric(temperature) && isnumeric(colorData) ...
    && isvector(salinity) && isvector(temperature) && isvector(colorData) ...
    && isreal(salinity) && isreal(temperature) && isreal(colorData) ...
    && ~any(isinf(salinity)) && ~any(isinf(temperature)) && ~any(isinf(colorData)), ...
    "oi_plot_ts_diagram:InvalidValues", ...
    "T-S inputs may contain NaN but not Inf or complex values");

salinityLabel = scalar_text(oi_get_option(options,"SalinityLabel","Salinity"), ...
    "oi_plot_ts_diagram:Units","SalinityLabel must be explicit nonblank text");
salinityUnit = scalar_text(oi_get_option(options,"SalinityUnit",""), ...
    "oi_plot_ts_diagram:Units","SalinityUnit must be explicit nonblank text");
temperatureLabel = scalar_text(oi_get_option(options,"TemperatureLabel","Temperature"), ...
    "oi_plot_ts_diagram:Units","TemperatureLabel must be explicit nonblank text");
temperatureUnit = scalar_text(oi_get_option(options,"TemperatureUnit",""), ...
    "oi_plot_ts_diagram:Units","TemperatureUnit must be explicit nonblank text");
colorLabel = scalar_text(oi_get_option(options, "ColorLabel", ""), ...
    "oi_plot_ts_diagram:Units","ColorLabel must be explicit nonblank text");
colorUnit = scalar_text(oi_get_option(options, "ColorUnit", ""), ...
    "oi_plot_ts_diagram:Units","ColorUnit must be explicit nonblank text");
salinityDefinition = scalar_text(oi_get_option(options,"SalinityDefinition",salinityLabel), ...
    "oi_plot_ts_diagram:Definitions","SalinityDefinition must be nonblank text");
temperatureDefinition = scalar_text(oi_get_option(options,"TemperatureDefinition",temperatureLabel), ...
    "oi_plot_ts_diagram:Definitions","TemperatureDefinition must be nonblank text");
referencePressure = string(oi_get_option(options,"ReferencePressure",""));
assert(isscalar(referencePressure) && ~ismissing(referencePressure), ...
    "oi_plot_ts_diagram:Definitions","ReferencePressure must be scalar text when supplied");
assert_ts_units(source,options,salinityUnit,temperatureUnit,colorUnit);

colorLimits = oi_get_option(options,"ColorLimits",[]);
assert(isnumeric(colorLimits) && isreal(colorLimits) && isequal(size(colorLimits),[1 2]) ...
    && all(isfinite(colorLimits)) && colorLimits(1) < colorLimits(2), ...
    "oi_plot_ts_diagram:ColorLimits", ...
    "ColorLimits must be an explicit finite increasing pair");
[qcAcceptedMask,qcProvided] = resolve_qc(source,options,numel(salinity));
finiteTupleMask = isfinite(salinity) & isfinite(temperature) & isfinite(colorData);
uncertainty = resolve_uncertainty(source,options,numel(salinity), ...
    salinityUnit,temperatureUnit,finiteTupleMask);
if uncertainty.Type ~= "none"
    uncertaintyFiniteMask = uncertainty.CompleteMask;
    assert(all(isfinite(salinity(uncertaintyFiniteMask) ...
        - uncertainty.SalinityMagnitude(uncertaintyFiniteMask))) ...
        && all(isfinite(salinity(uncertaintyFiniteMask) ...
        + uncertainty.SalinityMagnitude(uncertaintyFiniteMask))) ...
        && all(isfinite(temperature(uncertaintyFiniteMask) ...
        - uncertainty.TemperatureMagnitude(uncertaintyFiniteMask))) ...
        && all(isfinite(temperature(uncertaintyFiniteMask) ...
        + uncertainty.TemperatureMagnitude(uncertaintyFiniteMask))), ...
        "oi_plot_ts_diagram:UncertaintyValues", ...
        "Finite uncertainty magnitudes must not overflow plotted endpoints");
end
completeMask = finiteTupleMask & qcAcceptedMask & uncertainty.CompleteMask;
assert(any(completeMask),"oi_plot_ts_diagram:NoCompleteSamples", ...
    "At least one complete QC-accepted T-S sample is required");

[density,densityProvided] = resolve_density(options);
sampleLabels = resolve_sample_labels(source,options,numel(salinity));
[confounders,confounderLabel] = resolve_confounder(source,options,numel(salinity));
titleText = scalar_text(oi_get_option(options,"Title","Temperature-salinity diagram"), ...
    "oi_plot_ts_diagram:Title","Title must be explicit nonblank text");
theme = oi_get_option(options,"Theme",struct());
if isempty(fieldnames(theme))
    theme = oi_ocean_theme();
end
colorMap = oi_get_option(options,"Colormap",theme.SequentialMap);

holdCleanup = oi_hold_axes(axesHandle);
if densityProvided
    densityHandle = contour(axesHandle,density.Salinity,density.Temperature,density.Values, ...
        density.Levels,"Color",[0.35 0.35 0.35],"LineWidth",0.7,"ShowText","on", ...
        "HandleVisibility","off");
else
    densityHandle = gobjects(0);
end
uncertaintyHandles = plot_uncertainty(axesHandle,salinity,temperature, ...
    uncertainty,completeMask,theme.GridColor);
[scatterHandles,legendHandles,legendLabels] = plot_groups(axesHandle,salinity,temperature, ...
    colorData,completeMask,confounders,confounderLabel,theme);
clear holdCleanup;

xlabel(axesHandle,salinityLabel + " (" + salinityUnit + ")","Interpreter","none");
ylabel(axesHandle,temperatureLabel + " (" + temperatureUnit + ")","Interpreter","none");
title(axesHandle,titleText,"FontWeight","normal","Interpreter","none");
colorbarHandle = colorbar(axesHandle,"Location","eastoutside");
colorbarHandle.Label.String = colorLabel + " (" + colorUnit + ")";
oi_apply_axes(axesHandle,theme);
oi_apply_color_scale(axesHandle,colorbarHandle,colorMap,colorLimits,theme);
if ~isempty(legendHandles)
    legendHandle = legend(axesHandle,legendHandles,legendLabels,"Location", ...
        string(oi_get_option(options,"LegendLocation","best")),"Interpreter","none");
else
    legendHandle = gobjects(0);
end
configure_data_tips(scatterHandles,salinity(completeMask),temperature(completeMask), ...
    colorData(completeMask),sampleLabels(completeMask),confounders(completeMask), ...
    confounderLabel,salinityLabel,salinityUnit,temperatureLabel,temperatureUnit, ...
    colorLabel,colorUnit);

result = struct("Axes",axesHandle,"Scatter",scatterHandles, ...
    "DensityContours",densityHandle,"UncertaintyGraphics",uncertaintyHandles, ...
    "Colorbar",colorbarHandle,"Legend",legendHandle,"CompleteMask",completeMask, ...
    "FiniteTupleMask",finiteTupleMask,"QCAcceptedMask",qcAcceptedMask, ...
    "MissingCount",sum(~finiteTupleMask),"QCRejectedCount",sum(finiteTupleMask & ~qcAcceptedMask), ...
    "UncertaintyMissingCount",sum(finiteTupleMask & qcAcceptedMask & ~uncertainty.CompleteMask), ...
    "ValidCount",sum(completeMask),"MissingPolicy",missingPolicy, ...
    "QCProvided",qcProvided,"SalinityUnit",salinityUnit, ...
    "TemperatureUnit",temperatureUnit,"ColorUnit",colorUnit, ...
    "SalinityDefinition",salinityDefinition,"TemperatureDefinition",temperatureDefinition, ...
    "ReferencePressure",referencePressure,"ColorLimits",colorLimits,"Colormap",colorMap, ...
    "UncertaintyType",uncertainty.Type,"ConfidenceLevel",uncertainty.ConfidenceLevel, ...
    "DensityReference",density.Reference,"valid_count",sum(completeMask), ...
    "missing_count",sum(~finiteTupleMask));
end

function [data,source] = resolve_input(salinityInput,temperatureInput,colorInput,options)
if istable(salinityInput) || istimetable(salinityInput)
    assert(isempty(temperatureInput) && isempty(colorInput), ...
        "oi_plot_ts_diagram:InputType", ...
        "For table/timetable input, pass [] placeholders and explicit variable options");
    salinityVariable = scalar_text(oi_get_option(options,"SalinityVariable",""), ...
        "oi_plot_ts_diagram:Variables","SalinityVariable must be explicit");
    temperatureVariable = scalar_text(oi_get_option(options,"TemperatureVariable",""), ...
        "oi_plot_ts_diagram:Variables","TemperatureVariable must be explicit");
    colorVariable = scalar_text(oi_get_option(options,"ColorVariable",""), ...
        "oi_plot_ts_diagram:Variables","ColorVariable must be explicit");
    variables = [salinityVariable temperatureVariable colorVariable];
    assert(all(ismember(variables,string(salinityInput.Properties.VariableNames))), ...
        "oi_plot_ts_diagram:Variables","All T-S variables must exist in the table");
    temperatureColumn = salinityInput.(temperatureVariable);
    colorColumn = salinityInput.(colorVariable);
    salinityColumn = salinityInput.(salinityVariable);
    data = struct("Salinity",salinityColumn(:), ...
        "Temperature",temperatureColumn(:),"Color",colorColumn(:));
    source = salinityInput;
else
    assert(isnumeric(salinityInput) && isnumeric(temperatureInput) && isnumeric(colorInput) ...
        && isvector(salinityInput) && isvector(temperatureInput) && isvector(colorInput) ...
        && numel(salinityInput) == numel(temperatureInput) ...
        && numel(salinityInput) == numel(colorInput) && ~isempty(salinityInput), ...
        "oi_plot_ts_diagram:SizeMismatch","T-S inputs must have equal nonzero length");
    data = struct("Salinity",salinityInput(:),"Temperature",temperatureInput(:), ...
        "Color",colorInput(:));
    source = [];
end
end

function [mask,provided] = resolve_qc(source,options,count)
mask = true(count,1);
provided = false;
qcValues = [];
if isfield(options,"QCValues") && ~isempty(options.QCValues)
    qcValues = options.QCValues;
elseif isfield(options,"QCVariable") && strlength(string(options.QCVariable)) > 0
    variableName = scalar_text(options.QCVariable,"oi_plot_ts_diagram:QC", ...
        "QCVariable must be scalar text");
    assert(~isempty(source) && ismember(variableName,string(source.Properties.VariableNames)), ...
        "oi_plot_ts_diagram:QC","QCVariable must exist in table input");
    qcValues = source.(variableName);
end
if isempty(qcValues)
    return;
end
provided = true;
assert(isvector(qcValues) && numel(qcValues) == count, ...
    "oi_plot_ts_diagram:QC","QC data must align with T-S samples");
acceptedValues = oi_get_option(options,"AcceptedQCValues",[]);
assert(~isempty(acceptedValues),"oi_plot_ts_diagram:QC", ...
    "AcceptedQCValues must be explicit when QC data are supplied");
if isnumeric(qcValues) || islogical(qcValues) || isdatetime(qcValues) || isduration(qcValues)
    mask = ismember(qcValues(:),acceptedValues);
    missingMask = ismissing(qcValues(:));
else
    textValues = string(qcValues(:));
    mask = ismember(textValues,string(acceptedValues));
    missingMask = ismissing(textValues);
end
mask = mask & ~missingMask;
end

function uncertainty = resolve_uncertainty(source,options,count,salinityUnit,temperatureUnit,baseMask)
salinityMagnitude = resolve_vector(source,options,"SalinityUncertainty", ...
    "SalinityUncertaintyVariable",count);
temperatureMagnitude = resolve_vector(source,options,"TemperatureUncertainty", ...
    "TemperatureUncertaintyVariable",count);
uncertainty = struct("Type","none","ConfidenceLevel",NaN, ...
    "SalinityMagnitude",zeros(count,1),"TemperatureMagnitude",zeros(count,1), ...
    "CompleteMask",true(count,1));
if isempty(salinityMagnitude) && isempty(temperatureMagnitude)
    return;
end
assert(~isempty(salinityMagnitude) && ~isempty(temperatureMagnitude), ...
    "oi_plot_ts_diagram:UncertaintyValues", ...
    "Salinity and temperature uncertainty must be supplied together");
validate_magnitude(salinityMagnitude,count,"salinity");
validate_magnitude(temperatureMagnitude,count,"temperature");
uncertaintyType = scalar_text(oi_get_option(options,"UncertaintyType",""), ...
    "oi_plot_ts_diagram:UncertaintyType","UncertaintyType must be explicit");
allowedTypes = ["standard-deviation" "standard-error" "confidence-interval" ...
    "instrument-accuracy" "ensemble-spread"];
assert(any(uncertaintyType == allowedTypes),"oi_plot_ts_diagram:UncertaintyType", ...
    "UncertaintyType is not a supported scientific definition");
assert(scalar_text(oi_get_option(options,"SalinityUncertaintyUnit",""), ...
    "oi_plot_ts_diagram:UncertaintyUnit","SalinityUncertaintyUnit must be explicit") == salinityUnit ...
    && scalar_text(oi_get_option(options,"TemperatureUncertaintyUnit",""), ...
    "oi_plot_ts_diagram:UncertaintyUnit","TemperatureUncertaintyUnit must be explicit") == temperatureUnit, ...
    "oi_plot_ts_diagram:UncertaintyUnit", ...
    "Uncertainty units must equal their corresponding axis units");
confidenceLevel = oi_get_option(options,"ConfidenceLevel",NaN);
if uncertaintyType == "confidence-interval"
    assert(isnumeric(confidenceLevel) && isscalar(confidenceLevel) ...
        && isfinite(confidenceLevel) && confidenceLevel > 0 && confidenceLevel < 1, ...
        "oi_plot_ts_diagram:ConfidenceLevel", ...
        "Confidence intervals require ConfidenceLevel between zero and one");
else
    assert(isnumeric(confidenceLevel) && isscalar(confidenceLevel) && isnan(confidenceLevel), ...
        "oi_plot_ts_diagram:ConfidenceLevel", ...
        "ConfidenceLevel must be omitted for non-confidence uncertainty");
end
completeMask = isfinite(salinityMagnitude) & isfinite(temperatureMagnitude);
assert(isequal(isfinite(salinityMagnitude),isfinite(temperatureMagnitude)), ...
    "oi_plot_ts_diagram:UncertaintyValues", ...
    "Salinity and temperature uncertainty must share one finite/NaN mask");
assert(~any((isfinite(salinityMagnitude) | isfinite(temperatureMagnitude)) & ~baseMask), ...
    "oi_plot_ts_diagram:UncertaintyValues", ...
    "Finite uncertainty cannot accompany missing or QC-rejected samples");
uncertainty.Type = uncertaintyType;
uncertainty.ConfidenceLevel = confidenceLevel;
uncertainty.SalinityMagnitude = salinityMagnitude(:);
uncertainty.TemperatureMagnitude = temperatureMagnitude(:);
uncertainty.CompleteMask = completeMask;
end

function values = resolve_vector(source,options,arrayField,variableField,count)
values = [];
if isfield(options,arrayField) && ~isempty(options.(arrayField))
    values = options.(arrayField);
elseif isfield(options,variableField) && strlength(string(options.(variableField))) > 0
    variableName = scalar_text(options.(variableField), ...
        "oi_plot_ts_diagram:Variables","Metadata variable names must be scalar text");
    assert(~isempty(source) && ismember(variableName,string(source.Properties.VariableNames)), ...
        "oi_plot_ts_diagram:Variables","Metadata variable must exist in table input");
    values = source.(variableName);
end
if ~isempty(values)
    assert(isvector(values) && numel(values) == count, ...
        "oi_plot_ts_diagram:Variables","Metadata values must align with samples");
    values = values(:);
end
end

function [density,provided] = resolve_density(options)
densityValues = oi_get_option(options,"DensityValues",[]);
provided = ~isempty(densityValues);
density = struct("Values",[],"Salinity",[],"Temperature",[],"Levels",[],"Reference","");
if ~provided
    return;
end
densitySalinity = oi_get_option(options,"DensitySalinity",[]);
densityTemperature = oi_get_option(options,"DensityTemperature",[]);
densityLevels = oi_get_option(options,"DensityLevels",[]);
assert(isnumeric(densitySalinity) && isreal(densitySalinity) ...
    && isnumeric(densityTemperature) && isreal(densityTemperature) ...
    && isvector(densitySalinity) && isvector(densityTemperature) ...
    && numel(densitySalinity) >= 2 && numel(densityTemperature) >= 2 ...
    && isequal(size(densityValues),[numel(densityTemperature) numel(densitySalinity)]), ...
    "oi_plot_ts_diagram:DensityGrid","DensityValues must be temperature-by-salinity");
assert(isnumeric(densityValues) && isreal(densityValues) ...
    && ~any(isinf(densityValues),"all") && any(isfinite(densityValues),"all"), ...
    "oi_plot_ts_diagram:DensityValues", ...
    "DensityValues may contain NaN but must contain finite real data and no Inf");
assert(all(isfinite(densitySalinity)) && all(diff(densitySalinity) > 0) ...
    && all(isfinite(densityTemperature)) && all(diff(densityTemperature) > 0), ...
    "oi_plot_ts_diagram:DensityCoordinates", ...
    "Density coordinates must be finite and increasing");
assert(isnumeric(densityLevels) && isreal(densityLevels) && isvector(densityLevels) ...
    && numel(densityLevels) >= 1 && all(isfinite(densityLevels)) ...
    && (numel(densityLevels) == 1 || all(diff(densityLevels) > 0)), ...
    "oi_plot_ts_diagram:DensityLevels", ...
    "DensityLevels must be a finite scalar or strictly increasing vector");
densityReference = scalar_text(oi_get_option(options,"DensityReference", ...
    "caller-supplied density field"),"oi_plot_ts_diagram:DensityReference", ...
    "DensityReference must identify the supplied density definition and reference pressure");
density = struct("Values",densityValues,"Salinity",densitySalinity(:)', ...
    "Temperature",densityTemperature(:),"Levels",densityLevels,"Reference",densityReference);
end

function [values,label] = resolve_confounder(source,options,count)
values = repmat("All samples",count,1);
label = "";
valuesOption = resolve_vector(source,options,"ConfounderValues","ConfounderVariable",count);
if ~isempty(valuesOption)
    values = string(valuesOption);
    label = scalar_text(oi_get_option(options,"ConfounderLabel",""), ...
        "oi_plot_ts_diagram:Confounder", ...
        "ConfounderLabel must be explicit when confounder data are supplied");
end
assert(all(~ismissing(values)) && all(strlength(strtrim(values)) > 0), ...
    "oi_plot_ts_diagram:Confounder","Confounder values must be complete nonblank categories");
end

function labels = resolve_sample_labels(source,options,count)
labels = "Sample " + string((1:count)');
if isfield(options,"SampleLabels") && ~isempty(options.SampleLabels)
    labels = string(options.SampleLabels);
elseif isfield(options,"SampleLabelVariable") ...
        && strlength(string(options.SampleLabelVariable)) > 0
    variableName = scalar_text(options.SampleLabelVariable, ...
        "oi_plot_ts_diagram:SampleLabels","SampleLabelVariable must be scalar text");
    assert(~isempty(source) && ismember(variableName,string(source.Properties.VariableNames)), ...
        "oi_plot_ts_diagram:SampleLabels", ...
        "SampleLabelVariable must exist in table input");
    labels = string(source.(variableName));
end
assert(numel(labels) == count && all(~ismissing(labels)) ...
    && all(strlength(strtrim(labels)) > 0), ...
    "oi_plot_ts_diagram:SampleLabels","Sample labels must be aligned nonblank text");
labels = labels(:);
end

function [scatterHandles,legendHandles,legendLabels] = plot_groups(axesHandle,salinity,temperature, ...
    colorData,completeMask,confounders,confounderLabel,theme)
selectedConfounders = confounders(completeMask);
groups = unique(selectedConfounders,"stable");
markers = ["o" "s" "^" "d" "v" ">"];
assert(numel(groups) <= numel(markers),"oi_plot_ts_diagram:Confounder", ...
    "Confounder has more categories than the explicit marker palette");
scatterHandles = gobjects(numel(groups),1);
legendHandles = gobjects(0);
legendLabels = strings(0,1);
selectedSalinity = salinity(completeMask);
selectedTemperature = temperature(completeMask);
selectedColor = colorData(completeMask);
for groupIndex = 1:numel(groups)
    groupMask = selectedConfounders == groups(groupIndex);
    scatterHandles(groupIndex) = scatter(axesHandle,selectedSalinity(groupMask), ...
        selectedTemperature(groupMask),30,selectedColor(groupMask),"filled", ...
        "Marker",markers(groupIndex),"MarkerEdgeColor",[0.15 0.15 0.15], ...
        "HandleVisibility","off");
    if strlength(confounderLabel) > 0
        legendHandles(groupIndex,1) = plot(axesHandle,NaN,NaN,markers(groupIndex), ...
            "MarkerFaceColor",theme.AccentColor,"MarkerEdgeColor",[0.15 0.15 0.15], ...
            "LineStyle","none");
        legendLabels(groupIndex,1) = confounderLabel + ": " + groups(groupIndex);
    end
end
end

function handles = plot_uncertainty(axesHandle,salinity,temperature,uncertainty,mask,color)
if uncertainty.Type == "none"
    handles = gobjects(0);
    return;
end
indices = find(mask);
handles = gobjects(numel(indices)*2,1);
for pointIndex = 1:numel(indices)
    sourceIndex = indices(pointIndex);
    handles(2*pointIndex-1) = plot(axesHandle, ...
        salinity(sourceIndex) + [-1 1] * uncertainty.SalinityMagnitude(sourceIndex), ...
        [temperature(sourceIndex) temperature(sourceIndex)],"-","Color",color, ...
        "LineWidth",0.8,"HandleVisibility","off");
    handles(2*pointIndex) = plot(axesHandle, ...
        [salinity(sourceIndex) salinity(sourceIndex)], ...
        temperature(sourceIndex) + [-1 1] * uncertainty.TemperatureMagnitude(sourceIndex), ...
        "-","Color",color,"LineWidth",0.8,"HandleVisibility","off");
end
end

function configure_data_tips(handles,salinity,temperature,colorData,sampleLabels, ...
    confounders,confounderLabel,salinityLabel,salinityUnit,temperatureLabel, ...
    temperatureUnit,colorLabel,colorUnit)
groups = unique(confounders,"stable");
for groupIndex = 1:numel(handles)
    if ~isprop(handles(groupIndex),"DataTipTemplate")
        continue;
    end
    groupMask = confounders == groups(groupIndex);
    rows = [dataTipTextRow("Sample",sampleLabels(groupMask)); ...
        dataTipTextRow(salinityLabel + " (" + salinityUnit + ")",salinity(groupMask)); ...
        dataTipTextRow(temperatureLabel + " (" + temperatureUnit + ")",temperature(groupMask)); ...
        dataTipTextRow(colorLabel + " (" + colorUnit + ")",colorData(groupMask))];
    if strlength(confounderLabel) > 0
        rows = [rows;dataTipTextRow(confounderLabel,confounders(groupMask))];
    end
    handles(groupIndex).DataTipTemplate.DataTipRows = rows;
end
end

function validate_magnitude(values,count,name)
assert(isnumeric(values) && isreal(values) && isvector(values) && numel(values) == count ...
    && all(isnan(values(:)) | (isfinite(values(:)) & values(:) >= 0)), ...
    "oi_plot_ts_diagram:UncertaintyValues", ...
    string(name) + " uncertainty must be aligned nonnegative finite values or NaN");
end

function assert_ts_units(source,options,salinityUnit,temperatureUnit,colorUnit)
if isempty(source)
    return;
end
assert_table_unit(source,scalar_text(options.SalinityVariable, ...
    "oi_plot_ts_diagram:Variables","SalinityVariable must be explicit"),salinityUnit);
assert_table_unit(source,scalar_text(options.TemperatureVariable, ...
    "oi_plot_ts_diagram:Variables","TemperatureVariable must be explicit"),temperatureUnit);
assert_table_unit(source,scalar_text(options.ColorVariable, ...
    "oi_plot_ts_diagram:Variables","ColorVariable must be explicit"),colorUnit);
end

function assert_table_unit(data,variableName,expectedUnit)
variableNames = string(data.Properties.VariableNames);
variableUnits = string(data.Properties.VariableUnits);
position = find(variableNames == variableName,1);
if ~isempty(variableUnits) && numel(variableUnits) >= position ...
        && strlength(strtrim(variableUnits(position))) > 0
    assert(strtrim(variableUnits(position)) == expectedUnit, ...
        "oi_plot_ts_diagram:UnitMismatch", ...
        "Explicit unit conflicts with table VariableUnits metadata");
end
end

function value = scalar_text(value,errorIdentifier,errorMessage)
value = oi_require_text(value,errorIdentifier,errorMessage);
assert(isscalar(value),errorIdentifier,errorMessage);
end
