function result = oi_plot_hovmoller(axesHandle, timeValues, depthValues, fieldValues, options)
%OI_PLOT_HOVMOLLER Plot a regular UTC datetime-depth field.
% Input contract: time is N-by-1 UTC datetime and field is M-by-N double.
% Time is strictly increasing, uniformly spaced UTC datetime. Depth is
% uniformly spaced positive-down. Field dimensions are depth-by-time. NaN
% cells remain transparent; missing classes, QC, and uncertainty are kept.
arguments
    axesHandle (1,1) matlab.graphics.axis.Axes
    timeValues (:,1) datetime
    depthValues (:,1) double
    fieldValues (:,:) double
    options (1,1) struct = struct()
end
allowedOptions = ["ColorCenter" "ColorLimits" "ColorScale" "Colormap" ...
    "DepthUnit" "MissingColor" "MissingPolicy" "QCFlags" "QCPolicy" ...
    "QuantityLabel" "QuantityUnit" "ReportingMissingMask" ...
    "StructuralMissingMask" "Theme" "TimeDisplayFormat" "TimeZone" ...
    "Title" "UncertaintyType" "UncertaintyUnit" "UncertaintyValues"];
reject_unknown_options(options, allowedOptions);
assert(numel(timeValues) >= 2 && ~any(isnat(timeValues)) ...
    && all(diff(timeValues) > seconds(0)), "oi_plot_hovmoller:TimeCoordinate", ...
    "Time must be valid, unique, and strictly increasing");
assert(string(timeValues.TimeZone) == "UTC", "oi_plot_hovmoller:TimeZone", ...
    "Datetime values must use the UTC time zone");
requestedTimeZone = string(oi_get_option(options, "TimeZone", "UTC"));
assert(isscalar(requestedTimeZone) && requestedTimeZone == "UTC", ...
    "oi_plot_hovmoller:TimeZoneMismatch", ...
    "TimeZone must be UTC; no implicit conversion is performed");
assert(is_uniform(seconds(diff(timeValues))), "oi_plot_hovmoller:TimeCadence", ...
    "imagesc geometry requires uniform time cadence");
assert(numel(depthValues) >= 2 && all(isfinite(depthValues)) ...
    && all(depthValues >= 0) && all(diff(depthValues) > 0) && is_uniform(diff(depthValues)), ...
    "oi_plot_hovmoller:DepthCoordinate", ...
    "Depth must be finite, regular, nonnegative, and strictly increasing positive-down");
assert(isequal(size(fieldValues), [numel(depthValues) numel(timeValues)]), ...
    "oi_plot_hovmoller:SizeMismatch", "fieldValues must be depth-by-time");
assert(isreal(fieldValues) && ~any(isinf(fieldValues),"all") ...
    && any(isfinite(fieldValues),"all"), "oi_plot_hovmoller:InvalidField", ...
    "fieldValues may contain NaN but must contain finite data and no Inf");
missingPolicy = string(oi_get_option(options, "MissingPolicy", "preserve"));
assert(isscalar(missingPolicy) && missingPolicy == "preserve", ...
    "oi_plot_hovmoller:MissingPolicy", "Only MissingPolicy='preserve' is supported");
[structuralMask, reportingMask] = classify_missing(fieldValues, options);
[qcFlags, qcLevels, qcCounts, qcProvided] = validate_qc(fieldValues, options);
[uncertaintyValues, uncertaintyType, uncertaintyUnit, uncertaintyPresent] = ...
    validate_uncertainty(fieldValues, options);
uncertaintyMissingCount = 0;
if uncertaintyPresent
    uncertaintyMissingCount = sum(isnan(uncertaintyValues) & isfinite(fieldValues),"all");
end
colorLimits = oi_get_option(options, "ColorLimits", []);
assert(isnumeric(colorLimits) && isreal(colorLimits) ...
    && isequal(size(colorLimits),[1 2]) ...
    && all(isfinite(colorLimits)) && colorLimits(1) < colorLimits(2), ...
    "oi_plot_hovmoller:ColorLimits", "ColorLimits must be an explicit finite increasing pair");
colorScale = string(oi_get_option(options, "ColorScale", "linear"));
assert(isscalar(colorScale) && colorScale == "linear", ...
    "oi_plot_hovmoller:ColorScale", "Only an explicit linear color scale is supported");
theme = oi_get_option(options, "Theme", struct());
assert(isstruct(theme) && isscalar(theme), "oi_plot_hovmoller:Theme", ...
    "Theme must be a scalar struct");
if isempty(fieldnames(theme))
    theme = oi_ocean_theme();
end
[colorMap, colorCenter] = resolve_colormap(options, theme, colorLimits);
missingColor = oi_get_option(options, "MissingColor", theme.MissingColor);
depthUnit = require_scalar_text(oi_get_option(options, "DepthUnit", ""), ...
    "oi_plot_hovmoller:Units", "DepthUnit must be explicit nonblank text");
quantityLabel = require_scalar_text(oi_get_option(options, "QuantityLabel", ""), ...
    "oi_plot_hovmoller:Units", "QuantityLabel must be explicit nonblank text");
quantityUnit = require_scalar_text(oi_get_option(options, "QuantityUnit", ""), ...
    "oi_plot_hovmoller:Units", "QuantityUnit must be explicit nonblank text");
if uncertaintyPresent
    assert(uncertaintyUnit == quantityUnit, ...
        "oi_plot_hovmoller:UncertaintyUnit", ...
        "UncertaintyUnit must equal QuantityUnit");
end
titleText = require_scalar_text(oi_get_option(options, "Title", "Time-depth evolution"), ...
    "oi_plot_hovmoller:Title", "Title must be explicit nonblank text");
timeDisplayFormat = require_scalar_text(oi_get_option(options, "TimeDisplayFormat", ...
    "yyyy-MM-dd HH:mm"), "oi_plot_hovmoller:TimeDisplayFormat", ...
    "TimeDisplayFormat must be explicit nonblank text");

% MATLAB R2023b (version 23.2) accepts datetime imagesc coordinates.
useNumericTime = verLessThan("matlab", "23.2");
if useNumericTime
    imageHandle = imagesc(axesHandle, datenum(timeValues), depthValues, fieldValues, ...
        "AlphaData", isfinite(fieldValues));
    datetick(axesHandle, "x", "yyyy-mm-dd HH:MM", "keeplimits");
else
    imageHandle = imagesc(axesHandle, timeValues, depthValues, fieldValues, ...
        "AlphaData", isfinite(fieldValues));
    axesHandle.XAxis.TickLabelFormat = char(timeDisplayFormat);
end
axesHandle.YDir = "reverse";
xlabel(axesHandle, "Time (UTC)", "Interpreter", "none");
ylabel(axesHandle, "Depth (" + depthUnit + ", positive down)", "Interpreter", "none");
title(axesHandle, titleText, "FontWeight", "normal", "Interpreter", "none");
colorbarHandle = colorbar(axesHandle, "Location", "eastoutside");
colorbarHandle.Label.String = quantityLabel + " (" + quantityUnit + ")";
oi_apply_axes(axesHandle, theme);
oi_apply_color_scale(axesHandle, colorbarHandle, colorMap, colorLimits, ...
    theme, missingColor);
result = struct("Axes", axesHandle, "Image", imageHandle, "Colorbar", colorbarHandle, ...
    "MissingMask", isnan(fieldValues), "StructuralMissingMask", structuralMask, ...
    "ReportingMissingMask", reportingMask, ...
    "MissingCount", sum(isnan(fieldValues),"all"), ...
    "StructuralMissingCount", sum(structuralMask,"all"), ...
    "ReportingMissingCount", sum(reportingMask,"all"), ...
    "ValidCount", sum(isfinite(fieldValues),"all"), "MissingPolicy", missingPolicy, ...
    "QCFlags", qcFlags, "QCLevels", qcLevels, "QCCounts", qcCounts, ...
    "QCProvided", qcProvided, "QCPolicy", "preserve", ...
    "UncertaintyValues", uncertaintyValues, "UncertaintyPresent", uncertaintyPresent, ...
    "UncertaintyType", uncertaintyType, "UncertaintyUnit", uncertaintyUnit, ...
    "UncertaintyDisplay", "metadata", ...
    "UncertaintyMissingCount", uncertaintyMissingCount, ...
    "TimeZone", requestedTimeZone, "TimeDisplayFormat", timeDisplayFormat, ...
    "DepthUnit", depthUnit, "QuantityUnit", quantityUnit, ...
    "ColorLimits", colorLimits, "ColorScale", colorScale, "ColorCenter", colorCenter, ...
    "Colormap", colorMap, "MissingColor", missingColor, "Interpolated", false, ...
    "NumericTimeFallback", useNumericTime, "valid_count", ...
    sum(isfinite(fieldValues), "all"), "missing_count", sum(isnan(fieldValues), "all"));
end

function reject_unknown_options(options, allowedOptions)
unknownOptions = setdiff(string(fieldnames(options)), allowedOptions);
assert(isempty(unknownOptions), "oi_plot_hovmoller:UnknownOption", ...
    "Unsupported option: %s", strjoin(unknownOptions, ", "));
end

function value = require_scalar_text(value, identifier, message)
value = oi_require_text(value, identifier, message);
assert(isscalar(value), identifier, message);
end

function [structuralMask, reportingMask] = classify_missing(values, options)
missingMask = isnan(values);
structuralMask = oi_get_option(options, "StructuralMissingMask", false(size(values)));
assert(islogical(structuralMask) && isequal(size(structuralMask), size(values)), ...
    "oi_plot_hovmoller:StructuralMissingMask", ...
    "StructuralMissingMask must be logical and match field dimensions");
reportingMask = oi_get_option(options, "ReportingMissingMask", missingMask & ~structuralMask);
assert(islogical(reportingMask) && isequal(size(reportingMask), size(values)), ...
    "oi_plot_hovmoller:ReportingMissingMask", ...
    "ReportingMissingMask must be logical and match field dimensions");
assert(~any(structuralMask & reportingMask,"all"), ...
    "oi_plot_hovmoller:MissingMaskOverlap", "Missing classifications must be disjoint");
assert(isequal(structuralMask | reportingMask, missingMask), ...
    "oi_plot_hovmoller:MissingMaskCoverage", ...
    "Missing classifications must identify every and only NaN field cell");
end

function [qcFlags, qcLevels, qcCounts, qcProvided] = validate_qc(values, options)
qcPolicy = string(oi_get_option(options, "QCPolicy", "preserve"));
assert(isscalar(qcPolicy) && qcPolicy == "preserve", ...
    "oi_plot_hovmoller:QCPolicy", "Only QCPolicy='preserve' is supported");
qcProvided = isfield(options, "QCFlags");
if ~qcProvided
    qcFlags = strings(0,1); qcLevels = strings(0,1); qcCounts = zeros(0,1);
    return;
end
rawFlags = options.QCFlags;
assert(isstring(rawFlags) || iscellstr(rawFlags) || iscategorical(rawFlags), ...
    "oi_plot_hovmoller:QCFlags", "QCFlags must be string, cellstr, or categorical");
qcFlags = strtrim(string(rawFlags));
assert(isequal(size(qcFlags), size(values)) && all(~ismissing(qcFlags),"all") ...
    && all(strlength(qcFlags) > 0,"all"), "oi_plot_hovmoller:QCFlags", ...
    "QCFlags must contain one nonblank flag per field cell");
[qcLevels, ~, levelIndex] = unique(qcFlags(:), "stable");
qcCounts = accumarray(levelIndex, 1, [numel(qcLevels) 1]);
end

function [uncertainty, type, unit, present] = validate_uncertainty(values, options)
present = isfield(options, "UncertaintyValues");
if ~present
    assert(~isfield(options, "UncertaintyType") && ~isfield(options, "UncertaintyUnit"), ...
        "oi_plot_hovmoller:UncertaintyMetadata", ...
        "Uncertainty metadata requires UncertaintyValues");
    uncertainty = NaN(size(values)); type = ""; unit = "";
    return;
end
uncertainty = options.UncertaintyValues;
assert(isnumeric(uncertainty) && isreal(uncertainty) ...
    && isequal(size(uncertainty), size(values)) ...
    && ~any(isinf(uncertainty),"all") ...
    && all(uncertainty(isfinite(uncertainty)) >= 0), ...
    "oi_plot_hovmoller:UncertaintyValues", ...
    "UncertaintyValues must be aligned, real, nonnegative, and finite or NaN");
assert(~any(isfinite(uncertainty) & isnan(values),"all"), ...
    "oi_plot_hovmoller:UncertaintyAlignment", ...
    "Missing field cells cannot have finite uncertainty");
assert(any(isfinite(uncertainty),"all"), "oi_plot_hovmoller:UncertaintyValues", ...
    "UncertaintyValues must contain at least one finite magnitude");
type = require_scalar_text(oi_get_option(options, "UncertaintyType", ""), ...
    "oi_plot_hovmoller:UncertaintyMetadata", "UncertaintyType must be explicit");
unit = require_scalar_text(oi_get_option(options, "UncertaintyUnit", ""), ...
    "oi_plot_hovmoller:UncertaintyMetadata", "UncertaintyUnit must be explicit");
end

function [colorMap, center] = resolve_colormap(options, theme, limits)
if isfield(options, "ColorCenter")
    center = options.ColorCenter;
    assert(isnumeric(center) && isreal(center) && isscalar(center) ...
        && isfinite(center) && limits(1) < center && center < limits(2), ...
        "oi_plot_hovmoller:ColorCenter", ...
        "ColorCenter must be finite and strictly inside ColorLimits");
    baseMap = oi_get_option(options, "Colormap", theme.DivergingMap);
    colorMap = center_colormap(baseMap, limits, center);
else
    center = [];
    colorMap = oi_get_option(options, "Colormap", theme.SequentialMap);
end
end

function colorMap = center_colormap(baseMap, limits, center)
assert(isnumeric(baseMap) && isreal(baseMap) && size(baseMap,2) == 3 ...
    && size(baseMap,1) >= 2 && all(isfinite(baseMap),"all") ...
    && all(baseMap >= 0,"all") && all(baseMap <= 1,"all"), ...
    "oi_plot_hovmoller:Colormap", "Colormap must be a finite N-by-3 RGB array");
position = (center - limits(1)) / (limits(2) - limits(1));
displayCoordinate = linspace(0,1,size(baseMap,1))';
sourceCoordinate = zeros(size(displayCoordinate));
lower = displayCoordinate <= position;
sourceCoordinate(lower) = 0.5 * displayCoordinate(lower) / position;
sourceCoordinate(~lower) = 0.5 + 0.5 * ...
    (displayCoordinate(~lower) - position) / (1 - position);
colorMap = interp1(linspace(0,1,size(baseMap,1)), baseMap, ...
    sourceCoordinate, "linear");
end

function uniform = is_uniform(spacing)
tolerance = max(1,max(abs(spacing))) * 100 * eps('double');
uniform = max(abs(spacing - spacing(1))) <= tolerance;
end
