function result = oi_plot_section(axesHandle, distanceValues, depthValues, fieldValues, options)
%OI_PLOT_SECTION Plot a rectilinear positive-down ocean section.
% Input contract: distance is 1-by-N, depth is M-by-1, field is M-by-N.
% Distance is strictly increasing. Depth is nonnegative and strictly
% increasing. Field dimensions are depth-by-distance. No transpose,
% interpolation, smoothing, filling, sorting, or unit conversion occurs.
arguments
    axesHandle (1,1) matlab.graphics.axis.Axes
    distanceValues (1,:) double
    depthValues (:,1) double
    fieldValues (:,:) double
    options (1,1) struct = struct()
end
allowedOptions = ["ColorCenter" "ColorLimits" "ColorScale" "Colormap" ...
    "DepthUnit" "DistanceUnit" "Levels" "MissingColor" "MissingPolicy" ...
    "QCFlags" "QCPolicy" "QuantityLabel" "QuantityUnit" ...
    "ReportingMissingMask" "StructuralMissingMask" "Theme" "Title" ...
    "UncertaintyType" "UncertaintyUnit" "UncertaintyValues"];
reject_unknown_options(options, allowedOptions);
assert(numel(distanceValues) >= 2 && all(isfinite(distanceValues)) ...
    && all(diff(distanceValues) > 0), "oi_plot_section:DistanceCoordinate", ...
    "Distance must be finite, unique, and strictly increasing");
assert(numel(depthValues) >= 2 && all(isfinite(depthValues)) ...
    && all(depthValues >= 0) && all(diff(depthValues) > 0), ...
    "oi_plot_section:DepthCoordinate", ...
    "Depth must be finite, nonnegative, and strictly increasing positive-down");
assert(isequal(size(fieldValues), [numel(depthValues) numel(distanceValues)]), ...
    "oi_plot_section:SizeMismatch", "fieldValues must be depth-by-distance");
assert(isreal(fieldValues) && ~any(isinf(fieldValues),"all") ...
    && any(isfinite(fieldValues),"all"), "oi_plot_section:InvalidField", ...
    "fieldValues must contain finite data and may contain NaN but not Inf");
missingPolicy = string(oi_get_option(options, "MissingPolicy", "preserve"));
assert(isscalar(missingPolicy) && missingPolicy == "preserve", ...
    "oi_plot_section:MissingPolicy", "Only MissingPolicy='preserve' is supported");
[structuralMask, reportingMask] = classify_missing(fieldValues, options);
[qcFlags, qcLevels, qcCounts, qcProvided] = validate_qc(fieldValues, options);
[uncertaintyValues, uncertaintyType, uncertaintyUnit, uncertaintyPresent] = ...
    validate_uncertainty(fieldValues, options);
uncertaintyMissingCount = 0;
if uncertaintyPresent
    uncertaintyMissingCount = sum(isnan(uncertaintyValues) & isfinite(fieldValues),"all");
end
colorLimits = oi_get_option(options, "ColorLimits", []);
assert(isnumeric(colorLimits) && isreal(colorLimits) ...
    && isequal(size(colorLimits),[1 2]) ...
    && all(isfinite(colorLimits)) && colorLimits(1) < colorLimits(2), ...
    "oi_plot_section:ColorLimits", "ColorLimits must be an explicit finite increasing pair");
colorScale = string(oi_get_option(options, "ColorScale", "linear"));
assert(isscalar(colorScale) && colorScale == "linear", ...
    "oi_plot_section:ColorScale", "Only an explicit linear color scale is supported");
levels = oi_get_option(options, "Levels", linspace(colorLimits(1), colorLimits(2), 25));
assert(isnumeric(levels) && isreal(levels) && isvector(levels) ...
    && numel(levels) >= 3 && all(isfinite(levels)) ...
    && all(diff(levels) > 0), "oi_plot_section:Levels", ...
    "Contour levels must be finite and strictly increasing");
levels = reshape(levels, 1, []);
levelTolerance = max(1,max(abs(colorLimits))) * 100 * eps('double');
assert(abs(levels(1)-colorLimits(1)) <= levelTolerance ...
    && abs(levels(end)-colorLimits(2)) <= levelTolerance, ...
    "oi_plot_section:Levels", "Contour levels must span the complete ColorLimits range");
theme = oi_get_option(options, "Theme", struct());
assert(isstruct(theme) && isscalar(theme), "oi_plot_section:Theme", ...
    "Theme must be a scalar struct");
if isempty(fieldnames(theme))
    theme = oi_ocean_theme();
end
[colorMap, colorCenter] = resolve_colormap(options, theme, colorLimits);
missingColor = oi_get_option(options, "MissingColor", theme.MissingColor);
distanceUnit = require_scalar_text(oi_get_option(options, "DistanceUnit", ""), ...
    "oi_plot_section:Units", "DistanceUnit must be explicit nonblank text");
depthUnit = require_scalar_text(oi_get_option(options, "DepthUnit", ""), ...
    "oi_plot_section:Units", "DepthUnit must be explicit nonblank text");
quantityLabel = require_scalar_text(oi_get_option(options, "QuantityLabel", ""), ...
    "oi_plot_section:Units", "QuantityLabel must be explicit nonblank text");
quantityUnit = require_scalar_text(oi_get_option(options, "QuantityUnit", ""), ...
    "oi_plot_section:Units", "QuantityUnit must be explicit nonblank text");
if uncertaintyPresent
    assert(uncertaintyUnit == quantityUnit, ...
        "oi_plot_section:UncertaintyUnit", ...
        "UncertaintyUnit must equal QuantityUnit");
end
titleText = require_scalar_text(oi_get_option(options, "Title", "Ocean section"), ...
    "oi_plot_section:Title", "Title must be explicit nonblank text");

contourHandle = contourf(axesHandle, distanceValues, depthValues, fieldValues, ...
    levels, "LineStyle", "none");
axesHandle.YDir = "reverse";
xlabel(axesHandle, "Distance (" + distanceUnit + ")", "Interpreter", "none");
ylabel(axesHandle, "Depth (" + depthUnit + ", positive down)", "Interpreter", "none");
title(axesHandle, titleText, "FontWeight", "normal", "Interpreter", "none");
colorbarHandle = colorbar(axesHandle, "Location", "eastoutside");
colorbarHandle.Label.String = quantityLabel + " (" + quantityUnit + ")";
oi_apply_axes(axesHandle, theme);
oi_apply_color_scale(axesHandle, colorbarHandle, colorMap, colorLimits, ...
    theme, missingColor);
result = struct("Axes", axesHandle, "Contour", contourHandle, "Colorbar", colorbarHandle, ...
    "MissingMask", isnan(fieldValues), "StructuralMissingMask", structuralMask, ...
    "ReportingMissingMask", reportingMask, ...
    "MissingCount", sum(isnan(fieldValues),"all"), ...
    "StructuralMissingCount", sum(structuralMask,"all"), ...
    "ReportingMissingCount", sum(reportingMask,"all"), ...
    "ValidCount", sum(isfinite(fieldValues),"all"), "MissingPolicy", missingPolicy, ...
    "QCFlags", qcFlags, "QCLevels", qcLevels, "QCCounts", qcCounts, ...
    "QCProvided", qcProvided, "QCPolicy", "preserve", ...
    "UncertaintyValues", uncertaintyValues, "UncertaintyPresent", uncertaintyPresent, ...
    "UncertaintyType", uncertaintyType, "UncertaintyUnit", uncertaintyUnit, ...
    "UncertaintyDisplay", "metadata", ...
    "UncertaintyMissingCount", uncertaintyMissingCount, ...
    "ColorLimits", colorLimits, "ColorScale", colorScale, "ColorCenter", colorCenter, ...
    "Levels", levels, "DistanceUnit", distanceUnit, "DepthUnit", depthUnit, ...
    "QuantityUnit", quantityUnit, "Colormap", colorMap, "MissingColor", missingColor, ...
    "Interpolated", false, "valid_count", sum(isfinite(fieldValues), "all"), ...
    "missing_count", sum(isnan(fieldValues), "all"));
end

function reject_unknown_options(options, allowedOptions)
unknownOptions = setdiff(string(fieldnames(options)), allowedOptions);
assert(isempty(unknownOptions), "oi_plot_section:UnknownOption", ...
    "Unsupported option: %s", strjoin(unknownOptions, ", "));
end

function value = require_scalar_text(value, identifier, message)
value = oi_require_text(value, identifier, message);
assert(isscalar(value), identifier, message);
end

function [structuralMask, reportingMask] = classify_missing(values, options)
missingMask = isnan(values);
structuralMask = oi_get_option(options, "StructuralMissingMask", false(size(values)));
assert(islogical(structuralMask) && isequal(size(structuralMask), size(values)), ...
    "oi_plot_section:StructuralMissingMask", ...
    "StructuralMissingMask must be logical and match field dimensions");
reportingMask = oi_get_option(options, "ReportingMissingMask", missingMask & ~structuralMask);
assert(islogical(reportingMask) && isequal(size(reportingMask), size(values)), ...
    "oi_plot_section:ReportingMissingMask", ...
    "ReportingMissingMask must be logical and match field dimensions");
assert(~any(structuralMask & reportingMask,"all"), ...
    "oi_plot_section:MissingMaskOverlap", "Missing classifications must be disjoint");
assert(isequal(structuralMask | reportingMask, missingMask), ...
    "oi_plot_section:MissingMaskCoverage", ...
    "Missing classifications must identify every and only NaN field cell");
end

function [qcFlags, qcLevels, qcCounts, qcProvided] = validate_qc(values, options)
qcPolicy = string(oi_get_option(options, "QCPolicy", "preserve"));
assert(isscalar(qcPolicy) && qcPolicy == "preserve", ...
    "oi_plot_section:QCPolicy", "Only QCPolicy='preserve' is supported");
qcProvided = isfield(options, "QCFlags");
if ~qcProvided
    qcFlags = strings(0,1); qcLevels = strings(0,1); qcCounts = zeros(0,1);
    return;
end
rawFlags = options.QCFlags;
assert(isstring(rawFlags) || iscellstr(rawFlags) || iscategorical(rawFlags), ...
    "oi_plot_section:QCFlags", "QCFlags must be string, cellstr, or categorical");
qcFlags = strtrim(string(rawFlags));
assert(isequal(size(qcFlags), size(values)) && all(~ismissing(qcFlags),"all") ...
    && all(strlength(qcFlags) > 0,"all"), "oi_plot_section:QCFlags", ...
    "QCFlags must contain one nonblank flag per field cell");
[qcLevels, ~, levelIndex] = unique(qcFlags(:), "stable");
qcCounts = accumarray(levelIndex, 1, [numel(qcLevels) 1]);
end

function [uncertainty, type, unit, present] = validate_uncertainty(values, options)
present = isfield(options, "UncertaintyValues");
if ~present
    assert(~isfield(options, "UncertaintyType") && ~isfield(options, "UncertaintyUnit"), ...
        "oi_plot_section:UncertaintyMetadata", ...
        "Uncertainty metadata requires UncertaintyValues");
    uncertainty = NaN(size(values)); type = ""; unit = "";
    return;
end
uncertainty = options.UncertaintyValues;
assert(isnumeric(uncertainty) && isreal(uncertainty) ...
    && isequal(size(uncertainty), size(values)) ...
    && ~any(isinf(uncertainty),"all") ...
    && all(uncertainty(isfinite(uncertainty)) >= 0), ...
    "oi_plot_section:UncertaintyValues", ...
    "UncertaintyValues must be aligned, real, nonnegative, and finite or NaN");
assert(~any(isfinite(uncertainty) & isnan(values),"all"), ...
    "oi_plot_section:UncertaintyAlignment", ...
    "Missing field cells cannot have finite uncertainty");
assert(any(isfinite(uncertainty),"all"), "oi_plot_section:UncertaintyValues", ...
    "UncertaintyValues must contain at least one finite magnitude");
type = require_scalar_text(oi_get_option(options, "UncertaintyType", ""), ...
    "oi_plot_section:UncertaintyMetadata", "UncertaintyType must be explicit");
unit = require_scalar_text(oi_get_option(options, "UncertaintyUnit", ""), ...
    "oi_plot_section:UncertaintyMetadata", "UncertaintyUnit must be explicit");
end

function [colorMap, center] = resolve_colormap(options, theme, limits)
if isfield(options, "ColorCenter")
    center = options.ColorCenter;
    assert(isnumeric(center) && isreal(center) && isscalar(center) ...
        && isfinite(center) && limits(1) < center && center < limits(2), ...
        "oi_plot_section:ColorCenter", ...
        "ColorCenter must be finite and strictly inside ColorLimits");
    baseMap = oi_get_option(options, "Colormap", theme.DivergingMap);
    colorMap = center_colormap(baseMap, limits, center);
else
    center = [];
    colorMap = oi_get_option(options, "Colormap", theme.SequentialMap);
end
end

function colorMap = center_colormap(baseMap, limits, center)
assert(isnumeric(baseMap) && isreal(baseMap) && size(baseMap,2) == 3 ...
    && size(baseMap,1) >= 2 && all(isfinite(baseMap),"all") ...
    && all(baseMap >= 0,"all") && all(baseMap <= 1,"all"), ...
    "oi_plot_section:Colormap", "Colormap must be a finite N-by-3 RGB array");
position = (center - limits(1)) / (limits(2) - limits(1));
displayCoordinate = linspace(0,1,size(baseMap,1))';
sourceCoordinate = zeros(size(displayCoordinate));
lower = displayCoordinate <= position;
sourceCoordinate(lower) = 0.5 * displayCoordinate(lower) / position;
sourceCoordinate(~lower) = 0.5 + 0.5 * ...
    (displayCoordinate(~lower) - position) / (1 - position);
colorMap = interp1(linspace(0,1,size(baseMap,1)), baseMap, ...
    sourceCoordinate, "linear");
end
