function result = oi_plot_spectrum(axesHandle, frequencyValues, spectralDensity, options)
%OI_PLOT_SPECTRUM Plot traceable precomputed positive-frequency spectra.
% Input contract: frequencyValues is finite, positive, unique, and strictly
% increasing. spectralDensity is positive where finite. Optional lower/upper
% confidence bounds are supplied values, not inferred errors. NaN gaps remain
% breaks and confidence bands are split at every incomplete sample.
arguments
    axesHandle (1,1) matlab.graphics.axis.Axes
    frequencyValues (:,1) double
    spectralDensity (:,1) double
    options (1,1) struct = struct()
end
assert(numel(frequencyValues) >= 2 && all(isfinite(frequencyValues)) ...
    && all(frequencyValues > 0) && all(diff(frequencyValues) > 0), ...
    "oi_plot_spectrum:Frequency", ...
    "Frequency must be finite, positive, unique, and strictly increasing");
assert(numel(spectralDensity) == numel(frequencyValues) ...
    && isreal(spectralDensity) && ~any(isinf(spectralDensity)) ...
    && any(isfinite(spectralDensity)) ...
    && all(spectralDensity(isfinite(spectralDensity)) > 0), ...
    "oi_plot_spectrum:Density", ...
    "Finite spectral density must be positive and may contain NaN but not Inf");
missingPolicy = string(oi_get_option(options, "MissingPolicy", "preserve"));
assert(missingPolicy == "preserve", "oi_plot_spectrum:MissingPolicy", ...
    "Only MissingPolicy='preserve' is supported");
frequencyUnit = oi_require_text(oi_get_option(options, "FrequencyUnit", ""), ...
    "oi_plot_spectrum:Metadata", "FrequencyUnit must be explicit nonblank text");
periodUnit = oi_require_text(oi_get_option(options, "PeriodUnit", ""), ...
    "oi_plot_spectrum:Metadata", "PeriodUnit must be explicit nonblank text");
densityUnit = oi_require_text(oi_get_option(options, "DensityUnit", ""), ...
    "oi_plot_spectrum:Metadata", "DensityUnit must be explicit nonblank text");
windowDescription = oi_require_text(oi_get_option(options, "WindowDescription", ""), ...
    "oi_plot_spectrum:Metadata", "WindowDescription must be explicit nonblank text");
detrendDescription = oi_require_text(oi_get_option(options, "DetrendDescription", ""), ...
    "oi_plot_spectrum:Metadata", "DetrendDescription must be explicit nonblank text");
segmentDescription = oi_require_text(oi_get_option(options, "SegmentDescription", ""), ...
    "oi_plot_spectrum:Metadata", "SegmentDescription must be explicit nonblank text");
degreesOfFreedom = oi_get_option(options, "DegreesOfFreedom", NaN);
inputRepresentation = string(oi_get_option(options, "InputRepresentation", ...
    "precomputed-frequency-density"));
assert(isscalar(inputRepresentation) ...
    && inputRepresentation == "precomputed-frequency-density", ...
    "oi_plot_spectrum:InputRepresentation", ...
    "This plotting helper accepts only precomputed frequency-density input; raw samples must be estimated upstream");
estimatorKind = string(oi_get_option(options, "EstimatorKind", "precomputed-unspecified"));
assert(isscalar(estimatorKind) && any(estimatorKind == ...
    ["precomputed-unspecified" "fft" "periodogram" "welch" "lomb-scargle" "other"]), ...
    "oi_plot_spectrum:EstimatorKind", ...
    "EstimatorKind must identify the upstream spectral estimator");
regularSamplingVerified = oi_get_option(options, "RegularSamplingVerified", false);
assert(islogical(regularSamplingVerified) && isscalar(regularSamplingVerified), ...
    "oi_plot_spectrum:RegularSamplingEvidence", ...
    "RegularSamplingVerified must be a logical scalar");
sampleInterval = oi_get_option(options, "SampleInterval", NaN);
assert(isnumeric(sampleInterval) && isreal(sampleInterval) && isscalar(sampleInterval) ...
    && (isnan(sampleInterval) || (isfinite(sampleInterval) && sampleInterval > 0)), ...
    "oi_plot_spectrum:SampleInterval", ...
    "SampleInterval must be positive or NaN when not applicable to precomputed input");
sampleIntervalUnit = string(oi_get_option(options, "SampleIntervalUnit", ""));
regularEstimator = any(estimatorKind == ["fft" "periodogram" "welch"]);
if regularEstimator
    assert(regularSamplingVerified && isfinite(sampleInterval), ...
        "oi_plot_spectrum:RegularSamplingEvidence", ...
        "FFT, periodogram, and Welch spectra require verified regular sampling and a positive SampleInterval");
    sampleIntervalUnit = oi_require_text(sampleIntervalUnit, ...
        "oi_plot_spectrum:RegularSamplingEvidence", ...
        "Regular-sampling evidence requires SampleIntervalUnit");
    assert(isscalar(sampleIntervalUnit), ...
        "oi_plot_spectrum:RegularSamplingEvidence", ...
        "SampleIntervalUnit must be scalar text");
elseif regularSamplingVerified || isfinite(sampleInterval) || strlength(sampleIntervalUnit) > 0
    assert(regularSamplingVerified && isfinite(sampleInterval) ...
        && strlength(sampleIntervalUnit) > 0, ...
        "oi_plot_spectrum:RegularSamplingEvidence", ...
        "Regular-sampling evidence must include verification, interval, and interval unit together");
end
estimatorToolbox = string(oi_get_option(options, "EstimatorToolbox", "none"));
toolboxExecutionVerified = oi_get_option(options, "ToolboxExecutionVerified", false);
assert(isscalar(estimatorToolbox) && islogical(toolboxExecutionVerified) ...
    && isscalar(toolboxExecutionVerified), ...
    "oi_plot_spectrum:ToolboxEvidence", ...
    "EstimatorToolbox and ToolboxExecutionVerified must be scalar evidence fields");
if estimatorKind == "welch"
    assert(estimatorToolbox == "Signal Processing Toolbox" ...
        && toolboxExecutionVerified, ...
        "oi_plot_spectrum:ToolboxEvidence", ...
        "Welch evidence requires verified Signal Processing Toolbox execution upstream");
else
    assert(~toolboxExecutionVerified || estimatorToolbox ~= "none", ...
        "oi_plot_spectrum:ToolboxEvidence", ...
        "Verified toolbox execution requires an explicit toolbox name");
end
assert(all([isscalar(frequencyUnit) isscalar(periodUnit) isscalar(densityUnit) ...
    isscalar(windowDescription) isscalar(detrendDescription) ...
    isscalar(segmentDescription)]), "oi_plot_spectrum:Metadata", ...
    "Frequency, period, density, window, detrend, and segment metadata are required");
assert(isnumeric(degreesOfFreedom) && isreal(degreesOfFreedom) ...
    && isscalar(degreesOfFreedom) && (isnan(degreesOfFreedom) ...
    || (isfinite(degreesOfFreedom) && degreesOfFreedom > 0)), ...
    "oi_plot_spectrum:DegreesOfFreedom", ...
    "DegreesOfFreedom must be positive or NaN when explicitly unknown");
lowerBound = oi_get_option(options, "LowerBound", nan(size(spectralDensity)));
upperBound = oi_get_option(options, "UpperBound", nan(size(spectralDensity)));
lowerBound = lowerBound(:);
upperBound = upperBound(:);
assert(numel(lowerBound) == numel(frequencyValues) ...
    && numel(upperBound) == numel(frequencyValues), ...
    "oi_plot_spectrum:BoundSize", "Confidence bounds must match frequency length");
assert(isnumeric(lowerBound) && isreal(lowerBound) ...
    && isnumeric(upperBound) && isreal(upperBound) ...
    && ~any(isinf(lowerBound)) && ~any(isinf(upperBound)) ...
    && all(lowerBound(isfinite(lowerBound)) > 0) ...
    && all(upperBound(isfinite(upperBound)) > 0), ...
    "oi_plot_spectrum:Bounds", "Finite confidence bounds must be positive");
assert(isequal(isfinite(lowerBound), isfinite(upperBound)), ...
    "oi_plot_spectrum:BoundMaskMismatch", ...
    "LowerBound and UpperBound must have identical finite/NaN masks");
completeBoundMask = isfinite(lowerBound) & isfinite(upperBound);
hasConfidenceBounds = any(completeBoundMask);
assert(~any(completeBoundMask & ~isfinite(spectralDensity)), ...
    "oi_plot_spectrum:BoundWithoutDensity", ...
    "Confidence bounds cannot exist where spectral density is missing");
boundType = string(oi_get_option(options, "BoundType", ""));
confidenceLevel = oi_get_option(options, "ConfidenceLevel", NaN);
if hasConfidenceBounds
    assert(isscalar(boundType) && boundType == "confidence-interval", ...
        "oi_plot_spectrum:BoundType", ...
        "BoundType must be 'confidence-interval' when bounds are supplied");
    assert(isnumeric(confidenceLevel) && isscalar(confidenceLevel) ...
        && isfinite(confidenceLevel) ...
        && confidenceLevel > 0 && confidenceLevel < 1, ...
        "oi_plot_spectrum:ConfidenceLevel", ...
        "ConfidenceLevel must be an explicit fraction between zero and one");
    assert(all(lowerBound(completeBoundMask) <= spectralDensity(completeBoundMask)) ...
        && all(spectralDensity(completeBoundMask) <= upperBound(completeBoundMask)), ...
        "oi_plot_spectrum:BoundOrder", "Complete confidence bounds must enclose the spectrum");
    assert(isequal(completeBoundMask, isfinite(spectralDensity)), ...
        "oi_plot_spectrum:IncompleteConfidenceInterval", ...
        "Confidence intervals must be complete at every finite spectral-density sample");
    assert(isfinite(degreesOfFreedom), ...
        "oi_plot_spectrum:ConfidenceDegreesOfFreedom", ...
        "Confidence intervals require explicit positive DegreesOfFreedom");
else
    assert(isscalar(boundType) && strlength(boundType) == 0 ...
        && isnumeric(confidenceLevel) && isscalar(confidenceLevel) ...
        && isnan(confidenceLevel), ...
        "oi_plot_spectrum:UnusedUncertaintyMetadata", ...
        "Bound metadata must be omitted when no confidence bounds are supplied");
end
if hasConfidenceBounds
    missingBoundCount = sum(isfinite(spectralDensity) & ~completeBoundMask);
    boundStatus = "present";
else
    missingBoundCount = 0;
    boundStatus = "absent";
end
theme = oi_get_option(options, "Theme", struct());
if isempty(fieldnames(theme))
    theme = oi_ocean_theme();
end
titleText = oi_require_text(oi_get_option(options, "Title", "Power spectral density"), ...
    "oi_plot_spectrum:Title", "Title must be explicit nonblank text");
set(axesHandle, "XScale", "log", "YScale", "log");
holdCleanup = oi_hold_axes(axesHandle);
segments = contiguous_segments(completeBoundMask);
bandHandles = gobjects(size(segments,1),1);
for index = 1:size(segments,1)
    range = segments(index,1):segments(index,2);
    polygonX = [frequencyValues(range); flipud(frequencyValues(range))];
    polygonY = [lowerBound(range); flipud(upperBound(range))];
    bandHandles(index) = fill(axesHandle, polygonX, polygonY, ...
        [0.56 0.76 0.87], "EdgeColor", "none", "FaceAlpha", 0.4, ...
        "HandleVisibility", "off");
end
lineHandle = loglog(axesHandle, frequencyValues, spectralDensity, ...
    "Color", theme.NegativeColor, "LineWidth", 1.4, "DisplayName", "Spectral density");
clear holdCleanup;
xlabel(axesHandle, "Frequency (" + frequencyUnit + "); period unit: " ...
    + periodUnit, "Interpreter", "none");
ylabel(axesHandle, "Spectral density (" + densityUnit + ")", "Interpreter", "none");
title(axesHandle, titleText, ...
    "FontWeight", "normal", "Interpreter", "none");
metadataText = "Window: " + windowDescription + newline ...
    + "Detrend: " + detrendDescription + newline ...
    + "Segments: " + segmentDescription + newline ...
    + "DOF: " + string(degreesOfFreedom);
if hasConfidenceBounds
    metadataText = metadataText + newline + "Confidence interval: " ...
        + compose("%.3g%%", 100 * confidenceLevel);
end
text(axesHandle, 0.02, 0.03, metadataText, "Units", "normalized", ...
    "VerticalAlignment", "bottom", "Interpreter", "none", ...
    "FontName", theme.FontName, "FontSize", theme.FontSize, ...
    "Color", theme.TextColor);
oi_apply_axes(axesHandle, theme);
result = struct("Axes", axesHandle, "Line", lineHandle, "Bands", bandHandles, ...
    "MissingMask", isnan(spectralDensity), "MissingCount", sum(isnan(spectralDensity)), ...
    "ValidCount", sum(isfinite(spectralDensity)), "MissingPolicy", missingPolicy, ...
    "CompleteBoundMask", completeBoundMask, "FrequencyUnit", frequencyUnit, ...
    "PeriodUnit", periodUnit, "DensityUnit", densityUnit, ...
    "WindowDescription", windowDescription, "DetrendDescription", detrendDescription, ...
    "SegmentDescription", segmentDescription, "DegreesOfFreedom", degreesOfFreedom, ...
    "InputRepresentation",inputRepresentation,"EstimatorKind",estimatorKind, ...
    "RegularSamplingVerified",regularSamplingVerified, ...
    "SampleInterval",sampleInterval,"SampleIntervalUnit",sampleIntervalUnit, ...
    "EstimatorToolbox",estimatorToolbox, ...
    "ToolboxExecutionVerified",toolboxExecutionVerified, ...
    "BoundType", boundType, "ConfidenceLevel", confidenceLevel, ...
    "BoundStatus", boundStatus, "MissingBoundCount", missingBoundCount, ...
    "valid_count", sum(isfinite(spectralDensity)), "missing_count", ...
    sum(isnan(spectralDensity)));
end

function segments = contiguous_segments(mask)
padded = [false; mask(:); false];
segments = [find(diff(padded) == 1) find(diff(padded) == -1) - 1];
end
