function result = oi_plot_profile(axesHandle, depthValues, variableValues, options)
%OI_PLOT_PROFILE Plot positive-down ocean profiles without changing data.
% Input contract: depth is M-by-1 and profiles are M-by-P real doubles.
% Depth is finite, nonnegative, unique, and strictly increasing. Profiles
% are depth-by-series. NaN values remain line breaks. Missing classes, QC,
% and uncertainty are validated and preserved without filtering or filling.
arguments
    axesHandle (1,1) matlab.graphics.axis.Axes
    depthValues (:,1) double
    variableValues (:,:) double
    options (1,1) struct = struct()
end
allowedOptions = ["DepthUnit" "MissingPolicy" "QuantityLabel" ...
    "QuantityUnit" "QCFlags" "QCPolicy" "ReportingMissingMask" ...
    "SeriesLabels" "StructuralMissingMask" "Theme" "Title" ...
    "UncertaintyDisplay" "UncertaintyType" "UncertaintyUnit" ...
    "UncertaintyValues" "VerticalReference"];
reject_unknown_options(options, allowedOptions);
assert(numel(depthValues) >= 2 && all(isfinite(depthValues)), ...
    "oi_plot_profile:DepthCoordinate", "Depth coordinates must be finite");
assert(all(depthValues >= 0) && all(diff(depthValues) > 0), ...
    "oi_plot_profile:DepthDirection", ...
    "Depth must be strictly increasing, nonnegative, and positive downward");
assert(size(variableValues,1) == numel(depthValues) && size(variableValues,2) >= 1, ...
    "oi_plot_profile:SizeMismatch", "Profile rows must match depth coordinates");
assert(isreal(variableValues) && ~any(isinf(variableValues), "all"), ...
    "oi_plot_profile:InvalidValues", "Profiles may contain NaN but not Inf or complex values");
assert(all(any(isfinite(variableValues),1)), "oi_plot_profile:EmptySeries", ...
    "Every profile must contain a finite sample");
missingPolicy = string(oi_get_option(options, "MissingPolicy", "preserve"));
assert(isscalar(missingPolicy) && missingPolicy == "preserve", ...
    "oi_plot_profile:MissingPolicy", "Only MissingPolicy='preserve' is supported");
[structuralMask, reportingMask] = classify_missing(variableValues, options);
[qcFlags, qcLevels, qcCounts, qcProvided] = validate_qc(variableValues, options);
[uncertaintyValues, uncertaintyType, uncertaintyUnit, uncertaintyDisplay, ...
    uncertaintyPresent] = validate_uncertainty(variableValues, options);
uncertaintyMissingCount = 0;
if uncertaintyPresent
    uncertaintyMissingCount = sum(isnan(uncertaintyValues) & isfinite(variableValues),"all");
end
theme = oi_get_option(options, "Theme", struct());
assert(isstruct(theme) && isscalar(theme), "oi_plot_profile:Theme", ...
    "Theme must be a scalar struct");
if isempty(fieldnames(theme))
    theme = oi_ocean_theme();
end
quantityLabel = require_scalar_text(oi_get_option(options, "QuantityLabel", ""), ...
    "oi_plot_profile:Units", "QuantityLabel must be explicit nonblank text");
quantityUnit = require_scalar_text(oi_get_option(options, "QuantityUnit", ""), ...
    "oi_plot_profile:Units", "QuantityUnit must be explicit nonblank text");
depthUnit = require_scalar_text(oi_get_option(options, "DepthUnit", ""), ...
    "oi_plot_profile:Units", "DepthUnit must be explicit nonblank text");
verticalReference = require_scalar_text(oi_get_option(options, "VerticalReference", ""), ...
    "oi_plot_profile:Units", "VerticalReference must be explicit nonblank text");
seriesLabels = oi_require_text(oi_get_option(options, "SeriesLabels", ...
    "Profile " + string(1:size(variableValues,2))), ...
    "oi_plot_profile:SeriesLabels", "SeriesLabels must contain nonblank text");
assert(isvector(seriesLabels) && numel(seriesLabels) == size(variableValues,2), ...
    "oi_plot_profile:SeriesLabels", "SeriesLabels must match profile columns");
seriesLabels = reshape(seriesLabels, 1, []);
titleText = require_scalar_text(oi_get_option(options, "Title", "Ocean profile"), ...
    "oi_plot_profile:Title", "Title must be explicit nonblank text");

holdCleanup = oi_hold_axes(axesHandle);
uncertaintyHandles = gobjects(0,1);
if uncertaintyPresent && uncertaintyDisplay == "band"
    uncertaintyHandles = draw_uncertainty_bands(axesHandle, depthValues, ...
        variableValues, uncertaintyValues, theme);
end
lineHandles = gobjects(size(variableValues,2),1);
lineStyles = ["-" "--" ":" "-."];
for index = 1:size(variableValues,2)
    lineHandles(index) = plot(axesHandle, variableValues(:,index), depthValues, ...
        "LineWidth", 1.4, "Color", theme.LineColors(1 + mod(index-1,size(theme.LineColors,1)),:), ...
        "LineStyle", lineStyles(1 + mod(index-1,numel(lineStyles))), ...
        "DisplayName", seriesLabels(index));
end
clear holdCleanup;
axesHandle.YDir = "reverse";
xlabel(axesHandle, quantityLabel + " (" + quantityUnit + ")", "Interpreter", "none");
ylabel(axesHandle, "Depth (" + depthUnit + ", positive down; reference: " ...
    + verticalReference + ")", "Interpreter", "none");
title(axesHandle, titleText, "FontWeight", "normal", "Interpreter", "none");
oi_apply_axes(axesHandle, theme);
if numel(lineHandles) > 1
    legendHandle = legend(axesHandle, lineHandles, "Location", "eastoutside", ...
        "Box", "off", "Interpreter", "none", "FontName", theme.FontName, ...
        "FontSize", theme.FontSize, "TextColor", theme.TextColor);
else
    legendHandle = gobjects(0);
end
result = struct("Axes", axesHandle, "Lines", lineHandles, "Legend", legendHandle, ...
    "UncertaintyHandles", uncertaintyHandles, "MissingMask", isnan(variableValues), ...
    "StructuralMissingMask", structuralMask, "ReportingMissingMask", reportingMask, ...
    "MissingCount", sum(isnan(variableValues),"all"), ...
    "StructuralMissingCount", sum(structuralMask,"all"), ...
    "ReportingMissingCount", sum(reportingMask,"all"), ...
    "ValidCount", sum(isfinite(variableValues),"all"), "MissingPolicy", missingPolicy, ...
    "QCFlags", qcFlags, "QCLevels", qcLevels, "QCCounts", qcCounts, ...
    "QCProvided", qcProvided, "QCPolicy", "preserve", ...
    "UncertaintyValues", uncertaintyValues, "UncertaintyPresent", uncertaintyPresent, ...
    "UncertaintyType", uncertaintyType, "UncertaintyUnit", uncertaintyUnit, ...
    "UncertaintyDisplay", uncertaintyDisplay, ...
    "UncertaintyMissingCount", uncertaintyMissingCount, ...
    "QuantityUnit", quantityUnit, "DepthUnit", depthUnit, ...
    "VerticalReference", verticalReference, "Interpolated", false, ...
    "valid_count", sum(isfinite(variableValues), "all"), ...
    "missing_count", sum(isnan(variableValues), "all"));
end

function reject_unknown_options(options, allowedOptions)
unknownOptions = setdiff(string(fieldnames(options)), allowedOptions);
assert(isempty(unknownOptions), "oi_plot_profile:UnknownOption", ...
    "Unsupported option: %s", strjoin(unknownOptions, ", "));
end

function value = require_scalar_text(value, identifier, message)
value = oi_require_text(value, identifier, message);
assert(isscalar(value), identifier, message);
end

function [structuralMask, reportingMask] = classify_missing(values, options)
missingMask = isnan(values);
structuralMask = oi_get_option(options, "StructuralMissingMask", false(size(values)));
assert(islogical(structuralMask) && isequal(size(structuralMask), size(values)), ...
    "oi_plot_profile:StructuralMissingMask", ...
    "StructuralMissingMask must be logical and match profile dimensions");
reportingDefault = missingMask & ~structuralMask;
reportingMask = oi_get_option(options, "ReportingMissingMask", reportingDefault);
assert(islogical(reportingMask) && isequal(size(reportingMask), size(values)), ...
    "oi_plot_profile:ReportingMissingMask", ...
    "ReportingMissingMask must be logical and match profile dimensions");
assert(~any(structuralMask & reportingMask, "all"), ...
    "oi_plot_profile:MissingMaskOverlap", "Missing classifications must be disjoint");
assert(isequal(structuralMask | reportingMask, missingMask), ...
    "oi_plot_profile:MissingMaskCoverage", ...
    "Missing classifications must identify every and only NaN profile sample");
end

function [qcFlags, qcLevels, qcCounts, qcProvided] = validate_qc(values, options)
qcPolicy = string(oi_get_option(options, "QCPolicy", "preserve"));
assert(isscalar(qcPolicy) && qcPolicy == "preserve", ...
    "oi_plot_profile:QCPolicy", "Only QCPolicy='preserve' is supported");
qcProvided = isfield(options, "QCFlags");
if ~qcProvided
    qcFlags = strings(0,1);
    qcLevels = strings(0,1);
    qcCounts = zeros(0,1);
    return;
end
rawFlags = options.QCFlags;
assert(isstring(rawFlags) || iscellstr(rawFlags) || iscategorical(rawFlags), ...
    "oi_plot_profile:QCFlags", "QCFlags must be string, cellstr, or categorical");
qcFlags = strtrim(string(rawFlags));
assert(isequal(size(qcFlags), size(values)) && all(~ismissing(qcFlags),"all") ...
    && all(strlength(qcFlags) > 0,"all"), "oi_plot_profile:QCFlags", ...
    "QCFlags must contain one nonblank flag per profile sample");
[qcLevels, ~, levelIndex] = unique(qcFlags(:), "stable");
qcCounts = accumarray(levelIndex, 1, [numel(qcLevels) 1]);
end

function [uncertainty, type, unit, displayMode, present] = validate_uncertainty(values, options)
present = isfield(options, "UncertaintyValues");
if ~present
    assert(~isfield(options, "UncertaintyType") && ~isfield(options, "UncertaintyUnit") ...
        && ~isfield(options, "UncertaintyDisplay"), ...
        "oi_plot_profile:UncertaintyMetadata", ...
        "Uncertainty metadata requires UncertaintyValues");
    uncertainty = NaN(size(values));
    type = "";
    unit = "";
    displayMode = "none";
    return;
end
uncertainty = options.UncertaintyValues;
assert(isnumeric(uncertainty) && isreal(uncertainty) ...
    && isequal(size(uncertainty), size(values)) ...
    && ~any(isinf(uncertainty),"all") ...
    && all(uncertainty(isfinite(uncertainty)) >= 0), ...
    "oi_plot_profile:UncertaintyValues", ...
    "UncertaintyValues must be aligned, real, nonnegative, and finite or NaN");
assert(~any(isfinite(uncertainty) & isnan(values),"all"), ...
    "oi_plot_profile:UncertaintyAlignment", ...
    "Missing profile samples cannot have finite uncertainty");
assert(any(isfinite(uncertainty),"all"), "oi_plot_profile:UncertaintyValues", ...
    "UncertaintyValues must contain at least one finite magnitude");
type = require_scalar_text(oi_get_option(options, "UncertaintyType", ""), ...
    "oi_plot_profile:UncertaintyMetadata", "UncertaintyType must be explicit");
unit = require_scalar_text(oi_get_option(options, "UncertaintyUnit", ""), ...
    "oi_plot_profile:UncertaintyMetadata", "UncertaintyUnit must be explicit");
displayMode = string(oi_get_option(options, "UncertaintyDisplay", "band"));
assert(isscalar(displayMode) && any(displayMode == ["band" "metadata"]), ...
    "oi_plot_profile:UncertaintyDisplay", ...
    "UncertaintyDisplay must be 'band' or 'metadata'");
end

function handles = draw_uncertainty_bands(axesHandle, depth, values, uncertainty, theme)
handles = gobjects(0,1);
for seriesIndex = 1:size(values,2)
    complete = isfinite(values(:,seriesIndex)) & isfinite(uncertainty(:,seriesIndex));
    boundaries = diff([false; complete; false]);
    starts = find(boundaries == 1);
    stops = find(boundaries == -1) - 1;
    color = theme.LineColors(1 + mod(seriesIndex-1,size(theme.LineColors,1)),:);
    for segmentIndex = 1:numel(starts)
        indices = starts(segmentIndex):stops(segmentIndex);
        if numel(indices) < 2
            continue;
        end
        lower = values(indices,seriesIndex) - uncertainty(indices,seriesIndex);
        upper = values(indices,seriesIndex) + uncertainty(indices,seriesIndex);
        handle = patch(axesHandle, [lower; flipud(upper)], ...
            [depth(indices); flipud(depth(indices))], color, ...
            "FaceAlpha", 0.16, "EdgeColor", "none", "HandleVisibility", "off");
        handles(end+1,1) = handle;
    end
end
end
