function result = oi_plot_direction_rose(axesHandle, directionDegrees, options)
%OI_PLOT_DIRECTION_ROSE Plot a north-up clockwise directional distribution.
% Input contract: directionDegrees is a real vector in degrees clockwise
% from true north. DirectionConvention must be "from" or "to". Optional
% weights are finite and nonnegative. NaN direction/weight pairs are omitted
% and counted; directions are wrapped to [0,360) without changing convention.
arguments
    axesHandle (1,1)
    directionDegrees double
    options (1,1) struct = struct()
end
assert(isgraphics(axesHandle) ...
    && (isa(axesHandle, "matlab.graphics.axis.Axes") ...
    || isa(axesHandle, "matlab.graphics.axis.PolarAxes")), ...
    "oi_plot_direction_rose:InvalidAxes", ...
    "axesHandle must be a valid graphics axes");
assert((isempty(directionDegrees) || isvector(directionDegrees)) ...
    && isreal(directionDegrees) ...
    && ~any(isinf(directionDegrees)), "oi_plot_direction_rose:InvalidDirection", ...
    "Directions must be a real vector and may contain NaN but not Inf");
assert(~isempty(directionDegrees), "oi_plot_direction_rose:NoSamples", ...
    "At least one direction sample is required");
directionDegrees = directionDegrees(:);
missingPolicy = lower(oi_require_text( ...
    oi_get_option(options, "MissingPolicy", "preserve"), ...
    "oi_plot_direction_rose:MissingPolicy", ...
    "MissingPolicy must be explicit nonblank text"));
assert(isscalar(missingPolicy) && missingPolicy == "preserve", ...
    "oi_plot_direction_rose:MissingPolicy", ...
    "Only MissingPolicy='preserve' is supported");
directionConvention = lower(oi_require_text( ...
    oi_get_option(options, "DirectionConvention", ""), ...
    "oi_plot_direction_rose:DirectionConvention", ...
    "DirectionConvention must be explicit nonblank text"));
assert(isscalar(directionConvention) ...
    && any(directionConvention == ["from" "to"]), ...
    "oi_plot_direction_rose:DirectionConvention", ...
    "DirectionConvention must explicitly be 'from' or 'to'");
displayConvention = lower(oi_require_text( ...
    oi_get_option(options, "DisplayConvention", directionConvention), ...
    "oi_plot_direction_rose:DisplayConvention", ...
    "DisplayConvention must be explicit nonblank text"));
assert(isscalar(displayConvention) ...
    && any(displayConvention == ["from" "to"]), ...
    "oi_plot_direction_rose:DisplayConvention", ...
    "DisplayConvention must explicitly be 'from' or 'to'");
directionUnit = oi_require_text(oi_get_option(options, "DirectionUnit", ""), ...
    "oi_plot_direction_rose:Units", ...
    "DirectionUnit must explicitly describe the angular convention");
normalizedDirectionUnit = lower(directionUnit);
degreeUnits = ["degree" "degrees" "deg" "degree-true" "degrees-true" ...
    "degree clockwise from true north" "degrees clockwise from true north"];
assert(isscalar(normalizedDirectionUnit) ...
    && any(normalizedDirectionUnit == degreeUnits), ...
    "oi_plot_direction_rose:Units", ...
    "directionDegrees requires an explicit degree unit");
normalization = lower(oi_require_text(oi_get_option(options, "Normalization", ""), ...
    "oi_plot_direction_rose:Normalization", ...
    "Normalization must be explicit nonblank text"));
assert(isscalar(normalization) ...
    && any(normalization == ["count" "percent" "weight"]), ...
    "oi_plot_direction_rose:Normalization", ...
    "Normalization must be count, percent, or weight");
binCount = oi_get_option(options, "BinCount", 16);
assert(isnumeric(binCount) && isreal(binCount) && isscalar(binCount) ...
    && isfinite(binCount) && binCount >= 4 ...
    && fix(binCount) == binCount, "oi_plot_direction_rose:BinCount", ...
    "BinCount must be an integer of at least four");
weights = oi_get_option(options, "Weights", ones(size(directionDegrees)));
if isempty(weights)
    weights = ones(size(directionDegrees));
end
assert(normalization ~= "weight" || (isfield(options, "Weights") ...
    && ~isempty(options.Weights)), "oi_plot_direction_rose:WeightsRequired", ...
    "Normalization='weight' requires explicit Weights");
weights = weights(:);
assert(isnumeric(weights) && numel(weights) == numel(directionDegrees) ...
    && isreal(weights) ...
    && ~any(isinf(weights)) && all(weights(isfinite(weights)) >= 0), ...
    "oi_plot_direction_rose:Weights", ...
    "Weights must align with directions and be finite nonnegative or NaN");
validMask = isfinite(directionDegrees) & isfinite(weights);
assert(any(validMask), "oi_plot_direction_rose:NoValidSamples", ...
    "At least one finite direction-weight pair is required");
weightMeaning = lower(oi_require_text( ...
    oi_get_option(options, "WeightMeaning", "statistical-weight"), ...
    "oi_plot_direction_rose:WeightMeaning", ...
    "WeightMeaning must be explicit nonblank text"));
assert(isscalar(weightMeaning) ...
    && any(weightMeaning == ["statistical-weight" "speed"]), ...
    "oi_plot_direction_rose:WeightMeaning", ...
    "WeightMeaning must be 'statistical-weight' or 'speed'");
calmThreshold = oi_get_option(options, "CalmThreshold", 0);
assert(isnumeric(calmThreshold) && isreal(calmThreshold) && isscalar(calmThreshold) ...
    && isfinite(calmThreshold) && calmThreshold >= 0, ...
    "oi_plot_direction_rose:CalmThreshold", ...
    "CalmThreshold must be a finite nonnegative scalar");
assert(weightMeaning == "speed" || calmThreshold == 0, ...
    "oi_plot_direction_rose:CalmThreshold", ...
    "A nonzero CalmThreshold is valid only when WeightMeaning='speed'");
calmMask = false(size(validMask));
if weightMeaning == "speed"
    calmMask = validMask & weights <= calmThreshold;
end
directionalMask = validMask & ~calmMask;
assert(any(directionalMask), "oi_plot_direction_rose:NoDirectionalSamples", ...
    "At least one non-calm direction-weight pair is required");
displayDirection = directionDegrees;
conversionApplied = displayConvention ~= directionConvention;
if conversionApplied
    displayDirection = displayDirection + 180;
end
centeredDirection = mod(displayDirection(directionalMask), 360);
validWeights = weights(directionalMask);
binWidth = 360 / binCount;
binEdges = ((0:binCount) - 0.5) * binWidth;
binCenters = (0:binCount - 1) * binWidth;
binIndex = mod(floor((centeredDirection + binWidth / 2) / binWidth), binCount) + 1;
weightedCounts = accumarray(binIndex, validWeights, [binCount 1], @sum, 0);
sampleCounts = accumarray(binIndex, 1, [binCount 1], @sum, 0);
if normalization == "count"
    plotValues = sampleCounts;
    radialUnit = "sample count";
elseif normalization == "weight"
    plotValues = weightedCounts;
    radialUnit = "weight sum";
else
    totalWeight = sum(validWeights);
    assert(totalWeight > 0, "oi_plot_direction_rose:ZeroWeight", ...
        "Percent normalization requires positive total weight");
    plotValues = 100 * weightedCounts / totalWeight;
    radialUnit = "percent";
end
titleText = oi_require_text(oi_get_option(options, "Title", "Directional rose"), ...
    "oi_plot_direction_rose:Title", "Title must be explicit nonblank text");
polarAxes = ensure_polar_axes(axesHandle);
theme = oi_get_option(options, "Theme", struct());
if isempty(fieldnames(theme))
    theme = oi_ocean_theme();
end
histogramHandle = polarhistogram(polarAxes, "BinEdges", deg2rad(binEdges), ...
    "BinCounts", plotValues', "FaceColor", theme.AccentColor, ...
    "EdgeColor", "white", "LineWidth", 0.6);
polarAxes.ThetaZeroLocation = "top";
polarAxes.ThetaDir = "clockwise";
polarAxes.ThetaTick = 0:45:315;
polarAxes.ThetaTickLabel = ["N" "NE" "E" "SE" "S" "SW" "W" "NW"];
directionLabel = "Direction " + displayConvention ...
    + " (degree; clockwise from true north)";
title(polarAxes, [titleText + " (" + radialUnit + ")"; directionLabel], ...
    "FontWeight", "normal", "Interpreter", "none");
setappdata(polarAxes, "OI_AxisLabels", struct( ...
    "xlabel", directionLabel, ...
    "ylabel", radialUnit));
oi_apply_axes(polarAxes, theme);
polarAxes.RTickMode = "auto";
radialTicks = polarAxes.RTick;
polarAxes.RTick = radialTicks(radialTicks > 0);
result = struct("Axes", polarAxes, "Histogram", histogramHandle, ...
    "ValidMask", validMask, "ValidCount", sum(validMask), ...
    "MissingCount", sum(~validMask), "DirectionConvention", directionConvention, ...
    "DisplayConvention",displayConvention,"ConventionConversionApplied",conversionApplied, ...
    "MissingPolicy", missingPolicy, ...
    "DirectionUnit", directionUnit, "Normalization", normalization, ...
    "BinEdgesDegrees", binEdges, "BinCentersDegrees", binCenters, ...
    "BinBoundaryConvention", "clockwise half-open; ties enter the clockwise bin", ...
    "BinValues", plotValues, ...
    "SampleCounts", sampleCounts, "WeightSums", weightedCounts, ...
    "DisplayedDirectionsDegrees",mod(displayDirection,360), ...
    "WeightMeaning",weightMeaning,"CalmThreshold",calmThreshold, ...
    "CalmMask",calmMask,"CalmCount",sum(calmMask), ...
    "DirectionalCount",sum(directionalMask), ...
    "valid_count", sum(validMask), "missing_count", sum(~validMask));
end

function polarAxes = ensure_polar_axes(axesHandle)
if isa(axesHandle, "matlab.graphics.axis.PolarAxes")
    polarAxes = axesHandle;
    cla(polarAxes);
    return;
end
parent = axesHandle.Parent;
position = axesHandle.Position;
hasLayout = isprop(axesHandle, "Layout") && ~isempty(axesHandle.Layout) ...
    && isprop(axesHandle.Layout, "Tile");
if hasLayout
    tile = axesHandle.Layout.Tile;
end
if isa(parent, "matlab.graphics.layout.TiledChartLayout")
    delete(axesHandle);
    polarAxes = polaraxes(parent);
    if hasLayout
        polarAxes.Layout.Tile = tile;
    end
else
    polarAxes = polaraxes("Parent", parent, "Units", axesHandle.Units);
    if isprop(polarAxes, "PositionConstraint") && isprop(polarAxes, "OuterPosition")
        polarAxes.PositionConstraint = "outerposition";
        polarAxes.OuterPosition = axesHandle.OuterPosition;
    else
        polarAxes.Position = position;
    end
    set(axesHandle, "Visible", "off", "HandleVisibility", "off", "HitTest", "off");
    setappdata(axesHandle, "OI_ReplacementAxes", polarAxes);
end
end
