function manifest = oi_write_manifest(manifestPath, figureEntries)
%OI_WRITE_MANIFEST Validate entries and atomically write figures.json.
% Input contract: figureEntries is a deterministic struct array returned by
% oi_export_figure. Export paths must be relative, unique, and refer to fresh
% nonempty PNG/PDF and optional SVG files beside the manifest. Runtime,
% toolbox, format, byte-count, signature, dimension, and SHA-256 evidence is
% revalidated before the manifest is written. Supplied evidence is immutable:
% mismatches fail instead of being refreshed into a passing record.
% Mixed per-format APIs are summarized as api="mixed" plus sorted unique apis;
% each figure retains its concrete export_api and matching runtime evidence.
arguments
    manifestPath (1,1) string
    figureEntries struct
end
assert(~isempty(figureEntries) && isvector(figureEntries), ...
    "oi_write_manifest:EmptyEntries", "At least one figure entry is required");
figureEntries = figureEntries(:);
assert(~ismissing(manifestPath) && strlength(strtrim(manifestPath)) > 0, ...
    "oi_write_manifest:EmptyPath", ...
    "manifestPath must not be empty");
manifestDirectory = string(fileparts(manifestPath));
if strlength(manifestDirectory) == 0
    manifestDirectory = string(pwd);
end
if ~isfolder(manifestDirectory)
    [created, message] = mkdir(manifestDirectory);
    assert(created, "oi_write_manifest:CreateDirectory", "%s", message);
end
manifestDirectory = canonical_path(manifestDirectory);
[~, manifestName, manifestExtension] = fileparts(char(manifestPath));
assert(strlength(string(manifestName)) > 0, ...
    "oi_write_manifest:InvalidPath", "manifestPath must name a file");
manifestPath = fullfile(manifestDirectory, ...
    string(manifestName) + string(manifestExtension));
ids = strings(1, numel(figureEntries));
files = strings(0, 1);
allToolboxes = strings(0, 1);
allFormats = strings(0, 1);
runtimeReleases = strings(numel(figureEntries), 1);
installedToolboxReference = strings(0, 1);
runtimeBatchModes = false(numel(figureEntries), 1);
runtimeHeadlessModes = false(numel(figureEntries), 1);
exportApis = struct("png", strings(0, 1), "pdf", strings(0, 1), ...
    "svg", strings(0, 1));
artifactSnapshots = repmat(struct("file", "", "bytes", 0, ...
    "sha256", "", "format", ""), 0, 1);
for index = 1:numel(figureEntries)
    entry = figureEntries(index);
    require_fields(entry, ["id" "title" "source" "theme" "exports" ...
        "text_objects" "unmeasured_text_objects" "axes_objects" ...
        "accessibility" "rendering_evidence" ...
        "publication" "interaction" "runtime"]);
    identityValues = [string(entry.id) string(entry.title) ...
        string(entry.source) string(entry.theme)];
    assert(numel(identityValues) == 4 ...
        && all(strlength(strtrim(identityValues)) > 0), ...
        "oi_write_manifest:EmptyIdentity", ...
        "Figure id, title, source, and theme must be explicit and nonempty");
    assert(isstruct(entry.accessibility) ...
        && isfield(entry.accessibility, "alt_text") ...
        && isfield(entry.accessibility, "contrast_ratio") ...
        && isfield(entry.accessibility, "color_only_encoding"), ...
        "oi_write_manifest:AccessibilityEvidence", ...
        "Each figure must include complete accessibility evidence");
    require_fields(entry.rendering_evidence, ["drawnow_completed" ...
        "bounds_audited" "bounds_units" "clipped_count" ...
        "bounds_audit_scope" "bounds_audit_complete" "unmeasured_count" ...
        "text_overlap_count" "normalized_margins" ...
        "font_selection_verified" "png_embedded_dpi_verified" ...
        "physical_dimensions_verified" "visual_inspection_verified" ...
        "pdf_font_embedding_verified"]);
    require_fields(entry.rendering_evidence, "cjk_font_evidence");
    require_fields(entry.rendering_evidence.cjk_font_evidence, ...
        ["text_present" "candidate_verified" "selected_fonts" ...
        "verification_method" "glyph_rendering_verified"]);
    validate_text_audit(entry);
    assert(entry.rendering_evidence.drawnow_completed ...
        && entry.rendering_evidence.bounds_audited ...
        && string(entry.rendering_evidence.bounds_units) == "normalized" ...
        && entry.rendering_evidence.clipped_count == 0 ...
        && entry.rendering_evidence.text_overlap_count == 0 ...
        && isnumeric(entry.rendering_evidence.normalized_margins) ...
        && isequal(size(entry.rendering_evidence.normalized_margins), [1 4]) ...
        && all(isfinite(entry.rendering_evidence.normalized_margins)) ...
        && all(entry.rendering_evidence.normalized_margins >= 0) ...
        && entry.rendering_evidence.font_selection_verified ...
        && entry.rendering_evidence.png_embedded_dpi_verified ...
        && entry.rendering_evidence.physical_dimensions_verified ...
        && ~entry.rendering_evidence.visual_inspection_verified ...
        && ~entry.rendering_evidence.pdf_font_embedding_verified, ...
        "oi_write_manifest:RenderingEvidence", ...
        "Rendering evidence must be measured and must not overstate visual or PDF-font verification");
    cjkEvidence = entry.rendering_evidence.cjk_font_evidence;
    assert(islogical(cjkEvidence.text_present) ...
        && islogical(cjkEvidence.candidate_verified) ...
        && islogical(cjkEvidence.glyph_rendering_verified) ...
        && ~cjkEvidence.glyph_rendering_verified ...
        && strlength(strtrim(string(cjkEvidence.verification_method))) > 0 ...
        && (~cjkEvidence.text_present || cjkEvidence.candidate_verified), ...
        "oi_write_manifest:CJKFontEvidence", ...
        "CJK font evidence must identify the candidate check without claiming glyph verification");
    require_fields(entry, "artifact_freshness");
    require_fields(entry.artifact_freshness, ["export_started_at" ...
        "export_completed_at" "created_in_unique_staging_directory" ...
        "preexisting_destination_rejected" ...
        "content_verified_before_promotion" "promotion_strategy"]);
    assert(entry.artifact_freshness.created_in_unique_staging_directory ...
        && entry.artifact_freshness.preexisting_destination_rejected ...
        && entry.artifact_freshness.content_verified_before_promotion ...
        && string(entry.artifact_freshness.promotion_strategy) ...
            == "same-filesystem rename" ...
        && valid_utc_timestamp(entry.artifact_freshness.export_started_at) ...
        && valid_utc_timestamp(entry.artifact_freshness.export_completed_at), ...
        "oi_write_manifest:FreshnessEvidence", ...
        "Each export must carry verified staging and promotion freshness evidence");
    require_fields(entry.publication, ["layout" "typography" "color"]);
    require_fields(entry.publication.layout, ["stable" "overlap_count" ...
        "clipped_count" "margins"]);
    require_fields(entry.publication.typography, ["glyphs_verified" ...
        "cjk_verified" "pdf_fonts_embedded"]);
    require_fields(entry.publication.color, ["colorblind_safe" ...
        "redundant_encoding"]);
    assert(islogical(entry.publication.layout.stable) ...
        && isscalar(entry.publication.layout.stable) ...
        && entry.publication.layout.stable == entry.rendering_evidence.bounds_audit_complete ...
        && entry.publication.layout.overlap_count == entry.rendering_evidence.text_overlap_count ...
        && entry.publication.layout.clipped_count == entry.rendering_evidence.clipped_count ...
        && isequal(entry.publication.layout.margins, entry.rendering_evidence.normalized_margins) ...
        && ~entry.publication.typography.glyphs_verified ...
        && ~entry.publication.typography.cjk_verified ...
        && ~entry.publication.typography.pdf_fonts_embedded ...
        && ~entry.publication.color.colorblind_safe ...
        && entry.publication.color.redundant_encoding, ...
        "oi_write_manifest:PublicationEvidence", ...
        "Publication evidence must match measured layout and preserve unverified artifact checks");
    require_fields(entry.interaction, ["requested" "enabled" ...
        "desktop_available" "headless"]);
    require_fields(entry.interaction.headless, ["supported" "mode" "verified"]);
    assert(islogical(entry.interaction.requested) ...
        && islogical(entry.interaction.enabled) ...
        && islogical(entry.interaction.desktop_available) ...
        && entry.interaction.headless.supported ...
        && string(entry.interaction.headless.mode) == "static_export", ...
        "oi_write_manifest:InteractionEvidence", ...
        "Interaction evidence must use the canonical desktop/headless contract");
    require_fields(entry.runtime, ["minimum_release" "matlab_version" ...
        "matlab_release" "jvm_available" "desktop_available" ...
        "batch_startup_option_used" "figure_visible" ...
        "headless_static_export" "required_toolboxes" ...
        "installed_toolboxes" "toolboxes_verified" ...
        "toolbox_verification" "toolbox_installation_verified" ...
        "toolbox_license_verified" "toolbox_invocation_verified" ...
        "export_api"]);
    assert(string(entry.runtime.minimum_release) == "R2019b" ...
        && strlength(string(entry.runtime.matlab_version)) > 0 ...
        && strlength(string(entry.runtime.matlab_release)) > 0 ...
        && islogical(entry.runtime.jvm_available) ...
        && islogical(entry.runtime.desktop_available) ...
        && islogical(entry.runtime.batch_startup_option_used) ...
        && any(string(entry.runtime.figure_visible) == ["on" "off"]) ...
        && islogical(entry.runtime.headless_static_export) ...
        && entry.runtime.headless_static_export ...
            == (string(entry.runtime.figure_visible) == "off") ...
        && entry.runtime.toolboxes_verified ...
        && entry.runtime.toolbox_installation_verified ...
        && ~entry.runtime.toolbox_license_verified ...
        && ~entry.runtime.toolbox_invocation_verified ...
        && string(entry.runtime.toolbox_verification) ...
            == "installed product names returned by ver", ...
        "oi_write_manifest:RuntimeEvidence", ...
        "Each figure must include verified MATLAB release, headless, and toolbox evidence");
    requiredToolboxes = string(entry.runtime.required_toolboxes(:));
    installedToolboxes = sort(string(entry.runtime.installed_toolboxes(:)));
    assert(all(~ismissing(requiredToolboxes)) ...
        && all(strlength(strtrim(requiredToolboxes)) > 0), ...
        "oi_write_manifest:RuntimeEvidence", ...
        "Runtime required_toolboxes must contain exact nonempty product names");
    assert(~isempty(installedToolboxes) ...
        && all(~ismissing(installedToolboxes)) ...
        && all(strlength(strtrim(installedToolboxes)) > 0) ...
        && any(strcmpi(installedToolboxes, "MATLAB")) ...
        && all(ismember(lower(requiredToolboxes), lower(installedToolboxes))), ...
        "oi_write_manifest:RuntimeEvidence", ...
        "Installed products must include MATLAB and every required toolbox");
    if index == 1
        installedToolboxReference = installedToolboxes;
    else
        assert(isequal(installedToolboxReference, installedToolboxes), ...
            "oi_write_manifest:MixedRuntime", ...
            "All entries must report the same installed MATLAB products");
    end
    allToolboxes = [allToolboxes; requiredToolboxes]; %#ok<AGROW>
    runtimeReleases(index) = string(entry.runtime.matlab_release);
    runtimeBatchModes(index) = entry.runtime.batch_startup_option_used;
    runtimeHeadlessModes(index) = entry.runtime.headless_static_export;
    require_fields(entry.exports, ["png" "pdf"]);
    ids(index) = string(entry.id);
    exportFormats = string(fieldnames(entry.exports));
    assert(all(ismember(exportFormats, ["png" "pdf" "svg"])), ...
        "oi_write_manifest:UnsupportedFormat", ...
        "Only PNG, PDF, and SVG export records are supported");
    orderedFormats = ["png"; "pdf"];
    if isfield(entry.exports, "svg")
        orderedFormats(end + 1, 1) = "svg";
    end
    for exportIndex = 1:numel(orderedFormats)
        format = orderedFormats(exportIndex);
        exportRecord = entry.exports.(char(format));
        require_fields(exportRecord, ["figure_id" "title" "source" "theme" ...
            "file" "width" "height" "bytes" "sha256" "export_api"]);
        exportIdentity = [string(exportRecord.figure_id) string(exportRecord.title) ...
            string(exportRecord.source) string(exportRecord.theme)];
        assert(isequal(exportIdentity, identityValues), ...
            "oi_write_manifest:MetadataMismatch", ...
            "Every format must preserve the figure id, title, source, and theme");
        exportApi = string(exportRecord.export_api);
        require_fields(entry.runtime.export_api, format);
        runtimeApi = string(entry.runtime.export_api.(char(format)));
        assert(isscalar(exportApi) && ~ismissing(exportApi) ...
            && isscalar(runtimeApi) && ~ismissing(runtimeApi) ...
            && any(exportApi == ["exportgraphics" "print"]) ...
            && exportApi == runtimeApi, ...
            "oi_write_manifest:ExportApiMismatch", ...
            "Artifact and runtime export APIs must match for %s", format);
        formatApis = exportApis.(char(format));
        formatApis(end + 1, 1) = exportApi;
        exportApis.(char(format)) = formatApis;
        relativePath = replace(string(exportRecord.file), "\", "/");
        assert(is_safe_relative_path(relativePath), ...
            "oi_write_manifest:UnsafeExportPath", "Export paths must be safe and relative");
        [~, ~, extension] = fileparts(char(relativePath));
        assert(lower(string(extension)) == "." + format, ...
            "oi_write_manifest:FormatMismatch", ...
            "Export extension does not match its manifest format: %s", relativePath);
        assert(string(exportRecord.file) == relativePath, ...
            "oi_write_manifest:UnsafeExportPath", ...
            "Export paths must use canonical forward separators: %s", exportRecord.file);
        files(end + 1, 1) = relativePath; %#ok<AGROW>
        allFormats(end + 1, 1) = format; %#ok<AGROW>
        absolutePath = fullfile(manifestDirectory, relativePath);
        canonicalArtifactPath = canonical_path(absolutePath);
        assert(is_within_directory(canonicalArtifactPath, manifestDirectory), ...
            "oi_write_manifest:UnsafeExportPath", ...
            "Export path escapes the manifest directory: %s", relativePath);
        absolutePath = canonicalArtifactPath;
        snapshot = validate_artifact_evidence( ...
            absolutePath, relativePath, exportRecord, format);
        validate_artifact(absolutePath, exportRecord, format);
        artifactSnapshots(end + 1, 1) = snapshot; %#ok<AGROW>
    end
    validate_cross_format_geometry(entry);
    figureEntries(index) = entry;
end
assert(numel(unique(ids)) == numel(ids), "oi_write_manifest:DuplicateId", ...
    "Figure ids must be unique");
assert(issorted(ids), "oi_write_manifest:NonDeterministicOrder", ...
    "Figure ids must be sorted for deterministic manifests");
assert(numel(unique(files)) == numel(files), "oi_write_manifest:DuplicateFile", ...
    "Export file paths must be unique");
assert(numel(unique(runtimeReleases)) == 1, ...
    "oi_write_manifest:MixedRuntime", ...
    "All entries in one manifest must come from the same MATLAB release");
requiredToolboxes = sort(unique(allToolboxes));
canonicalFormats = ["png"; "pdf"; "svg"];
exportFormats = canonicalFormats(ismember(canonicalFormats, unique(allFormats)));
exportStrategies = struct();
for formatIndex = 1:numel(exportFormats)
    format = exportFormats(formatIndex);
    formatApis = unique(exportApis.(char(format)));
    if isscalar(formatApis)
        exportStrategies.(char(format)) = struct("api", formatApis(1));
    else
        exportStrategies.(char(format)) = struct("api", "mixed", "apis", formatApis);
    end
end
artifactValidation = struct("status", "passed", "verified", true, ...
    "verified_by", "oi_export_figure and oi_write_manifest");
visualInspection = struct("status", "not_run", "verified", false);
runtime = struct("engine", "MATLAB", "runtime_status", "ready", ...
    "execution_verified", true, "matlab_release", runtimeReleases(1), ...
    "installed_toolboxes", installedToolboxReference, ...
    "required_toolboxes", requiredToolboxes, ...
    "toolbox_verification_scope", "installation_only", ...
    "toolbox_license_verified", false, ...
    "toolbox_invocation_verified", false, ...
    "export_strategies", exportStrategies, ...
    "batch_startup_option_used", all(runtimeBatchModes), ...
    "artifact_validation", artifactValidation, ...
    "visual_inspection", visualInspection, "errors", struct([]));
if all(runtimeHeadlessModes)
    runtime.headless = struct("figure_visible", "off", ...
        "desktop_independent", true, "non_interactive", true, ...
        "dialogs", false, "wait_for_input", false, "no_jvm", false, ...
        "batch_api", "matlab -batch");
end
manifest = struct("schema_version", 2, ...
    "generated_at", char(datetime("now", "TimeZone", "UTC", ...
        "Format", "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'")), ...
    "generator", "Ocean Intelligence MATLAB native assets", ...
    "runtime_status", "ready", ...
    "execution_verified", true, ...
    "matlab_release", runtimeReleases(1), ...
    "minimum_matlab_release", "R2019b", ...
    "toolboxes", installedToolboxReference, ...
    "required_toolboxes", requiredToolboxes, ...
    "export_formats", exportFormats, ...
    "export_strategies", exportStrategies, ...
    "runtime", runtime, ...
    "runtime_contract", struct("authoritative_runtime", "MATLAB", ...
        "jvm_required", false, "toolbox_check", "ver product Name", ...
        "required_toolboxes", requiredToolboxes, ...
        "toolbox_installation_verified", true, ...
        "toolbox_license_verified", false, ...
        "toolbox_invocation_verified", false, ...
        "octave_substitution_allowed", false), ...
    "artifact_validation", artifactValidation, ...
    "visual_inspection", visualInspection, ...
    "warnings", strings(0, 1), ...
    "errors", struct([]), ...
    "figures", figureEntries);
temporaryPath = string(tempname(manifestDirectory)) + ".json";
cleanup = onCleanup(@() delete_if_present(temporaryPath));
assert_artifacts_unchanged(manifestDirectory, artifactSnapshots);
fileHandle = fopen(char(temporaryPath), "w", "n", "UTF-8");
assert(fileHandle >= 0, "oi_write_manifest:OpenFailed", ...
    "Cannot open temporary manifest file");
fileCleanup = onCleanup(@() fclose(fileHandle));
fwrite(fileHandle, jsonencode(manifest), "char");
clear fileCleanup;
assert_artifacts_unchanged(manifestDirectory, artifactSnapshots);
validate_written_manifest(temporaryPath, manifestDirectory, artifactSnapshots);
atomic_replace_file(temporaryPath, manifestPath);
clear cleanup;
info = dir(manifestPath);
assert(~isempty(info) && info.bytes > 0, "oi_write_manifest:EmptyManifest", ...
    "Manifest was not written or is empty");
validate_written_manifest(manifestPath, manifestDirectory, artifactSnapshots);
end

function validate_text_audit(entry)
unmeasured = entry.unmeasured_text_objects;
fields = ["role"; "string"; "font_name"; "font_size"; "class"; "geometry_status"];
assert(isstruct(unmeasured) && (isempty(unmeasured) || isvector(unmeasured)) ...
    && isequal(sort(string(fieldnames(unmeasured))), sort(fields)), ...
    "oi_write_manifest:UnmeasuredTextEvidence", ...
    "Unmeasured layout text must contain only public text/font identity and unverified geometry status");
for index = 1:numel(unmeasured)
    record = unmeasured(index);
    for fieldName = ["role" "string" "font_name" "class" "geometry_status"]
        value = record.(char(fieldName));
        assert((ischar(value) || isstring(value)) && isscalar(string(value)) ...
            && ~ismissing(string(value)) && strlength(strtrim(string(value))) > 0, ...
            "oi_write_manifest:UnmeasuredTextEvidence", ...
            "Unmeasured layout text %s must be explicit nonempty text", fieldName);
    end
    assert(any(string(record.role) == ["layout.title" "layout.subtitle" ...
            "layout.xlabel" "layout.ylabel"]) ...
        && string(record.class) == "matlab.graphics.layout.Text" ...
        && string(record.geometry_status) == "unverified" ...
        && positive_scalar(record.font_size), ...
        "oi_write_manifest:UnmeasuredTextEvidence", ...
        "Native layout text has no measured geometry; its class, role, font, and status must be honest");
    assert(any(string(record.font_name) == string(entry.rendering_evidence.cjk_font_evidence.selected_fonts)), ...
        "oi_write_manifest:CJKFontEvidence", ...
        "Unmeasured layout fonts must be included in the audited font list");
end
rendering = entry.rendering_evidence;
assert(islogical(rendering.bounds_audited) && isscalar(rendering.bounds_audited) ...
    && rendering.bounds_audited ...
    && isscalar(string(rendering.bounds_audit_scope)) ...
    && string(rendering.bounds_audit_scope) == "measured_objects_only" ...
    && islogical(rendering.bounds_audit_complete) && isscalar(rendering.bounds_audit_complete) ...
    && rendering.bounds_audit_complete == isempty(unmeasured) ...
    && isnumeric(rendering.unmeasured_count) && isreal(rendering.unmeasured_count) ...
    && isscalar(rendering.unmeasured_count) && isfinite(rendering.unmeasured_count) ...
    && rendering.unmeasured_count == numel(unmeasured), ...
    "oi_write_manifest:BoundsAuditEvidence", ...
    "Bounds audit scope, completeness, and unmeasured count must match the unmeasured text list");
require_fields(entry.text_objects, "string");
require_fields(entry.axes_objects, ["xlabel" "ylabel"]);
require_fields(entry.accessibility, ["cjk_text_present" "cjk_font_verified"]);
require_fields(rendering, "cjk_font_candidate_verified");
renderedText = strjoin([string({entry.text_objects.string}) ...
    string({unmeasured.string}) ...
    string({entry.axes_objects.xlabel}) string({entry.axes_objects.ylabel})], " ");
codeUnits = double(char(renderedText));
cjkPresent = any((codeUnits >= hex2dec("3400") & codeUnits <= hex2dec("9FFF")) ...
    | (codeUnits >= hex2dec("F900") & codeUnits <= hex2dec("FAFF")) ...
    | (codeUnits >= hex2dec("3040") & codeUnits <= hex2dec("30FF")) ...
    | (codeUnits >= hex2dec("AC00") & codeUnits <= hex2dec("D7AF")));
assert(islogical(entry.accessibility.cjk_text_present) ...
    && isequal(entry.accessibility.cjk_text_present, cjkPresent) ...
    && isequal(rendering.cjk_font_evidence.text_present, cjkPresent) ...
    && islogical(entry.accessibility.cjk_font_verified) ...
    && isscalar(entry.accessibility.cjk_font_verified) ...
    && isequal(entry.accessibility.cjk_font_verified, rendering.cjk_font_evidence.candidate_verified) ...
    && isequal(rendering.cjk_font_candidate_verified, rendering.cjk_font_evidence.candidate_verified), ...
    "oi_write_manifest:CJKFontEvidence", ...
    "CJK presence must include unmeasured layout strings and candidate evidence must agree");
end

function snapshot = validate_artifact_evidence(filePath, relativePath, exportRecord, format)
assert(isnumeric(exportRecord.bytes) && isreal(exportRecord.bytes) ...
    && isscalar(exportRecord.bytes) && isfinite(exportRecord.bytes) ...
    && exportRecord.bytes > 0 && exportRecord.bytes == fix(exportRecord.bytes), ...
    "oi_write_manifest:ByteMismatch", ...
    "Manifest byte count must be a positive integer: %s", relativePath);
declaredDigest = string(exportRecord.sha256);
assert(isscalar(declaredDigest) && ~ismissing(declaredDigest) ...
    && ~isempty(regexp(char(declaredDigest), "^[0-9A-Fa-f]{64}$", "once")), ...
    "oi_write_manifest:HashMismatch", ...
    "Manifest SHA-256 must contain exactly 64 hexadecimal digits: %s", relativePath);
fileInfoBefore = dir(filePath);
assert(isscalar(fileInfoBefore) && fileInfoBefore.bytes > 0, ...
    "oi_write_manifest:MissingExport", ...
    "Manifest export is missing or empty: %s", filePath);
assert(fileInfoBefore.bytes == exportRecord.bytes, ...
    "oi_write_manifest:ByteMismatch", ...
    "Manifest byte count does not match the artifact: %s", relativePath);
digest = oi_sha256_file(filePath);
fileInfoAfter = dir(filePath);
assert(isscalar(fileInfoAfter) && fileInfoAfter.bytes == fileInfoBefore.bytes, ...
    "oi_write_manifest:ByteMismatch", ...
    "Artifact byte count changed during validation: %s", relativePath);
assert(strcmpi(string(digest), declaredDigest), ...
    "oi_write_manifest:HashMismatch", ...
    "Manifest SHA-256 does not match the artifact: %s", relativePath);
snapshot = struct("file", relativePath, "bytes", exportRecord.bytes, ...
    "sha256", declaredDigest, "format", format);
end

function validate_cross_format_geometry(entry)
png = entry.exports.png;
pdf = entry.exports.pdf;
pngSize = [png.width / png.dpi png.height / png.dpi];
pdfSize = [pdf.width / 72 pdf.height / 72];
assert(all(abs(pngSize - pdfSize) <= 1 / 72), ...
    "oi_write_manifest:PhysicalSizeMismatch", ...
    "PNG and PDF physical dimensions must match for figure %s", entry.id);
if isfield(entry.exports, "svg")
    svg = entry.exports.svg;
    svgSize = [svg.physical_width_in svg.physical_height_in];
    assert(all(abs(pngSize - svgSize) <= 1 / 72), ...
        "oi_write_manifest:PhysicalSizeMismatch", ...
        "PNG, PDF, and SVG physical dimensions must match for figure %s", entry.id);
end
end

function value = svg_physical_length(root, attributeName)
attribute = string(char(root.getAttribute(char(attributeName))));
value = str2double(attribute);
assert(isfinite(value) && value > 0, "oi_write_manifest:InvalidSvg", ...
    "SVG %s must contain a positive physical length", attributeName);
end

function assert_artifacts_unchanged(manifestDirectory, snapshots)
for index = 1:numel(snapshots)
    filePath = canonical_path(fullfile(manifestDirectory, snapshots(index).file));
    assert(is_within_directory(filePath, manifestDirectory), ...
        "oi_write_manifest:UnsafeExportPath", ...
        "Export path escapes the manifest directory: %s", snapshots(index).file);
    digest = oi_sha256_file(filePath);
    fileInfo = dir(filePath);
    assert(isscalar(fileInfo) && fileInfo.bytes == snapshots(index).bytes, ...
        "oi_write_manifest:ByteMismatch", ...
        "Artifact byte count changed after metadata freeze: %s", snapshots(index).file);
    assert(strcmpi(digest, snapshots(index).sha256), ...
        "oi_write_manifest:HashMismatch", ...
        "Artifact SHA-256 changed after metadata freeze: %s", snapshots(index).file);
end
end

function validate_written_manifest(manifestPath, manifestDirectory, snapshots)
decoded = jsondecode(fileread(manifestPath));
assert(isstruct(decoded) && isfield(decoded, "figures"), ...
    "oi_write_manifest:SelfValidation", ...
    "Written manifest cannot be decoded into the expected schema");
figures = decoded.figures;
if iscell(figures)
    figures = [figures{:}];
end
seen = strings(0, 1);
for figureIndex = 1:numel(figures)
    exports = figures(figureIndex).exports;
    formats = fieldnames(exports);
    for formatIndex = 1:numel(formats)
        record = exports.(formats{formatIndex});
        relativePath = replace(string(record.file), "\", "/");
        assert(is_safe_relative_path(relativePath), ...
            "oi_write_manifest:UnsafeExportPath", ...
            "Written manifest contains an unsafe artifact path");
        snapshotIndex = find(string({snapshots.file}) == relativePath, 1);
        assert(~isempty(snapshotIndex), "oi_write_manifest:SelfValidation", ...
            "Written manifest references an artifact outside the frozen set: %s", relativePath);
        filePath = canonical_path(fullfile(manifestDirectory, relativePath));
        digest = oi_sha256_file(filePath);
        fileInfo = dir(filePath);
        assert(isscalar(fileInfo) && fileInfo.bytes == record.bytes ...
            && fileInfo.bytes == snapshots(snapshotIndex).bytes, ...
            "oi_write_manifest:ByteMismatch", ...
            "Written manifest byte count is stale: %s", relativePath);
        assert(strcmpi(digest, string(record.sha256)) ...
            && strcmpi(digest, snapshots(snapshotIndex).sha256), ...
            "oi_write_manifest:HashMismatch", ...
            "Written manifest SHA-256 is stale: %s", relativePath);
        seen(end + 1, 1) = relativePath; %#ok<AGROW>
    end
end
assert(numel(seen) == numel(snapshots) && numel(unique(seen)) == numel(seen), ...
    "oi_write_manifest:SelfValidation", ...
    "Written manifest does not contain the frozen artifact set exactly once");
end

function [dpiX, dpiY] = png_physical_dpi(filePath)
fileHandle = fopen(filePath, "rb");
assert(fileHandle >= 0, "oi_write_manifest:InvalidPng", ...
    "Cannot inspect PNG metadata: %s", filePath);
cleanup = onCleanup(@() fclose(fileHandle));
signature = fread(fileHandle, 8, "*uint8")';
assert(isequal(signature, uint8([137 80 78 71 13 10 26 10])), ...
    "oi_write_manifest:InvalidPng", "PNG signature is invalid: %s", filePath);
dpiX = NaN;
dpiY = NaN;
physicalChunkSeen = false;
while true
    chunkLength = fread(fileHandle, 1, "uint32", 0, "ieee-be");
    assert(~isempty(chunkLength), "oi_write_manifest:InvalidPng", ...
        "PNG ended before image data: %s", filePath);
    chunkType = char(fread(fileHandle, 4, "*uint8")');
    chunkData = fread(fileHandle, double(chunkLength), "*uint8")';
    chunkCrc = fread(fileHandle, 4, "*uint8");
    assert(numel(chunkType) == 4 && numel(chunkData) == double(chunkLength) ...
        && numel(chunkCrc) == 4, "oi_write_manifest:InvalidPng", ...
        "PNG contains a truncated chunk: %s", filePath);
    if strcmp(chunkType, 'pHYs')
        assert(~physicalChunkSeen && chunkLength == 9 && chunkData(9) == 1, ...
            "oi_write_manifest:InvalidPng", ...
            "PNG physical-resolution metadata is invalid: %s", filePath);
        physicalChunkSeen = true;
        pixelsPerMeterX = typecast(uint8(chunkData(1:4)), "uint32");
        pixelsPerMeterY = typecast(uint8(chunkData(5:8)), "uint32");
        [~, ~, endian] = computer;
        if endian == 'L'
            pixelsPerMeterX = swapbytes(pixelsPerMeterX);
            pixelsPerMeterY = swapbytes(pixelsPerMeterY);
        end
        dpiX = double(pixelsPerMeterX) * 0.0254;
        dpiY = double(pixelsPerMeterY) * 0.0254;
    elseif strcmp(chunkType, 'IDAT') || strcmp(chunkType, 'IEND')
        break;
    end
end
clear cleanup;
end

function [widthPoints, heightPoints, pageCount] = pdf_geometry(filePath)
fileHandle = fopen(filePath, "rb");
assert(fileHandle >= 0, "oi_write_manifest:InvalidPdf", ...
    "Cannot inspect PDF geometry: %s", filePath);
cleanup = onCleanup(@() fclose(fileHandle));
pdfText = char(fread(fileHandle, Inf, "*uint8")');
clear cleanup;
pageCount = numel(regexp(pdfText, "/Type\s*/Page(?!s)", "match"));
tokens = regexp(pdfText, ...
    "/MediaBox\s*\[\s*(-?\d+(?:\.\d+)?)\s+(-?\d+(?:\.\d+)?)\s+(-?\d+(?:\.\d+)?)\s+(-?\d+(?:\.\d+)?)\s*\]", ...
    "tokens");
assert(pageCount > 0 && ~isempty(tokens), "oi_write_manifest:InvalidPdf", ...
    "PDF page count or MediaBox is unavailable: %s", filePath);
dimensions = zeros(numel(tokens), 2);
for index = 1:numel(tokens)
    values = str2double(tokens{index});
    dimensions(index, :) = [abs(values(3) - values(1)) abs(values(4) - values(2))];
end
dimensions = unique(round(dimensions, 6), "rows");
assert(size(dimensions, 1) == 1, "oi_write_manifest:InvalidPdf", ...
    "PDF pages do not share one physical size: %s", filePath);
widthPoints = dimensions(1, 1);
heightPoints = dimensions(1, 2);
end

function validate_artifact(filePath, exportRecord, format)
assert(isnumeric(exportRecord.width) && isscalar(exportRecord.width) ...
    && isfinite(exportRecord.width) && exportRecord.width > 0 ...
    && isnumeric(exportRecord.height) && isscalar(exportRecord.height) ...
    && isfinite(exportRecord.height) && exportRecord.height > 0, ...
    "oi_write_manifest:InvalidDimensions", ...
    "Export dimensions must be finite positive scalars: %s", filePath);
prefix = oi_read_file_prefix(filePath, 8192);
if format == "png"
    require_fields(exportRecord, ["dpi" "embedded_dpi_x" "embedded_dpi_y" ...
        "physical_width_in" "physical_height_in"]);
    pngSignature = uint8([137 80 78 71 13 10 26 10]);
    assert(numel(prefix) >= numel(pngSignature) ...
        && isequal(prefix(1:numel(pngSignature))', pngSignature), ...
        "oi_write_manifest:InvalidPng", "PNG signature is invalid: %s", filePath);
    imageInfo = imfinfo(filePath);
    [dpiX, dpiY] = png_physical_dpi(filePath);
    assert(imageInfo.Width == exportRecord.width ...
        && imageInfo.Height == exportRecord.height ...
        && positive_scalar(exportRecord.dpi) ...
        && isfinite(dpiX) && isfinite(dpiY) ...
        && abs(dpiX - dpiY) <= 0.6 ...
        && abs(dpiX - exportRecord.dpi) <= 0.6 ...
        && abs(dpiY - exportRecord.dpi) <= 0.6 ...
        && approximately_equal(dpiX, exportRecord.embedded_dpi_x, 1e-9) ...
        && approximately_equal(dpiY, exportRecord.embedded_dpi_y, 1e-9) ...
        && approximately_equal(exportRecord.physical_width_in, ...
            exportRecord.width / exportRecord.dpi, 1e-9) ...
        && approximately_equal(exportRecord.physical_height_in, ...
            exportRecord.height / exportRecord.dpi, 1e-9), ...
        "oi_write_manifest:InvalidPng", ...
        "PNG dimensions, DPI, or physical-size evidence does not match the artifact: %s", filePath);
elseif format == "pdf"
    require_fields(exportRecord, ["pages" "text" ...
        "physical_width_in" "physical_height_in"]);
    [widthPoints, heightPoints, pageCount] = pdf_geometry(filePath);
    assert(numel(prefix) >= 5 && strcmp(char(prefix(1:5))', '%PDF-') ...
        && pageCount == 1 && exportRecord.pages == pageCount ...
        && approximately_equal(exportRecord.width, widthPoints, 1e-9) ...
        && approximately_equal(exportRecord.height, heightPoints, 1e-9) ...
        && approximately_equal(exportRecord.physical_width_in, widthPoints / 72, 1e-9) ...
        && approximately_equal(exportRecord.physical_height_in, heightPoints / 72, 1e-9) ...
        && strlength(strtrim(string(exportRecord.text))) > 0, ...
        "oi_write_manifest:InvalidPdf", ...
        "PDF signature, geometry, page count, or text evidence is invalid: %s", filePath);
else
    require_fields(exportRecord, ["title" "description" "accessible_name" ...
        "viewbox_width" "viewbox_height" ...
        "physical_width_in" "physical_height_in"]);
    assert(~isempty(regexpi(char(prefix'), "<svg(?=[\s>])", "once")), ...
        "oi_write_manifest:InvalidSvg", "SVG signature is invalid: %s", filePath);
    validate_svg(filePath, exportRecord);
end
end

function validate_svg(filePath, exportRecord)
assert(~isempty(which('xmlread')), ...
    "oi_write_manifest:SvgParserUnavailable", ...
    "SVG validation requires a callable xmlread implementation");
try
    document = xmlread(char(filePath));
catch errorRecord
    error("oi_write_manifest:InvalidSvg", ...
        "SVG XML parsing failed for %s: %s", filePath, errorRecord.message);
end
root = document.getDocumentElement();
assert(strcmpi(char(root.getLocalName()), 'svg') ...
    || strcmpi(char(root.getNodeName()), 'svg'), ...
    "oi_write_manifest:InvalidSvg", "SVG export has no svg root: %s", filePath);
width = svg_pixel_length(root, "width");
height = svg_pixel_length(root, "height");
[viewBoxWidth, viewBoxHeight] = svg_viewbox_size(root);
physicalWidth = svg_physical_length(root, "data-physical-width-in");
physicalHeight = svg_physical_length(root, "data-physical-height-in");
[styleWidth, styleHeight] = svg_style_physical_size(root);
titleNodes = root.getElementsByTagName('title');
descriptionNodes = root.getElementsByTagName('desc');
assert(titleNodes.getLength() > 0 && descriptionNodes.getLength() > 0, ...
    "oi_write_manifest:InvalidSvg", ...
    "SVG must contain title and description metadata: %s", filePath);
role = string(char(root.getAttribute('role')));
accessibleName = string(char(root.getAttribute('aria-label')));
titleNode = titleNodes.item(0);
descriptionNode = descriptionNodes.item(0);
pixelAspect = width / height;
viewBoxAspect = viewBoxWidth / viewBoxHeight;
physicalAspect = physicalWidth / physicalHeight;
assert(approximately_equal(width, exportRecord.width, 1e-9) ...
    && approximately_equal(height, exportRecord.height, 1e-9) ...
    && approximately_equal(viewBoxWidth, exportRecord.viewbox_width, 1e-9) ...
    && approximately_equal(viewBoxHeight, exportRecord.viewbox_height, 1e-9) ...
    && approximately_equal(physicalWidth, exportRecord.physical_width_in, 1e-9) ...
    && approximately_equal(physicalHeight, exportRecord.physical_height_in, 1e-9) ...
    && approximately_equal(styleWidth, physicalWidth, 1e-9) ...
    && approximately_equal(styleHeight, physicalHeight, 1e-9) ...
    && approximately_equal(pixelAspect, viewBoxAspect, 1e-7) ...
    && approximately_equal(pixelAspect, physicalAspect, 1e-7) ...
    && strlength(strtrim(string(char(titleNode.getTextContent())))) > 0 ...
    && strlength(strtrim(string(char(descriptionNode.getTextContent())))) > 0 ...
    && role == "img" && strlength(strtrim(accessibleName)) > 0 ...
        && strlength(strtrim(string(exportRecord.title))) > 0 ...
        && strlength(strtrim(string(exportRecord.description))) > 0 ...
        && strlength(strtrim(string(exportRecord.accessible_name))) > 0 ...
        && string(char(titleNode.getTextContent())) == string(exportRecord.title) ...
        && string(char(descriptionNode.getTextContent())) == string(exportRecord.description) ...
        && accessibleName == string(exportRecord.accessible_name), ...
    "oi_write_manifest:InvalidSvg", ...
    "SVG dimensions or accessibility metadata are invalid: %s", filePath);
end

function value = svg_pixel_length(root, attributeName)
attribute = string(char(root.getAttribute(char(attributeName))));
numberPattern = "[+]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][+-]?\d+)?";
token = regexp(char(strtrim(attribute)), ...
    char("^(" + numberPattern + ")px$"), "tokens", "once");
assert(~isempty(token), "oi_write_manifest:InvalidSvg", ...
    "SVG %s must use an explicit positive px length", attributeName);
value = str2double(token{1});
assert(isfinite(value) && value > 0, "oi_write_manifest:InvalidSvg", ...
    "SVG %s must use an explicit positive px length", attributeName);
end

function [width, height] = svg_viewbox_size(root)
attribute = string(char(root.getAttribute('viewBox')));
numberPattern = "([+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][+-]?\d+)?)";
separator = "[,\s]+";
pattern = "^\s*" + numberPattern + separator + numberPattern + separator ...
    + numberPattern + separator + numberPattern + "\s*$";
tokens = regexp(char(attribute), char(pattern), "tokens", "once");
assert(~isempty(tokens), "oi_write_manifest:InvalidSvg", ...
    "SVG viewBox must contain four finite numeric coordinates");
values = str2double(tokens);
assert(all(isfinite(values)) && all(values(3:4) > 0), ...
    "oi_write_manifest:InvalidSvg", ...
    "SVG viewBox width and height must be positive");
width = values(3);
height = values(4);
end

function [width, height] = svg_style_physical_size(root)
style = string(char(root.getAttribute('style')));
width = svg_style_length(style, "width");
height = svg_style_length(style, "height");
end

function value = svg_style_length(style, propertyName)
numberPattern = "[+]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][+-]?\d+)?";
pattern = "^\s*" + propertyName + "\s*:\s*(" ...
    + numberPattern + ")in\s*$";
declarations = split(style, ";");
value = NaN;
for declarationIndex = numel(declarations):-1:1
    token = regexp(char(declarations(declarationIndex)), ...
        char(pattern), "tokens", "once");
    if ~isempty(token)
        value = str2double(token{1});
        break;
    end
end
assert(isfinite(value), "oi_write_manifest:InvalidSvg", ...
    "SVG style must declare %s in inches", propertyName);
assert(value > 0, "oi_write_manifest:InvalidSvg", ...
    "SVG style %s must be a positive inch length", propertyName);
end

function valid = positive_scalar(value)
valid = isnumeric(value) && isreal(value) && isscalar(value) ...
    && isfinite(value) && value > 0;
end

function equal = approximately_equal(left, right, tolerance)
equal = positive_scalar(left) && positive_scalar(right) ...
    && abs(left - right) <= tolerance * max([1 abs(left) abs(right)]);
end

function require_fields(value, names)
for name = names
    assert(isfield(value, char(name)), "oi_write_manifest:MissingField", ...
        "Required manifest field is missing: %s", name);
end
end

function safe = is_safe_relative_path(pathValue)
safe = false;
if ~isstring(pathValue) || ~isscalar(pathValue) || ismissing(pathValue) ...
        || strlength(strtrim(pathValue)) == 0
    return;
end
value = char(pathValue);
normalized = replace(pathValue, "\", "/");
if startsWith(normalized, "/") ...
        || ~isempty(regexp(value, "^[A-Za-z]:[\\/]", "once"))
    return;
end
segments = split(normalized, "/");
safe = all(strlength(segments) > 0) ...
    && ~any(segments == "." | segments == "..");
end

function pathValue = canonical_path(pathValue)
[status, attributes] = fileattrib(char(pathValue));
assert(status, "oi_write_manifest:PathResolutionFailed", ...
    "Cannot resolve an existing path relative to the MATLAB working directory: %s", pathValue);
pathValue = string(attributes.Name);
if usejava("jvm")
    pathValue = string(char(java.io.File(char(pathValue)).getCanonicalPath()));
end
end

function inside = is_within_directory(candidatePath, directoryPath)
candidate = char(candidatePath);
directory = char(directoryPath);
if endsWith(directory, filesep)
    prefix = directory;
else
    prefix = [directory filesep];
end
if ispc
    inside = startsWith(candidate, prefix, "IgnoreCase", true);
else
    inside = startsWith(candidate, prefix);
end
end

function delete_if_present(filePath)
if isfile(filePath)
    delete(filePath);
end
end

function valid = valid_utc_timestamp(value)
valid = false;
try
    parsed = datetime(string(value), "InputFormat", ...
        "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'", "TimeZone", "UTC");
    valid = isscalar(parsed) && ~isnat(parsed);
catch
end
end

function atomic_replace_file(sourcePath, targetPath)
if ~usejava("jvm")
    [moved, message] = movefile(sourcePath, targetPath, "f");
    assert(moved, "oi_write_manifest:MoveFailed", "%s", message);
    return;
end
sourceFile = java.io.File(char(sourcePath));
targetFile = java.io.File(char(targetPath));
options = javaArray('java.nio.file.CopyOption', 2);
options(1) = javaMethod('valueOf', 'java.nio.file.StandardCopyOption', ...
    'ATOMIC_MOVE');
options(2) = javaMethod('valueOf', 'java.nio.file.StandardCopyOption', ...
    'REPLACE_EXISTING');
try
    javaMethod('move', 'java.nio.file.Files', ...
        sourceFile.toPath(), targetFile.toPath(), options);
catch errorRecord
    warning("oi_write_manifest:AtomicMoveFallback", ...
        "Atomic Java move unavailable; using same-directory movefile fallback: %s", ...
        errorRecord.message);
    [moved, message] = movefile(sourcePath, targetPath, "f");
    assert(moved, "oi_write_manifest:MoveFailed", "%s", message);
end
end
