function view = adapt_astra_argo_r24c_candidate(result)
arguments
    result (1,1) struct
end
require_fields(result, {'RawRecords', 'HelperResult', 'Figure', 'RawJSONText', ...
    'OriginalData', 'OriginalDataInfo', 'SourceDeclarations', ...
    'VerticalSamplingSchemeText', 'GraphicsRecordMap', 'DisplayPermutation', ...
    'QC', 'Uncertainty'});
assert((ischar(result.RawJSONText) && isrow(result.RawJSONText)) ...
    || (isstring(result.RawJSONText) && isscalar(result.RawJSONText) ...
    && ~ismissing(result.RawJSONText)), 'argo_adapter_r24c:MissingMetadata', ...
    'Complete profile metadata must come from retained result.RawJSONText');
profiles = jsondecode(result.RawJSONText);
assert(isstruct(profiles) && numel(profiles) == 3, ...
    'argo_adapter_r24c:RawJSON', 'Expected the three retained original profile objects');
records = result.RawRecords;
columns = {'ObservationID', 'ProfileID', 'PlatformID', 'ProfileIndex', 'SourceRow', ...
    'SourceFileRow', 'Time', 'TimeText', 'Longitude', 'Latitude', 'pressure', ...
    'temperature', 'salinity', 'pressure_argoqc', 'temperature_argoqc', 'salinity_argoqc', ...
    'PressureMode', 'TemperatureMode', 'SalinityMode', 'PressureUnit', ...
    'TemperatureUnit', 'SalinityUnit', 'ProfileDirection', 'PositionQC', 'TimeQC', 'Series'};
assert(istable(records) && height(records) == 1785 ...
    && all(ismember(columns, records.Properties.VariableNames)), ...
    'argo_adapter_r24c:RawRecords', 'Expected all current named RawRecords columns and 1785 rows');
for columnIndex = 1:numel(columns)
    assert(isequal(size(records.(columns{columnIndex})), [1785 1]), ...
        'argo_adapter_r24c:RecordColumnShape', ...
        'Every retained record variable must be one scalar per row: %s', columns{columnIndex});
end
assert(isdatetime(records.Time) && strcmp(records.Time.TimeZone, 'UTC') ...
    && isequal(records.SourceFileRow, (1:1785).') ...
    && isequal(result.DisplayPermutation, records.SourceFileRow), ...
    'argo_adapter_r24c:RecordOrder', 'UTC and original concatenation must remain explicit');
variableNames = {'pressure', 'pressure_argoqc', 'salinity', ...
    'salinity_argoqc', 'temperature', 'temperature_argoqc'};
values = records{:, variableNames};
assert(isa(values, 'double') && isreal(values) && all(isfinite(values(:))), ...
    'argo_adapter_r24c:Values', 'Read actual finite original numeric/QC table values');
cellFields = {'OriginalData', 'OriginalDataInfo', 'SourceDeclarations', 'GraphicsRecordMap'};
for fieldIndex = 1:numel(cellFields)
    value = result.(cellFields{fieldIndex});
    assert(iscell(value) && numel(value) == 3, ...
        'argo_adapter_r24c:Interface', 'Expected three entries in %s', cellFields{fieldIndex});
end
assert(isstring(result.VerticalSamplingSchemeText) ...
    && numel(result.VerticalSamplingSchemeText) == 3, ...
    'argo_adapter_r24c:MissingMetadata', 'Original sampling descriptions must be retained');
helper = result.HelperResult;
require_fields(helper, {'Axes', 'Scatter', 'CompleteMask'});
assert(isgraphics(result.Figure, 'figure') && isgraphics(helper.Axes, 'axes') ...
    && isequal(ancestor(helper.Axes, 'figure'), result.Figure) ...
    && numel(helper.Scatter) == 3 && all(isgraphics(helper.Scatter, 'scatter')) ...
    && isequal(size(helper.CompleteMask), [1785 1]) && islogical(helper.CompleteMask), ...
    'argo_adapter_r24c:Helper', 'Expected the actual returned helper and original native handles');
rowGroups = cell(3, 1);
nativeMappings = cell(3, 1);
returnedMappings = cell(3, 1);
offset = 0;
for profileIndex = 1:3
    profile = profiles(profileIndex);
    require_fields(profile, {matlab.lang.makeValidName('_id'), 'data', 'data_info', ...
        'timestamp', 'geolocation', 'source', 'vertical_sampling_scheme', ...
        'profile_direction', 'geolocation_argoqc', 'timestamp_argoqc'});
    data = profile.data;
    assert(isa(data, 'double') && ismatrix(data) && size(data, 1) == 6, ...
        'argo_adapter_r24c:RawJSON', 'Retained data must remain variable-by-layer');
    count = size(data, 2);
    rows = offset + (1:count).';
    assert(count > 0 && rows(end) <= 1785, ...
        'argo_adapter_r24c:RecordCount', 'Retained profile sizes exceed the raw table');
    profileID = string(profile.(matlab.lang.makeValidName('_id')));
    levels = (1:count).';
    assert(isequal(values(rows, :), data.') ...
        && isequal(records.ProfileIndex(rows), repmat(profileIndex, count, 1)) ...
        && isequal(records.SourceRow(rows), levels) ...
        && isequal(records.ProfileID(rows), repmat(profileID, count, 1)) ...
        && isequal(records.ObservationID(rows), profileID + ":layer:" + compose("%04d", levels)) ...
        && isequal(records.PlatformID(rows), repmat(extractBefore(profileID, "_"), count, 1)), ...
        'argo_adapter_r24c:RecordIdentity', 'Actual table values and composite identities differ');
    timestamp = datetime(profile.timestamp, 'InputFormat', ...
        "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'", 'TimeZone', 'UTC');
    assert(all(records.Time(rows) == timestamp) ...
        && all(records.TimeText(rows) == string(profile.timestamp)) ...
        && all(records.Longitude(rows) == profile.geolocation.coordinates(1)) ...
        && all(records.Latitude(rows) == profile.geolocation.coordinates(2)) ...
        && all(records.ProfileDirection(rows) == string(profile.profile_direction)) ...
        && all(records.PositionQC(rows) == profile.geolocation_argoqc) ...
        && all(records.TimeQC(rows) == profile.timestamp_argoqc) ...
        && all(records.Series(rows) == "Profile: " + profileID), ...
        'argo_adapter_r24c:RowMetadata', 'Actual row UTC/lon/lat/direction/QC/series differs');
    assert(isequaln(result.OriginalData{profileIndex}, data) ...
        && isequaln(result.OriginalDataInfo{profileIndex}, profile.data_info) ...
        && isequaln(result.SourceDeclarations{profileIndex}, profile.source) ...
        && result.VerticalSamplingSchemeText(profileIndex) == string(profile.vertical_sampling_scheme), ...
        'argo_adapter_r24c:RetainedCopies', 'Returned original data and metadata copies disagree');
    unitFields = {'PressureUnit', 'SalinityUnit', 'TemperatureUnit'};
    modeFields = {'PressureMode', 'SalinityMode', 'TemperatureMode'};
    variableRows = [1 3 5];
    for quantityIndex = 1:3
        unit = metadata_entry(profile.data_info{3}, variableRows(quantityIndex), 1);
        mode = metadata_entry(profile.data_info{3}, variableRows(quantityIndex), 2);
        assert(all(records.(unitFields{quantityIndex})(rows) == string(unit)) ...
            && all(records.(modeFields{quantityIndex})(rows) == string(mode)), ...
            'argo_adapter_r24c:UnitsMode', 'Actual row units/modes differ from retained metadata');
        tableVariable = variableNames{variableRows(quantityIndex)};
        variableIndex = find(strcmp(records.Properties.VariableNames, tableVariable));
        assert(string(records.Properties.VariableUnits{variableIndex}) == string(unit), ...
            'argo_adapter_r24c:TableUnits', 'Raw table VariableUnits disagrees with retained source');
    end
    selectedRows = find(helper.CompleteMask & records.ProfileIndex == profileIndex);
    scatterHandle = helper.Scatter(profileIndex);
    check_mapping(result.GraphicsRecordMap{profileIndex}, scatterHandle, selectedRows, records, profileID);
    native = scatterHandle.UserData;
    require_fields(native, {'RecordMapping', 'RawRecordsField'});
    assert(string(native.RawRecordsField) == "result.RawRecords", ...
        'argo_adapter_r24c:NativeIdentity', 'Native UserData must name the retained record source');
    check_mapping(native.RecordMapping, scatterHandle, selectedRows, records, profileID);
    rowGroups{profileIndex} = result.GraphicsRecordMap{profileIndex}.RawRecordRows;
    nativeMappings{profileIndex} = mapping_projection(native.RecordMapping);
    nativeMappings{profileIndex}.RawRecordsField = string(native.RawRecordsField);
    returnedMappings{profileIndex} = mapping_projection(result.GraphicsRecordMap{profileIndex});
    offset = offset + count;
end
assert(offset == 1785, 'argo_adapter_r24c:RecordCount', 'All original profile levels must be present');
require_fields(result.QC, {'Status', 'VariableOrder', 'AcceptedMask', ...
    'MissingMask', 'InvalidMask', 'SuspectMask'});
assert(string(result.QC.Status) == "present" ...
    && isequal(result.QC.VariableOrder, ["pressure" "temperature" "salinity"]) ...
    && isequal(result.QC.AcceptedMask, all(values(:, [2 4 6]) == 1, 2)) ...
    && isequal(result.QC.MissingMask, isnan(values(:, [1 5 3]))) ...
    && isequal(result.QC.InvalidMask, false(1785, 3)) ...
    && isequal(result.QC.SuspectMask, false(1785, 3)), ...
    'argo_adapter_r24c:QC', 'Returned QC declarations must agree with all three actual columns');
uncertaintyFields = {'Status', 'pressure', 'temperature', 'salinity'};
require_fields(result.Uncertainty, uncertaintyFields);
for fieldIndex = 1:numel(uncertaintyFields)
    assert(string(result.Uncertainty.(uncertaintyFields{fieldIndex})) == "not_provided", ...
        'argo_adapter_r24c:Uncertainty', 'Do not turn helper defaults into observed uncertainty');
end
view = struct('Helper', helper, 'Values', values, 'ProfileIndex', records.ProfileIndex, ...
    'LevelIndex', records.SourceRow, 'ProfileMetadata', rmfield(profiles, 'data'));
view.ScatterSourceRows = rowGroups;
view.RawJSONText = string(result.RawJSONText);
recordCopy = records;
times = records.Time;
times.Format = "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'";
recordCopy.Time = string(times);
view.Records = table2struct(recordCopy, 'ToScalar', true);
view.RecordVariableNames = string(records.Properties.VariableNames(:));
view.RecordVariableUnits = string(records.Properties.VariableUnits(:));
view.RecordTimeZone = string(records.Time.TimeZone);
view.RecordTimeFormat = string(records.Time.Format);
view.NativeMappings = nativeMappings;
view.ReturnedMappings = returnedMappings;
view.QC = result.QC;
view.Uncertainty = result.Uncertainty;
end

function require_fields(value, names)
assert(isstruct(value) && isscalar(value), ...
    'argo_adapter_r24c:Interface', 'Expected a scalar retained structure');
missing = names(~isfield(value, names));
assert(isempty(missing), 'argo_adapter_r24c:MissingMetadata', ...
    'Missing retained fields: %s; no expected-input fallback is permitted', strjoin(missing, ', '));
end

function value = metadata_entry(metadata, row, column)
assert(iscell(metadata), 'argo_adapter_r24c:MetadataShape', 'Expected retained metadata cells');
if isequal(size(metadata), [6 2])
    value = metadata{row, column};
elseif isvector(metadata) && numel(metadata) == 6
    pair = metadata{row};
    assert(iscell(pair) && numel(pair) == 2, ...
        'argo_adapter_r24c:MetadataShape', 'Expected the original unit/mode pair');
    value = pair{column};
else
    error('argo_adapter_r24c:MetadataShape', 'Unrecognized retained metadata shape');
end
end

function check_mapping(mapping, scatterHandle, rows, records, profileID)
require_fields(mapping, {'Scatter', 'ProfileID', 'RawRecordRows', ...
    'ObservationID', 'SourceRow', 'SourceFileRow'});
assert(isequal(mapping.Scatter, scatterHandle) && string(mapping.ProfileID) == profileID ...
    && isequal(mapping.RawRecordRows, rows) ...
    && isequal(mapping.ObservationID, records.ObservationID(rows)) ...
    && isequal(mapping.SourceRow, records.SourceRow(rows)) ...
    && isequal(mapping.SourceFileRow, records.SourceFileRow(rows)), ...
    'argo_adapter_r24c:NativeIdentity', 'Returned or actual native mapping differs from raw records');
actualValues = [scatterHandle.XData(:), scatterHandle.YData(:), scatterHandle.CData(:)];
assert(isequal(actualValues, records{rows, {'salinity', 'temperature', 'pressure'}}), ...
    'argo_adapter_r24c:NativeValues', 'Actual Scatter X/Y/CData differs from its mapped record rows');
end

function projection = mapping_projection(mapping)
projection = struct('ProfileID', string(mapping.ProfileID), ...
    'RawRecordRows', mapping.RawRecordRows, 'ObservationID', mapping.ObservationID, ...
    'SourceRow', mapping.SourceRow, 'SourceFileRow', mapping.SourceFileRow);
end
