function full100_family_a_contracts()
%FULL100_FAMILY_A_CONTRACTS Verify profile and two-dimensional field assets.
theme = fixture_theme();
test_profile(theme);
test_hovmoller(theme);
test_section(theme);
fprintf("MATLAB_FULL100_FAMILY_A_CONTRACTS=ok\n");
end

function test_profile(theme)
[figureHandle, axesHandle] = make_axes();
figureCleanup = onCleanup(@() close_if_valid(figureHandle));
depth = [0; 10; 20; 30];
values = [12 11; 11.5 10.5; NaN 10; 10.5 9.5];
structural = false(size(values));
structural(3,1) = true;
reporting = false(size(values));
qc = ["good" "good"; "good" "suspect"; "not-reported" "good"; "good" "good"];
uncertainty = 0.2 * ones(size(values));
uncertainty(3,1) = NaN;
result = oi_plot_profile(axesHandle, depth, values, struct( ...
    "QuantityLabel", "Temperature", "QuantityUnit", "degC", ...
    "DepthUnit", "m", "VerticalReference", "mean sea level", ...
    "SeriesLabels", ["cast-a" "cast-b"], "Theme", theme, ...
    "StructuralMissingMask", structural, "ReportingMissingMask", reporting, ...
    "QCFlags", qc, "QCPolicy", "preserve", ...
    "UncertaintyValues", uncertainty, "UncertaintyType", "standard-deviation", ...
    "UncertaintyUnit", "degC", "UncertaintyDisplay", "band"));
assert(result.ValidCount == 7 && result.MissingCount == 1 ...
    && result.StructuralMissingCount == 1 && result.ReportingMissingCount == 0, ...
    "full100_family_a:ProfileMissing", "Profile missing classes were not preserved");
assert(result.QCProvided && sum(result.QCCounts) == numel(values) ...
    && result.UncertaintyPresent && result.UncertaintyMissingCount == 0 ...
    && result.UncertaintyDisplay == "band" && axesHandle.YDir == "reverse", ...
    "full100_family_a:ProfileMetadata", "Profile QC or uncertainty contract failed");
must_throw(@() oi_plot_profile(axesHandle, depth, values, struct( ...
    "QuantityLabel", "Temperature", "QuantityUnit", "degC", ...
    "DepthUnit", "m", "VerticalReference", "mean sea level", ...
    "Theme", theme, "Unknown", true)), "UnknownOption");
must_throw(@() oi_plot_profile(axesHandle, depth, values, struct( ...
    "QuantityLabel", "Temperature", "QuantityUnit", "degC", ...
    "DepthUnit", "m", "VerticalReference", "mean sea level", ...
    "Theme", theme, "StructuralMissingMask", structural, ...
    "ReportingMissingMask", structural)), "MissingMaskOverlap");
badUncertainty = uncertainty;
badUncertainty(1,1) = -1;
must_throw(@() oi_plot_profile(axesHandle, depth, values, struct( ...
    "QuantityLabel", "Temperature", "QuantityUnit", "degC", ...
    "DepthUnit", "m", "VerticalReference", "mean sea level", ...
    "Theme", theme, "UncertaintyValues", badUncertainty, ...
    "UncertaintyType", "standard-deviation", "UncertaintyUnit", "degC")), ...
    "UncertaintyValues");
clear figureCleanup;
close_if_valid(figureHandle);
end

function test_hovmoller(theme)
[figureHandle, axesHandle] = make_axes();
figureCleanup = onCleanup(@() close_if_valid(figureHandle));
time = datetime(2026, 9, 5, 0:3, 0, 0, "TimeZone", "UTC")';
depth = [0; 10; 20];
field = [1 2 3 4; 2 NaN 4 5; 3 4 NaN 6];
structural = false(size(field));
structural(2,2) = true;
reporting = false(size(field));
reporting(3,3) = true;
qc = repmat("good", size(field));
qc(3,3) = "not-reported";
uncertainty = 0.1 * ones(size(field));
uncertainty(isnan(field)) = NaN;
result = oi_plot_hovmoller(axesHandle, time, depth, field, struct( ...
    "TimeZone", "UTC", "TimeDisplayFormat", "yyyy-MM-dd HH:mm", ...
    "DepthUnit", "m", "QuantityLabel", "Temperature", ...
    "QuantityUnit", "degC", "ColorLimits", [0 6], "ColorCenter", 2, ...
    "Theme", theme, "StructuralMissingMask", structural, ...
    "ReportingMissingMask", reporting, "QCFlags", qc, ...
    "UncertaintyValues", uncertainty, "UncertaintyType", "instrument-accuracy", ...
    "UncertaintyUnit", "degC"));
assert(result.TimeZone == "UTC" && result.StructuralMissingCount == 1 ...
    && result.ReportingMissingCount == 1 && result.MissingCount == 2 ...
    && result.QCProvided && sum(result.QCCounts) == numel(field) ...
    && result.UncertaintyPresent && result.ColorCenter == 2 ...
    && axesHandle.YDir == "reverse" && all(result.Image.AlphaData(:) == isfinite(field(:))), ...
    "full100_family_a:HovmollerContract", "Hovmoller contract failed");
localTime = time;
localTime.TimeZone = "America/New_York";
must_throw(@() oi_plot_hovmoller(axesHandle, localTime, depth, field, struct( ...
    "TimeZone", "UTC", "DepthUnit", "m", "QuantityLabel", "Temperature", ...
    "QuantityUnit", "degC", "ColorLimits", [0 6], "Theme", theme)), "TimeZone");
must_throw(@() oi_plot_hovmoller(axesHandle, time, depth, field, struct( ...
    "TimeZone", "UTC", "DepthUnit", "m", "QuantityLabel", "Temperature", ...
    "QuantityUnit", "degC", "ColorLimits", [0 6], "ColorScale", "log", ...
    "Theme", theme)), "ColorScale");
must_throw(@() oi_plot_hovmoller(axesHandle, time, depth, field, struct( ...
    "TimeZone", "UTC", "DepthUnit", "m", "QuantityLabel", "Temperature", ...
    "QuantityUnit", "degC", "ColorLimits", [0 6], "QCFlags", "good", ...
    "Theme", theme)), "QCFlags");
clear figureCleanup;
close_if_valid(figureHandle);
end

function test_section(theme)
[figureHandle, axesHandle] = make_axes();
figureCleanup = onCleanup(@() close_if_valid(figureHandle));
distance = [0 5 10 15];
depth = [0; 50; 100];
field = [-2 -1 0 1; -1 NaN 1 2; 0 1 NaN 4];
structural = false(size(field));
structural(3,3) = true;
reporting = false(size(field));
reporting(2,2) = true;
qc = repmat("good", size(field));
qc(2,2) = "not-reported";
uncertainty = 0.25 * ones(size(field));
uncertainty(isnan(field)) = NaN;
levels = linspace(-2,4,13);
result = oi_plot_section(axesHandle, distance, depth, field, struct( ...
    "DistanceUnit", "km", "DepthUnit", "m", ...
    "QuantityLabel", "Anomaly", "QuantityUnit", "degC", ...
    "ColorLimits", [-2 4], "ColorCenter", 0, "Levels", levels, ...
    "Theme", theme, "StructuralMissingMask", structural, ...
    "ReportingMissingMask", reporting, "QCFlags", qc, ...
    "UncertaintyValues", uncertainty, "UncertaintyType", "standard-error", ...
    "UncertaintyUnit", "degC"));
assert(result.StructuralMissingCount == 1 && result.ReportingMissingCount == 1 ...
    && result.ValidCount == 10 && result.QCProvided ...
    && sum(result.QCCounts) == numel(field) && result.UncertaintyPresent ...
    && result.ColorCenter == 0 && isequal(result.Levels, levels) ...
    && axesHandle.YDir == "reverse" && isequal(axesHandle.CLim, [-2 4]), ...
    "full100_family_a:SectionContract", "Section contract failed");
must_throw(@() oi_plot_section(axesHandle, distance, depth, field, struct( ...
    "DistanceUnit", "km", "DepthUnit", "m", ...
    "QuantityLabel", "Anomaly", "QuantityUnit", "degC", ...
    "ColorLimits", [-2 4], "Levels", [-1 0 1], "Theme", theme)), "Levels");
badMask = structural;
badMask(1,1) = true;
must_throw(@() oi_plot_section(axesHandle, distance, depth, field, struct( ...
    "DistanceUnit", "km", "DepthUnit", "m", ...
    "QuantityLabel", "Anomaly", "QuantityUnit", "degC", ...
    "ColorLimits", [-2 4], "Theme", theme, ...
    "StructuralMissingMask", badMask)), "MissingMaskCoverage");
must_throw(@() oi_plot_section(axesHandle, distance, depth, field, struct( ...
    "DistanceUnit", "km", "DepthUnit", "m", ...
    "QuantityLabel", "Anomaly", "QuantityUnit", "degC", ...
    "ColorLimits", [-2 4], "ColorCenter", 5, "Theme", theme)), "ColorCenter");
clear figureCleanup;
close_if_valid(figureHandle);
end

function theme = fixture_theme()
theme = struct("FontName", "DejaVu Sans", "FontSize", 10, ...
    "TitleSize", 13, "LabelSize", 11, "CanvasColor", [1 1 1], ...
    "AxesColor", [0.97 0.98 0.99], "MissingColor", [0.86 0.88 0.89], ...
    "TextColor", [0.05 0.14 0.20], "GridColor", [0.74 0.82 0.85], ...
    "PositiveColor", [0.85 0.30 0.18], "NegativeColor", [0.05 0.42 0.65], ...
    "AccentColor", [0 0.60 0.65], ...
    "LineColors", [0 0.36 0.55; 0 0.62 0.65; 0.93 0.46 0.16], ...
    "SequentialMap", parula(64), "DivergingMap", cool(65), ...
    "Name", "family-a-test");
end

function [figureHandle, axesHandle] = make_axes()
figureHandle = figure("Visible", "off", "Color", "w");
axesHandle = axes(figureHandle);
end

function must_throw(action, identifierFragment)
didThrow = false;
try
    action();
catch errorValue
    didThrow = contains(string(errorValue.identifier), identifierFragment) ...
        || contains(string(errorValue.message), identifierFragment);
end
assert(didThrow, "full100_family_a:ExpectedError", ...
    "Expected an error containing '%s'", identifierFragment);
end

function close_if_valid(figureHandle)
if ~isempty(figureHandle) && isgraphics(figureHandle)
    close(figureHandle);
end
end
