function entries = full100_family_b_runtime(outputDirectory)
%FULL100_FAMILY_B_RUNTIME Run MATLAB-only family-b contracts and exports.
arguments
    outputDirectory (1,1) string
end
assert(~verLessThan("matlab","9.9"), ...
    "family_b:UnsupportedRelease","Family-b runtime evidence requires MATLAB R2020b or newer");
assert(strlength(strtrim(outputDirectory)) > 0,"family_b:OutputDirectory", ...
    "outputDirectory must be explicit nonblank text");
assetDirectory = fullfile(fileparts(mfilename("fullpath")),"..","assets");
addpath(assetDirectory);
if ~isfolder(outputDirectory)
    mkdir(outputDirectory);
end
theme = oi_ocean_theme();
entries = struct([]);

time = datetime(2026,9,1,[0 1 5 6 7],0,0,"TimeZone","UTC")';
value = [10;11;12;NaN;14];
uncertainty = [0.2;0.2;0.3;NaN;0.2];
qc = ["good";"good";"suspect";"good";"good"];
station = repmat("Station-A",5,1);
series = timetable(time,value,uncertainty,qc,station, ...
    'VariableNames',["Temperature" "TemperatureUncertainty" "QC" "Station"]);
series.Properties.VariableUnits = ["degC" "degC" "1" "1"];
[figureHandle,axesHandle,cleanup] = make_axes(theme);
timeResult = oi_plot_time_series(axesHandle,series,struct( ...
    "ValueVariables","Temperature","ValueLabels","Sea temperature", ...
    "QCVariables","QC","AcceptedQCValues","good","QCPolicy","mark", ...
    "UncertaintyVariables","TemperatureUncertainty", ...
    "UncertaintyType","instrument-accuracy","UncertaintyUnits","degC", ...
    "GapThreshold",hours(2),"DisplayTimeZone","UTC", ...
    "SampleLabelVariable","Station","Theme",theme,"Title","Family B time series"));
assert(timeResult.ValidCount == 3 && timeResult.MissingCount == 1 ...
    && timeResult.QCRejectedCount == 1 && timeResult.GapCount == 1, ...
    "family_b:TimeSeriesCounts","Time-series masks or gap accounting are incorrect");
entries = append_entry(entries,oi_export_figure(figureHandle,outputDirectory, ...
    "family-b-time-series",1200,675,180,"Title","Family B time series", ...
    "Source","full100_family_b_runtime","Theme",theme.Name,"ExportSVG",true));
clear cleanup;

observationTable = table(["A";"B";"C";"D"],[1;2;3;4], ...
    ["good";"suspect";"good";"good"],[0.1;0.1;0.2;0.1], ...
    ["Shelf";"Shelf";"Slope";"Slope"], ...
    'VariableNames',["Key" "Observation" "QC" "Uncertainty" "Region"]);
modelTable = table(["C";"A";"B";"E"],[3.1;1.1;1.8;5], ...
    ["good";"good";"good";"good"],[0.15;0.1;0.1;0.2], ...
    'VariableNames',["Key" "Model" "QC" "Uncertainty"]);
[figureHandle,axesHandle,cleanup] = make_axes(theme);
comparisonOptions = struct( ...
    "PairingRule","inner-key","PairKeys","Key", ...
    "ObservationVariable","Observation","ModelVariable","Model", ...
    "ObservationQCVariable","QC","ModelQCVariable","QC", ...
    "AcceptedQCValues","good","ObservationUncertaintyVariable","Uncertainty", ...
    "ModelUncertaintyVariable","Uncertainty","UncertaintyType","standard-deviation", ...
    "UncertaintyUnit","degC","QuantityUnit","degC", ...
    "ObservationLabel","Observed temperature","ModelLabel","Model temperature", ...
    "ConfounderVariable","Region","ConfounderLabel","Region", ...
    "SampleLabelVariable","Key","Theme",theme,"Title","Family B paired comparison");
comparisonResult = oi_plot_comparison(axesHandle,observationTable,modelTable,comparisonOptions);
assert(comparisonResult.ValidCount == 2 ...
    && comparisonResult.UnmatchedObservationCount == 1 ...
    && comparisonResult.UnmatchedModelCount == 1 ...
    && comparisonResult.QCRejectedCount == 1 ...
    && numel(comparisonResult.StratifiedMetrics) == 2, ...
    "family_b:ComparisonCounts","Pairing, QC, or confounder accounting is incorrect");
render_comparison_probe(figureHandle,outputDirectory,"family-b-comparison-before-export");
assert_comparison_legend_layout(comparisonResult,figureHandle);
entries = append_entry(entries,oi_export_figure(figureHandle,outputDirectory, ...
    "family-b-comparison",1200,675,180,"Title","Family B paired comparison", ...
    "Source","full100_family_b_runtime","Theme",theme.Name,"ExportSVG",true));
assert_comparison_legend_layout(comparisonResult,figureHandle);
clear cleanup;
test_comparison_legend_overrides(observationTable,modelTable,comparisonOptions,comparisonResult,outputDirectory);
fprintf("FAMILY_B_COMPARISON_LAYOUT=passed\n");

tsTable = table([34.2;34.5;34.7;35.0],[12;9;NaN;5],[0;20;40;60], ...
    ["good";"suspect";"good";"good"],[0.02;0.02;NaN;0.03], ...
    [0.1;0.1;NaN;0.1],["Cast-1";"Cast-1";"Cast-2";"Cast-2"], ...
    'VariableNames',["Salinity" "Temperature" "Depth" "QC" ...
    "SalinityUncertainty" "TemperatureUncertainty" "Cast"]);
[figureHandle,axesHandle,cleanup] = make_axes(theme);
tsResult = oi_plot_ts_diagram(axesHandle,tsTable,[],[],struct( ...
    "SalinityVariable","Salinity","TemperatureVariable","Temperature", ...
    "ColorVariable","Depth","QCVariable","QC","AcceptedQCValues","good", ...
    "SalinityUncertaintyVariable","SalinityUncertainty", ...
    "TemperatureUncertaintyVariable","TemperatureUncertainty", ...
    "UncertaintyType","instrument-accuracy","SalinityUncertaintyUnit","g/kg", ...
    "TemperatureUncertaintyUnit","degC","SalinityLabel","Absolute salinity", ...
    "SalinityUnit","g/kg","SalinityDefinition","Absolute salinity", ...
    "TemperatureLabel","Conservative temperature","TemperatureUnit","degC", ...
    "TemperatureDefinition","Conservative temperature","ReferencePressure","0 dbar", ...
    "ColorLabel","Sample depth","ColorUnit","m","ColorLimits",[0 65], ...
    "ConfounderVariable","Cast","ConfounderLabel","Cast", ...
    "Theme",theme,"Title","Family B T-S diagram"));
assert(tsResult.ValidCount == 2 && tsResult.MissingCount == 1 ...
    && tsResult.QCRejectedCount == 1, ...
    "family_b:TSCounts","T-S tuple, QC, or uncertainty accounting is incorrect");
entries = append_entry(entries,oi_export_figure(figureHandle,outputDirectory, ...
    "family-b-ts-diagram",1200,675,180,"Title","Family B T-S diagram", ...
    "Source","full100_family_b_runtime","Theme",theme.Name,"ExportSVG",true));
clear cleanup;

run_negative_contracts(theme);
save(fullfile(outputDirectory,"family-b-runtime-evidence.mat"),"entries", ...
    "timeResult","comparisonResult","tsResult");
fprintf("FAMILY_B_MATLAB_RUNTIME=passed\n");
fprintf("FAMILY_B_EXPORT_COUNT=%d\n",numel(entries));
end

function assert_comparison_legend_layout(result,figureHandle)
assert(string(result.Legend.Location) == "southoutside", ...
    "family_b:ComparisonLegendLocation", ...
    "Default comparison legend must remain southoutside after layout and export");
assert(string(result.Legend.Orientation) == "horizontal", ...
    "family_b:ComparisonLegendOrientation", ...
    "The outside legend must share one row rather than consume data height");
textHandles = findall(result.Axes,"Type","text");
diagnosticMask = false(size(textHandles));
for textIndex = 1:numel(textHandles)
    textValue = strjoin(string(textHandles(textIndex).String)," ");
    diagnosticMask(textIndex) = contains(textValue,"Missing/QC rejected =") ...
        && contains(textValue,"Unmatched obs/model =");
end
assert(nnz(diagnosticMask) == 1,"family_b:ComparisonDiagnostics", ...
    "Comparison must retain one complete metrics and QC diagnostic block");
metricBounds = oi_text_bounds(textHandles(diagnosticMask),figureHandle);
titleBounds = oi_text_bounds(result.Axes.Title,figureHandle);
xlabelBounds = oi_text_bounds(result.Axes.XLabel,figureHandle);
ylabelBounds = oi_text_bounds(result.Axes.YLabel,figureHandle);
figurePixels = double(getpixelposition(figureHandle));
legendPixels = double(getpixelposition(result.Legend,true));
legendBounds = [(legendPixels(1:2) - 1) ./ figurePixels(3:4), ...
    legendPixels(3:4) ./ figurePixels(3:4)];
assert(all(isfinite(legendBounds)) && all(legendBounds(3:4) > 0), ...
    "family_b:ComparisonLegendBounds","Legend must have finite positive rendered bounds");
diagnostics = struct("release",version('-release'),"figure_pixels",figurePixels, ...
    "axes_pixels",double(getpixelposition(result.Axes,true)), ...
    "statistics",metricBounds,"title",titleBounds,"xlabel",xlabelBounds, ...
    "ylabel",ylabelBounds,"legend",legendBounds, ...
    "statistics_font_size",textHandles(diagnosticMask).FontSize, ...
    "axes_font_size",result.Axes.FontSize, ...
    "title_font_size_multiplier",result.Axes.TitleFontSizeMultiplier);
fprintf("FAMILY_B_COMPARISON_GEOMETRY=%s\n",jsonencode(diagnostics));
otherBounds = [titleBounds;xlabelBounds;ylabelBounds];
for textIndex = 1:size(otherBounds,1)
    textOverlap = min(metricBounds(1:2) + metricBounds(3:4), ...
        otherBounds(textIndex,1:2) + otherBounds(textIndex,3:4)) ...
        - max(metricBounds(1:2),otherBounds(textIndex,1:2));
    assert(~all(textOverlap > 0),"family_b:ComparisonTextOverlap", ...
        "Statistics overlap title or axis labels: %s",jsonencode(diagnostics));
end
overlap = min(metricBounds(1:2) + metricBounds(3:4), ...
    legendBounds(1:2) + legendBounds(3:4)) ...
    - max(metricBounds(1:2),legendBounds(1:2));
assert(~all(overlap > 0),"family_b:ComparisonLegendOverlap", ...
    "Legend overlaps metrics/QC text: metrics=%s, legend=%s", ...
    mat2str(metricBounds,17),mat2str(legendBounds,17));
end

function test_comparison_legend_overrides(observations,modelValues,options,defaultResult,outputDirectory)
for location = ["northwest" "best"]
    [figureHandle,axesHandle,cleanup] = make_axes(options.Theme); %#ok<ASGLU>
    options.LegendLocation = location;
    result = oi_plot_comparison(axesHandle,observations,modelValues,options);
    render_comparison_probe(figureHandle,outputDirectory,"family-b-comparison-" + location);
    assert(string(result.Legend.Location) == location, ...
        "family_b:ComparisonLegendOverride", ...
        "Explicit LegendLocation='%s' must override the default",location);
    assert(isequaln(result.Metrics,defaultResult.Metrics) ...
        && isequaln(result.StratifiedMetrics,defaultResult.StratifiedMetrics) ...
        && isequal(result.PairedMask,defaultResult.PairedMask) ...
        && result.MissingCount == defaultResult.MissingCount ...
        && result.QCRejectedCount == defaultResult.QCRejectedCount ...
        && result.UnmatchedObservationCount == defaultResult.UnmatchedObservationCount ...
        && result.UnmatchedModelCount == defaultResult.UnmatchedModelCount, ...
        "family_b:ComparisonLegendStatistics", ...
        "Legend placement must not change paired statistics or QC accounting");
    clear cleanup;
end
end

function render_comparison_probe(figureHandle,outputDirectory,identifier)
filePath = fullfile(outputDirectory,identifier + ".png");
assert(~isfile(filePath),"family_b:StaleLayoutProbe", ...
    "Refusing to overwrite a comparison layout probe");
print(figureHandle,char(filePath),"-dpng","-r180");
imageInfo = imfinfo(filePath);
assert(imageInfo.Width == 1200 && imageInfo.Height == 675, ...
    "family_b:LayoutProbeDimensions","Layout must be rendered at the final physical size");
end

function run_negative_contracts(theme)
[figureHandle,axesHandle,cleanup] = make_axes(theme);
unzoned = timetable(datetime(2026,9,1,0,0,0)',1,'VariableNames',"Value");
must_throw(@() oi_plot_time_series(axesHandle,unzoned,struct( ...
    "ValueVariables","Value","ValueUnits","1","Theme",theme)),"TimeZone");
clear cleanup;
[figureHandle,axesHandle,cleanup] = make_axes(theme); %#ok<ASGLU>
duplicateTable = table(["A";"A"],[1;2],'VariableNames',["Key" "Value"]);
must_throw(@() oi_plot_comparison(axesHandle,duplicateTable,duplicateTable,struct( ...
    "PairingRule","inner-key","PairKeys","Key","ObservationVariable","Value", ...
    "ModelVariable","Value","QuantityUnit","1","Theme",theme)),"DuplicateKeys");
clear cleanup;
[figureHandle,axesHandle,cleanup] = make_axes(theme); %#ok<ASGLU>
must_throw(@() oi_plot_ts_diagram(axesHandle,[34;35],[5;6],[0;10],struct( ...
    "SalinityUnit","g/kg","TemperatureUnit","degC","ColorLabel","Depth", ...
    "ColorUnit","m","ColorLimits",[0 20],"SalinityUncertainty",[0.1;-1], ...
    "TemperatureUncertainty",[0.1;0.1],"UncertaintyType","instrument-accuracy", ...
    "SalinityUncertaintyUnit","g/kg","TemperatureUncertaintyUnit","degC", ...
    "Theme",theme)),"UncertaintyValues");
clear cleanup;
end

function [figureHandle,axesHandle,cleanup] = make_axes(theme)
figureHandle = oi_figure(1200,675,"off");
pageSize = [1200 675] / 180;
figureHandle.Units = "inches";
figureHandle.Position(3:4) = pageSize;
figureHandle.PaperUnits = "inches";
figureHandle.PaperPosition = [0 0 pageSize];
figureHandle.PaperSize = pageSize;
figureHandle.PaperPositionMode = "manual";
layout = tiledlayout(figureHandle,1,1,"TileSpacing","compact","Padding","compact");
axesHandle = nexttile(layout);
axesHandle.Color = theme.AxesColor;
cleanup = onCleanup(@() close_if_valid(figureHandle));
end

function entries = append_entry(entries,entry)
if isempty(entries)
    entries = entry;
else
    entries(end+1) = entry;
end
end

function must_throw(callback,identifierFragment)
threw = false;
try
    callback();
catch exception
    threw = contains(string(exception.identifier),identifierFragment) ...
        || contains(string(exception.message),identifierFragment);
end
assert(threw,"family_b:ExpectedFailure", ...
    "Expected failure containing '%s'",identifierFragment);
end

function close_if_valid(figureHandle)
if isgraphics(figureHandle,"figure")
    close(figureHandle);
end
end
