function snapshot = read_argo_ts_native(figureHandle, view, expected, identity)
arguments
    figureHandle
    view (1,1) struct
    expected (1,1) struct
    identity (1,1) struct
end
assert(isgraphics(figureHandle, 'figure'), ...
    'argo_native_probe:Figure', 'Expected the original live model figure');
required = {'Helper', 'Values', 'ProfileIndex', 'LevelIndex', ...
    'ProfileMetadata', 'ScatterSourceRows', 'RawJSONText', 'Records', ...
    'RecordVariableNames', 'RecordVariableUnits', 'RecordTimeZone', ...
    'RecordTimeFormat', 'NativeMappings', 'ReturnedMappings', 'QC', 'Uncertainty'};
assert(all(isfield(view, required)), 'argo_native_probe:AdapterContract', ...
    'The reviewed adapter must expose the diagnostic projection, not invented records');
assert(isequaln(view.Values, expected.Values) ...
    && isequaln(view.ProfileIndex, expected.ProfileIndex) ...
    && isequaln(view.LevelIndex, expected.LevelIndex) ...
    && isequaln(view.ProfileMetadata, expected.ProfileMetadata), ...
    'argo_native_probe:RawRecords', ...
    'All 1785 ordered values, QC, composite identities and profile metadata must match');
assert(all(isfield(identity, {'figure_id', 'input_sha256', 'input_bytes', 'source_sha256'})), ...
    'argo_native_probe:EvidenceIdentity', 'Source/input identities must come from the driver pins');
rawBytes = unicode2native(char(view.RawJSONText), 'UTF-8');
assert(isequal(view.RawJSONText, expected.RawJSONText) ...
    && isequal(rawBytes, expected.RawBytes) && numel(rawBytes) == identity.input_bytes, ...
    'argo_native_probe:RetainedRawJSON', 'Retained complete JSON must match original input bytes');
rawHash = identity.input_sha256;
assert(isequaln(orderfields(view.Records), orderfields(expected.Records)) ...
    && isequal(view.RecordVariableNames, expected.RecordVariableNames) ...
    && isequal(view.RecordVariableUnits, expected.RecordVariableUnits) ...
    && view.RecordTimeZone == "UTC", 'argo_native_probe:RecordState', ...
    'All actual record columns, UTC identities and table units must match the independent input reader');
helper = view.Helper;
axesHandle = helper.Axes;
assert(isscalar(axesHandle) && isgraphics(axesHandle, 'axes') ...
    && isequal(ancestor(axesHandle, 'figure'), figureHandle), ...
    'argo_native_probe:Ownership', 'Helper axes must belong to the returned model figure');
finiteMask = all(isfinite(expected.Values(:, [1 3 5])), 2);
qcMask = all(expected.Values(:, [2 4 6]) == 1, 2);
completeMask = finiteMask & qcMask;
assert(isequal(helper.FiniteTupleMask, finiteMask) ...
    && isequal(helper.QCAcceptedMask, qcMask) ...
    && isequal(helper.CompleteMask, completeMask) ...
    && helper.ValidCount == sum(completeMask) && helper.MissingCount == 0 ...
    && helper.QCRejectedCount == 0 && helper.UncertaintyMissingCount == 0, ...
    'argo_native_probe:Masks', 'Helper masks/counts must cover the full original input');
assert(string(helper.UncertaintyType) == "none", ...
    'argo_native_probe:Uncertainty', 'The bound file supplies no uncertainty measurements');
assert(any(lower(string(helper.ColorUnit)) == ["decibar", "dbar"]), ...
    'argo_native_probe:PressureUnit', 'Color is pressure in decibar, not depth');
assert(any(lower(string(helper.SalinityUnit)) == ["psu", "1", "pss-78"]) ...
    && any(lower(string(helper.TemperatureUnit)) ...
    == ["degc", "degree_celsius", lower(string(char(176)) + "C")]), ...
    'argo_native_probe:QuantityUnits', 'Display units must preserve original quantity values');
assert(isequal(colormap(axesHandle), helper.Colormap) ...
    && isequal(get(axesHandle, 'CLim'), helper.ColorLimits), ...
    'argo_native_probe:ColorScale', 'Actual axes colormap/CLim differs from helper result');
outOfRange = completeMask & (expected.Values(:, 1) < helper.ColorLimits(1) ...
    | expected.Values(:, 1) > helper.ColorLimits(2));
assert(isequal(helper.ColorOutOfRangeMask, outOfRange) ...
    && helper.ColorSaturatedCount == sum(outOfRange), ...
    'argo_native_probe:ColorMask', 'Pressure saturation must not be concealed');
handles = helper.Scatter(:);
actualHandles = findall(figureHandle, 'Type', 'scatter');
assert(~isempty(handles) && all(isgraphics(handles, 'scatter')) ...
    && numel(actualHandles) == numel(handles) ...
    && iscell(view.ScatterSourceRows) && numel(view.ScatterSourceRows) == numel(handles) ...
    && iscell(view.NativeMappings) && numel(view.NativeMappings) == numel(handles) ...
    && iscell(view.ReturnedMappings) && numel(view.ReturnedMappings) == numel(handles), ...
    'argo_native_probe:ScatterSet', 'Expected every original Scatter and explicit row mapping');
groups = cell(numel(handles), 1);
usedRows = zeros(0, 1);
for groupIndex = 1:numel(handles)
    scatterHandle = handles(groupIndex);
    rows = view.ScatterSourceRows{groupIndex};
    assert(any(actualHandles == scatterHandle) ...
        && sum(handles == scatterHandle) == 1 ...
        && isequal(scatterHandle.Parent, axesHandle), ...
        'argo_native_probe:ScatterOwnership', 'Scatter ownership or uniqueness differs');
    assert(isnumeric(rows) && iscolumn(rows) && ~isempty(rows) ...
        && all(isfinite(rows) & rows == fix(rows) & rows >= 1 & rows <= 1785) ...
        && all(diff(rows) > 0), 'argo_native_probe:SourceRows', ...
        'Each reviewed group mapping must retain source order without coordinate matching');
    actual = [scatterHandle.XData(:), scatterHandle.YData(:), scatterHandle.CData(:)];
    assert(isequaln(actual, expected.Values(rows, [3 5 1])), ...
        'argo_native_probe:NativeValues', 'Actual X/Y/CData must be salinity/temperature/pressure');
    expectedMapping = struct('ProfileID', expected.Records.ProfileID(rows(1)), ...
        'RawRecordRows', rows, 'ObservationID', expected.Records.ObservationID(rows), ...
        'SourceRow', expected.Records.SourceRow(rows), ...
        'SourceFileRow', expected.Records.SourceFileRow(rows));
    assert(isequaln(view.ReturnedMappings{groupIndex}, expectedMapping), ...
        'argo_native_probe:ReturnedMapping', 'Returned group identity differs from original input');
    expectedMapping.RawRecordsField = "result.RawRecords";
    assert(isequaln(view.NativeMappings{groupIndex}, expectedMapping), ...
        'argo_native_probe:NativeMapping', 'Actual native UserData identity differs from original input');
    assert(strcmp(scatterHandle.Visible, 'on') && strcmp(axesHandle.Visible, 'on') ...
        && all(isfinite(scatterHandle.SizeData(:)) & scatterHandle.SizeData(:) > 0) ...
        && ~strcmp(scatterHandle.Marker, 'none') ...
        && strcmp(scatterHandle.MarkerFaceColor, 'flat') ...
        && isnumeric(scatterHandle.MarkerFaceAlpha) ...
        && isscalar(scatterHandle.MarkerFaceAlpha) ...
        && isfinite(scatterHandle.MarkerFaceAlpha) && scatterHandle.MarkerFaceAlpha > 0, ...
        'argo_native_probe:Visibility', 'A hidden or zero/NaN-size Scatter is not a plotted sample');
    groups{groupIndex} = struct('source_rows', rows, 'xyc', actual, ...
        'size_data', scatterHandle.SizeData, 'marker', scatterHandle.Marker, ...
        'face_color', scatterHandle.MarkerFaceColor, 'edge_color', scatterHandle.MarkerEdgeColor, ...
        'face_alpha', scatterHandle.MarkerFaceAlpha, 'edge_alpha', scatterHandle.MarkerEdgeAlpha);
    groups{groupIndex}.native_user_data = view.NativeMappings{groupIndex};
    groups{groupIndex}.returned_mapping = view.ReturnedMappings{groupIndex};
    usedRows = [usedRows; rows]; %#ok<AGROW>
end
assert(isequal(sort(usedRows), find(completeMask)), ...
    'argo_native_probe:Coverage', 'Scatter row coverage must have no omissions or duplicates');
colorbarHandle = helper.Colorbar;
assert(isscalar(colorbarHandle) && isgraphics(colorbarHandle) ...
    && isequal(ancestor(colorbarHandle, 'figure'), figureHandle), ...
    'argo_native_probe:Colorbar', 'Expected the original figure colorbar');
snapshot = struct('schema_version', 1, 'evidence_contract', 'argo-ts-native-v1', ...
    'scope', 'bound_argo_ts_native_snapshot_only', ...
    'plot_type', 'temperature-salinity-diagram', 'figure_id', identity.figure_id, ...
    'input_sha256', identity.input_sha256, 'source_sha256', identity.source_sha256, ...
    'matlab_release', "R" + string(version('-release')), ...
    'profile_counts', expected.ProfileCounts, 'profile_ids', expected.ProfileIDs, ...
    'raw_json_text', view.RawJSONText, 'raw_json_bytes', numel(rawBytes), 'raw_json_sha256', rawHash, ...
    'raw_json_hash_method', 'byte_equal_to_independently_hash_bound_input', ...
    'records', view.Records, 'record_variable_names', view.RecordVariableNames, ...
    'record_variable_units', view.RecordVariableUnits, ...
    'record_time_zone', view.RecordTimeZone, 'record_time_format', view.RecordTimeFormat, ...
    'raw_values', view.Values, 'profile_index', view.ProfileIndex, ...
    'level_index', view.LevelIndex, 'profile_metadata', view.ProfileMetadata, ...
    'finite_mask', helper.FiniteTupleMask, 'qc_mask', helper.QCAcceptedMask, ...
    'complete_mask', helper.CompleteMask, 'qc_provided', helper.QCProvided, ...
    'colormap', colormap(axesHandle), 'clim', axesHandle.CLim, ...
    'color_out_of_range_mask', outOfRange, 'color_policy', helper.ColorOutOfRangePolicy, ...
    'scientific_metadata', helper.ManifestMetadata, ...
    'figure_units', figureHandle.Units, 'figure_position', figureHandle.Position, ...
    'axes_units', axesHandle.Units, 'axes_position', axesHandle.Position, ...
    'xlim', axesHandle.XLim, 'ylim', axesHandle.YLim, ...
    'xscale', axesHandle.XScale, 'yscale', axesHandle.YScale, ...
    'xdir', axesHandle.XDir, 'ydir', axesHandle.YDir, ...
    'font_name', axesHandle.FontName, 'font_size', axesHandle.FontSize, ...
    'font_units', axesHandle.FontUnits, 'xlabel', string(axesHandle.XLabel.String), ...
    'ylabel', string(axesHandle.YLabel.String), 'title', string(axesHandle.Title.String), ...
    'color_label', string(colorbarHandle.Label.String));
snapshot.scatter_groups = groups;
snapshot.shape = {1785};
snapshot.dimension_order = {"source_record"};
snapshot.consumer_status = 'not_integrated';
snapshot.qc_declaration = view.QC;
snapshot.uncertainty = view.Uncertainty;
snapshot.visual_verified = false;
snapshot.desktop_interaction_verified = false;
snapshot.comparison_v3_consumer_compatible = false;
end
