function run_github_full100(expected_release, output_root, nonce)
%RUN_GITHUB_FULL100 Execute all licensed GitHub MATLAB runtime gates.
arguments
    expected_release (1,1) string
    output_root (1,1) string
    nonce (1,1) string
end

detected_release = "R" + string(version('-release'));
assert(detected_release == expected_release, ...
    "run_github_full100:Release", ...
    "Expected MATLAB %s, detected %s", expected_release, detected_release);
assert(license('test', 'MATLAB') == 1, ...
    "run_github_full100:License", "Base MATLAB license is unavailable");
assert(strlength(strtrim(nonce)) >= 32, ...
    "run_github_full100:Nonce", "Evaluation nonce is invalid");

tests_directory = fileparts(mfilename("fullpath"));
matlab_directory = fileparts(tests_directory);
runtime_directory = fileparts(matlab_directory);
repository_root = fileparts(runtime_directory);
assets_directory = fullfile(matlab_directory, "assets");
eval_directory = fullfile(matlab_directory, "evals");
fixture_directory = fullfile(eval_directory, "fixtures");
interaction_directory = fullfile(repository_root, ".codex-evals", ...
    "matlab-100-20260905", "interaction");

output_root = string(output_root);
regression_directory = fullfile(output_root, "regression", "run");
family_b_directory = fullfile(output_root, "family-b");
export_directory = fullfile(output_root, "export");
interaction_output = fullfile(output_root, "interaction-headless");
evaluator_output = fullfile(output_root, "evaluator-runtime");
directories = [regression_directory family_b_directory export_directory ...
    interaction_output evaluator_output];
for directory = directories
    if ~isfolder(directory)
        mkdir(directory);
    end
end

addpath(assets_directory, tests_directory, eval_directory, interaction_directory);
old_directory = pwd;
directory_cleanup = onCleanup(@() cd(old_directory));
old_visibility = get(0, "DefaultFigureVisible");
visibility_cleanup = onCleanup(@() set(0, "DefaultFigureVisible", old_visibility));
set(0, "DefaultFigureVisible", "off");

probe = struct( ...
    "runtime", "matlab", ...
    "vendor", "MathWorks", ...
    "release", detected_release, ...
    "version", string(version), ...
    "executable", string(fullfile(matlabroot, "bin", "matlab")), ...
    "jvm_available", logical(usejava("jvm")), ...
    "desktop_available", logical(usejava("desktop")), ...
    "display_available", strlength(string(getenv("DISPLAY"))) > 0, ...
    "headless", true, ...
    "non_interactive", true, ...
    "figure_visible", false, ...
    "matlab_license_tested", true, ...
    "matlab_license_available", logical(license('test', 'MATLAB')), ...
    "products", product_records(ver));
write_json(fullfile(output_root, "matlab-runtime-probe.json"), probe);

stage_status_path = fullfile(output_root, "ci-stage-status.json");
stage_records = repmat(struct( ...
    "id", "", ...
    "status", "pending", ...
    "started_at", "", ...
    "completed_at", "", ...
    "error_identifier", "", ...
    "error_message", "", ...
    "error_report", ""), 0, 1);

[stage_records, ~] = run_stage(stage_records, "plot-regression", ...
    @() run_plot_regression(regression_directory), stage_status_path, expected_release);
[stage_records, ~] = run_stage(stage_records, "family-a-contracts", ...
    @() full100_family_a_contracts, stage_status_path, expected_release);
[stage_records, ~] = run_stage(stage_records, "family-b-runtime", ...
    @() full100_family_b_runtime(family_b_directory), stage_status_path, expected_release);
[stage_records, ~] = run_stage(stage_records, "family-c-contracts", ...
    @() full100_family_c_contracts, stage_status_path, expected_release);
[stage_records, ~] = run_stage(stage_records, "export-runtime", ...
    @() run_export_gate(export_directory, tests_directory), stage_status_path, expected_release);
[stage_records, ~] = run_stage(stage_records, "interaction-headless", ...
    @() run_interaction_acceptance("headless", interaction_output), stage_status_path, expected_release);
[stage_records, ~] = run_stage(stage_records, "evaluator-runtime", ...
    @() run_matlab_gate(fixture_directory, evaluator_output, nonce), stage_status_path, expected_release);

failed_stages = stage_records([stage_records.status] == "failed");
if ~isempty(failed_stages)
    failed_ids = strjoin([failed_stages.id], ", ");
    error("run_github_full100:StagesFailed", ...
        "MATLAB full-score stages failed: %s. See %s", failed_ids, stage_status_path);
end

clear visibility_cleanup directory_cleanup;
fprintf("MATLAB_FULL100_RELEASE=%s\n", expected_release);
fprintf("MATLAB_FULL100_OUTPUT=%s\n", output_root);
end

function [records, passed] = run_stage(records, stage_id, callback, status_path, expected_release)
record = struct( ...
    "id", string(stage_id), ...
    "status", "running", ...
    "started_at", utc_timestamp(), ...
    "completed_at", "", ...
    "error_identifier", "", ...
    "error_message", "", ...
    "error_report", "");
records(end + 1, 1) = record;
write_stage_status(status_path, expected_release, records);
try
    callback();
    records(end).status = "passed";
    passed = true;
catch stage_error
    records(end).status = "failed";
    records(end).error_identifier = string(stage_error.identifier);
    records(end).error_message = string(stage_error.message);
    records(end).error_report = string(getReport(stage_error, "extended", "hyperlinks", "off"));
    passed = false;
end
records(end).completed_at = utc_timestamp();
write_stage_status(status_path, expected_release, records);
end

function run_export_gate(export_directory, tests_directory)
old_directory = pwd;
cleanup = onCleanup(@() cd(old_directory));
cd(export_directory);
run(fullfile(tests_directory, "full100_export_runtime_gate.m"));
clear cleanup;
end

function write_stage_status(path, expected_release, stages)
payload = struct( ...
    "schema_version", 1, ...
    "generated_at", utc_timestamp(), ...
    "expected_release", string(expected_release), ...
    "stages", stages);
write_json(path, payload);
end

function value = utc_timestamp()
value = string(datetime("now", "TimeZone", "UTC", ...
    "Format", "yyyy-MM-dd'T'HH:mm:ss'Z'"));
end

function records = product_records(products)
records = arrayfun(@(product) struct( ...
    "name", string(product.Name), ...
    "version", string(product.Version)), products);
end

function write_json(path, payload)
file_id = fopen(path, "w", "n", "UTF-8");
assert(file_id >= 0, "run_github_full100:Write", ...
    "Unable to open JSON output: %s", path);
cleanup = onCleanup(@() fclose(file_id));
encoded = jsonencode(payload);
written = fwrite(file_id, encoded, "char");
assert(written == strlength(string(encoded)), ...
    "run_github_full100:Write", "Incomplete JSON write: %s", path);
clear cleanup;
end
