function manifest = run_plot_regression(output_directory)
%RUN_PLOT_REGRESSION Execute every MATLAB-native ocean asset in one fixture.
if nargin < 1 || isempty(output_directory)
    output_directory = fullfile(fileparts(mfilename("fullpath")), "output");
end
output_directory = string(output_directory);
if ~isfolder(output_directory)
    [created, message] = mkdir(output_directory);
    assert(created, "run_plot_regression:CreateDirectory", "%s", message);
end
clear_regression_outputs(output_directory);
asset_directory = fullfile(fileparts(mfilename("fullpath")), "..", "assets");
assert(isfolder(asset_directory), "run_plot_regression:MissingAssets", ...
    "MATLAB asset directory does not exist");
addpath(asset_directory);
test_asset_contracts();
test_asset_adversarial_contracts();

old_visible = get(0, "DefaultFigureVisible");
visible_cleanup = onCleanup(@() set(0, "DefaultFigureVisible", old_visible));
set(0, "DefaultFigureVisible", "off");
theme = oi_ocean_theme();
entries = struct([]);
assert(oi_get_option(struct("probe", true), "probe", false), ...
    "oi_get_option wiring is unavailable");
assert(oi_require_text("probe", "run_plot_regression:Text", ...
    "text metadata required") == "probe", ...
    "oi_require_text wiring is unavailable");

depth = [0; 10; 20; 30; 40];
profile_values = [9 10; NaN 11; 8 12; 7 NaN; 6 13];
entries = append_entry(entries, export_one(output_directory, "profile", ...
    "Ocean profile", theme, fixture_science_contract("numeric", [5 2], ...
    ["depth" "series"], struct("depth", "m", "series", "1", "value", "degC"), ...
    struct("depth", "positive_down", "series", "increasing"), ""), ...
    @(axes_handle) oi_plot_profile(axes_handle, depth, ...
    profile_values, struct("QuantityLabel", "Temperature", "QuantityUnit", "degC", ...
    "DepthUnit", "m", "VerticalReference", "mean sea level", ...
    "SeriesLabels", ["Station A" "Station B"], "MissingPolicy", "preserve", ...
    "Theme", theme, "Title", "Ocean profile"))));

distance = [0 5 10 15];
section_field = [10 11 12 13; 9 NaN 11 12; 8 9 10 11];
entries = append_entry(entries, export_one(output_directory, "section", ...
    "Ocean section", theme, fixture_science_contract("numeric", [3 4], ...
    ["depth" "distance"], struct("depth", "m", "distance", "km", "value", "degC"), ...
    struct("depth", "positive_down", "distance", "increasing"), ""), ...
    @(axes_handle) oi_plot_section(axes_handle, distance, ...
    depth(1:3), section_field, struct("DistanceUnit", "km", "DepthUnit", "m", ...
    "QuantityLabel", "Temperature", "QuantityUnit", "degC", ...
    "ColorLimits", [7 14], "MissingPolicy", "preserve", "Theme", theme, ...
    "Title", "Ocean section"))));

time_values = datetime(2024, 1, 1, 0:4, 0, 0, "TimeZone", "UTC");
time_values = time_values(:);
hovmoller_field = [10 11 12 13 14; 9 10 NaN 12 13; 8 9 10 11 12];
entries = append_entry(entries, export_one(output_directory, "hovmoller", ...
    "Time-depth evolution", theme, fixture_science_contract("datetime", [3 5], ...
    ["depth" "time"], struct("depth", "m", "time", "datetime", "value", "degC"), ...
    struct("depth", "positive_down", "time", "increasing"), "UTC"), ...
    @(axes_handle) oi_plot_hovmoller(axes_handle, ...
    time_values, depth(1:3), hovmoller_field, struct("TimeZone", "UTC", ...
    "DepthUnit", "m", "QuantityLabel", "Temperature", "QuantityUnit", "degC", ...
    "ColorLimits", [7 15], "MissingPolicy", "preserve", "Theme", theme, ...
    "Title", "Time-depth evolution"))));

series_time = datetime(2024, 1, 1, [0 1 2 6 7 8], 0, 0, "TimeZone", "UTC")';
series_table = timetable(series_time, [10; NaN; 12; 13; 14; 15], ...
    [0.2; NaN; 0.3; 0.2; 0.4; 0.3], ...
    ["good"; "missing"; "good"; "good"; "good"; "good"], ...
    'VariableNames', ["Temperature" "TemperatureUncertainty" "QCFlag"]);
series_table.Properties.VariableUnits = {'degC', 'degC', '1'};
series_contract = fixture_science_contract("timetable", 6, "time", ...
    struct("time", "datetime", "value", "degC"), ...
    struct("time", "increasing"), "UTC");
series_contract = with_qc(series_contract, "QCFlag", "time", ...
    struct("good", "accepted", "missing", "suspect"));
series_contract = with_uncertainty(series_contract, "standard-deviation", ...
    "magnitude", "degC", "time", NaN, "", "");
entries = append_entry(entries, export_one(output_directory, "time-series", ...
    "Validated time series", theme, series_contract, ...
    @(axes_handle) oi_plot_time_series(axes_handle, series_table, struct( ...
    "ValueVariables", "Temperature", "ValueLabels", "Sea temperature", ...
    "QCVariables", "QCFlag", "AcceptedQCValues", "good", ...
    "UncertaintyVariables", "TemperatureUncertainty", ...
    "UncertaintyType", "standard-deviation", "UncertaintyUnits", "degC", ...
    "GapThreshold", hours(2), "DisplayTimeZone", "UTC", ...
    "MissingPolicy", "preserve", "Theme", theme, ...
    "Title", "Validated time series"))));

x_values = [0 1 2 3];
y_values = [0; 1; 2];
u_component = [1 0.8 NaN 0.5; 0.9 0.7 0.4 0.3; 0.8 0.6 0.3 0.2];
v_component = [0.3 0.2 NaN 0.1; 0.4 0.3 0.2 0.1; 0.5 0.4 0.3 0.2];
entries = append_entry(entries, export_one(output_directory, "vector-field", ...
    "Ocean vector field", theme, fixture_science_contract("numeric", [3 4], ...
    ["y" "x"], struct("y", "km", "x", "km", "value", "m/s"), ...
    struct("y", "increasing", "x", "increasing"), ""), ...
    @(axes_handle) oi_plot_vector_field(axes_handle, ...
    x_values, y_values, u_component, v_component, struct("XUnit", "km", ...
    "YUnit", "km", "VectorUnit", "m/s", "ComponentFrame", "eastward/northward", ...
    "ReferenceMagnitude", 1, "XLabel", "East distance", "YLabel", "North distance", ...
    "MissingPolicy", "preserve", "Theme", theme, "Title", "Ocean vector field"))));

observation_values = [1; 2; 3; NaN; 5];
model_values = [1.1; 1.8; 3.2; 4; 4.7];
entries = append_entry(entries, export_one(output_directory, "comparison", ...
    "Observation-model comparison", theme, fixture_science_contract("numeric", 5, ...
    "sample", struct("sample", "1", "value", "degC"), ...
    struct("sample", "increasing"), ""), ...
    @(axes_handle) oi_plot_comparison(axes_handle, ...
    observation_values, model_values, struct("QuantityUnit", "degC", ...
    "ObservationLabel", "Observation", "ModelLabel", "Model", ...
    "MissingPolicy", "preserve", "Theme", theme, ...
    "Title", "Observation-model comparison"))));

salinity = [34.1; 34.4; NaN; 35.0; 35.2];
temperature = [12; 9; 7; NaN; 4];
sample_depth = [0; 10; 20; 30; 40];
entries = append_entry(entries, export_one(output_directory, "ts-diagram", ...
    "Temperature-salinity diagram", theme, fixture_science_contract("numeric", 5, ...
    "sample", struct("sample", "1", "value", "degC", "salinity", "PSU", "depth", "m"), ...
    struct("sample", "increasing"), ""), ...
    @(axes_handle) oi_plot_ts_diagram(axes_handle, ...
    salinity, temperature, sample_depth, struct("SalinityLabel", "Salinity", ...
    "SalinityUnit", "PSU", "TemperatureLabel", "Temperature", ...
    "TemperatureUnit", "degC", "ColorLabel", "Depth", "ColorUnit", "m", ...
    "ColorLimits", [0 45], "MissingPolicy", "preserve", "Theme", theme, ...
    "Title", "Temperature-salinity diagram"))));

frequency = logspace(-2, 0, 25)';
spectral_density = (frequency .^ -0.7) .* exp(-frequency / 0.8);
spectral_density(10) = NaN;
lower_bound = 0.8 * spectral_density;
upper_bound = 1.2 * spectral_density;
entries = append_entry(entries, export_one(output_directory, "spectrum", ...
    "Power spectral density", theme, with_uncertainty(fixture_science_contract("numeric", 25, ...
    "frequency", struct("frequency", "Hz", "value", "degC^2/Hz"), ...
    struct("frequency", "increasing"), ""), "confidence-interval", "bounds", ...
    "degC^2/Hz", "frequency", 0.95, "LowerBound", "UpperBound"), ...
    @(axes_handle) oi_plot_spectrum(axes_handle, ...
    frequency, spectral_density, struct("FrequencyUnit", "Hz", "PeriodUnit", "s", ...
    "DensityUnit", "degC^2/Hz", "WindowDescription", "Hann window", ...
    "DetrendDescription", "linear detrend", "SegmentDescription", "two valid segments", ...
    "DegreesOfFreedom", 8, "LowerBound", lower_bound, "UpperBound", upper_bound, ...
    "BoundType", "confidence-interval", "ConfidenceLevel", 0.95, ...
    "MissingPolicy", "preserve", "Theme", theme, "Title", "Power spectral density"))));

direction = [0; 45; 90; 135; 180; 225; 270; 315; NaN];
weights = [1; 2; 1; 3; 2; 1; 2; 1; NaN];
entries = append_entry(entries, export_one(output_directory, "direction-rose", ...
    "Directional rose", theme, fixture_science_contract("numeric", 9, ...
    "sample", struct("sample", "1", "value", "degree", "weight", "1"), ...
    struct("sample", "increasing"), ""), ...
    @(axes_handle) render_direction(axes_handle, direction, ...
    weights, theme)));

observation_time = datetime(2024, 1, 1, 0:5, 0, 0, "TimeZone", "UTC")';
observation_table = table(observation_time, [10; NaN; 12; 13; 14; 15], ...
    [0.2; NaN; 0.3; 0.2; 0.4; 0.3], ...
    "obs-" + string((1:6)'), repmat("Station A", 6, 1), ...
    ["good"; "missing"; "good"; "good"; "suspect"; "good"], ...
    'VariableNames', ["Time" "Value" "Uncertainty" "ObservationID" "Station" "QCFlag"]);
interactive_output = interactive_timeseries_native_template(observation_table, ...
    fullfile(output_directory, "interactive-timeseries"), "Interactive", false, ...
    "ExportMode", "graphics", "ExportSVG", true, ...
    "Title", "Interactive time series", ...
    "ValueLabel", "Temperature", "ValueUnit", "degC", ...
    "UncertaintyType", "standard-deviation", "UncertaintyUnit", "degC");
assert(isstruct(interactive_output.ManifestEntry) ...
    && ~isempty(interactive_output.ManifestEntry), ...
    "Interactive template did not return a manifest entry");
assert(interactive_output.ValidCount == 5 && interactive_output.MissingCount == 1, ...
    "Interactive template returned incorrect valid/missing counts");
assert(interactive_output.QCPolicy == "preserve" ...
    && sum(interactive_output.QCSummary.Count) == height(observation_table), ...
    "Interactive template did not preserve and count every QC flag");
assert(interactive_output.UncertaintyPresent ...
    && interactive_output.UncertaintyRepresentation == "magnitude" ...
    && interactive_output.UncertaintyMissingCount == 0, ...
    "Interactive template did not preserve uncertainty semantics");
interactive_output.Lines(1).BrushData = [0; 1; 0; 0; 1; 0];
selected_ids = interactive_output.GetSelectedObservationIDs();
assert(isequal(string(selected_ids), ["obs-2"; "obs-5"]), ...
    "Interactive brush selection did not preserve ObservationID mapping");
interactive_output.ClearBrushSelection();
assert(isempty(interactive_output.GetSelectedObservationIDs()), ...
    "Interactive brush selection was not cleared");
interactive_contract = fixture_science_contract("datetime", 6, "time", ...
    struct("time", "datetime", "value", "degC"), struct("time", "increasing"), "UTC");
interactive_contract = with_qc(interactive_contract, "QCFlag", "time", ...
    struct("good", "accepted", "missing", "suspect", "suspect", "suspect"));
interactive_contract = with_uncertainty(interactive_contract, "standard-deviation", ...
    "magnitude", "degC", "time", NaN, "", "");
interactive_contract = finalize_science_contract(interactive_contract, ...
    interactive_output.ValidCount, interactive_output.MissingCount);
interactive_entry = interactive_output.ManifestEntry;
interactive_entry.scientific_data_contract = interactive_contract;
entries = append_entry(entries, interactive_entry);
close(interactive_output.Figure);
assert(~isgraphics(interactive_output.Figure), ...
    "Interactive figure was not closed after export");

figure_ids = string({entries.id});
[~, sort_order] = sort(figure_ids);
entries = entries(sort_order);
manifest = oi_write_manifest(fullfile(output_directory, "figures.json"), entries);
assert(isfile(fullfile(output_directory, "figures.json")) ...
    && dir(fullfile(output_directory, "figures.json")).bytes > 0, ...
    "figures.json was not written");
assert(manifest.execution_verified && manifest.runtime_status == "ready" ...
    && manifest.artifact_validation.status == "passed" ...
    && manifest.visual_inspection.verified == false ...
    && strlength(manifest.matlab_release) > 0, ...
    "Regression manifest status is incomplete");
clear visible_cleanup;
fprintf("MATLAB_ASSET_REGRESSION_FIGURES=%d\n", numel(entries));
end

function entry = export_one(output_directory, figure_id, title_text, theme, science_contract, plotter)
figure_handle = oi_figure(2400, 1500, "off");
cleanup = onCleanup(@() close_if_valid(figure_handle));
figure_handle.Units = "inches";
figure_handle.Position(3:4) = [2400 / 300 1500 / 300];
axes_handle = axes("Parent", figure_handle, "Units", "normalized", ...
    "PositionConstraint", "outerposition", "OuterPosition", [0.04 0.04 0.92 0.92]);
result = plotter(axes_handle);
assert(isstruct(result) && isfield(result, "Axes"), ...
    "Plot helper did not return an Axes field");
assert(isfield(result, "ValidCount") && isfield(result, "MissingCount") ...
    && isfield(result, "valid_count") && isfield(result, "missing_count"), ...
    "Plot helper result does not satisfy the router count contract");
assert(result.ValidCount == result.valid_count ...
    && result.MissingCount == result.missing_count && result.MissingCount > 0, ...
    "Plot helper did not preserve missing counts in both result contracts");
oi_apply_axes(axes_handle, theme);
drawnow;
entry = oi_export_figure(figure_handle, output_directory, figure_id, 2400, 1500, 300, ...
    "Title", title_text, "Source", "MATLAB ocean asset regression", ...
    "Theme", theme.Name, "ExportSVG", true);
entry.scientific_data_contract = finalize_science_contract(science_contract, ...
    result.ValidCount, result.MissingCount);
close(figure_handle);
clear cleanup;
assert(~isgraphics(figure_handle), "Figure handle remained valid after export");
end

function contract = fixture_science_contract(data_type, shape, dimension_order, units, directions, time_zone)
shape = double(shape(:)');
dimension_order = string(dimension_order(:)');
coordinates = struct();
for index = 1:numel(dimension_order)
    name = dimension_order(index);
    coordinate = struct("count", shape(index), "unit", string(units.(name)), ...
        "direction", string(directions.(name)));
    if name == "time"
        coordinate.timezone = string(time_zone);
    end
    coordinates.(name) = coordinate;
end
contract = struct("schemaVersion", 1, "provided", true, "required", true, ...
    "dataType", string(data_type), "shape", shape, "rank", numel(shape), ...
    "dimensionOrder", dimension_order, "observationDimension", dimension_order(1), ...
    "coordinates", coordinates, "units", units, ...
    "missing", struct("status", "present", "policy", "preserve", ...
        "representation", "NaN", "masked_count", 0), ...
    "qc", struct("status", "absent", "action", "preserve"), ...
    "uncertainty", struct("status", "absent"), ...
    "unresolvedRequirements", strings(0, 1));
if any(dimension_order == "time")
    contract.timeZone = string(time_zone);
end
end

function contract = finalize_science_contract(contract, valid_count, missing_count)
total_count = prod(contract.shape);
assert(valid_count + missing_count == total_count, ...
    "run_plot_regression:ScienceCounts", ...
    "Scientific valid/missing counts must equal the declared shape product");
contract.missing.total_count = total_count;
contract.missing.valid_count = valid_count;
contract.missing.missing_count = missing_count;
end

function contract = with_qc(contract, variable, alignment, flag_meanings)
contract.qc = struct("status", "present", "variable", string(variable), ...
    "alignment", string(alignment), "action", "preserve", ...
    "flagMeanings", flag_meanings);
end

function contract = with_uncertainty(contract, type, representation, unit, alignment, confidence_level, lower, upper)
contract.uncertainty = struct("status", "present", "type", string(type), ...
    "representation", string(representation), "unit", string(unit), ...
    "alignment", string(alignment));
if isfinite(confidence_level)
    contract.uncertainty.confidenceLevel = confidence_level;
end
if strlength(string(lower)) > 0
    contract.uncertainty.lower = string(lower);
    contract.uncertainty.upper = string(upper);
end
end

function result = render_direction(axes_handle, direction, weights, theme)
result = oi_plot_direction_rose(axes_handle, direction, struct( ...
    "Weights", weights, "DirectionConvention", "from", ...
    "DirectionUnit", "degree", "Normalization", "percent", ...
    "MissingPolicy", "preserve", "Theme", theme, "Title", "Directional rose"));
oi_apply_axes(axes_handle, theme);
assert(isgraphics(axes_handle), "Original direction axes handle was destroyed");
end

function entries = append_entry(entries, entry)
if isempty(entries)
    entries = entry;
else
    entries(end + 1) = entry;
end
end

function close_if_valid(figure_handle)
if isgraphics(figure_handle)
    close(figure_handle);
end
end

function clear_regression_outputs(output_directory)
figure_ids = ["comparison" "direction-rose" "hovmoller" "interactive-timeseries" ...
    "profile" "section" "spectrum" "time-series" "ts-diagram" "vector-field"];
for figure_id = figure_ids
    for extension = [".png" ".pdf" ".svg"]
        file_path = fullfile(output_directory, figure_id + extension);
        if isfile(file_path)
            delete(file_path);
        end
    end
end
manifest_path = fullfile(output_directory, "figures.json");
if isfile(manifest_path)
    delete(manifest_path);
end
end
