function run_github_full100(expected_release, output_root, nonce)
%RUN_GITHUB_FULL100 Execute all licensed GitHub MATLAB runtime gates.
arguments
    expected_release (1,1) string
    output_root (1,1) string
    nonce (1,1) string
end

detected_release = "R" + string(version('-release'));
assert(detected_release == expected_release, ...
    "run_github_full100:Release", ...
    "Expected MATLAB %s, detected %s", expected_release, detected_release);
assert(license('test', 'MATLAB') == 1, ...
    "run_github_full100:License", "Base MATLAB license is unavailable");
assert(strlength(strtrim(nonce)) >= 32, ...
    "run_github_full100:Nonce", "Evaluation nonce is invalid");

tests_directory = fileparts(mfilename("fullpath"));
matlab_directory = fileparts(tests_directory);
runtime_directory = fileparts(matlab_directory);
repository_root = fileparts(runtime_directory);
assets_directory = fullfile(matlab_directory, "assets");
eval_directory = fullfile(matlab_directory, "evals");
fixture_directory = fullfile(eval_directory, "fixtures");
interaction_directory = fullfile(repository_root, ".codex-evals", ...
    "matlab-100-20260905", "interaction");

output_root = string(output_root);
regression_directory = fullfile(output_root, "regression", "run");
family_b_directory = fullfile(output_root, "family-b");
export_directory = fullfile(output_root, "export");
interaction_output = fullfile(output_root, "interaction-headless");
evaluator_output = fullfile(output_root, "evaluator-runtime");
font_export_output = fullfile(output_root, "font-export-probe");
directories = [regression_directory family_b_directory export_directory ...
    interaction_output evaluator_output];
for directory = directories
    if ~isfolder(directory)
        mkdir(directory);
    end
end

addpath(assets_directory, tests_directory, eval_directory, interaction_directory);
old_directory = pwd;
directory_cleanup = onCleanup(@() cd(old_directory));
old_visibility = get(0, "DefaultFigureVisible");
visibility_cleanup = onCleanup(@() set(0, "DefaultFigureVisible", old_visibility));
set(0, "DefaultFigureVisible", "off");

probe = struct( ...
    "runtime", "matlab", ...
    "vendor", "MathWorks", ...
    "release", detected_release, ...
    "version", string(version), ...
    "executable", string(fullfile(matlabroot, "bin", "matlab")), ...
    "jvm_available", logical(usejava("jvm")), ...
    "desktop_available", logical(usejava("desktop")), ...
    "display_available", strlength(string(getenv("DISPLAY"))) > 0, ...
    "screen_pixels_per_inch", get(groot, "ScreenPixelsPerInch"), ...
    "exportgraphics_path", string(which("exportgraphics")), ...
    "exportgraphics_file_type", exist("exportgraphics", "file"), ...
    "xmlread_path", string(which("xmlread")), ...
    "xmlread_file_type", exist("xmlread", "file"), ...
    "headless", true, ...
    "non_interactive", true, ...
    "figure_visible", false, ...
    "matlab_license_tested", true, ...
    "matlab_license_available", logical(license('test', 'MATLAB')), ...
    "products", product_records(ver));
write_json(fullfile(output_root, "matlab-runtime-probe.json"), probe);

stage_status_path = fullfile(output_root, "ci-stage-status.json");
stage_records = repmat(struct( ...
    "id", "", ...
    "status", "pending", ...
    "started_at", "", ...
    "completed_at", "", ...
    "error_identifier", "", ...
    "error_message", "", ...
    "error_report", ""), 0, 1);

[stage_records, ~] = run_stage(stage_records, "font-export-probe", ...
    @() diagnose_font_exports(font_export_output), stage_status_path, expected_release);
[stage_records, ~] = run_stage(stage_records, "generated-router-runtime", ...
    @() test_generated_plot_router(output_root), stage_status_path, expected_release);
[stage_records, ~] = run_stage(stage_records, "plot-regression", ...
    @() run_plot_regression(regression_directory), stage_status_path, expected_release);
[stage_records, ~] = run_stage(stage_records, "family-a-contracts", ...
    @() full100_family_a_contracts, stage_status_path, expected_release);
[stage_records, ~] = run_stage(stage_records, "family-b-runtime", ...
    @() full100_family_b_runtime(family_b_directory), stage_status_path, expected_release);
[stage_records, ~] = run_stage(stage_records, "family-c-contracts", ...
    @() full100_family_c_contracts, stage_status_path, expected_release);
[stage_records, ~] = run_stage(stage_records, "export-metadata", ...
    @() test_svg_metadata, stage_status_path, expected_release);
[stage_records, ~] = run_stage(stage_records, "manifest-evidence-integrity", ...
    @() test_manifest_evidence_integrity(export_directory), ...
    stage_status_path, expected_release);
[stage_records, ~] = run_stage(stage_records, "text-bounds", ...
    @() test_text_bounds, stage_status_path, expected_release);
[stage_records, ~] = run_stage(stage_records, "font-availability", ...
    @() test_font_available, stage_status_path, expected_release);
[stage_records, ~] = run_stage(stage_records, "color-accessibility", ...
    @() test_color_accessibility, stage_status_path, expected_release);
[stage_records, ~] = run_stage(stage_records, "series-style-preservation", ...
    @() test_series_style_preservation, stage_status_path, expected_release);
[stage_records, ~] = run_stage(stage_records, "export-runtime", ...
    @() run_export_gate(export_directory), stage_status_path, expected_release);
[stage_records, ~] = run_stage(stage_records, "interaction-native-compatibility", ...
    @() test_interaction_native_compatibility, stage_status_path, expected_release);
[stage_records, ~] = run_stage(stage_records, "interaction-headless", ...
    @() run_interaction_acceptance("headless", interaction_output), stage_status_path, expected_release);
[stage_records, ~] = run_stage(stage_records, "evaluator-runtime", ...
    @() run_matlab_gate(fixture_directory, evaluator_output, nonce), stage_status_path, expected_release);

stage_summary = summarize_stages(stage_records);
assert(stage_summary.pending == 0 && stage_summary.running == 0 ...
    && stage_summary.total == stage_summary.passed + stage_summary.failed, ...
    "run_github_full100:StageSummary", ...
    "Stage summary does not match the completed stage records");
failed_stages = stage_records([stage_records.status] == "failed");
if ~isempty(failed_stages)
    failed_ids = strjoin([failed_stages.id], ", ");
    error("run_github_full100:StagesFailed", ...
        "MATLAB full-score stages failed: %s (%d/%d passed, %d failed). See %s", ...
        failed_ids, stage_summary.passed, stage_summary.total, ...
        stage_summary.failed, stage_status_path);
end

clear visibility_cleanup directory_cleanup;
fprintf("MATLAB_FULL100_RELEASE=%s\n", expected_release);
fprintf("MATLAB_FULL100_OUTPUT=%s\n", output_root);
fprintf("MATLAB_FULL100_STAGE_COUNT=%d\n", stage_summary.total);
fprintf("MATLAB_FULL100_STAGE_PASSED=%d\n", stage_summary.passed);
fprintf("MATLAB_FULL100_STAGE_FAILED=%d\n", stage_summary.failed);
end

function [records, passed] = run_stage(records, stage_id, callback, status_path, expected_release)
record = struct( ...
    "id", string(stage_id), ...
    "status", "running", ...
    "started_at", utc_timestamp(), ...
    "completed_at", "", ...
    "error_identifier", "", ...
    "error_message", "", ...
    "error_report", "");
records(end + 1, 1) = record;
write_stage_status(status_path, expected_release, records);
try
    callback();
    records(end).status = "passed";
    passed = true;
catch stage_error
    records(end).status = "failed";
    records(end).error_identifier = string(stage_error.identifier);
    records(end).error_message = string(stage_error.message);
    records(end).error_report = string(getReport(stage_error, "extended", "hyperlinks", "off"));
    passed = false;
end
records(end).completed_at = utc_timestamp();
write_stage_status(status_path, expected_release, records);
end

function run_export_gate(export_directory)
working_directory = string(pwd);
artifact_directory = fullfile(export_directory, "full100-export-artifacts");
full100_export_contracts(artifact_directory, true);
assert(string(pwd) == working_directory, ...
    "run_github_full100:ExportWorkingDirectory", ...
    "The export gate changed the caller working directory");
required_artifacts = ["publication.png" "publication.pdf" ...
    "publication.svg" "figures.json"];
for artifact = required_artifacts
    artifact_path = fullfile(artifact_directory, artifact);
    assert(isfile(artifact_path) && dir(artifact_path).bytes > 0, ...
        "run_github_full100:MissingExportArtifact", ...
        "Export gate did not archive a nonempty artifact at %s", artifact_path);
end
end

function write_stage_status(path, expected_release, stages)
payload = struct( ...
    "schema_version", 1, ...
    "generated_at", utc_timestamp(), ...
    "expected_release", string(expected_release), ...
    "summary", summarize_stages(stages), ...
    "stages", stages);
write_json(path, payload);
end

function summary = summarize_stages(stages)
statuses = string({stages.status});
summary = struct( ...
    "total", numel(stages), ...
    "pending", sum(statuses == "pending"), ...
    "running", sum(statuses == "running"), ...
    "passed", sum(statuses == "passed"), ...
    "failed", sum(statuses == "failed"));
end

function value = utc_timestamp()
value = string(datetime("now", "TimeZone", "UTC", ...
    "Format", "yyyy-MM-dd'T'HH:mm:ss'Z'"));
end

function records = product_records(products)
records = arrayfun(@(product) struct( ...
    "name", string(product.Name), ...
    "version", string(product.Version)), products);
end

function write_json(path, payload)
file_id = fopen(path, "w", "n", "UTF-8");
assert(file_id >= 0, "run_github_full100:Write", ...
    "Unable to open JSON output: %s", path);
cleanup = onCleanup(@() fclose(file_id));
encoded = jsonencode(payload);
written = fwrite(file_id, encoded, "char");
assert(written == strlength(string(encoded)), ...
    "run_github_full100:Write", "Incomplete JSON write: %s", path);
clear cleanup;
end
