function test_asset_contracts()
%TEST_ASSET_CONTRACTS Run focused MATLAB-native contract and lifecycle checks.
theme = oi_ocean_theme();
assert(oi_get_option(struct("Value", 4), "Value", 0) == 4, ...
    "oi_get_option did not return a present value");

[figure_handle, axes_handle] = make_axes();
cleanup_figure = onCleanup(@() close_if_valid(figure_handle));
oi_apply_axes(axes_handle, theme);
hold_cleanup = oi_hold_axes(axes_handle);
assert(ishold(axes_handle), "oi_hold_axes did not enable additive plotting");
clear hold_cleanup;
assert(~ishold(axes_handle), "oi_hold_axes did not restore the caller hold state");
imagesc(axes_handle, [0 1], [0 1], [0 1; 1 0]);
colorbar_handle = colorbar(axes_handle);
colorbar_handle.Label.String = "Temperature (degC)";
oi_apply_color_scale(axes_handle, colorbar_handle, theme.SequentialMap, ...
    [0 1], theme, theme.MissingColor);
assert(isequal(axes_handle.CLim, [0 1]) ...
    && isequal(axes_handle.Color, theme.MissingColor) ...
    && string(colorbar_handle.FontName) == theme.FontName ...
    && string(colorbar_handle.Label.Interpreter) == "none", ...
    "oi_apply_color_scale did not apply the shared publication contract");
must_throw(@() oi_apply_color_scale(axes_handle, colorbar_handle, ...
    [0 0 0; NaN 1 1], [0 1], theme), "InvalidColormap");
cla(axes_handle);
must_throw(@() oi_plot_profile(axes_handle, [-1; 1], [2; 3], ...
    struct("QuantityUnit", "degC", "DepthUnit", "m", ...
    "VerticalReference", "sea surface", "Theme", theme)), "DepthDirection");
must_throw(@() oi_plot_profile(axes_handle, [0; 1], [2; Inf], ...
    struct("QuantityUnit", "degC", "DepthUnit", "m", ...
    "VerticalReference", "sea surface", "Theme", theme)), "InvalidValues");
must_throw(@() oi_plot_profile(axes_handle, [0; 1], [2; 3], ...
    struct("QuantityUnit", "degC", "DepthUnit", "m", "Theme", theme)), "Units");
clear cleanup_figure;
close_if_valid(figure_handle);

[figure_handle, axes_handle] = make_axes();
cleanup_figure = onCleanup(@() close_if_valid(figure_handle));
series_time = datetime(2024, 1, 1, [0 1 5 6 7], 0, 0, "TimeZone", "UTC")';
series_table = timetable(series_time, [1; 2; 3; NaN; 5], ...
    [0.1; 0.1; 0.2; NaN; 0.1], ...
    ["good"; "good"; "suspect"; "missing"; "good"], ...
    'VariableNames', ["Value" "Uncertainty" "QCFlag"]);
series_table.Properties.VariableUnits = {'degC', 'degC', '1'};
series_result = oi_plot_time_series(axes_handle, series_table, struct( ...
    "ValueVariables", "Value", "ValueLabels", "Temperature", ...
    "QCVariables", "QCFlag", "AcceptedQCValues", ["good" "suspect"], ...
    "UncertaintyVariables", "Uncertainty", ...
    "UncertaintyType", "standard-deviation", "UncertaintyUnits", "degC", ...
    "GapThreshold", hours(2), "DisplayTimeZone", "UTC", "Theme", theme));
assert(series_result.ValidCount == 4 && series_result.MissingCount == 1 ...
    && series_result.GapCount == 1 && series_result.QCRejectedCount == 0 ...
    && series_result.DisplayTimeZone == "UTC", ...
    "Time-series table, gap, QC, uncertainty, or timezone contract changed");
unzoned_table = timetable(datetime(2024, 1, 1, [0 1], 0, 0)', [1; 2], ...
    'VariableNames', "Value");
must_throw(@() oi_plot_time_series(axes_handle, unzoned_table, struct( ...
    "ValueVariables", "Value", "ValueUnits", "degC", "Theme", theme)), ...
    "TimeZone");
must_throw(@() oi_plot_time_series(axes_handle, series_table, struct( ...
    "ValueVariables", "Value", "ValueUnits", "kelvin", "Theme", theme)), ...
    "ValueUnits");
clear cleanup_figure;
close_if_valid(figure_handle);

[figure_handle, axes_handle] = make_axes();
cleanup_figure = onCleanup(@() close_if_valid(figure_handle));
must_throw(@() oi_plot_section(axes_handle, [0 1], [0; 1], [1 2; 3 4], ...
    struct("ColorLimits", [1 1], "DistanceUnit", "km", ...
    "DepthUnit", "m", "QuantityUnit", "degC", "Theme", theme)), "ColorLimits");
must_throw(@() oi_plot_section(axes_handle, [0 1], [0; 1], [1 2; 3 4], ...
    struct("ColorLimits", [1 2], "DepthUnit", "m", ...
    "QuantityUnit", "degC", "Theme", theme)), "Units");
must_throw(@() oi_plot_section(axes_handle, [0 1 2], [0; 1], ...
    ones(3, 2), struct("ColorLimits", [0 2], "DistanceUnit", "km", ...
    "DepthUnit", "m", "QuantityLabel", "Temperature", ...
    "QuantityUnit", "degC", "Theme", theme)), "SizeMismatch");
clear cleanup_figure;
close_if_valid(figure_handle);

[figure_handle, axes_handle] = make_axes();
cleanup_figure = onCleanup(@() close_if_valid(figure_handle));
time_values = datetime(2024, 1, 1, [0 1 3], 0, 0, "TimeZone", "UTC")';
must_throw(@() oi_plot_hovmoller(axes_handle, time_values, [0; 1], ...
    ones(2, 3), struct("TimeZone", "UTC", "ColorLimits", [0 2], ...
    "DepthUnit", "m", "QuantityUnit", "degC", "Theme", theme)), "TimeCadence");
must_throw(@() oi_plot_hovmoller(axes_handle, time_values, [0; 1], ...
    ones(2, 3), struct("TimeZone", "Asia/Shanghai", "ColorLimits", [0 2], ...
    "DepthUnit", "m", "QuantityLabel", "Temperature", ...
    "QuantityUnit", "degC", "Theme", theme)), "TimeZoneMismatch");
must_throw(@() oi_plot_hovmoller(axes_handle, time_values(1:2), [0; 1], ...
    ones(2, 2), struct("TimeZone", "UTC", "ColorLimits", [0 2], ...
    "QuantityUnit", "degC", "Theme", theme)), "Units");
clear cleanup_figure;
close_if_valid(figure_handle);

[figure_handle, axes_handle] = make_axes();
cleanup_figure = onCleanup(@() close_if_valid(figure_handle));
must_throw(@() oi_plot_ts_diagram(axes_handle, [NaN; NaN], [NaN; NaN], ...
    [NaN; NaN], struct("ColorLimits", [0 1], "SalinityUnit", "PSU", ...
    "TemperatureUnit", "degC", "ColorLabel", "Depth", ...
    "ColorUnit", "m", "Theme", theme)), "NoCompleteSamples");
must_throw(@() oi_plot_ts_diagram(axes_handle, [34; 35], [5; 6], ...
    [0; 10], struct("ColorLimits", [0 20], "SalinityUnit", "PSU", ...
    "TemperatureUnit", "degC", "ColorLabel", "Depth", ...
    "Theme", theme)), "Units");
clear cleanup_figure;
close_if_valid(figure_handle);

[figure_handle, axes_handle] = make_axes();
cleanup_figure = onCleanup(@() close_if_valid(figure_handle));
must_throw(@() oi_plot_spectrum(axes_handle, [0; 1], [1; 2], ...
    struct("FrequencyUnit", "Hz", "PeriodUnit", "s", ...
    "DensityUnit", "unit", "WindowDescription", "Hann", ...
    "DetrendDescription", "linear", "SegmentDescription", "one", ...
    "Theme", theme)), "Frequency");
must_throw(@() oi_plot_spectrum(axes_handle, [1; 2], [2; 1], ...
    struct("FrequencyUnit", "Hz", "PeriodUnit", "s", ...
    "DensityUnit", "unit", "WindowDescription", "Hann", ...
    "DetrendDescription", "linear", "SegmentDescription", "one", ...
    "LowerBound", [1; NaN], "UpperBound", [3; 2], ...
    "BoundType", "confidence-interval", "ConfidenceLevel", 0.95, ...
    "Theme", theme)), "BoundMaskMismatch");
must_throw(@() oi_plot_spectrum(axes_handle, [1; 2], [2; 1], ...
    struct("FrequencyUnit", "Hz", "PeriodUnit", "s", ...
    "DensityUnit", "unit", "WindowDescription", "Hann", ...
    "DetrendDescription", "linear", "SegmentDescription", "one", ...
    "LowerBound", [1; 0.5], "UpperBound", [3; 2], ...
    "BoundType", "confidence-interval", "Theme", theme)), "ConfidenceLevel");
clear cleanup_figure;
close_if_valid(figure_handle);

[figure_handle, axes_handle] = make_axes();
cleanup_figure = onCleanup(@() close_if_valid(figure_handle));
must_throw(@() oi_plot_direction_rose(axes_handle, [0; 90], ...
    struct("DirectionUnit", "degree clockwise from true north", ...
    "Theme", theme)), "DirectionConvention");
must_throw(@() oi_plot_direction_rose(axes_handle, [0; 90], ...
    struct("DirectionConvention", "from", "DirectionUnit", "radian", ...
    "Theme", theme)), "Units");
must_throw(@() oi_plot_direction_rose(axes_handle, [0; 90], ...
    struct("DirectionConvention", "from", ...
    "DirectionUnit", "degree clockwise from true north", ...
    "Theme", theme)), "Normalization");
clear cleanup_figure;
close_if_valid(figure_handle);

[figure_handle, axes_handle] = make_axes();
cleanup_figure = onCleanup(@() close_if_valid(figure_handle));
direction_result = oi_plot_direction_rose(axes_handle, [0; 90; NaN], ...
    struct("DirectionConvention", "from", ...
    "DirectionUnit", "degree clockwise from true north", ...
    "Normalization", "percent", ...
    "Theme", theme));
assert(isgraphics(axes_handle) && isgraphics(direction_result.Axes), ...
    "Direction rose destroyed the caller axes handle");
direction_labels = getappdata(direction_result.Axes, "OI_AxisLabels");
assert(isstruct(direction_labels) && strlength(string(direction_labels.xlabel)) > 0 ...
    && strlength(string(direction_labels.ylabel)) > 0, ...
    "Direction rose did not preserve polar axis unit labels");
oi_apply_axes(axes_handle, theme);
clear cleanup_figure;
close_if_valid(figure_handle);

tiled_figure = oi_figure(640, 480, "off");
tiled_cleanup = onCleanup(@() close_if_valid(tiled_figure));
tiled_layout = tiledlayout(tiled_figure, 1, 1);
tiled_axes = nexttile(tiled_layout);
tiled_result = oi_plot_direction_rose(tiled_axes, [0; 90; 180], ...
    struct("DirectionConvention", "to", ...
    "DirectionUnit", "degree", ...
    "Normalization", "count", ...
    "Theme", theme));
assert(isgraphics(tiled_result.Axes) && ~isgraphics(tiled_axes) ...
    && tiled_result.Axes.Layout.Tile == 1, ...
    "Direction rose did not replace the original tiled axis");
clear tiled_cleanup;
close_if_valid(tiled_figure);

qc_flags = ["good"; "suspect"; "good"];
qc_flags(2) = missing;
qc_table = table(datetime(2024, 1, 1, 0:2, 0, 0, "TimeZone", "UTC")', ...
    [1; 2; 3], ["obs-1"; "obs-2"; "obs-3"], ...
    repmat("Station A", 3, 1), qc_flags, ...
    'VariableNames', ["Time" "Value" "ObservationID" "Station" "QCFlag"]);
must_throw(@() interactive_timeseries_native_template(qc_table, "unused", ...
    "Interactive", false, "Export", false, ...
    "ValueLabel", "Temperature", "ValueUnit", "degC"), "nonmissing");
single_table = table(datetime(2024, 1, 1, "TimeZone", "UTC"), 1, "obs-single", ...
    "Station A", "good", ...
    'VariableNames', ["Time" "Value" "ObservationID" "Station" "QCFlag"]);
must_throw(@() interactive_timeseries_native_template(single_table, "unused", ...
    "Interactive", false, "Export", false, "TimeZone", "Asia/Shanghai", ...
    "ValueLabel", "Temperature", "ValueUnit", "degC"), "declared TimeZone");
single_output = interactive_timeseries_native_template(single_table, "unused", ...
    "Interactive", false, "Export", false, "TimeZone", "UTC", ...
    "ValueLabel", "Temperature", "ValueUnit", "degC");
assert(single_output.ValidCount == 1 && single_output.MissingCount == 0 ...
    && isgraphics(single_output.Figure) ...
    && string(single_output.Axes(1).XDir) == "normal" ...
    && string(single_output.Axes(1).FontName) == single_output.FontName ...
    && single_output.Layout.Padding == "loose" ...
    && single_output.ExportTarget == "plot" && ~single_output.ExportPerformed ...
    && ~single_output.PublicationExport ...
    && ~single_output.ManifestAvailable ...
    && single_output.ManifestReason == "export_not_performed" ...
    && single_output.ExportAPI.png == "not_performed" ...
    && single_output.RequiredProducts == "MATLAB" ...
    && isempty(single_output.RequiredToolboxes) ...
    && strlength(single_output.RuntimeRelease) > 0 ...
    && ~single_output.CJKTextPresent && ~single_output.FontRenderingVerified, ...
    "Interactive template rejected a valid singleton or reversed time direction");
valid_tip = single_output.DataCursorUpdateFcn([], ...
    struct("Target", single_output.Lines(1), "DataIndex", 1));
assert(numel(valid_tip) == 5 && contains(string(valid_tip{1}), "obs-single") ...
    && contains(string(valid_tip{3}), "good"), ...
    "Data cursor callback did not return aligned observation metadata");
invalid_indices = {0, 1.5, NaN, Inf, 2, 1 + 1i};
for invalid_index = 1:numel(invalid_indices)
    fallback_tip = single_output.DataCursorUpdateFcn([], ...
        struct("Target", single_output.Lines(1), ...
        "DataIndex", invalid_indices{invalid_index}));
    assert(isequal(fallback_tip, {'Data tip unavailable'}), ...
        "Data cursor callback accepted an invalid DataIndex");
end
original_metadata = single_output.Lines(1).UserData;
malformed_metadata = rmfield(original_metadata, "UncertaintyUnit");
malformed_metadata.UncertaintyRepresentation = "magnitude";
single_output.Lines(1).UserData = malformed_metadata;
partial_tip = single_output.DataCursorUpdateFcn([], ...
    struct("Target", single_output.Lines(1), "DataIndex", 1));
assert(numel(partial_tip) == 5, ...
    "Data cursor callback failed on incomplete optional uncertainty metadata");
malformed_metadata.ObservationID = missing;
single_output.Lines(1).UserData = malformed_metadata;
fallback_tip = single_output.DataCursorUpdateFcn([], ...
    struct("Target", single_output.Lines(1), "DataIndex", 1));
assert(isequal(fallback_tip, {'Data tip unavailable'}), ...
    "Data cursor callback exposed a missing observation identifier");
malformed_metadata = original_metadata;
malformed_metadata.ObservationID = ["duplicate"; "duplicate"];
single_output.Lines(1).UserData = malformed_metadata;
single_output.Lines(1).BrushData = 1;
assert(isempty(single_output.GetSelectedObservationIDs()), ...
    "Brush callback accepted duplicate or misaligned observation identifiers");
single_output.Lines(1).UserData = original_metadata;
single_output.Lines(1).BrushData = 0;
stale_mode = figure("Visible", "off");
delete(stale_mode);
interaction_state = getappdata(single_output.Figure, "OceanInteractionState");
interaction_state.BrushMode = stale_mode;
interaction_state.DataCursorMode = stale_mode;
interaction_state.LinkDataEnabled = "invalid";
interaction_state.UsesAxesInteractionModes = "invalid";
setappdata(single_output.Figure, "OceanInteractionState", interaction_state);
close(single_output.Figure);
assert(~isgraphics(single_output.Figure), ...
    "Interactive close callback did not tolerate stale mode handles");
must_throw(@() interactive_timeseries_native_template(single_table, "unused", ...
    "Interactive", false, "Export", false, "TimeZone", "UTC", ...
    "FontName", "__ocean_missing_font__", ...
    "ValueLabel", "Temperature", "ValueUnit", "degC"), "FontUnavailable");
cjk_label = string(char([hex2dec("4E2D") hex2dec("6587")]));
cjk_font = "";
cjk_font_candidates = ["Noto Sans CJK SC" "Noto Sans CJK TC" "Noto Sans CJK HK" ...
    "Noto Sans CJK JP" "Noto Sans CJK KR" "Source Han Sans SC" ...
    "WenQuanYi Zen Hei" "Droid Sans Fallback" "Microsoft YaHei" ...
    "PingFang SC" "SimHei" "SimSun" "Arial Unicode MS"];
installed_fonts = string(listfonts);
for font_index = 1:numel(cjk_font_candidates)
    installed_index = find(strcmpi(installed_fonts, cjk_font_candidates(font_index)), 1);
    if ~isempty(installed_index)
        cjk_font = installed_fonts(installed_index);
        break;
    end
    if isunix
        command = sprintf("fc-match -f '%%{family}' '%s' 2>/dev/null", ...
            char(cjk_font_candidates(font_index)));
        [status, output] = system(command);
        if status == 0 && contains(lower(string(output)), ...
                lower(cjk_font_candidates(font_index)))
            cjk_font = cjk_font_candidates(font_index);
            break;
        end
    end
end
if strlength(cjk_font) == 0
    must_throw(@() interactive_timeseries_native_template(single_table, "unused", ...
        "Interactive", false, "Export", false, "TimeZone", "UTC", ...
        "Title", cjk_label, "ValueLabel", "Temperature", "ValueUnit", "degC"), ...
        "CJKFontUnavailable");
else
    cjk_output = interactive_timeseries_native_template(single_table, "unused", ...
        "Interactive", false, "Export", false, "TimeZone", "UTC", ...
        "FontName", cjk_font, "Title", cjk_label, ...
        "ValueLabel", "Temperature", "ValueUnit", "degC");
    assert(cjk_output.CJKTextPresent && strcmpi(cjk_output.FontName, cjk_font) ...
        && ~cjk_output.FontRenderingVerified, ...
        "Interactive template did not preserve explicit CJK font verification semantics");
    close(cjk_output.Figure);
end
generic_fonts = intersect(string(listfonts), ["Helvetica" "Arial"], "stable");
if ~isempty(generic_fonts)
    must_throw(@() interactive_timeseries_native_template(single_table, "unused", ...
        "Interactive", false, "Export", false, "TimeZone", "UTC", ...
        "FontName", generic_fonts(1), "Title", cjk_label, ...
        "ValueLabel", "Temperature", "ValueUnit", "degC"), "CJKFontUnavailable");
end
unit_table = qc_table;
unit_table.QCFlag(2) = "suspect";
unit_table.Properties.VariableUnits = {'', 'K', '', '', ''};
must_throw(@() interactive_timeseries_native_template(unit_table, "unused", ...
    "Interactive", false, "Export", false, ...
    "ValueLabel", "Temperature", "ValueUnit", "degC"), "UnitMismatch");
uncertainty_table = qc_table;
uncertainty_table.QCFlag(2) = "suspect";
uncertainty_table.UncertaintyLower = [0.8; NaN; 2.8];
uncertainty_table.UncertaintyUpper = [1.2; 2.2; 3.2];
must_throw(@() interactive_timeseries_native_template(uncertainty_table, "unused", ...
    "Interactive", false, "Export", false, ...
    "ValueLabel", "Temperature", "ValueUnit", "degC", ...
    "UncertaintyType", "confidence-interval", "UncertaintyUnit", "degC", ...
    "ConfidenceLevel", 0.95), "identical finite/NaN masks");
uncertainty_table.UncertaintyLower(2) = 1.8;
must_throw(@() interactive_timeseries_native_template(uncertainty_table, "unused", ...
    "Interactive", false, "Export", false, ...
    "ValueLabel", "Temperature", "ValueUnit", "degC", ...
    "UncertaintyType", "confidence-interval", ...
    "UncertaintyUnit", "degC"), "ConfidenceLevel");
uncertainty_output = interactive_timeseries_native_template(uncertainty_table, "unused", ...
    "Interactive", false, "Export", false, "TimeZone", "UTC", ...
    "ValueLabel", "Temperature", "ValueUnit", "degC", ...
    "UncertaintyType", "confidence-interval", "UncertaintyUnit", "degC", ...
    "ConfidenceLevel", 0.95);
assert(uncertainty_output.UncertaintyPresent ...
    && uncertainty_output.UncertaintyRepresentation == "bounds" ...
    && uncertainty_output.ValidCount == 3 ...
    && isgraphics(uncertainty_output.UncertaintyHandles(1)), ...
    "Interactive confidence bounds were not wired to the plotted observations");
close(uncertainty_output.Figure);

[figure_handle, axes_handle] = make_axes();
cleanup_figure = onCleanup(@() close_if_valid(figure_handle));
must_throw(@() oi_plot_vector_field(axes_handle, [0 1], [0; 1], ...
    [1 NaN; 2 3], [1 2; 3 4], struct("XUnit", "km", "YUnit", "km", ...
    "VectorUnit", "m/s", "ReferenceMagnitude", 1, "Theme", theme)), "MaskMismatch");
must_throw(@() oi_plot_vector_field(axes_handle, [0 1], [0; 1], ...
    [1 2; 3 4], [1 2; 3 4], struct("XUnit", "km", "YUnit", "km", ...
    "VectorUnit", "m/s", "XLabel", "East distance", ...
    "YLabel", "North distance", "Theme", theme)), "Units");
clear cleanup_figure;
close_if_valid(figure_handle);

[figure_handle, axes_handle] = make_axes();
cleanup_figure = onCleanup(@() close_if_valid(figure_handle));
must_throw(@() oi_plot_comparison(axes_handle, [NaN; NaN], [1; 2], ...
    struct("QuantityUnit", "degC", "Theme", theme)), "NoCompletePairs");
clear cleanup_figure;
close_if_valid(figure_handle);

temporary_directory = string(tempname);
[created, message] = mkdir(temporary_directory);
assert(created, "test_asset_contracts:CreateDirectory", "%s", message);
cleanup_directory = onCleanup(@() remove_directory(temporary_directory));
[figure_handle, axes_handle] = make_axes();
cleanup_figure = onCleanup(@() close_if_valid(figure_handle));
plot(axes_handle, [0 1], [0 1], "LineWidth", 1.4);
xlabel(axes_handle, "Distance (km)", "Interpreter", "none");
ylabel(axes_handle, "Value (degC)", "Interpreter", "none");
title(axes_handle, cjk_label, "Interpreter", "none");
oi_apply_axes(axes_handle, theme);
entry = oi_export_figure(figure_handle, temporary_directory, "contract", 400, 300, 150, ...
    "Title", cjk_label, "Source", "MATLAB contract test", ...
    "Theme", theme.Name, "ExportSVG", true);
assert(strcmpi(oi_sha256_file(fullfile(temporary_directory, entry.exports.png.file)), ...
    entry.exports.png.sha256), ...
    "oi_sha256_file disagrees with the exported PNG manifest digest");
png_prefix = oi_read_file_prefix( ...
    fullfile(temporary_directory, entry.exports.png.file), 8);
assert(isequal(png_prefix', uint8([137 80 78 71 13 10 26 10])), ...
    "oi_read_file_prefix did not preserve the PNG signature bytes");
must_throw(@() oi_sha256_file(fullfile(temporary_directory, "missing.bin")), ...
    "MissingFile");
entry.scientific_data_contract = struct("schemaVersion", 1, "required", true, ...
    "shape", 2, "dimensionOrder", "sample", ...
    "coordinates", struct("sample", struct("count", 2, "unit", "1", ...
        "direction", "increasing")), ...
    "units", struct("sample", "1", "value", "degC"), ...
    "missing", struct("status", "absent", "policy", "preserve", ...
        "total_count", 2, "valid_count", 2, "missing_count", 0, "masked_count", 0), ...
    "qc", struct("status", "absent"), "uncertainty", struct("status", "absent"));
assert(entry.exports.png.width == 400 && entry.exports.png.height == 300, ...
    "PNG export dimensions were not preserved");
assert(entry.exports.pdf.width == 192 && entry.exports.pdf.height == 144, ...
    "PDF export dimensions were not recorded in points");
assert(isfield(entry.exports, "svg") ...
    && strlength(entry.exports.svg.title) > 0 ...
    && strlength(entry.exports.svg.description) > 0 ...
    && strlength(entry.exports.svg.accessible_name) > 0 ...
    && isfile(fullfile(temporary_directory, entry.exports.svg.file)), ...
    "SVG export dimensions, accessibility, or artifact are incomplete");
assert_svg_geometry(entry.exports.svg, ...
    fullfile(temporary_directory, entry.exports.svg.file), ...
    entry.exports.png.width, entry.exports.png.height);
assert(~entry.accessibility.color_only_encoding, ...
    "Manifest accessibility must not rely on color alone");
assert(entry.accessibility.cjk_text_present && entry.accessibility.cjk_font_verified ...
    && numel(entry.accessibility.foreground_color) == 3 ...
    && numel(entry.accessibility.background_color) == 3, ...
    "Export did not preserve CJK font and measured color-pair evidence");
assert(all(string({entry.text_objects.bounds_units}) == "normalized") ...
    && all(string({entry.axes_objects.bounds_units}) == "normalized") ...
    && ~any([entry.text_objects.clipped]) && ~any([entry.axes_objects.clipped]), ...
    "Export layout evidence is not normalized or reports clipped content");
assert(entry.rendering_evidence.drawnow_completed ...
    && entry.rendering_evidence.bounds_audited ...
    && entry.rendering_evidence.clipped_count == 0 ...
    && entry.rendering_evidence.text_overlap_count == 0 ...
    && numel(entry.rendering_evidence.normalized_margins) == 4 ...
    && all(entry.rendering_evidence.normalized_margins >= 0) ...
    && entry.rendering_evidence.font_selection_verified ...
    && ~entry.rendering_evidence.visual_inspection_verified ...
    && ~entry.rendering_evidence.pdf_font_embedding_verified, ...
    "Export rendering evidence overstates or omits verification status");
assert(entry.publication.layout.stable ...
    && entry.publication.layout.overlap_count == 0 ...
    && entry.publication.layout.clipped_count == 0 ...
    && isequal(entry.publication.layout.margins, entry.rendering_evidence.normalized_margins) ...
    && ~entry.publication.typography.glyphs_verified ...
    && ~entry.publication.typography.cjk_verified ...
    && ~entry.publication.typography.pdf_fonts_embedded ...
    && ~entry.publication.color.colorblind_safe ...
    && entry.publication.color.redundant_encoding, ...
    "Export publication evidence is missing or overstates artifact verification");
assert(~entry.interaction.requested && ~entry.interaction.enabled ...
    && islogical(entry.interaction.desktop_available) ...
    && entry.interaction.headless.supported ...
    && entry.interaction.headless.mode == "static_export" ...
    && entry.interaction.headless.verified, ...
    "Export interaction evidence does not describe the static headless fallback");
assert(entry.runtime.minimum_release == "R2019b" ...
    && strlength(entry.runtime.matlab_version) > 0 ...
    && strlength(entry.runtime.matlab_release) > 0 ...
    && islogical(entry.runtime.jvm_available) && entry.runtime.headless_static_export ...
    && entry.runtime.toolboxes_verified ...
    && entry.runtime.toolbox_installation_verified ...
    && ~entry.runtime.toolbox_license_verified ...
    && ~entry.runtime.toolbox_invocation_verified ...
    && isempty(entry.runtime.required_toolboxes) ...
    && any(strcmpi(entry.runtime.installed_toolboxes, "MATLAB")) ...
    && any(entry.runtime.export_api.png == ["exportgraphics" "print"]) ...
    && any(entry.runtime.export_api.pdf == ["exportgraphics" "print"]) ...
    && any(entry.runtime.export_api.svg == ["exportgraphics" "print"]) ...
    && entry.exports.png.export_api == entry.runtime.export_api.png ...
    && entry.exports.pdf.export_api == entry.runtime.export_api.pdf ...
    && entry.exports.svg.export_api == entry.runtime.export_api.svg ...
    && entry.exports.svg.export_device == entry.runtime.export_device.svg ...
    && ((entry.runtime.export_api.svg == "print" ...
        && entry.runtime.export_device.svg == "-dsvg") ...
        || (entry.runtime.export_api.svg == "exportgraphics" ...
        && strlength(entry.runtime.export_device.svg) == 0)), ...
    "Export runtime, release, toolbox, or API evidence is incomplete");
manifest = oi_write_manifest(fullfile(temporary_directory, "figures.json"), entry(:));
assert(isfile(fullfile(temporary_directory, "figures.json")) ...
    && ~isempty(manifest.figures), "Manifest did not contain the exported figure");
assert_svg_geometry(manifest.figures.exports.svg, ...
    fullfile(temporary_directory, manifest.figures.exports.svg.file), ...
    manifest.figures.exports.png.width, manifest.figures.exports.png.height);
assert(isfield(manifest.figures, "scientific_data_contract") ...
    && manifest.figures.scientific_data_contract.required, ...
    "Manifest did not preserve the scientific data contract");
assert(manifest.execution_verified && manifest.runtime_status == "ready" ...
    && manifest.schema_version == 2 ...
    && manifest.artifact_validation.status == "passed" ...
    && manifest.visual_inspection.verified == false ...
    && strlength(manifest.matlab_release) > 0 ...
    && manifest.minimum_matlab_release == "R2019b" ...
    && isequal(string(manifest.export_formats(:)), ["png"; "pdf"; "svg"]) ...
    && any(strcmpi(manifest.toolboxes, "MATLAB")) ...
    && isempty(manifest.required_toolboxes) ...
    && manifest.runtime.engine == "MATLAB" ...
    && manifest.runtime.runtime_status == "ready" ...
    && manifest.runtime.execution_verified ...
    && manifest.runtime.toolbox_verification_scope == "installation_only" ...
    && ~manifest.runtime.toolbox_license_verified ...
    && ~manifest.runtime.toolbox_invocation_verified ...
    && manifest.runtime.headless.figure_visible == "off" ...
    && manifest.runtime.headless.desktop_independent ...
    && manifest.runtime.headless.non_interactive ...
    && manifest.runtime.headless.batch_api == "matlab -batch" ...
    && manifest.export_strategies.png.api == entry.exports.png.export_api ...
    && manifest.export_strategies.pdf.api == entry.exports.pdf.export_api ...
    && manifest.export_strategies.svg.api == entry.exports.svg.export_api ...
    && manifest.runtime_contract.authoritative_runtime == "MATLAB" ...
    && ~manifest.runtime_contract.octave_substitution_allowed, ...
    "Manifest runtime and verification status is incomplete");
invalid_runtime_entry = entry;
invalid_runtime_entry.runtime.toolboxes_verified = false;
must_throw(@() oi_write_manifest(fullfile(temporary_directory, "invalid.json"), ...
    invalid_runtime_entry), "RuntimeEvidence");
invalid_format_entry = entry;
invalid_format_entry.exports.svg.file = "contract.pdf";
must_throw(@() oi_write_manifest(fullfile(temporary_directory, "invalid.json"), ...
    invalid_format_entry), "FormatMismatch");
invalid_metadata_entry = entry;
invalid_metadata_entry.exports.png.title = "forged title";
must_throw(@() oi_write_manifest(fullfile(temporary_directory, "invalid.json"), ...
    invalid_metadata_entry), "MetadataMismatch");
invalid_path_entry = entry;
invalid_path_entry.exports.png.file = "../contract.png";
must_throw(@() oi_write_manifest(fullfile(temporary_directory, "invalid.json"), ...
    invalid_path_entry), "UnsafeExportPath");
invalid_svg_entry = entry;
invalid_svg_entry.exports.svg.description = "forged description";
must_throw(@() oi_write_manifest(fullfile(temporary_directory, "invalid.json"), ...
    invalid_svg_entry), "InvalidSvg");
must_throw(@() oi_export_figure(figure_handle, temporary_directory, ...
    "missing-toolbox", 400, 300, 150, ...
    "Title", "Missing toolbox rejection", ...
    "RequiredToolboxes", "Ocean Intelligence Missing Toolbox"), "MissingToolbox");
must_throw(@() oi_export_figure(figure_handle, temporary_directory, ...
    "empty-title", 400, 300, 150), "EmptyTitle");
must_throw(@() oi_export_figure(figure_handle, "   ", ...
    "empty-directory", 400, 300, 150, "Title", "Empty directory"), ...
    "EmptyDirectory");
must_throw(@() oi_export_figure(figure_handle, temporary_directory, ...
    "complex-contrast", 400, 300, 150, "Title", "Complex contrast", ...
    "ContrastRatio", 4.5 + 0.1i), "ContrastRatio");
axes_handle.XColor = [0.8 0.8 0.8];
axes_handle.YColor = [0.8 0.8 0.8];
must_throw(@() oi_export_figure(figure_handle, temporary_directory, ...
    "cleanup-on-failure", 400, 300, 150, ...
    "Title", "Cleanup failed export", "Source", "adversarial contract test", ...
    "Theme", theme.Name), "Contrast");
assert(~isfile(fullfile(temporary_directory, "cleanup-on-failure.png")) ...
    && ~isfile(fullfile(temporary_directory, "cleanup-on-failure.pdf")), ...
    "Failed export left partial artifacts behind");
oi_apply_axes(axes_handle, theme);
must_throw(@() oi_export_figure(figure_handle, temporary_directory, "contract", ...
    400, 300, 150, "Title", cjk_label), "StaleArtifact");
clear cleanup_figure;
close_if_valid(figure_handle);
clear cleanup_directory;
remove_directory(temporary_directory);
fprintf("MATLAB_ASSET_CONTRACT_TESTS=passed\n");
fprintf("MATLAB_ASSET_VERSION_EXPORT=passed\n");
end

function assert_svg_geometry(svg_record, svg_path, reference_width, reference_height)
document = xmlread(char(svg_path));
root = document.getDocumentElement();
assert(strcmpi(char(root.getNodeName()), "svg"), ...
    "test_asset_contracts:InvalidSvg", "SVG has no root element");
measured_width = svg_numeric_length(root, "width");
measured_height = svg_numeric_length(root, "height");
view_box = svg_view_box(root);
assert_close(double(svg_record.width), measured_width, ...
    "SVG width evidence does not match the artifact");
assert_close(double(svg_record.height), measured_height, ...
    "SVG height evidence does not match the artifact");
assert_close(double(svg_record.viewbox_width), view_box(3), ...
    "SVG viewBox width evidence does not match the artifact");
assert_close(double(svg_record.viewbox_height), view_box(4), ...
    "SVG viewBox height evidence does not match the artifact");
assert_close(view_box(3) / view_box(4), measured_width / measured_height, ...
    "SVG viewBox and viewport aspect ratios differ");
assert_close(view_box(3) / view_box(4), ...
    double(reference_width) / double(reference_height), ...
    "SVG and reference raster aspect ratios differ");
end

function value = svg_numeric_length(root, attribute_name)
attribute = strtrim(string(char(root.getAttribute(char(attribute_name)))));
token = regexp(attribute, ...
    "^([-+]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][-+]?\d+)?)(?:[A-Za-z%]+)?$", ...
    "tokens", "once");
assert(~isempty(token), "test_asset_contracts:InvalidSvg", ...
    "SVG %s is not an explicit numeric length", attribute_name);
value = str2double(token{1});
assert(isfinite(value) && value > 0, "test_asset_contracts:InvalidSvg", ...
    "SVG %s must be positive", attribute_name);
end

function values = svg_view_box(root)
attribute = string(char(root.getAttribute('viewBox')));
tokens = regexp(attribute, ...
    "[-+]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][-+]?\d+)?", "match");
values = str2double(tokens);
assert(numel(values) == 4 && all(isfinite(values)) ...
    && values(3) > 0 && values(4) > 0, ...
    "test_asset_contracts:InvalidSvg", ...
    "SVG viewBox must contain four finite values with positive dimensions");
end

function assert_close(actual, expected, message)
tolerance = 1e-8 * max([1 abs(actual) abs(expected)]);
assert(isfinite(actual) && isfinite(expected) && abs(actual - expected) <= tolerance, ...
    "test_asset_contracts:GeometryMismatch", "%s", message);
end

function [figure_handle, axes_handle] = make_axes()
figure_handle = oi_figure(640, 480, "off");
axes_handle = axes("Parent", figure_handle);
end

function must_throw(callback, expected_text)
thrown = false;
try
    callback();
catch error_record
    thrown = true;
    assert(contains(string(error_record.identifier), expected_text) ...
        || contains(string(error_record.message), expected_text), ...
        "Unexpected MATLAB error: %s", error_record.message);
end
assert(thrown, "Expected MATLAB contract rejection containing %s", expected_text);
end

function close_if_valid(figure_handle)
if ~isempty(figure_handle) && isgraphics(figure_handle)
    close(figure_handle);
end
end

function remove_directory(directory_path)
if isfolder(directory_path)
    rmdir(directory_path, "s");
end
end
