function result = test_interaction_native_compatibility()
%TEST_INTERACTION_NATIVE_COMPATIBILITY Exercise UI, traditional, and headless paths.
testsDirectory = fileparts(mfilename("fullpath"));
assetsDirectory = fullfile(testsDirectory, "..", "assets");
originalPath = path;
addpath(assetsDirectory);
pathCleanup = onCleanup(@() path(originalPath));

assert_axes_mode_calls_do_not_capture_outputs(assetsDirectory);
data = interaction_fixture();
desktopAvailable = usejava("desktop");

test_static_or_headless_path(data, desktopAvailable);
traditionalDesktopExecuted = false;
uiAxesDesktopExecuted = false;
if desktopAvailable
    test_traditional_desktop_path(data);
    traditionalDesktopExecuted = true;
    if ~verLessThan("matlab", "9.14")
        test_ui_axes_desktop_path(data);
        uiAxesDesktopExecuted = true;
    end
end

result = struct( ...
    "DesktopAvailable", logical(desktopAvailable), ...
    "TraditionalDesktopExecuted", traditionalDesktopExecuted, ...
    "UIAxesDesktopExecuted", uiAxesDesktopExecuted, ...
    "MATLABRelease", string(version("-release")));
fprintf("MATLAB_INTERACTION_NATIVE_COMPATIBILITY=passed\n");
fprintf("MATLAB_INTERACTION_DESKTOP_AVAILABLE=%d\n", desktopAvailable);
fprintf("MATLAB_INTERACTION_UIAXES_EXECUTED=%d\n", uiAxesDesktopExecuted);
clear pathCleanup;
end

function assert_axes_mode_calls_do_not_capture_outputs(assetsDirectory)
sourcePath = fullfile(assetsDirectory, "interactive_timeseries_native_template.m");
sourceText = fileread(sourcePath);
assert(~isempty(regexp(sourceText, ...
    "datacursormode\(axes_handles\(axes_index\), 'on'\)", "once")), ...
    "test_interaction_native_compatibility:MissingDataCursorEnable", ...
    "The UI axes data cursor mode must be enabled explicitly");
assert(~isempty(regexp(sourceText, ...
    "brush\(axes_handles\(axes_index\), 'on'\)", "once")), ...
    "test_interaction_native_compatibility:MissingBrushEnable", ...
    "The UI axes brush mode must be enabled explicitly");
assert(isempty(regexp(sourceText, ...
    "=\s*datacursormode\(axes_handles\(axes_index\)", "once")), ...
    "test_interaction_native_compatibility:DataCursorOutput", ...
    "Axes-targeted datacursormode calls must not request an output");
assert(isempty(regexp(sourceText, ...
    "=\s*brush\(axes_handles\(axes_index\)", "once")), ...
    "test_interaction_native_compatibility:BrushOutput", ...
    "Axes-targeted brush calls must not request an output");
end

function test_static_or_headless_path(data, desktopAvailable)
beforeFigures = findall(groot, "Type", "figure");
requestInteraction = ~desktopAvailable;
outputs = interactive_timeseries_native_template(data, "unused", ...
    "Interactive", requestInteraction, "UseUIFigure", true, ...
    "UseDataCursorCallback", true, "Export", false, ...
    "TimeZone", "UTC", "ValueLabel", "Temperature", ...
    "ValueUnit", "degC");
figureCleanup = onCleanup(@() close_if_valid(outputs.Figure));
assert(~outputs.InteractiveEnabled && ~outputs.UIFigureEnabled, ...
    "test_interaction_native_compatibility:StaticFallback", ...
    "The noninteractive path must use a traditional static figure");
assert(outputs.PublicationWidthPixels == 2400 ...
    && outputs.PublicationHeightPixels == 1500 ...
    && outputs.PublicationDPI == 300 ...
    && outputs.PublicationPhysicalWidthIn == 8 ...
    && outputs.PublicationPhysicalHeightIn == 5, ...
    "test_interaction_native_compatibility:PublicationGeometry", ...
    "The default publication export geometry must remain 8 by 5 inches at 300 DPI");
if ~desktopAvailable
    assert(outputs.HeadlessFallbackUsed, ...
        "test_interaction_native_compatibility:HeadlessFallback", ...
        "A requested headless interaction must report its fallback");
end
verify_stable_selection(outputs, data);
lineHandle = outputs.Lines(1);
close(outputs.Figure);
assert(~isgraphics(outputs.Figure) ...
    && isempty(outputs.GetSelectedObservationIDs()) ...
    && isequal(outputs.DataCursorUpdateFcn([], ...
        struct("Target", lineHandle, "DataIndex", 1)), ...
        {'Data tip unavailable'}), ...
    "test_interaction_native_compatibility:StaticCleanup", ...
    "Static or headless cleanup left unsafe callbacks or selection state");
clear figureCleanup;
assert(numel(findall(groot, "Type", "figure")) == numel(beforeFigures), ...
    "test_interaction_native_compatibility:StaticFigureLeak", ...
    "The static or headless path leaked a figure");
end

function test_traditional_desktop_path(data)
beforeFigures = findall(groot, "Type", "figure");
outputs = interactive_timeseries_native_template(data, "unused", ...
    "Interactive", true, "UseUIFigure", false, ...
    "UseDataCursorCallback", true, "Export", false, ...
    "TimeZone", "UTC", "ValueLabel", "Temperature", ...
    "ValueUnit", "degC");
figureCleanup = onCleanup(@() close_if_valid(outputs.Figure));
assert(outputs.InteractiveEnabled && ~outputs.UIFigureEnabled, ...
    "test_interaction_native_compatibility:TraditionalDesktop", ...
    "The traditional desktop path did not enable interaction");
interactionState = getappdata(outputs.Figure, "OceanInteractionState");
dataCursorMode = interactionState.DataCursorMode;
brushMode = interactionState.BrushMode;
assert(is_live_mode(dataCursorMode) && is_live_mode(brushMode), ...
    "test_interaction_native_compatibility:TraditionalModes", ...
    "Traditional figures must retain live interaction mode objects");
verify_stable_selection(outputs, data);
tipRows = outputs.DataCursorUpdateFcn([], ...
    struct("Target", outputs.Lines(1), "DataIndex", 2));
assert(any(contains(string(tipRows), data.ObservationID(2))) ...
    && any(contains(string(tipRows), string(data.SourceRow(2)))), ...
    "test_interaction_native_compatibility:TraditionalDataTip", ...
    "The traditional data cursor callback lost stable point identity");
close(outputs.Figure);
assert(~is_live_mode(dataCursorMode) && ~is_live_mode(brushMode), ...
    "test_interaction_native_compatibility:TraditionalCleanup", ...
    "Traditional interaction mode objects survived figure cleanup");
clear figureCleanup;
assert(numel(findall(groot, "Type", "figure")) == numel(beforeFigures), ...
    "test_interaction_native_compatibility:TraditionalFigureLeak", ...
    "The traditional desktop path leaked a figure");
end

function test_ui_axes_desktop_path(data)
beforeFigures = findall(groot, "Type", "figure");
outputs = interactive_timeseries_native_template(data, "unused", ...
    "Interactive", true, "UseUIFigure", true, ...
    "UseDataCursorCallback", false, "Export", false, ...
    "TimeZone", "UTC", "ValueLabel", "Temperature", ...
    "ValueUnit", "degC");
figureCleanup = onCleanup(@() close_if_valid(outputs.Figure));
assert(outputs.InteractiveEnabled && outputs.UIFigureEnabled, ...
    "test_interaction_native_compatibility:UIAxesDesktop", ...
    "The uifigure desktop path did not enable UI axes interaction");
interactionState = getappdata(outputs.Figure, "OceanInteractionState");
assert(isequal(interactionState.UsesAxesInteractionModes, true) ...
    && all(cellfun(@isempty, interactionState.DataCursorModes)) ...
    && all(cellfun(@isempty, interactionState.BrushModes)), ...
    "test_interaction_native_compatibility:UIAxesModeObjects", ...
    "UI axes interaction must not depend on returned mode objects");
verify_stable_selection(outputs, data);
lineHandle = outputs.Lines(1);
close(outputs.Figure);
assert(~isgraphics(outputs.Figure) ...
    && isempty(outputs.GetSelectedObservationIDs()) ...
    && isequal(outputs.DataCursorUpdateFcn([], ...
        struct("Target", lineHandle, "DataIndex", 1)), ...
        {'Data tip unavailable'}), ...
    "test_interaction_native_compatibility:UIAxesCleanup", ...
    "UI axes cleanup left unsafe callbacks or selection state");
clear figureCleanup;
assert(numel(findall(groot, "Type", "figure")) == numel(beforeFigures), ...
    "test_interaction_native_compatibility:UIAxesFigureLeak", ...
    "The uifigure desktop path leaked a figure");
end

function verify_stable_selection(outputs, data)
outputs.Lines(1).BrushData = [1; 0; 1; 0];
identity = outputs.GetSelectedObservationIdentity();
assert(isequal(identity.ObservationID, data.ObservationID([1 3])) ...
    && isequal(identity.SourceRow, data.SourceRow([1 3])), ...
    "test_interaction_native_compatibility:StableIdentity", ...
    "Brush selection did not preserve ObservationID and SourceRow");
identityAgain = outputs.GetSelectedObservationIdentity();
assert(isequal(identityAgain, identity), ...
    "test_interaction_native_compatibility:StableReentry", ...
    "Repeated brush selection collection was not stable");
outputs.ClearBrushSelection();
assert(isempty(outputs.GetSelectedObservationIDs()), ...
    "test_interaction_native_compatibility:ClearSelection", ...
    "Brush selection was not cleared");
end

function data = interaction_fixture()
time = datetime(2026, 9, 5, 0:3, 0, 0, "TimeZone", "UTC")';
value = [20.1; 20.4; 20.2; 20.8];
observationID = ["OBS-101"; "OBS-102"; "OBS-103"; "OBS-104"];
station = repmat("STATION-A", 4, 1);
qcFlag = ["good"; "suspect"; "good"; "good"];
sourceRow = [9; 3; 14; 6];
data = table(time, value, observationID, station, qcFlag, sourceRow, ...
    "VariableNames", ...
    {"Time", "Value", "ObservationID", "Station", "QCFlag", "SourceRow"});
data.Properties.VariableUnits = {'', 'degC', '', '', '', ''};
end

function valid = is_live_mode(modeObject)
valid = false;
if isempty(modeObject) || ~isscalar(modeObject)
    return;
end
try
    valid = isvalid(modeObject);
catch
end
end

function close_if_valid(figureHandle)
if isgraphics(figureHandle)
    close(figureHandle);
end
end
