function report = test_astra_generated_comparison(outputDirectory, fixturePath, expectedSourceHash, generationRound)
arguments
    outputDirectory (1,1) string
    fixturePath (1,1) string
    expectedSourceHash (1,1) string
    generationRound (1,1) string = "round22"
end
assert(~exist('OCTAVE_VERSION', 'builtin'), ...
    'test_astra_generated_comparison:MatlabRequired', 'This trial requires MATLAB');
assert(isfolder(outputDirectory), 'test_astra_generated_comparison:OutputDirectory', ...
    'The caller must supply an existing output directory');
testsDirectory = fileparts(mfilename('fullpath'));
matlabDirectory = fileparts(testsDirectory);
assetsDirectory = canonical_path(fullfile(matlabDirectory, 'assets'));
evalDirectory = canonical_path(fullfile(matlabDirectory, 'evals'));
assert(any(generationRound == ["round22", "round23"]), ...
    'test_astra_generated_comparison:GenerationRound', 'Unknown pinned generation round');
pins = generation_pins(generationRound);
bundleDirectory = canonical_path(fullfile(testsDirectory, "model-generated-" + generationRound));
trialDirectory = fullfile(canonical_path(outputDirectory), 'astra-comparison-trial');
assert(~isfolder(trialDirectory) && ~isfile(trialDirectory), ...
    'test_astra_generated_comparison:StaleOutput', 'Trial output must be fresh: %s', trialDirectory);
[created, message] = mkdir(trialDirectory);
assert(created, 'test_astra_generated_comparison:CreateDirectory', '%s', message);
evidencePath = fullfile(trialDirectory, 'astra-generated-comparison-evidence.json');
originalPath = path;
originalDirectory = pwd;
previousFigures = findall(groot, 'Type', 'figure');
pathCleanup = onCleanup(@() path(originalPath));
directoryCleanup = onCleanup(@() cd(originalDirectory));
figureCleanup = onCleanup(@() close_new_figures(previousFigures));
profile = "astra-temperature-labels";
pageInches = [10 8.5];
pixelSize = [3000 2550];
dpi = 300;
expectedLabels = ["Observation temperature (degC)", "Model temperature (degC)"];
report = struct('schema_version', 1, 'scope', 'model_generated_synthetic_comparison_only', ...
    'status', 'running', 'phase', 'preflight', 'matlab_release', "R" + string(version('-release')), ...
    'matlab_version', string(version), 'matlab_call_completed', false, ...
    'execution_verified', false, 'native_proof_status', 'not_run', ...
    'export_status', 'not_run', 'manifest_status', 'not_run', ...
    'visual_verified', false, 'desktop_interaction_verified', false, ...
    'real_ocean_observations', false, 'reader_profile', profile, ...
    'ci_run_id', string(getenv('GITHUB_RUN_ID')), 'ci_job', string(getenv('GITHUB_JOB')), ...
    'execution_commit', string(getenv('GITHUB_SHA')));
report.requested_output = struct('page_inches', pageInches, 'pixels', pixelSize, 'dpi', dpi);
report.generation_round = generationRound;
try
    addpath(assetsDirectory, evalDirectory, bundleDirectory, '-begin');
    clear astra_comparison_trial;
    rehash;
    dependencyNames = ["measure_comparison_plot_data", "oi_plot_comparison", ...
        "oi_export_figure", "oi_write_manifest", "oi_figure", "oi_ocean_theme", ...
        "oi_apply_axes", "oi_sha256_file", "oi_read_file_prefix", "oi_font_available"];
    dependencyPaths = strings(size(dependencyNames));
    for dependencyIndex = 1:numel(dependencyNames)
        directory = assetsDirectory;
        if dependencyNames(dependencyIndex) == "measure_comparison_plot_data"
            directory = evalDirectory;
        end
        dependencyPaths(dependencyIndex) = canonical_path( ...
            fullfile(directory, dependencyNames(dependencyIndex) + ".m"));
    end
    sourcePath = canonical_path(fullfile(bundleDirectory, 'astra_comparison_trial.m'));
    functionNames = [dependencyNames, "astra_comparison_trial"];
    functionPaths = [dependencyPaths, sourcePath];
    assert_function_paths(functionNames, functionPaths);
    executionPath = path;
    source = file_record(sourcePath);
    assert(strcmpi(expectedSourceHash, pins.source_sha256) ...
        && source.bytes == pins.source_bytes && strcmpi(source.sha256, expectedSourceHash), ...
        'test_astra_generated_comparison:SourceHash', ...
        'Only the explicitly pinned, unchanged generated source may execute');
    generatedReport = file_record(fullfile(bundleDirectory, 'astra_comparison_trial.md'));
    assert(generatedReport.bytes == pins.report_bytes && strcmpi(generatedReport.sha256, pins.report_sha256), ...
        'test_astra_generated_comparison:ReportHash', 'Original generated report bytes changed');
    prompt = file_record(fullfile(bundleDirectory, 'generation-prompt.zh.txt'));
    assert(prompt.bytes == pins.prompt_bytes && strcmpi(prompt.sha256, pins.prompt_sha256), ...
        'test_astra_generated_comparison:PromptHash', 'Original generation prompt bytes changed');
    provenanceRecord = file_record(fullfile(bundleDirectory, 'generation-provenance.json'));
    assert(strcmpi(provenanceRecord.sha256, pins.provenance_sha256), ...
        'test_astra_generated_comparison:ProvenanceHash', 'Pinned generation provenance bytes changed');
    provenance = read_json(provenanceRecord.path);
    fixtureRecord = file_record(fixturePath);
    assert(fixtureRecord.bytes == 2771 && strcmpi(fixtureRecord.sha256, ...
        'dfdd4a9b3270151e02b8c91970775ed10ebfc862bc8119c3cccb85b99b6f676b'), ...
        'test_astra_generated_comparison:FixtureHash', 'The supplied fixture must be the pinned paired input');
    fixture = read_json(fixtureRecord.path);
    assert(fixture.schema_version == 1 && isequal(fixture.synthetic, true) ...
        && string(fixture.id) == "paired-observation-model" && numel(fixture.records) == 12, ...
        'test_astra_generated_comparison:Fixture', 'Expected all 12 original synthetic records');
    validate_provenance(provenance, source, generatedReport, fixtureRecord, pageInches, expectedLabels);
    trackedFiles = [source; generatedReport; prompt; provenanceRecord; fixtureRecord; ...
        file_record(string(mfilename('fullpath')) + ".m")];
    for dependencyIndex = 1:numel(dependencyPaths)
        trackedFiles(end + 1, 1) = file_record(dependencyPaths(dependencyIndex)); %#ok<AGROW>
    end
    report.source = source;
    report.expected_source_sha256 = expectedSourceHash;
    report.generated_report = generatedReport;
    report.prompt = prompt;
    report.provenance = provenanceRecord;
    report.generation_provenance = provenance;
    report.provenance_scope = 'coordinator_record_hash_binding_not_model_authentication';
    report.input = fixtureRecord;
    report.execution_files = trackedFiles;
    inputSnapshot = struct('id', string(fixture.id), 'sha256', fixtureRecord.sha256);
    report.phase = 'construction';
    fprintf('ASTRA_COMPARISON_TRIAL_BEGIN=%s\n', source.sha256);
    [figureHandle, result] = astra_comparison_trial(fixtureRecord.path);
    report.matlab_call_completed = true;
    assert(strcmp(path, executionPath) && strcmp(pwd, originalDirectory), ...
        'test_astra_generated_comparison:EnvironmentChanged', 'Generated code changed path or working directory');
    assert_function_paths(functionNames, functionPaths);
    assert_files_unchanged(trackedFiles);
    report.phase = 'native-before-export';
    report.figure_before_export = inspect_figure( ...
        figureHandle, result, previousFigures, pageInches, fixture.title);
    before = measure_comparison_plot_data(result, fixture, inputSnapshot, figureHandle, profile);
    assert_complete_v3(before);
    report.native_proof_status = 'passed_before_export';
    report.native_before_export = before;
    report.phase = 'export';
    theme = getappdata(figureHandle, 'OI_OceanTheme');
    entry = oi_export_figure(figureHandle, trialDirectory, string(fixture.id), ...
        pixelSize(1), pixelSize(2), dpi, 'Title', string(fixture.title), ...
        'Source', "Model-generated trial: tests/model-generated-" + generationRound + "/astra_comparison_trial.m", ...
        'Theme', string(theme.Name), 'ExportSVG', true);
    report.export_status = 'completed';
    report.phase = 'native-after-export';
    report.figure_after_export = inspect_figure( ...
        figureHandle, result, previousFigures, pageInches, fixture.title);
    after = measure_comparison_plot_data(result, fixture, inputSnapshot, figureHandle, profile);
    assert_complete_v3(after);
    assert(isequaln(before, after), 'test_astra_generated_comparison:ExportMutation', ...
        'Export changed the complete native v3 declaration of the generated figure');
    report.native_proof_status = 'passed_before_and_after_export';
    report.plot_data_evidence = after;
    report.phase = 'manifest';
    manifestPath = fullfile(trialDirectory, 'figures.json');
    oi_write_manifest(manifestPath, entry);
    manifest = read_json(manifestPath);
    assert(numel(manifest.figures) == 1 ...
        && string(manifest.figures.id) == string(after.figure_id) ...
        && isequaln(manifest.figures.exports, jsondecode(jsonencode(entry.exports))), ...
        'test_astra_generated_comparison:ManifestBinding', 'Manifest must bind the same generated figure exports');
    artifacts = verify_exports(trialDirectory, entry, pixelSize, pageInches, dpi);
    report.exports = entry.exports;
    report.export_api = entry.runtime.export_api;
    report.artifacts = artifacts;
    report.manifest = file_record(manifestPath);
    report.manifest_status = 'passed';
    report.phase = 'final-integrity';
    assert_function_paths(functionNames, functionPaths);
    assert_files_unchanged([trackedFiles; artifacts; report.manifest]);
    assert(strcmp(path, executionPath) && strcmp(pwd, originalDirectory), ...
        'test_astra_generated_comparison:EnvironmentChanged', 'Trial changed path or working directory');
    report.original_files_unchanged = true;
    report.status = 'passed';
    report.phase = 'complete';
    report.execution_verified = true;
    write_json(evidencePath, report);
    fprintf('ASTRA_COMPARISON_TRIAL_PROFILE=%s\n', profile);
    fprintf('ASTRA_COMPARISON_TRIAL=passed_synthetic_native_v3_and_exports_only\n');
catch trialError
    report.status = 'failed';
    report.execution_verified = false;
    report.error_identifier = string(trialError.identifier);
    report.error_message = string(trialError.message);
    report.error_report = string(getReport(trialError, 'extended', 'hyperlinks', 'off'));
    try
        write_json(evidencePath, report);
    catch evidenceError
        warning('test_astra_generated_comparison:FailureEvidence', ...
            'Cannot record trial failure: %s', evidenceError.message);
    end
    fprintf('ASTRA_COMPARISON_TRIAL_FAILED=%s:%s\n', report.phase, trialError.identifier);
    rethrow(trialError);
end
clear figureCleanup directoryCleanup pathCleanup;
end

function pins = generation_pins(generationRound)
if generationRound == "round22"
    pins = struct('source_bytes', 9303, ...
        'source_sha256', '508a8c8430c6d0d28797df1bc4256c1eca24eafe7fb816c8b77f686aa121e665', ...
        'report_bytes', 8241, ...
        'report_sha256', '656c2d4025b7a6536fd50a905094fecb83e7cb2c53100c256f8cad1cad4f51e8', ...
        'prompt_bytes', 1716, ...
        'prompt_sha256', '4dd60bda58a58d90474beb76a692763c8a83f31cdfc6a5afdf35a9c5ee36b13b', ...
        'provenance_sha256', '46e13d23b461b8d64299803a809b2f4f9c6187c4cb7d7a59cbd3f21799e0fa58');
else
    pins = struct('source_bytes', 9405, ...
        'source_sha256', '3faec2ab0fd5d7a2e5fcf43a211f3848f399e6a28eae2618566ba3ec6f4021f0', ...
        'report_bytes', 12115, ...
        'report_sha256', 'd79d73b4f66fc9e273158bdf5e165d517991d4ef090a3fa0233acd63c6ab9c0b', ...
        'prompt_bytes', 2054, ...
        'prompt_sha256', '3be8b9c417de16b10afe1e945cc6bd374835c2957d4b1dfa7a2a94a3793c643f', ...
        'provenance_sha256', '16c1ef24350afaf6c3078fdfe666d9fa843dad730a6bc128f6991391412ca8a5');
end
end

function validate_provenance(provenance, source, generatedReport, fixture, pageInches, labels)
assert(provenance.schema_version == 1 ...
    && string(provenance.scope) == "isolated_builtin_codex_generation_only" ...
    && isequal(provenance.generated_source_edited, false) ...
    && string(provenance.matlab_execution_status) == "not_run" ...
    && isequal(provenance.visual_verified, false) ...
    && isequal(provenance.desktop_interaction_verified, false) ...
    && isequal(provenance.real_ocean_observations, false), ...
    'test_astra_generated_comparison:Provenance', 'Generation must not claim prior native or visual acceptance');
records = {source, generatedReport, fixture};
fields = {'source', 'report', 'fixture'};
for recordIndex = 1:numel(records)
    declared = provenance.(fields{recordIndex});
    actual = records{recordIndex};
    assert(string(declared.file) == actual.file && declared.bytes == actual.bytes ...
        && strcmpi(declared.sha256, actual.sha256), ...
        'test_astra_generated_comparison:ProvenanceBinding', 'Source/report/fixture provenance differs from bytes');
end
assert(isequal(provenance.fixture.synthetic, true) ...
    && string(provenance.generation.thread_id) == "01a07422-6d4a-7052-8d6a-993e40f9d46a" ...
    && string(provenance.generation.cli_version) == "0.153.4" ...
    && string(provenance.generation.provider_id_from_session_meta) == "OpenAI" ...
    && string(provenance.generation.model_from_both_turn_contexts) == "gpt-6-astra" ...
    && string(provenance.generation.effort) == "high" ...
    && numel(provenance.generation.turns) == 2 ...
    && all(string({provenance.generation.turns.status}) == "completed") ...
    && string(provenance.generation_snapshot.local_commit) == "587c382a7155c265abb82137b6e5ce47717b8de0", ...
    'test_astra_generated_comparison:GenerationOrigin', 'Expected the recorded original two-turn generation');
assert(isequal(provenance.observed_output_contract.page_inches(:)', pageInches) ...
    && string(provenance.observed_output_contract.xlabel) == labels(1) ...
    && string(provenance.observed_output_contract.ylabel) == labels(2), ...
    'test_astra_generated_comparison:ObservedContract', 'Preserve the reviewed original page and descriptive labels');
end

function geometry = inspect_figure(figureHandle, result, previousFigures, pageInches, titleText)
createdFigures = new_figures(previousFigures);
assert(isscalar(figureHandle) && isgraphics(figureHandle, 'figure') ...
    && isscalar(createdFigures) && isequal(createdFigures, figureHandle) ...
    && string(figureHandle.Visible) == "off" && string(figureHandle.Units) == "inches" ...
    && all(abs(double(figureHandle.Position(3:4)) - pageInches) <= 1e-10), ...
    'test_astra_generated_comparison:Figure', 'Require the one original invisible 10x8.5-inch figure');
assert(isstruct(result) && isscalar(result) && isgraphics(result.Axes, 'axes') ...
    && isequal(findall(figureHandle, 'Type', 'axes'), result.Axes) ...
    && isequal(ancestor(result.Axes, 'figure'), figureHandle) ...
    && string(result.Axes.Title.String) == string(titleText) ...
    && string(result.Axes.Title.Visible) == "on", ...
    'test_astra_generated_comparison:Axes', 'The returned axes and original title must belong to the same figure');
reference = result.OneToOne;
assert(isscalar(reference) && isgraphics(reference, 'line') ...
    && isequal(reference.Parent, result.Axes) && string(reference.Visible) == "on" ...
    && string(reference.LineStyle) ~= "none" && reference.LineWidth > 0, ...
    'test_astra_generated_comparison:ReferenceLine', 'The original 1:1 reference must remain visible');
geometry = struct('units', string(figureHandle.Units), 'position', double(figureHandle.Position), ...
    'axes_units', string(result.Axes.Units), 'axes_position', double(result.Axes.Position), ...
    'xlabel', string(result.Axes.XLabel.String), 'ylabel', string(result.Axes.YLabel.String), ...
    'title', string(result.Axes.Title.String), 'font_name', string(result.Axes.FontName), ...
    'screen_pixels_per_inch', get(groot, 'ScreenPixelsPerInch'), 'display', string(getenv('DISPLAY')));
end

function assert_complete_v3(evidence)
assert(evidence.schema_version == 3 && isequal(evidence.shape, {12}) ...
    && isequal(evidence.dimension_order, {'observation'}) ...
    && numel(evidence.records.ids) == 12 && numel(evidence.records.time_utc) == 12 ...
    && numel(evidence.records.depth_m) == 12 ...
    && isequal(cell2mat(evidence.records.source_rows), (1:12)') ...
    && numel(evidence.input_values.observation) == 12 && numel(evidence.input_values.model) == 12 ...
    && isnan(evidence.input_values.observation{12}) && evidence.input_values.model{12} == 13.96 ...
    && numel(evidence.native_scatter.x_values) == 11 && numel(evidence.native_scatter.y_values) == 11 ...
    && numel(evidence.uncertainty.segments) == 11, ...
    'test_astra_generated_comparison:CompleteV3', 'Retain 12 complete records, 11 pairs and 11 native intervals');
wire = jsondecode(jsonencode(evidence));
assert(numel(wire.records.ids) == 12 && numel(wire.input_values.observation) == 12 ...
    && isnan(wire.input_values.observation(12)) && wire.input_values.model(12) == 13.96 ...
    && numel(wire.qc.observation.flags) == 12 && strcmp(wire.qc.observation.flags{6}, 'suspect') ...
    && numel(wire.uncertainty.observation.values) == 12 && isnan(wire.uncertainty.observation.values(12)) ...
    && isstruct(wire.uncertainty.segments) && numel(wire.uncertainty.segments) == 11 ...
    && islogical(wire.pairing.finite_pair_mask) && islogical(wire.pairing.paired_mask) ...
    && islogical(wire.qc.accepted_mask) && islogical(wire.uncertainty.graphics_mask) ...
    && isequal(fieldnames(wire.qc.model), {'status'}) ...
    && strcmp(wire.qc.model.status, 'not_provided') ...
    && isequal(fieldnames(wire.uncertainty.model), {'status'}) ...
    && strcmp(wire.uncertainty.model.status, 'not_provided'), ...
    'test_astra_generated_comparison:JSONRoundTrip', 'JSON must preserve full QC/U arrays, nulls and masks');
end

function records = verify_exports(directory, entry, pixelSize, pageInches, dpi)
assert(isequal(sort(string(fieldnames(entry.exports))), sort(["png"; "pdf"; "svg"])), ...
    'test_astra_generated_comparison:Formats', 'Exactly PNG, PDF and SVG must be present');
records = repmat(file_record(fullfile(directory, entry.exports.png.file)), 0, 1);
for format = ["png", "pdf", "svg"]
    exported = entry.exports.(format);
    assert(string(exported.file) == string(entry.id) + "." + format, ...
        'test_astra_generated_comparison:ExportPath', 'Unexpected export path');
    actual = file_record(fullfile(directory, exported.file));
    assert(actual.bytes == exported.bytes && strcmpi(actual.sha256, exported.sha256) ...
        && string(exported.export_api) == string(entry.runtime.export_api.(format)), ...
        'test_astra_generated_comparison:ArtifactBinding', 'Actual artifact and API must match the manifest');
    records(end + 1, 1) = actual; %#ok<AGROW>
end
png = imfinfo(fullfile(directory, entry.exports.png.file));
assert(png.Width == pixelSize(1) && png.Height == pixelSize(2) ...
    && entry.exports.png.dpi == dpi ...
    && all(abs([entry.exports.pdf.width entry.exports.pdf.height] - pageInches * 72) <= 1) ...
    && entry.exports.pdf.pages == 1 ...
    && entry.exports.svg.width == pixelSize(1) && entry.exports.svg.height == pixelSize(2), ...
    'test_astra_generated_comparison:Dimensions', 'Preserve 3000x2550 at 300 DPI and the original physical page');
end

function assert_function_paths(names, paths)
for functionIndex = 1:numel(names)
    actual = which(char(names(functionIndex)));
    assert(~isempty(actual) && canonical_path(actual) == paths(functionIndex), ...
        'test_astra_generated_comparison:FunctionPath', 'Unexpected implementation of %s', names(functionIndex));
end
end

function assert_files_unchanged(records)
for recordIndex = 1:numel(records)
    actual = file_record(records(recordIndex).path);
    assert(actual.bytes == records(recordIndex).bytes ...
        && strcmpi(actual.sha256, records(recordIndex).sha256), ...
        'test_astra_generated_comparison:FileChanged', 'File changed during trial: %s', actual.path);
end
end

function record = file_record(pathValue)
pathValue = canonical_path(pathValue);
info = dir(pathValue);
assert(isscalar(info) && ~info.isdir && info.bytes > 0, ...
    'test_astra_generated_comparison:MissingFile', 'Expected nonempty file: %s', pathValue);
[~, name, extension] = fileparts(pathValue);
record = struct('file', string(name) + string(extension), 'path', pathValue, ...
    'bytes', info.bytes, 'sha256', string(oi_sha256_file(pathValue)));
end

function value = canonical_path(value)
[found, attributes] = fileattrib(char(value));
assert(found, 'test_astra_generated_comparison:MissingPath', 'Missing path: %s', value);
value = string(attributes.Name);
if usejava('jvm')
    value = string(char(java.io.File(char(value)).getCanonicalPath()));
end
end

function value = read_json(filePath)
fileHandle = fopen(filePath, 'rb');
assert(fileHandle >= 0, 'test_astra_generated_comparison:Read', 'Cannot read %s', filePath);
cleanup = onCleanup(@() fclose(fileHandle));
content = fread(fileHandle, Inf, '*uint8');
value = jsondecode(native2unicode(content', 'UTF-8'));
clear cleanup;
end

function write_json(filePath, value)
fileHandle = fopen(filePath, 'wb');
assert(fileHandle >= 0, 'test_astra_generated_comparison:Write', 'Cannot write %s', filePath);
cleanup = onCleanup(@() fclose(fileHandle));
content = unicode2native(jsonencode(value), 'UTF-8');
assert(fwrite(fileHandle, content, 'uint8') == numel(content), ...
    'test_astra_generated_comparison:Write', 'Incomplete evidence write: %s', filePath);
clear cleanup;
end

function handles = new_figures(previousFigures)
handles = findall(groot, 'Type', 'figure');
keep = true(size(handles));
for handleIndex = 1:numel(handles)
    keep(handleIndex) = ~any(handles(handleIndex) == previousFigures(isgraphics(previousFigures)));
end
handles = handles(keep);
end

function close_new_figures(previousFigures)
handles = new_figures(previousFigures);
for handleIndex = 1:numel(handles)
    if isgraphics(handles(handleIndex), 'figure')
        delete(handles(handleIndex));
    end
end
end
