function result = test_interaction_native_compatibility()
%TEST_INTERACTION_NATIVE_COMPATIBILITY Exercise UI, traditional, and headless paths.
testsDirectory = fileparts(mfilename("fullpath"));
assetsDirectory = fullfile(testsDirectory, "..", "assets");
originalPath = path;
addpath(assetsDirectory);
pathCleanup = onCleanup(@() path(originalPath));

assert_axes_mode_calls_do_not_capture_outputs(assetsDirectory);
data = interaction_fixture();
desktopAvailable = usejava("desktop");

test_static_or_headless_path(data, desktopAvailable);
cjkDefaultFontExecuted = test_publication_layout(data);
test_explicit_font(data);
test_standard_uncertainty(data);
test_time_axis_padding(data);
traditionalDesktopExecuted = false;
uiAxesDesktopExecuted = false;
if desktopAvailable
    test_traditional_desktop_path(data);
    traditionalDesktopExecuted = true;
    if ~verLessThan("matlab", "9.14")
        test_ui_axes_desktop_path(data);
        uiAxesDesktopExecuted = true;
    end
end

result = struct( ...
    "DesktopAvailable", logical(desktopAvailable), ...
    "CJKDefaultFontExecuted", cjkDefaultFontExecuted, ...
    "TraditionalDesktopExecuted", traditionalDesktopExecuted, ...
    "UIAxesDesktopExecuted", uiAxesDesktopExecuted, ...
    "MATLABRelease", string(version('-release')));
fprintf("MATLAB_INTERACTION_NATIVE_COMPATIBILITY=passed\n");
fprintf("MATLAB_INTERACTION_DESKTOP_AVAILABLE=%d\n", desktopAvailable);
fprintf("MATLAB_INTERACTION_UIAXES_EXECUTED=%d\n", uiAxesDesktopExecuted);
fprintf("MATLAB_INTERACTION_CJK_DEFAULT_FONT_EXECUTED=%d\n", cjkDefaultFontExecuted);
clear pathCleanup;
end

function assert_axes_mode_calls_do_not_capture_outputs(assetsDirectory)
sourcePath = fullfile(assetsDirectory, "interactive_timeseries_native_template.m");
sourceText = fileread(sourcePath);
assert(~isempty(regexp(sourceText, ...
    "datacursormode\(axes_handles\(axes_index\), 'on'\)", "once")), ...
    "test_interaction_native_compatibility:MissingDataCursorEnable", ...
    "The UI axes data cursor mode must be enabled explicitly");
assert(~isempty(regexp(sourceText, ...
    "brush\(axes_handles\(axes_index\), 'on'\)", "once")), ...
    "test_interaction_native_compatibility:MissingBrushEnable", ...
    "The UI axes brush mode must be enabled explicitly");
assert(isempty(regexp(sourceText, ...
    "=\s*datacursormode\(axes_handles\(axes_index\)", "once")), ...
    "test_interaction_native_compatibility:DataCursorOutput", ...
    "Axes-targeted datacursormode calls must not request an output");
assert(isempty(regexp(sourceText, ...
    "=\s*brush\(axes_handles\(axes_index\)", "once")), ...
    "test_interaction_native_compatibility:BrushOutput", ...
    "Axes-targeted brush calls must not request an output");
end

function test_static_or_headless_path(data, desktopAvailable)
beforeFigures = findall(groot, "Type", "figure");
requestInteraction = ~desktopAvailable;
outputs = interactive_timeseries_native_template(data, "unused", ...
    "Interactive", requestInteraction, "UseUIFigure", true, ...
    "UseDataCursorCallback", true, "Export", false, ...
    "TimeZone", "UTC", "ValueLabel", "Temperature", ...
    "ValueUnit", "degC");
figureCleanup = onCleanup(@() close_if_valid(outputs.Figure));
assert(~outputs.InteractiveEnabled && ~outputs.UIFigureEnabled, ...
    "test_interaction_native_compatibility:StaticFallback", ...
    "The noninteractive path must use a traditional static figure");
assert(isfield(outputs, "UncertaintyUnit") ...
    && isequal(outputs.UncertaintyUnit, ""), ...
    "test_interaction_native_compatibility:EmptyUncertaintyUnit", ...
    "Output must expose an empty uncertainty unit when uncertainty is absent");
assert(outputs.PublicationWidthPixels == 2400 ...
    && outputs.PublicationHeightPixels == 1500 ...
    && outputs.PublicationDPI == 300 ...
    && outputs.PublicationPhysicalWidthIn == 8 ...
    && outputs.PublicationPhysicalHeightIn == 5, ...
    "test_interaction_native_compatibility:PublicationGeometry", ...
    "The default publication export geometry must remain 8 by 5 inches at 300 DPI");
verify_publication_layout(outputs, [8 5]);
verify_default_font(outputs);
if ~desktopAvailable
    assert(outputs.HeadlessFallbackUsed, ...
        "test_interaction_native_compatibility:HeadlessFallback", ...
        "A requested headless interaction must report its fallback");
end
verify_stable_selection(outputs, data);
lineHandle = outputs.Lines(1);
close(outputs.Figure);
assert(~isgraphics(outputs.Figure) ...
    && isempty(outputs.GetSelectedObservationIDs()) ...
    && isequal(outputs.DataCursorUpdateFcn([], ...
        struct("Target", lineHandle, "DataIndex", 1)), ...
        {'Data tip unavailable'}), ...
    "test_interaction_native_compatibility:StaticCleanup", ...
    "Static or headless cleanup left unsafe callbacks or selection state");
clear figureCleanup;
assert(numel(findall(groot, "Type", "figure")) == numel(beforeFigures), ...
    "test_interaction_native_compatibility:StaticFigureLeak", ...
    "The static or headless path leaked a figure");
end

function cjkDefaultFontExecuted = test_publication_layout(data)
data.SecondaryValue = [35.1; 35.3; 35.2; 35.5];
data.Properties.VariableUnits{end} = 'g/kg';
theme = oi_ocean_theme();
cjkDefaultFontExecuted = theme.CJKFontCapable;
titleText = "Interactive time series";
if cjkDefaultFontExecuted
    titleText = string(char([20132 20114 26102 38388 24207 21015])) ...
        + " / Interactive time series";
end
outputs = interactive_timeseries_native_template(data, "unused", ...
    "Interactive", false, "Export", false, "Title", titleText, ...
    "TimeZone", "UTC", "ValueLabel", "Temperature", "ValueUnit", "degC", ...
    "SecondaryValueLabel", "Salinity", "SecondaryValueUnit", "g/kg", ...
    "PublicationWidthPixels", 1400, "PublicationHeightPixels", 1200, ...
    "PublicationDPI", 200);
figureCleanup = onCleanup(@() close_if_valid(outputs.Figure));
assert(numel(outputs.Axes) == 2 && numel(outputs.Lines) == 2 ...
    && outputs.PublicationWidthPixels == 1400 ...
    && outputs.PublicationHeightPixels == 1200 ...
    && outputs.PublicationDPI == 200 ...
    && outputs.PublicationPhysicalWidthIn == 7 ...
    && outputs.PublicationPhysicalHeightIn == 6, ...
    "test_interaction_native_compatibility:CustomPublicationGeometry", ...
    "The two-panel layout must honor custom publication dimensions and DPI");
verify_publication_layout(outputs, [7 6]);
verify_default_font(outputs);
assert(outputs.CJKTextPresent == cjkDefaultFontExecuted ...
    && string(outputs.Layout.Title.String) == titleText ...
    && string(outputs.Layout.Title.FontName) == outputs.FontName ...
    && outputs.Layout.Title.FontSize == theme.TitleSize ...
    && ~outputs.FontRenderingVerified, ...
    "test_interaction_native_compatibility:PublicationTitle", ...
    "Publication sizing must preserve the full title, font, and verification status");
verify_stable_selection(outputs, data);
outputs.Lines(2).BrushData = [0; 1; 0; 1];
identity = outputs.GetSelectedObservationIdentity();
assert(isequal(identity.ObservationID, data.ObservationID([2 4])) ...
    && isequal(identity.SourceRow, data.SourceRow([2 4])), ...
    "test_interaction_native_compatibility:SecondaryStableIdentity", ...
    "The resized secondary panel must preserve stable observation identity");
outputs.ClearBrushSelection();
assert(isempty(outputs.GetSelectedObservationIDs()), ...
    "test_interaction_native_compatibility:SecondaryClearSelection", ...
    "Clearing selection must include the secondary panel");
clear figureCleanup;
end

function verify_publication_layout(outputs, expectedSize)
assert(string(outputs.Figure.Units) == "inches" ...
    && all(abs(outputs.Figure.Position(3:4) - expectedSize) < 1e-6) ...
    && string(outputs.Figure.PaperUnits) == "inches" ...
    && all(abs(outputs.Figure.PaperSize - expectedSize) < 1e-6) ...
    && all(abs(outputs.Figure.PaperPosition - [0 0 expectedSize]) < 1e-6) ...
    && string(outputs.Figure.PaperPositionMode) == "manual", ...
    "test_interaction_native_compatibility:PreExportPhysicalSize", ...
    "Traditional figures must have publication physical dimensions before export");
outerPosition = outputs.Layout.OuterPosition;
pageMargins = [outerPosition(1:2), ...
    1 - outerPosition(1:2) - outerPosition(3:4)] .* [expectedSize expectedSize];
assert(string(outputs.Layout.Units) == "normalized" ...
    && string(outputs.Layout.PositionConstraint) == "outerposition" ...
    && all(abs(pageMargins - 0.25) < 1e-6) ...
    && string(outputs.Layout.Padding) == "loose", ...
    "test_interaction_native_compatibility:PublicationPageMargins", ...
    "The complete tiled layout must reserve quarter-inch page margins");
end

function verify_default_font(outputs)
theme = oi_ocean_theme();
expectedFont = theme.FontName;
if oi_font_available("WenQuanYi Zen Hei")
    expectedFont = "WenQuanYi Zen Hei";
end
assert(strcmpi(outputs.FontName, expectedFont), ...
    "test_interaction_native_compatibility:DefaultFont", ...
    "The default font must prefer installed WenQuanYi Zen Hei before fallback");
for axesIndex = 1:numel(outputs.Axes)
    assert(strcmpi(outputs.Axes(axesIndex).FontName, expectedFont) ...
        && outputs.Axes(axesIndex).FontSize == theme.FontSize, ...
        "test_interaction_native_compatibility:AxesTypography", ...
        "Every panel must retain the selected font and the original font size");
end
end

function test_explicit_font(data)
theme = oi_ocean_theme();
fontName = theme.FontName;
candidates = ["Noto Sans CJK SC" "DejaVu Sans" "Liberation Sans" "Arial" "Helvetica"];
for fontIndex = 1:numel(candidates)
    if oi_font_available(candidates(fontIndex))
        fontName = candidates(fontIndex);
        break;
    end
end
outputs = interactive_timeseries_native_template(data, "unused", ...
    "Interactive", false, "Export", false, "FontName", " " + fontName + " ", ...
    "TimeZone", "UTC", "ValueLabel", "Temperature", "ValueUnit", "degC");
figureCleanup = onCleanup(@() close_if_valid(outputs.Figure));
assert(strcmpi(outputs.FontName, fontName) ...
    && strcmpi(outputs.Axes(1).FontName, fontName) ...
    && ~outputs.FontRenderingVerified, ...
    "test_interaction_native_compatibility:ExplicitFont", ...
    "WenQuanYi preference must not override an explicitly requested available font");
clear figureCleanup;
end

function test_standard_uncertainty(data)
data.Value(2) = NaN;
data.Uncertainty = [0.11; NaN; NaN; 0.23];
data.Properties.VariableUnits{end} = 'degC';
for typeInput = ["standard-uncertainty" "standard_uncertainty" "standard-deviation"]
    expectedType = replace(typeInput, "_", "-");
    outputs = render_uncertainty(data, typeInput);
    figureCleanup = onCleanup(@() close_if_valid(outputs.Figure));
    assert(isfield(outputs, "UncertaintyUnit") ...
        && isequal(outputs.UncertaintyUnit, "degC"), ...
        "test_interaction_native_compatibility:UncertaintyUnitField", ...
        "Output must expose the validated uncertainty unit as a scalar string");
    metadata = outputs.Lines(1).UserData;
    assert(outputs.UncertaintyType == expectedType ...
        && outputs.UncertaintyUnit == "degC" && isnan(outputs.ConfidenceLevel) ...
        && outputs.UncertaintyRepresentation == "magnitude" ...
        && metadata.UncertaintyType == expectedType ...
        && metadata.UncertaintyUnit == "degC" && metadata.QuantityUnit == "degC" ...
        && isequaln(metadata.Uncertainty, data.Uncertainty) ...
        && isequaln(metadata.PlottedValue, data.Value) ...
        && isequaln(outputs.Lines(1).YData(:), data.Value), ...
        "test_interaction_native_compatibility:UncertaintySemantics", ...
        "Uncertainty type, unit, and raw values must survive without statistical reinterpretation");
    assert(outputs.ValidCount == 2 && outputs.MissingCount == 2 ...
        && outputs.UncertaintyMissingCount == 1, ...
        "test_interaction_native_compatibility:UncertaintyMissing", ...
        "Adding an uncertainty type must preserve existing missing-data counts");
    for dataIndex = [1 4]
        tipRows = outputs.DataCursorUpdateFcn([], ...
            struct("Target", outputs.Lines(1), "DataIndex", dataIndex));
        expectedTip = sprintf('Uncertainty (%s, degC): %.6g', ...
            char(expectedType), data.Uncertainty(dataIndex));
        assert(any(strcmp(tipRows, expectedTip)), ...
            "test_interaction_native_compatibility:UncertaintyDataTip", ...
            "Data cursor uncertainty must retain the declared type, unit, and magnitude");
    end
    missingTip = outputs.DataCursorUpdateFcn([], ...
        struct("Target", outputs.Lines(1), "DataIndex", 2));
    incompleteTip = outputs.DataCursorUpdateFcn([], ...
        struct("Target", outputs.Lines(1), "DataIndex", 3));
    assert(isequal(missingTip, {'Data tip unavailable'}) ...
        && ~any(startsWith(string(incompleteTip), "Uncertainty (")), ...
        "test_interaction_native_compatibility:MissingUncertaintyDataTip", ...
        "Missing values or uncertainty must not be inferred by data cursors");
    clear figureCleanup;
end
for unknownType = ["variance" "std" "standard uncertainty"]
    assert_interaction_error(@() render_uncertainty(data, unknownType), ...
        "supported scientific uncertainty semantic");
end
assert_interaction_error(@() render_uncertainty(data, "standard-uncertainty", ...
    "ConfidenceLevel", 0.95), "ConfidenceLevel applies only");
for invalidLevel = [NaN 0 1 Inf]
    assert_interaction_error(@() render_uncertainty(data, "confidence-interval", ...
        "ConfidenceLevel", invalidLevel), "ConfidenceLevel must be an explicit fraction");
end
assert_interaction_error(@() interactive_timeseries_native_template(data, "unused", ...
    "Interactive", false, "Export", false, "TimeZone", "UTC", ...
    "ValueLabel", "Temperature", "ValueUnit", "degC", ...
    "UncertaintyType", "standard-uncertainty", "UncertaintyUnit", "K"), ...
    "UncertaintyUnit must match ValueUnit");
invalidData = data;
invalidData.Uncertainty(2) = 0.1;
assert_interaction_error(@() render_uncertainty(invalidData, "standard-uncertainty"), ...
    "Finite uncertainty cannot exist where Value is missing");
end

function outputs = render_uncertainty(data, uncertaintyType, varargin)
outputs = interactive_timeseries_native_template(data, "unused", ...
    "Interactive", false, "Export", false, "TimeZone", "UTC", ...
    "ValueLabel", "Temperature", "ValueUnit", "degC", ...
    "UncertaintyType", uncertaintyType, "UncertaintyUnit", "degC", varargin{:});
end

function test_time_axis_padding(data)
data.Uncertainty = [0.11; 0.14; 0.17; 0.23];
data.Properties.VariableUnits{end} = 'degC';
missingData = data;
missingData.Value(2) = NaN;
missingData.Uncertainty(2:3) = NaN;
missingData.SecondaryValue = [35.1; 35.3; NaN; 35.5];
missingData.Properties.VariableUnits{end} = 'g/kg';
subsecondData = removevars(data, 'Uncertainty');
subsecondData.Time = datetime(2026, 9, 5, 'TimeZone', 'Asia/Shanghai') ...
    + seconds([0; 0.25; 0.5; 0.75]);
subsecondData.Time.Format = 'yyyy-MM-dd HH:mm:ss.SSS';
subsecondData.UncertaintyLower = subsecondData.Value - [0.1; 0.2; 0.15; 0.25];
subsecondData.UncertaintyUpper = subsecondData.Value + [0.2; 0.15; 0.3; 0.4];
subsecondData.Properties.VariableUnits(end-1:end) = {'degC', 'degC'};
singletonData = data(1, :);
singletonData.Time.TimeZone = 'Asia/Shanghai';
fixtures = {data, missingData, subsecondData, singletonData};
caseNames = ["magnitude", "missing-linked", "subsecond-bounds", "singleton"];
outputRoot = string(getenv("MATLAB_FULL100_OUTPUT"));
if strlength(outputRoot) == 0
    outputDirectory = string(tempname);
else
    outputDirectory = fullfile(outputRoot, "interaction-time-padding");
end
assert(~isfolder(outputDirectory) && ~isfile(outputDirectory), ...
    "test_interaction_native_compatibility:FreshPaddingOutput", ...
    "Time padding artifacts require a fresh directory: %s", outputDirectory);
mkdir(outputDirectory);
if strlength(outputRoot) == 0
    directoryCleanup = onCleanup(@() rmdir(outputDirectory, 's'));
end
fprintf("MATLAB_INTERACTION_TIME_PADDING_OUTPUT=%s\n", outputDirectory);
for caseIndex = 1:numel(fixtures)
    source = fixtures{caseIndex};
    extraOptions = {};
    if ismember('SecondaryValue', source.Properties.VariableNames)
        extraOptions = {'SecondaryValueLabel', 'Salinity', 'SecondaryValueUnit', 'g/kg', ...
            'PublicationWidthPixels', 1400, 'PublicationHeightPixels', 1200, ...
            'PublicationDPI', 200};
    end
    uncertaintyType = "standard-uncertainty";
    if ismember('UncertaintyLower', source.Properties.VariableNames)
        uncertaintyType = "confidence-interval";
        extraOptions = [extraOptions, {'ConfidenceLevel', 0.95}]; %#ok<AGROW>
    end
    outputs = interactive_timeseries_native_template(source, ...
        fullfile(outputDirectory, caseNames(caseIndex)), ...
        'Interactive', false, 'Export', true, 'ExportSVG', true, ...
        'TimeZone', string(source.Time.TimeZone), ...
        'ValueLabel', 'Temperature', 'ValueUnit', 'degC', ...
        'UncertaintyType', uncertaintyType, 'UncertaintyUnit', 'degC', extraOptions{:});
    figureCleanup = onCleanup(@() close_if_valid(outputs.Figure));
    drawnow;
    imageInfo = imfinfo(outputs.PNG);
    assert(outputs.ExportPerformed && isfile(outputs.PDF) && isfile(outputs.SVG) ...
        && imageInfo.Width == outputs.PublicationWidthPixels ...
        && imageInfo.Height == outputs.PublicationHeightPixels, ...
        "test_interaction_native_compatibility:PaddingExports", ...
        "Time padding must render all three formats at the unchanged final size");
    verify_publication_layout(outputs, ...
        [outputs.PublicationPhysicalWidthIn outputs.PublicationPhysicalHeightIn]);
    verify_default_font(outputs);
    verify_time_axis_clearance(outputs, source, caseNames(caseIndex));
    verify_time_padding_data(outputs, source);
    limits = outputs.Axes(1).XLim;
    if height(source) == 1
        xlim(outputs.Axes(1), 'auto');
        drawnow;
        nativeLimits = xlim(outputs.Axes(1));
        nativeMargin = seconds(0.04 * seconds(nativeLimits(2) - nativeLimits(1)));
        expectedLimits = [nativeLimits(1) - nativeMargin nativeLimits(2) + nativeMargin];
        limitErrorSeconds = seconds(limits - expectedLimits);
        fprintf("MATLAB_INTERACTION_SINGLETON_LIMITS=%s\n", jsonencode(struct( ...
            "padded_limits", string(limits), "native_auto_limits_after_export", string(nativeLimits), ...
            "expected_limits_after_export", string(expectedLimits), "error_seconds", limitErrorSeconds, ...
            "visual_verified", false)));
        assert(all(abs(limitErrorSeconds) < 1e-9), ...
            "test_interaction_native_compatibility:SingletonTimeLimits", ...
            "Singleton padding must extend native auto limits without a calendar-unit guess");
        xlim(outputs.Axes(1), limits);
    elseif numel(outputs.Axes) == 2
        assert(outputs.ValidCount == 2 && outputs.MissingCount == 2 ...
            && outputs.UncertaintyMissingCount == 1, ...
            "test_interaction_native_compatibility:PaddingMissingCounts", ...
            "Padding must not change the missing-value or incomplete-uncertainty counts");
        shiftedLimits = limits + seconds(0.1 * seconds(limits(2) - limits(1)));
        xlim(outputs.Axes(2), shiftedLimits);
        drawnow;
        assert(isequal(outputs.Axes(1).XLim, shiftedLimits), ...
            "test_interaction_native_compatibility:PaddingLinkedLimits", ...
            "Changing the secondary time limits must still update the primary axes");
        xlim(outputs.Axes(1), limits);
        assert(isequal(outputs.Axes(2).XLim, limits), ...
            "test_interaction_native_compatibility:PaddingLinkedRestore", ...
            "Changing primary time limits must still update the secondary axes");
        verify_stable_selection(outputs, source);
    end
    verify_time_padding_data(outputs, source);
    clear figureCleanup;
end
duplicateData = data;
duplicateData.Time(:) = duplicateData.Time(1);
assert_interaction_error(@() render_uncertainty(duplicateData, "standard-uncertainty"), ...
    "Time must be unique and strictly increasing");
clear directoryCleanup;
end

function verify_time_axis_clearance(outputs, data, caseName)
figurePixels = getpixelposition(outputs.Figure);
for axesIndex = 1:numel(outputs.Axes)
    axesHandle = outputs.Axes(axesIndex);
    limits = axesHandle.XLim;
    assert(isdatetime(limits) && strcmp(limits.TimeZone, data.Time.TimeZone) ...
        && limits(1) < data.Time(1) && limits(2) > data.Time(end) ...
        && isequal(limits, outputs.Axes(1).XLim), ...
        "test_interaction_native_compatibility:TimeLimits", ...
        "%s panel %d must keep both endpoints strictly inside shared zoned limits", ...
        caseName, axesIndex);
    if height(data) > 1
        expectedMargin = seconds(0.04 * seconds(data.Time(end) - data.Time(1)));
        expectedLimits = [data.Time(1) - expectedMargin data.Time(end) + expectedMargin];
        assert(all(abs(seconds(limits - expectedLimits)) < 1e-9), ...
            "test_interaction_native_compatibility:TimeMarginDuration", ...
            "Time limits must reserve exactly four percent of elapsed duration at each end");
    end
    axesPixels = getpixelposition(axesHandle, true);
    axesWidthPoints = axesPixels(3) / figurePixels(3) ...
        * outputs.PublicationPhysicalWidthIn * 72;
    endpointMargins = seconds([data.Time(1) - limits(1), limits(2) - data.Time(end)]) ...
        / seconds(limits(2) - limits(1)) * axesWidthPoints;
    lineHandle = outputs.Lines(axesIndex);
    glyphHalfWidth = (lineHandle.MarkerSize + lineHandle.LineWidth) / 2;
    if isgraphics(outputs.UncertaintyHandles(axesIndex))
        errorHandle = outputs.UncertaintyHandles(axesIndex);
        glyphHalfWidth = max(glyphHalfWidth, (errorHandle.CapSize + errorHandle.LineWidth) / 2);
    end
    clearancePoints = endpointMargins - glyphHalfWidth - axesHandle.LineWidth / 2;
    fprintf('MATLAB_INTERACTION_TIME_MARGIN case=%s panel=%d axes_width_pt=%.9g clearance_pt=%s\n', ...
        caseName, axesIndex, axesWidthPoints, mat2str(clearancePoints, 12));
    assert(all(isfinite(clearancePoints)) && all(clearancePoints > 0), ...
        "test_interaction_native_compatibility:EndpointClearance", ...
        "%s panel %d has no physical clearance: margins_pt=%s glyph_half_width_pt=%g axis_width_pt=%g", ...
        caseName, axesIndex, mat2str(endpointMargins, 12), glyphHalfWidth, axesHandle.LineWidth);
end
end

function verify_time_padding_data(outputs, data)
identityFields = ["Time", "ObservationID", "Station", "QCFlag", "SourceRow"];
uncertaintyFields = ["Uncertainty", "UncertaintyLower", "UncertaintyUpper"];
for lineIndex = 1:numel(outputs.Lines)
    lineHandle = outputs.Lines(lineIndex);
    metadata = lineHandle.UserData;
    expectedValues = data.Value;
    if lineIndex == 2
        expectedValues = data.SecondaryValue;
    end
    assert(isequal(lineHandle.XData(:), data.Time) ...
        && strcmp(lineHandle.XData.TimeZone, data.Time.TimeZone) ...
        && strcmp(metadata.Time.TimeZone, data.Time.TimeZone) ...
        && strcmp(metadata.Time.Format, data.Time.Format) ...
        && isequaln(lineHandle.YData(:), expectedValues) ...
        && isequaln(metadata.PlottedValue, expectedValues) ...
        && metadata.SourceRowOrigin == "supplied_pre_filter_identity", ...
        "test_interaction_native_compatibility:PaddingRawSeries", ...
        "Padding must preserve every original time, zone, format, value, and source-row identity");
    for fieldName = identityFields
        assert(isequaln(metadata.(fieldName), data.(fieldName)), ...
            "test_interaction_native_compatibility:PaddingIdentity", ...
            "Time padding changed aligned metadata %s", fieldName);
    end
    for fieldName = uncertaintyFields
        expectedValues = nan(height(data), 1);
        if ismember(fieldName, string(data.Properties.VariableNames))
            expectedValues = data.(fieldName);
        end
        assert(isequaln(metadata.(fieldName), expectedValues), ...
            "test_interaction_native_compatibility:PaddingUncertainty", ...
            "Time padding changed raw uncertainty metadata %s", fieldName);
    end
end
errorHandle = outputs.UncertaintyHandles(1);
if ismember('Uncertainty', data.Properties.VariableNames)
    expectedLowerDelta = data.Uncertainty;
    expectedUpperDelta = data.Uncertainty;
else
    expectedLowerDelta = data.Value - data.UncertaintyLower;
    expectedUpperDelta = data.UncertaintyUpper - data.Value;
end
assert(isequal(errorHandle.XData(:), data.Time) ...
    && strcmp(errorHandle.XData.TimeZone, data.Time.TimeZone) ...
    && isequaln(errorHandle.YData(:), data.Value) ...
    && isequaln(errorHandle.YNegativeDelta(:), expectedLowerDelta) ...
    && isequaln(errorHandle.YPositiveDelta(:), expectedUpperDelta), ...
    "test_interaction_native_compatibility:PaddingErrorBars", ...
    "Padding must not insert observations or change plotted errors, times, or missing masks");
expectedFlags = unique(data.QCFlag, 'stable');
expectedCounts = zeros(numel(expectedFlags), 1);
for flagIndex = 1:numel(expectedFlags)
    expectedCounts(flagIndex) = sum(data.QCFlag == expectedFlags(flagIndex));
end
assert(outputs.QCPolicy == "preserve" ...
    && isequal(outputs.QCSummary.Flag, expectedFlags) ...
    && isequal(outputs.QCSummary.Count, expectedCounts), ...
    "test_interaction_native_compatibility:PaddingQC", ...
    "Time padding must preserve every QC flag and count");
end

function assert_interaction_error(callback, expectedMessage)
try
    outputs = callback();
catch exception
    assert(contains(string(exception.message), expectedMessage), ...
        "test_interaction_native_compatibility:UnexpectedError", ...
        "Unexpected error: %s", exception.message);
    return;
end
close_if_valid(outputs.Figure);
error("test_interaction_native_compatibility:MissingError", ...
    "Expected uncertainty validation to reject: %s", expectedMessage);
end

function test_traditional_desktop_path(data)
beforeFigures = findall(groot, "Type", "figure");
outputs = interactive_timeseries_native_template(data, "unused", ...
    "Interactive", true, "UseUIFigure", false, ...
    "UseDataCursorCallback", true, "Export", false, ...
    "TimeZone", "UTC", "ValueLabel", "Temperature", ...
    "ValueUnit", "degC");
figureCleanup = onCleanup(@() close_if_valid(outputs.Figure));
assert(outputs.InteractiveEnabled && ~outputs.UIFigureEnabled, ...
    "test_interaction_native_compatibility:TraditionalDesktop", ...
    "The traditional desktop path did not enable interaction");
verify_publication_layout(outputs, [8 5]);
interactionState = getappdata(outputs.Figure, "OceanInteractionState");
dataCursorMode = interactionState.DataCursorMode;
brushMode = interactionState.BrushMode;
assert(is_live_mode(dataCursorMode) && is_live_mode(brushMode), ...
    "test_interaction_native_compatibility:TraditionalModes", ...
    "Traditional figures must retain live interaction mode objects");
verify_stable_selection(outputs, data);
tipRows = outputs.DataCursorUpdateFcn([], ...
    struct("Target", outputs.Lines(1), "DataIndex", 2));
assert(any(contains(string(tipRows), data.ObservationID(2))) ...
    && any(contains(string(tipRows), string(data.SourceRow(2)))), ...
    "test_interaction_native_compatibility:TraditionalDataTip", ...
    "The traditional data cursor callback lost stable point identity");
close(outputs.Figure);
assert(~is_live_mode(dataCursorMode) && ~is_live_mode(brushMode), ...
    "test_interaction_native_compatibility:TraditionalCleanup", ...
    "Traditional interaction mode objects survived figure cleanup");
clear figureCleanup;
assert(numel(findall(groot, "Type", "figure")) == numel(beforeFigures), ...
    "test_interaction_native_compatibility:TraditionalFigureLeak", ...
    "The traditional desktop path leaked a figure");
end

function test_ui_axes_desktop_path(data)
beforeFigures = findall(groot, "Type", "figure");
outputs = interactive_timeseries_native_template(data, "unused", ...
    "Interactive", true, "UseUIFigure", true, ...
    "UseDataCursorCallback", false, "Export", false, ...
    "PublicationWidthPixels", 1400, "PublicationHeightPixels", 1200, ...
    "PublicationDPI", 200, ...
    "TimeZone", "UTC", "ValueLabel", "Temperature", ...
    "ValueUnit", "degC");
figureCleanup = onCleanup(@() close_if_valid(outputs.Figure));
assert(outputs.InteractiveEnabled && outputs.UIFigureEnabled, ...
    "test_interaction_native_compatibility:UIAxesDesktop", ...
    "The uifigure desktop path did not enable UI axes interaction");
assert(string(outputs.Figure.Units) == "pixels" ...
    && isequal(outputs.Figure.Position(3:4), [1200 720]) ...
    && string(outputs.Layout.Units) == "normalized" ...
    && all(abs(outputs.Layout.OuterPosition - [0 0 1 1]) < 1e-6), ...
    "test_interaction_native_compatibility:UIFigureGeometry", ...
    "Publication dimensions and page margins must not change the UI figure layout");
interactionState = getappdata(outputs.Figure, "OceanInteractionState");
assert(isequal(interactionState.UsesAxesInteractionModes, true) ...
    && all(cellfun(@isempty, interactionState.DataCursorModes)) ...
    && all(cellfun(@isempty, interactionState.BrushModes)), ...
    "test_interaction_native_compatibility:UIAxesModeObjects", ...
    "UI axes interaction must not depend on returned mode objects");
verify_stable_selection(outputs, data);
lineHandle = outputs.Lines(1);
close(outputs.Figure);
assert(~isgraphics(outputs.Figure) ...
    && isempty(outputs.GetSelectedObservationIDs()) ...
    && isequal(outputs.DataCursorUpdateFcn([], ...
        struct("Target", lineHandle, "DataIndex", 1)), ...
        {'Data tip unavailable'}), ...
    "test_interaction_native_compatibility:UIAxesCleanup", ...
    "UI axes cleanup left unsafe callbacks or selection state");
clear figureCleanup;
assert(numel(findall(groot, "Type", "figure")) == numel(beforeFigures), ...
    "test_interaction_native_compatibility:UIAxesFigureLeak", ...
    "The uifigure desktop path leaked a figure");
end

function verify_stable_selection(outputs, data)
outputs.Lines(1).BrushData = [1; 0; 1; 0];
identity = outputs.GetSelectedObservationIdentity();
assert(isequal(identity.ObservationID, data.ObservationID([1 3])) ...
    && isequal(identity.SourceRow, data.SourceRow([1 3])), ...
    "test_interaction_native_compatibility:StableIdentity", ...
    "Brush selection did not preserve ObservationID and SourceRow");
identityAgain = outputs.GetSelectedObservationIdentity();
assert(isequal(identityAgain, identity), ...
    "test_interaction_native_compatibility:StableReentry", ...
    "Repeated brush selection collection was not stable");
outputs.ClearBrushSelection();
assert(isempty(outputs.GetSelectedObservationIDs()), ...
    "test_interaction_native_compatibility:ClearSelection", ...
    "Brush selection was not cleared");
end

function data = interaction_fixture()
time = datetime(2026, 9, 5, 0:3, 0, 0, "TimeZone", "UTC")';
value = [20.1; 20.4; 20.2; 20.8];
observationID = ["OBS-101"; "OBS-102"; "OBS-103"; "OBS-104"];
station = repmat("STATION-A", 4, 1);
qcFlag = ["good"; "suspect"; "good"; "good"];
sourceRow = [9; 3; 14; 6];
data = table(time, value, observationID, station, qcFlag, sourceRow, ...
    'VariableNames', ...
    {'Time', 'Value', 'ObservationID', 'Station', 'QCFlag', 'SourceRow'});
data.Properties.VariableUnits = {'', 'degC', '', '', '', ''};
end

function valid = is_live_mode(modeObject)
valid = false;
if isempty(modeObject) || ~isscalar(modeObject)
    return;
end
try
    valid = isvalid(modeObject);
catch
end
end

function close_if_valid(figureHandle)
if isgraphics(figureHandle)
    close(figureHandle);
end
end
