function test_ts_diagram_runtime(outputDirectory)
arguments
    outputDirectory (1,1) string = string(fullfile(tempdir,"oi-ts-diagram-runtime"))
end
assert(~verLessThan("matlab","9.10"), ...
    "test_ts_diagram_runtime:UnsupportedRelease", ...
    "T-S runtime validation requires MATLAB R2021a or newer");

assetDirectory = fullfile(fileparts(mfilename("fullpath")),"..","assets");
addpath(assetDirectory);
if isfolder(outputDirectory)
    rmdir(outputDirectory,"s");
end
mkdir(outputDirectory);

theme = oi_ocean_theme();
salinity = [34.45;34.62;NaN;34.91;35.03];
temperature = [13.2;11.4;8.7;6.3;4.8];
depth = [5;25;50;75;100];
densitySalinity = linspace(34.3,35.2,12);
densityTemperature = linspace(4,14,14);
[salinityGrid,temperatureGrid] = meshgrid(densitySalinity,densityTemperature);
densityValues = 25.5 + 0.78 * (salinityGrid - 34.3) - 0.18 * (temperatureGrid - 4);

figureHandle = figure("Visible","off","Color","white","Position",[100 100 1200 675]);
cleanup = onCleanup(@() close_if_valid(figureHandle));
axesHandle = axes(figureHandle);
result = oi_plot_ts_diagram(axesHandle,salinity,temperature,depth,struct( ...
    "SalinityLabel","Absolute salinity","SalinityType","absolute", ...
    "SalinityDefinition","TEOS-10 Absolute Salinity","SalinityUnit","g/kg", ...
    "TemperatureLabel","Conservative temperature","TemperatureType","conservative", ...
    "TemperatureDefinition","TEOS-10 Conservative Temperature", ...
    "TemperatureUnit","degC","ReferencePressure","0 dbar", ...
    "ColorLabel","Sample depth","ColorUnit","m","ColorLimits",[0 100], ...
    "DensityValues",densityValues,"DensitySalinity",densitySalinity, ...
    "DensityTemperature",densityTemperature,"DensityLevels",[25.5 26 26.5 27], ...
    "DensityType","sigma-theta","DensityUnit","kg/m^3", ...
    "DensityReference","TEOS-10 sigma-theta referenced to 0 dbar", ...
    "DensityReferencePressure","0 dbar","DensitySource","test analytic field", ...
    "Theme",theme,"Title","T-S runtime contract"));
assert(result.ValidCount == 4 && result.MissingCount == 1 ...
    && result.ColorSaturatedCount == 0 && result.DensityType == "sigma-theta", ...
    "test_ts_diagram_runtime:ResultMetadata","T-S counts or metadata are incorrect");
assert(result.ManifestMetadata.density.source == "test analytic field" ...
    && result.ManifestMetadata.salinity.type == "absolute", ...
    "test_ts_diagram_runtime:ManifestMetadata", ...
    "Scientific manifest metadata is incomplete");

entry = oi_export_figure(figureHandle,outputDirectory,"ts-diagram-runtime", ...
    1200,675,180,"Title","T-S runtime contract", ...
    "Source","test_ts_diagram_runtime","Theme",theme.Name);
entry.scientific_metadata = result.ManifestMetadata;
manifestPath = fullfile(outputDirectory,"figures.json");
manifest = oi_write_manifest(manifestPath,entry);
assert(isfile(fullfile(outputDirectory,"ts-diagram-runtime.png")) ...
    && isfile(fullfile(outputDirectory,"ts-diagram-runtime.pdf")) ...
    && isfile(manifestPath) && numel(manifest.figures) == 1 ...
    && manifest.figures.scientific_metadata.density.type == "sigma-theta", ...
    "test_ts_diagram_runtime:Artifacts","PNG, PDF, or manifest artifact is missing");

must_throw(@() run_empty_case(theme),"NoCompleteSamples");
must_throw(@() run_saturated_case(theme),"ColorOutOfRange");
must_throw(@() run_bad_unit_case(theme),"SalinityUnit");
saturatedResult = run_explicit_saturation_case(theme);
assert(saturatedResult.ColorSaturatedCount == 1 ...
    && saturatedResult.ManifestMetadata.color.saturated_count == 1, ...
    "test_ts_diagram_runtime:ColorSaturation", ...
    "Explicit color saturation must be counted in result and manifest metadata");
fprintf("TS_DIAGRAM_RUNTIME=passed\n");
end

function run_empty_case(theme)
[figureHandle,axesHandle,cleanup] = make_axes(); %#ok<ASGLU>
oi_plot_ts_diagram(axesHandle,[NaN;NaN],[NaN;NaN],[NaN;NaN],struct( ...
    "SalinityUnit","PSU","TemperatureUnit","degC","ColorLabel","Depth", ...
    "ColorUnit","m","ColorLimits",[0 10],"Theme",theme));
end

function run_saturated_case(theme)
[figureHandle,axesHandle,cleanup] = make_axes(); %#ok<ASGLU>
oi_plot_ts_diagram(axesHandle,[34;35],[5;6],[0;20],struct( ...
    "SalinityUnit","PSU","TemperatureUnit","degC","ColorLabel","Depth", ...
    "ColorUnit","m","ColorLimits",[0 10],"Theme",theme));
end

function run_bad_unit_case(theme)
[figureHandle,axesHandle,cleanup] = make_axes(); %#ok<ASGLU>
oi_plot_ts_diagram(axesHandle,[34;35],[5;6],[0;10],struct( ...
    "SalinityType","absolute","SalinityUnit","PSU", ...
    "TemperatureType","in-situ","TemperatureUnit","degC", ...
    "ColorLabel","Depth","ColorUnit","m","ColorLimits",[0 10],"Theme",theme));
end

function result = run_explicit_saturation_case(theme)
[figureHandle,axesHandle,cleanup] = make_axes(); %#ok<ASGLU>
result = oi_plot_ts_diagram(axesHandle,[34;35],[5;6],[0;20],struct( ...
    "SalinityUnit","PSU","TemperatureUnit","degC","ColorLabel","Depth", ...
    "ColorUnit","m","ColorLimits",[0 10],"ColorOutOfRangePolicy","saturate", ...
    "Theme",theme));
end

function [figureHandle,axesHandle,cleanup] = make_axes()
figureHandle = figure("Visible","off","Color","white");
cleanup = onCleanup(@() close_if_valid(figureHandle));
axesHandle = axes(figureHandle);
end

function must_throw(callback,identifierFragment)
thrown = false;
try
    callback();
catch exception
    thrown = contains(string(exception.identifier),identifierFragment) ...
        || contains(string(exception.message),identifierFragment);
end
assert(thrown,"test_ts_diagram_runtime:ExpectedError", ...
    "Expected an error containing '%s'",identifierFragment);
end

function close_if_valid(figureHandle)
if isgraphics(figureHandle)
    close(figureHandle);
end
end
