function report = test_astra_generated_argo(outputDirectory)
arguments
    outputDirectory (1,1) string
end
assert(~exist('OCTAVE_VERSION', 'builtin'), ...
    'argo_native_probe:MatlabRequired', 'Native MATLAB is required');
assert(~verLessThan('matlab', '9.10'), ...
    'argo_native_probe:UnsupportedRelease', 'MATLAB R2021a or newer is required');
assert(~ismissing(outputDirectory) && strlength(strtrim(outputDirectory)) > 0, ...
    'argo_native_probe:OutputDirectory', 'An explicit output root is required');
assert(isfolder(outputDirectory), 'argo_native_probe:OutputDirectory', ...
    'The caller must provide an existing output root');
originalDirectory = pwd;
originalPath = path;
previousFigures = findall(groot, 'Type', 'figure');
directoryCleanup = onCleanup(@() cd(originalDirectory));
pathCleanup = onCleanup(@() path(originalPath));
figureCleanup = onCleanup(@() close_new_figures(previousFigures));
testsDirectory = canonical_path(fileparts(mfilename('fullpath')));
bundleDirectory = fullfile(testsDirectory, 'model-generated-round24');
helperDirectory = canonical_path(fullfile(testsDirectory, '..', 'assets'));
addpath(helperDirectory, '-begin');
assert_paths("oi_sha256_file", fullfile(helperDirectory, 'oi_sha256_file.m'));
fileNames = ["astra_argo_trial.m", "argo-4903822-30d.json", ...
    "generation-provenance.json", "astra-argo-round24.md", ...
    "generation-prompt.zh.txt", "review-prompt.zh.txt"];
hashes = ["aaed9d3606d52f43bdefbfe220a6a187e311a4c78109f1191ca3b2c2ad548df0", ...
    "33959a0d9296cf3d0739375d0d551550d493dddbe3aa8cc3606b67ac7df0b7fa", ...
    "28b01ff3d66e88c69d52290e8b597e2594ea505a7056f04ee99bd2734682ac86", ...
    "b2baec1748545efa399c2458a368c378de678be740679baabcedfafdf4c12099", ...
    "2b2c3c4fc182b0caff4a81e7efee0c9d43e86698dcdc3ae7ed8fb54ccf9f7d52", ...
    "19dada738708de3e5ea9d6d912daf5c4756d6a6d254b570c3c42f22c188cb6b2"];
tracked = pinned_file(fullfile(bundleDirectory, fileNames(1)), hashes(1));
for fileIndex = 2:numel(fileNames)
    tracked(end + 1, 1) = pinned_file(fullfile(bundleDirectory, fileNames(fileIndex)), hashes(fileIndex)); %#ok<AGROW>
end
source = tracked(1);
input = tracked(2);
provenanceRecord = tracked(3);
assert(source.bytes == 22579 && input.bytes == 58061, ...
    'argo_native_probe:SourceBinding', 'Execute only the archived unedited source and input');
provenance = jsondecode(fileread(provenanceRecord.path));
validate_provenance(provenance, tracked);
tracked(end + 1, 1) = file_record(fullfile(bundleDirectory, 'README.md'));
helperListing = dir(fullfile(helperDirectory, '*.m'));
helperNames = erase(string({helperListing.name}), '.m');
assert(all(ismember(["oi_plot_ts_diagram", "oi_export_figure", "oi_write_manifest"], helperNames)), ...
    'argo_native_probe:Helpers', 'Plot, export and manifest helpers must exist in the sibling assets');
for helperIndex = 1:numel(helperNames)
    tracked(end + 1, 1) = file_record(fullfile(helperDirectory, helperNames(helperIndex) + ".m")); %#ok<AGROW>
end
probeNames = ["test_astra_generated_argo", "read_argo_trial_input", ...
    "read_argo_ts_native", "adapt_astra_argo_r24c_candidate"];
for probeIndex = 1:numel(probeNames)
    tracked(end + 1, 1) = file_record(fullfile(testsDirectory, probeNames(probeIndex) + ".m")); %#ok<AGROW>
end
adapterName = "adapt_astra_argo_r24c_candidate";
pixelSize = [2400 1500];
pageInches = [8 5];
dpi = 300;
outputDirectory = fullfile(canonical_path(outputDirectory), 'astra-argo-trial');
assert(~isfolder(outputDirectory) && ~isfile(outputDirectory), ...
    'argo_native_probe:StaleOutput', 'Output must be a fresh directory');
[created, message] = mkdir(outputDirectory);
assert(created, 'argo_native_probe:OutputDirectory', '%s', message);
evidencePath = fullfile(outputDirectory, 'astra-generated-argo-evidence.json');
report = struct('schema_version', 1, 'scope', 'model_generated_argo_ts_native_trial_only', 'status', 'running', ...
    'phase', 'preflight', 'matlab_call_completed', false, ...
    'visual_verified', false, 'desktop_interaction_verified', false, ...
    'tooltip_fields_complete', false, 'native_data_status', 'not_run', ...
    'export_status', 'not_run', 'manifest_status', 'not_run', ...
    'complete_acceptance_verified', false, 'matlab_release', "R" + string(version('-release')), ...
    'jvm_available', logical(usejava('jvm')), ...
    'executed_source', source, 'input', input, 'provenance_file', provenanceRecord, ...
    'generation_provenance', provenance, 'original_generation_status', 'incomplete', ...
    'read_only_review_status', 'completed', 'execution_files', tracked, ...
    'ci_run_id', string(getenv('GITHUB_RUN_ID')), 'execution_commit', string(getenv('GITHUB_SHA')));
report.provenance_scope = 'hash_bound_recorded_generation_identifiers_not_model_architecture_attestation';
report.evidence_contract = 'argo-ts-native-v1';
report.consumer_status = 'not_integrated';
report.report_consumer_status = 'not_integrated';
report.upstream_authenticity = 'not_independently_verified';
report.requested_output = struct('pixels', pixelSize, 'page_inches', pageInches, 'dpi', dpi, ...
    'formats', ["png", "pdf", "svg"], 'additional_svg_request', 'coordinator_native_trial');
try
    addpath(helperDirectory, bundleDirectory, testsDirectory, '-begin');
    cd(outputDirectory);
    clear astra_argo_trial;
    rehash;
    functionNames = ["astra_argo_trial", helperNames, probeNames];
    functionPaths = [source.path, fullfile(helperDirectory, helperNames + ".m"), ...
        fullfile(testsDirectory, probeNames + ".m")];
    assert_paths(functionNames, functionPaths);
    executionPath = path;
    expected = read_argo_trial_input(input.path);
    identity = struct('figure_id', "astra-argo-trial", 'input_sha256', input.sha256, ...
        'input_bytes', input.bytes, 'source_sha256', source.sha256);
    report.phase = 'construction';
    fprintf('ASTRA_ARGO_TRIAL_BEGIN=%s\n', source.sha256);
    [figureHandle, result] = astra_argo_trial(input.path);
    report.matlab_call_completed = true;
    assert(isgraphics(figureHandle, 'figure') ...
        && ~any(previousFigures(isgraphics(previousFigures, 'figure')) == figureHandle), ...
        'argo_native_probe:FreshFigure', 'The source must return its own new live figure');
    assert(strcmp(path, executionPath) && strcmp(pwd, outputDirectory), ...
        'argo_native_probe:EnvironmentChanged', 'Generated code changed path or working directory');
    assert_paths(functionNames, functionPaths);
    assert_unchanged(tracked);
    drawnow;
    report.phase = 'native-before-export';
    view = feval(adapterName, result);
    before = read_argo_ts_native(figureHandle, view, expected, identity);
    assert_native_data(before);
    originalScatter = view.Helper.Scatter;
    originalAxes = view.Helper.Axes;
    report.native_before_export = before;
    report.native_data_status = 'passed_before_export';
    assert(string(figureHandle.Units) == "inches" ...
        && all(abs(figureHandle.Position(3:4) - pageInches) <= 1e-10), ...
        'argo_native_probe:PageContractPending', ...
        'Export contract must match the original model canvas; do not resize it in the driver');
    report.phase = 'export';
    entry = oi_export_figure(figureHandle, outputDirectory, 'astra-argo-trial', ...
        pixelSize(1), pixelSize(2), dpi, ...
        'Title', strjoin(before.title(:), ' '), 'Source', source.path, 'ExportSVG', true);
    report.exports = entry.exports;
    report.export_api = entry.runtime.export_api;
    report.export_runtime = entry.runtime;
    report.export_status = 'completed';
    report.svg_processing = 'repository_export_and_annotation_not_untouched_native_svg';
    report.phase = 'native-after-export';
    drawnow;
    afterView = feval(adapterName, result);
    assert(isequal(afterView.Helper.Axes, originalAxes) ...
        && isequal(afterView.Helper.Scatter, originalScatter), ...
        'argo_native_probe:ReplacedGraphics', 'Export must not substitute axes or Scatter handles');
    after = read_argo_ts_native(figureHandle, afterView, expected, identity);
    assert_native_data(after);
    report.native_after_export = after;
    assert(isequaln(before, after), 'argo_native_probe:ExportMutation', ...
        'Export changed captured source records, native arrays, masks, scale or layout');
    report.native_data_status = 'passed_before_and_after_export';
    [artifacts, artifactReadback] = verify_exports(outputDirectory, entry, pixelSize, pageInches, dpi);
    report.artifacts = artifacts;
    report.artifact_readback = artifactReadback;
    report.phase = 'manifest';
    entry.scientific_metadata = after.scientific_metadata;
    entry.scientific_data_contract = struct('plot_type', 'temperature-salinity-diagram', ...
        'schema_version', 1, 'evidence_contract', 'argo-ts-native-v1', ...
        'consumer_status', 'not_integrated', 'plot_data_evidence', after);
    manifestPath = fullfile(outputDirectory, 'figures.json');
    oi_write_manifest(manifestPath, entry);
    manifest = jsondecode(fileread(manifestPath));
    assert(numel(manifest.figures) == 1 && string(manifest.figures.id) == identity.figure_id ...
        && isequaln(manifest.figures.exports, jsondecode(jsonencode(entry.exports))) ...
        && string(manifest.figures.scientific_data_contract.consumer_status) == "not_integrated" ...
        && isequaln(manifest.figures.scientific_data_contract.plot_data_evidence, ...
        jsondecode(jsonencode(after))), 'argo_native_probe:ManifestBinding', ...
        'Manifest must bind these actual exports and the same independent Argo TS snapshot');
    report.manifest = file_record(manifestPath);
    report.manifest_status = 'passed';
    report.artifact_check_scope = 'actual_bytes_hash_PNG_header_PDF_signature_and_exporter_declarations';
    report.external_physical_check_status = 'pending';
    report.svg_full_xml_check_status = 'not_run_by_driver';
    report.external_font_glyph_visual_inspection = 'not_run';
    report.phase = 'final-integrity';
    finalView = feval(adapterName, result);
    assert(isequal(finalView.Helper.Axes, originalAxes) ...
        && isequal(finalView.Helper.Scatter, originalScatter), ...
        'argo_native_probe:ReplacedGraphics', 'Manifest creation must not substitute native handles');
    final = read_argo_ts_native(figureHandle, finalView, expected, identity);
    assert_native_data(final);
    assert(isequaln(before, final), 'argo_native_probe:ManifestMutation', ...
        'Manifest creation changed the bound TS snapshot');
    report.native_after_manifest = final;
    report.native_data_status = 'passed_before_and_after_export_and_manifest';
    assert_paths(functionNames, functionPaths);
    assert_unchanged([tracked; artifacts; report.manifest]);
    assert(strcmp(path, executionPath) && strcmp(pwd, outputDirectory), ...
        'argo_native_probe:EnvironmentChanged', 'Export or adapter changed execution environment');
    report.status = 'completed_bound_argo_ts_native_data_and_exports_only';
    report.phase = 'complete';
    report.tracked_files_unchanged = true;
    write_json(evidencePath, report);
    fprintf('ASTRA_ARGO_TRIAL_DATA=passed_argo_ts_native_v1_consumer_not_integrated\n');
    fprintf('ASTRA_ARGO_TRIAL=passed_bound_native_data_and_three_exports_only\n');
catch trialError
    report.status = 'failed';
    report.error_identifier = string(trialError.identifier);
    report.error_message = string(trialError.message);
    report.error_report = string(getReport(trialError, 'extended', 'hyperlinks', 'off'));
    try
        assert_unchanged(tracked);
        report.tracked_files_unchanged = true;
    catch integrityError
        report.tracked_files_unchanged = false;
        report.integrity_error = string(integrityError.message);
    end
    try
        write_json(evidencePath, report);
    catch evidenceError
        warning('argo_native_probe:FailureEvidence', ...
            'Cannot record the original trial failure: %s', evidenceError.message);
    end
    fprintf('ASTRA_ARGO_TRIAL_FAILED=%s:%s\n', report.phase, trialError.identifier);
    rethrow(trialError);
end
clear figureCleanup pathCleanup directoryCleanup;
end

function validate_provenance(provenance, tracked)
assert(numel(provenance.generation.turns) == 2, ...
    'argo_native_probe:ProvenanceStatus', 'Expected original generation and read-only review turns');
generationTurn = json_object_at(provenance.generation.turns, 1);
reviewTurn = json_object_at(provenance.generation.turns, 2);
assert(provenance.schema_version == 1 && isequal(provenance.generated_source_edited, false) ...
    && string(provenance.scope) ...
    == "isolated_builtin_codex_argo_candidate_incomplete_generation_and_completed_read_only_review" ...
    && string(provenance.generation.generation_status) == "incomplete" ...
    && string(provenance.generation.reason) == "turn_1_deadline_no_retry" ...
    && string(generationTurn.status) == "interrupted" ...
    && string(reviewTurn.status) == "completed" ...
    && string(provenance.review.status) == "completed" ...
    && provenance.review.artifacts_unchanged && provenance.review.original_rollout_prefix_preserved ...
    && string(provenance.matlab_execution_status) == "not_run" ...
    && ~provenance.visual_verified && ~provenance.native_interaction_verified ...
    && ~provenance.complete_report_verified && ~provenance.review.report_complete, ...
    'argo_native_probe:ProvenanceStatus', 'Do not turn interrupted generation or read-only review into a native pass');
assert(string(provenance.generation.thread_id) == "01a0747b-ae57-74e2-a5d1-1e23a7176d7d" ...
    && string(reviewTurn.id) == "01a07489-b34c-7e10-8d01-55a38eb5059f" ...
    && provenance.local_evidence.original_rollout.bytes == 848664 ...
    && provenance.local_evidence.resumed_rollout.bytes == 1345018 ...
    && string(provenance.local_evidence.resumed_rollout.sha256) ...
    == "e3c164e0fd9338e4aa50904a0d00bc414e91398c9b9f8412f523703c1df5d076", ...
    'argo_native_probe:GenerationOrigin', 'Expected the coordinator-pinned original thread and read-only review');
declarations = {provenance.source, provenance.input, provenance.report, ...
    json_object_at(provenance.prompts, 1), json_object_at(provenance.prompts, 2)};
recordIndices = [1 2 4 5 6];
for declarationIndex = 1:numel(declarations)
    declared = declarations{declarationIndex};
    actual = tracked(recordIndices(declarationIndex));
    assert(string(declared.file) == actual.file && declared.bytes == actual.bytes ...
        && strcmpi(declared.sha256, actual.sha256), ...
        'argo_native_probe:ProvenanceBinding', 'Archived source/input/report/prompt differs from provenance');
end
assert(~provenance.input.synthetic && provenance.input.layer_count == 1785 ...
    && provenance.input.profile_count == 3 && string(provenance.input.pressure_unit) == "decibar" ...
    && string(provenance.input.upstream_authenticity) == "not_independently_verified" ...
    && isequal(provenance.observed_output_contract.page_inches(:).', [8 5]) ...
    && isequal(provenance.observed_output_contract.planned_pixels(:).', [2400 1500]) ...
    && provenance.observed_output_contract.planned_dpi == 300, ...
    'argo_native_probe:ScientificContract', 'Preserve original Argo scope, pressure units and 8-by-5 canvas');
end

function value = json_object_at(values, index)
if iscell(values)
    value = values{index};
else
    value = values(index);
end
assert(isstruct(value) && isscalar(value), ...
    'argo_native_probe:ProvenanceShape', 'Expected a decoded provenance object');
end

function assert_native_data(snapshot)
assert(snapshot.schema_version == 1 && string(snapshot.evidence_contract) == "argo-ts-native-v1" ...
    && string(snapshot.plot_type) == "temperature-salinity-diagram" ...
    && isequal(snapshot.shape, {1785}) ...
    && isequal(snapshot.dimension_order, {"source_record"}) ...
    && strcmp(jsonencode(snapshot.shape), '[1785]') ...
    && strcmp(jsonencode(snapshot.dimension_order), '["source_record"]') ...
    && string(snapshot.consumer_status) == "not_integrated" ...
    && isequal(snapshot.profile_counts, [595; 596; 594]) ...
    && isequal(snapshot.records.SourceFileRow, (1:1785).') ...
    && numel(snapshot.records.ObservationID) == 1785 ...
    && size(snapshot.raw_values, 1) == 1785 && size(snapshot.raw_values, 2) == 6 ...
    && numel(snapshot.scatter_groups) == 3 && sum(snapshot.complete_mask) == 1785 ...
    && ~snapshot.comparison_v3_consumer_compatible ...
    && ~snapshot.visual_verified && ~snapshot.desktop_interaction_verified ...
    && ~isfield(snapshot, 'pairing') && ~isfield(snapshot, 'paired_stats'), ...
    'argo_native_probe:NativeData', 'Expected complete independent Argo TS evidence, not comparison-v3');
wire = jsondecode(jsonencode(snapshot));
assert(isequal(wire.shape, 1785) && isequal(string(wire.dimension_order), "source_record") ...
    && numel(wire.records.ObservationID) == 1785 && numel(wire.records.Time) == 1785 ...
    && numel(wire.records.pressure_argoqc) == 1785 ...
    && numel(wire.records.temperature_argoqc) == 1785 && numel(wire.records.salinity_argoqc) == 1785 ...
    && numel(wire.scatter_groups) == 3 && strcmp(wire.raw_json_text, char(snapshot.raw_json_text)), ...
    'argo_native_probe:JSONRoundTrip', 'Argo TS serialization must retain dimensions, every record and original JSON');
end

function [artifacts, actual] = verify_exports(directory, entry, pixels, inches, dpi)
formats = ["png", "pdf", "svg"];
assert(isequal(sort(string(fieldnames(entry.exports))), sort(formats(:))), ...
    'argo_native_probe:Formats', 'Exactly PNG/PDF/SVG must be produced by the same figure');
artifacts = repmat(file_record(fullfile(directory, entry.exports.png.file)), 0, 1);
for formatIndex = 1:numel(formats)
    format = formats(formatIndex);
    declared = entry.exports.(format);
    assert(string(declared.file) == string(entry.id) + "." + format, ...
        'argo_native_probe:ExportPath', 'Unexpected artifact filename');
    artifact = file_record(fullfile(directory, declared.file));
    assert(strcmpi(declared.sha256, artifact.sha256) && declared.bytes == artifact.bytes ...
        && string(declared.export_api) == string(entry.runtime.export_api.(format)), ...
        'argo_native_probe:ArtifactBinding', 'Actual artifact bytes/hash/API differs from the export declaration');
    artifacts(end + 1, 1) = artifact; %#ok<AGROW>
end
png = imfinfo(artifacts(1).path);
assert(isequal([png.Width png.Height], pixels) && entry.exports.png.dpi == dpi ...
    && entry.exports.pdf.pages == 1 ...
    && all(abs([entry.exports.pdf.width entry.exports.pdf.height] - inches * 72) <= 1) ...
    && isequal([entry.exports.svg.width entry.exports.svg.height], pixels), ...
    'argo_native_probe:Dimensions', 'Original 8-by-5-inch page and 2400-by-1500 output must be retained');
pdfPrefix = oi_read_file_prefix(artifacts(2).path, 5);
assert(isequal(pdfPrefix(:).', uint8('%PDF-')), ...
    'argo_native_probe:PDFSignature', 'Expected actual PDF bytes; this is not a page geometry check');
actual = struct('png_pixels', [png.Width png.Height], ...
    'png_dpi_declared', entry.exports.png.dpi, 'pdf_signature', '%PDF-', ...
    'pdf_points_declared_by_exporter', [entry.exports.pdf.width entry.exports.pdf.height], ...
    'pdf_pages_declared_by_exporter', entry.exports.pdf.pages, ...
    'svg_pixels_declared_by_exporter', [entry.exports.svg.width entry.exports.svg.height], ...
    'svg_full_xml_check_status', 'not_run_by_driver', ...
    'external_physical_check_status', 'pending');
end

function record = pinned_file(filePath, expectedHash)
assert((ischar(expectedHash) || (isstring(expectedHash) && isscalar(expectedHash))) ...
    && ~isempty(regexp(char(expectedHash), '^[0-9a-fA-F]{64}$', 'once')), ...
    'argo_native_probe:PinPending', 'Expected SHA-256 must come from the real frozen bundle');
record = file_record(filePath);
assert(strcmpi(record.sha256, expectedHash), ...
    'argo_native_probe:HashMismatch', 'Frozen bytes differ: %s', record.path);
end

function record = file_record(filePath)
filePath = canonical_path(filePath);
info = dir(filePath);
assert(isscalar(info) && ~info.isdir && info.bytes > 0, ...
    'argo_native_probe:File', 'Expected a nonempty original file: %s', filePath);
digest = string(oi_sha256_file(filePath));
[~, name, extension] = fileparts(filePath);
record = struct('path', filePath, 'file', name + extension, 'bytes', info.bytes, 'sha256', string(digest));
end

function resolved = canonical_path(filePath)
[found, attributes] = fileattrib(char(filePath));
assert(found, 'argo_native_probe:MissingPath', 'Missing path: %s', filePath);
resolved = string(attributes.Name);
if usejava('jvm')
    resolved = string(char(java.io.File(char(resolved)).getCanonicalPath()));
end
end

function assert_paths(names, expectedPaths)
for functionIndex = 1:numel(names)
    actual = string(which(names(functionIndex)));
    assert(strlength(actual) > 0 && canonical_path(actual) == canonical_path(expectedPaths(functionIndex)), ...
        'argo_native_probe:ShadowedFunction', 'Wrong function resolution: %s', names(functionIndex));
end
end

function assert_unchanged(records)
for recordIndex = 1:numel(records)
    actual = file_record(records(recordIndex).path);
    assert(isequal(actual, records(recordIndex)), ...
        'argo_native_probe:ChangedFile', 'Tracked source/input/helper changed: %s', actual.path);
end
end

function write_json(filePath, value)
fileHandle = fopen(filePath, 'w', 'n', 'UTF-8');
assert(fileHandle >= 0, 'argo_native_probe:EvidenceWrite', 'Cannot write diagnostic evidence');
cleanup = onCleanup(@() fclose(fileHandle));
fprintf(fileHandle, '%s\n', jsonencode(value));
end

function close_new_figures(previousFigures)
previousFigures = previousFigures(isgraphics(previousFigures, 'figure'));
figures = findall(groot, 'Type', 'figure');
for figureIndex = 1:numel(figures)
    if isgraphics(figures(figureIndex), 'figure') && ~any(previousFigures == figures(figureIndex))
        delete(figures(figureIndex));
    end
end
end
