function artifacts = test_time_series_runtime(outputDirectory)
%TEST_TIME_SERIES_RUNTIME Exercise datetime, gaps, uncertainty, CJK, and export.
arguments
    outputDirectory (1,1) string = string(tempname)
end
assert(~verLessThan("matlab","9.10"), ...
    "test_time_series_runtime:UnsupportedRelease", ...
    "This runtime test requires MATLAB R2021a or newer");
assert(strlength(strtrim(outputDirectory)) > 0, ...
    "test_time_series_runtime:OutputDirectory", ...
    "outputDirectory must be explicit nonblank text");

testDirectory = fileparts(mfilename("fullpath"));
assetDirectory = fullfile(testDirectory,"..","assets");
addpath(assetDirectory);
if ~isfolder(outputDirectory)
    mkdir(outputDirectory);
end

theme = oi_ocean_theme();
figureHandle = oi_figure(1200,675,"off");
cleanupFigure = onCleanup(@() close_if_valid(figureHandle));
layout = tiledlayout(figureHandle,1,1,"TileSpacing","compact","Padding","compact");
axesHandle = nexttile(layout);
cjkStation = unicode_text([19996 28023 28014 26631 19968 21495]);
cjkValueLabel = unicode_text([28023 28201]);
cjkTimeLabel = unicode_text([26102 38388]);
cjkTitle = unicode_text([19996 28023 28023 28201 26102 38388 24207 21015]);

observationTime = datetime(2026,9,1,[0 1 2 7 8 9],0,0,"TimeZone","UTC")';
temperature = [10;NaN;12;13;14;15];
uncertainty = [0.2;NaN;NaN;0.3;0.2;0.2];
quality = ["good";"good";"good";"good";"suspect";"good"];
station = repmat(cjkStation,numel(observationTime),1);
series = timetable(observationTime,temperature,uncertainty,quality,station, ...
    'VariableNames',{'Temperature','TemperatureUncertainty','QC','Station'});
series.Properties.VariableUnits = {'degC','degC','1','1'};

result = oi_plot_time_series(axesHandle,series,struct( ...
    "ValueVariables","Temperature", ...
    "ValueLabels",cjkValueLabel, ...
    "QCVariables","QC", ...
    "AcceptedQCValues","good", ...
    "QCPolicy","mark", ...
    "UncertaintyVariables","TemperatureUncertainty", ...
    "UncertaintyType","instrument-accuracy", ...
    "UncertaintyUnits","degC", ...
    "GapThreshold",hours(2), ...
    "DisplayTimeZone","Asia/Shanghai", ...
    "SampleLabelVariable","Station", ...
    "TimeLabel",cjkTimeLabel, ...
    "Title",cjkTitle, ...
    "LegendLocation","northeast", ...
    "Theme",theme));

assert(result.SourceTimeZone == "UTC" ...
    && result.DisplayTimeZone == "Asia/Shanghai" ...
    && hour(result.RowTimes(1)) == 8, ...
    "test_time_series_runtime:TimeZone", ...
    "Time-zone conversion did not preserve the source instant");
assert(result.ValidCount == 4 && result.MissingCount == 1 ...
    && result.UncertaintyMissingCount == 1 ...
    && result.QCRejectedCount == 1 && result.GapCount == 1, ...
    "test_time_series_runtime:Masks", ...
    "Missing, uncertainty, QC, or gap masks are incorrect");
assert(result.ValidMask(3) && result.UncertaintyMissingMask(3), ...
    "test_time_series_runtime:UncertaintyIsolation", ...
    "Missing uncertainty must not remove an otherwise valid observation");
assert(string(axesHandle.FontName) == theme.FontName ...
    && string(axesHandle.Title.String) == cjkTitle, ...
    "test_time_series_runtime:CJK", ...
    "The selected font or Chinese title was not preserved");
test_standard_uncertainty(series,theme);

drawnow;
pngPath = fullfile(outputDirectory,"time-series-runtime.png");
pdfPath = fullfile(outputDirectory,"time-series-runtime.pdf");
exportgraphics(figureHandle,pngPath,"Resolution",180,"BackgroundColor","white");
exportgraphics(figureHandle,pdfPath,"ContentType","vector","BackgroundColor","white");
assert(isfile(pngPath) && file_size(pngPath) > 0, ...
    "test_time_series_runtime:PNG", "Headless PNG export failed");
assert(isfile(pdfPath) && file_size(pdfPath) > 0, ...
    "test_time_series_runtime:PDF", "Headless PDF export failed");

artifacts = struct("PNG",string(pngPath),"PDF",string(pdfPath), ...
    "MATLABRelease",string(version('-release')), ...
    "FontName",string(theme.FontName),"CJKFontCapable",theme.CJKFontCapable, ...
    "Result",result);
fprintf("TIME_SERIES_RUNTIME=passed\n");
fprintf("TIME_SERIES_PNG=%s\n",pngPath);
fprintf("TIME_SERIES_PDF=%s\n",pdfPath);
clear cleanupFigure;
end

function test_standard_uncertainty(series,theme)
figureHandle = figure("Visible","off");
cleanupFigure = onCleanup(@() close_if_valid(figureHandle));
axesHandle = axes(figureHandle);
options = struct("ValueVariables","Temperature", ...
    "QCVariables","QC","AcceptedQCValues","good","QCPolicy","mark", ...
    "UncertaintyVariables","TemperatureUncertainty", ...
    "UncertaintyUnits","degC","GapThreshold",hours(2),"Theme",theme);
for typeInput = ["standard-uncertainty" "standard_uncertainty" "standard-deviation"]
    cla(axesHandle);
    options.UncertaintyType = typeInput;
    result = oi_plot_time_series(axesHandle,series,options);
    assert(result.UncertaintyType == replace(typeInput,"_","-") ...
        && result.UncertaintyUnit == "degC" && isnan(result.ConfidenceLevel) ...
        && result.ValidCount == 4 && result.MissingCount == 1 ...
        && result.UncertaintyMissingCount == 1 && result.QCRejectedCount == 1 ...
        && result.GapCount == 1 ...
        && result.ValidMask(3) && result.UncertaintyMissingMask(3) ...
        && isequaln(result.Lines(1).YData(:),[10;NaN;12;NaN;13;NaN;15]), ...
        "test_time_series_runtime:StandardUncertainty", ...
        "Declared uncertainty semantics, values, units, and missing/QC/gap masks must be preserved");
    graphics = result.UncertaintyGraphics{1};
    sourceRows = [1 4 6];
    assert(numel(graphics) == numel(sourceRows), ...
        "test_time_series_runtime:UncertaintySegments", ...
        "Uncertainty bands must retain breaks at missing, rejected, and gap samples");
    for segmentIndex = 1:numel(sourceRows)
        sourceRow = sourceRows(segmentIndex);
        expectedBounds = series.Temperature(sourceRow) ...
            + [-1;1] * series.TemperatureUncertainty(sourceRow);
        assert(all(abs(graphics(segmentIndex).YData(:) - expectedBounds) < 1e-12), ...
            "test_time_series_runtime:UncertaintyMagnitude", ...
            "Standard uncertainty must be plotted at its supplied magnitude without rescaling");
    end
end
for unknownType = ["variance" "std" "standard uncertainty"]
    options.UncertaintyType = unknownType;
    assert_time_series_error(@() oi_plot_time_series(axesHandle,series,options), ...
        "oi_plot_time_series:UncertaintyType");
end
options.UncertaintyType = "standard-uncertainty";
options.ConfidenceLevel = 0.95;
assert_time_series_error(@() oi_plot_time_series(axesHandle,series,options), ...
    "oi_plot_time_series:ConfidenceLevel");
options.UncertaintyType = "confidence_interval";
cla(axesHandle);
confidenceResult = oi_plot_time_series(axesHandle,series,options);
assert(confidenceResult.UncertaintyType == "confidence-interval" ...
    && confidenceResult.ConfidenceLevel == 0.95, ...
    "test_time_series_runtime:ConfidenceInterval", ...
    "Explicit confidence intervals must keep their required confidence level");
for invalidLevel = [NaN 0 1 Inf]
    options.ConfidenceLevel = invalidLevel;
    assert_time_series_error(@() oi_plot_time_series(axesHandle,series,options), ...
        "oi_plot_time_series:ConfidenceLevel");
end
options.UncertaintyType = "standard-uncertainty";
options.ConfidenceLevel = NaN;
options.UncertaintyUnits = "K";
assert_time_series_error(@() oi_plot_time_series(axesHandle,series,options), ...
    "oi_plot_time_series:UncertaintyUnit");
options.UncertaintyUnits = "degC";
invalidSeries = series;
invalidSeries.TemperatureUncertainty(2) = 0.1;
assert_time_series_error(@() oi_plot_time_series(axesHandle,invalidSeries,options), ...
    "oi_plot_time_series:UncertaintyValues");
clear cleanupFigure;
end

function assert_time_series_error(callback, expectedIdentifier)
try
    callback();
catch exception
    assert(string(exception.identifier) == expectedIdentifier, ...
        "test_time_series_runtime:UnexpectedError", ...
        "Unexpected error: %s", exception.message);
    return;
end
error("test_time_series_runtime:MissingError", ...
    "Expected uncertainty validation to reject: %s", expectedIdentifier);
end

function text = unicode_text(codePoints)
text = string(char(codePoints));
end

function bytes = file_size(path)
fileInfo = dir(path);
assert(isscalar(fileInfo),"test_time_series_runtime:Artifact", ...
    "Expected exactly one exported artifact");
bytes = fileInfo.bytes;
end

function close_if_valid(figureHandle)
if isgraphics(figureHandle)
    close(figureHandle);
end
end
