function entry = test_comparison_uncertainty(outputRoot)
if nargin == 0
    outputRoot = string(tempname);
    mkdir(outputRoot);
end
outputRoot = string(outputRoot);
assert(isfolder(outputRoot), "test_comparison_uncertainty:MissingRoot", ...
    "Output root must already exist");
outputDirectory = fullfile(outputRoot, "comparison-uncertainty");
assert(~isfolder(outputDirectory) && ~isfile(outputDirectory), ...
    "test_comparison_uncertainty:Reuse", "Uncertainty artifacts must use a fresh directory");
mkdir(outputDirectory);
addpath(fullfile(fileparts(mfilename("fullpath")), "..", "assets"));
theme = oi_ocean_theme();
[observations, models, options] = synthetic_inputs(theme);
originalObservations = observations;
originalModels = models;

[~, baselineAxes, baselineCleanup] = make_axes();
baselineOptions = rmfield(options, {'UncertaintySides', 'UncertaintyType', ...
    'UncertaintyUnit', 'ObservationUncertaintyVariable'});
baseline = oi_plot_comparison(baselineAxes, observations, models, baselineOptions);

[figureHandle, axesHandle, figureCleanup] = make_axes();
result = oi_plot_comparison(axesHandle, observations, models, options);
assert_observation_case(result, baseline, observations, models);
test_qc_policy(observations, models, options);
test_missing_and_zero_uncertainty(theme);
test_default_both(theme);
test_negative_contracts(theme);
assert(isequaln(observations, originalObservations) && isequaln(models, originalModels), ...
    "test_comparison_uncertainty:InputMutation", "Tests must preserve every source row");

entry = oi_export_figure(figureHandle, outputDirectory, "synthetic-observation-uncertainty", ...
    2400, 1500, 300, "Title", options.Title, ...
    "Source", "synthetic observation-only uncertainty regression; not ocean observations", ...
    "Theme", theme.Name, "ExportSVG", true);
assert_observation_case(result, baseline, observations, models);
nativeLines = read_lines(result.UncertaintyGraphics);
entry.comparison_uncertainty_evidence = struct( ...
    "schema_version", 1, "data_source", "synthetic benchmark, not observed ocean conditions", ...
    "native_array_assertions_passed", true, "visual_inspection_verified", false, ...
    "observation_keys", observations.Key, "observation_values", observations.Observation, ...
    "observation_uncertainty", observations.Uncertainty, "observation_qc", observations.QC, ...
    "model_keys", models.Key, "model_values", models.Model, "model_qc", models.QC, ...
    "observation_pair_indices", result.ObservationPairIndices, ...
    "model_pair_indices", result.ModelPairIndices, "paired_mask", result.PairedMask, ...
    "finite_pair_mask", result.FinitePairMask, "qc_accepted_mask", result.QCAcceptedMask, ...
    "metrics", result.Metrics, "native_scatter_x", double(result.Scatter.XData(:)), ...
    "native_scatter_y", double(result.Scatter.YData(:)), ...
    "native_uncertainty_lines", nativeLines, "uncertainty_type", result.UncertaintyType, ...
    "uncertainty_unit", result.UncertaintyUnit, "uncertainty_metadata", result.Uncertainty, ...
    "native_legend_title", string(result.Legend.Title.String), ...
    "native_legend_title_class", string(class(result.Legend.Title)), ...
    "native_text", visible_text(axesHandle));
manifestPath = fullfile(outputDirectory, "figures.json");
oi_write_manifest(manifestPath, entry);
decoded = jsondecode(fileread(manifestPath));
assert(decoded.figures.comparison_uncertainty_evidence.native_array_assertions_passed ...
    && ~decoded.figures.comparison_uncertainty_evidence.visual_inspection_verified, ...
    "test_comparison_uncertainty:Manifest", "Manifest must retain scoped native evidence");
for format = ["png" "pdf" "svg"]
    record = decoded.figures.exports.(format);
    artifactPath = fullfile(outputDirectory, string(record.file));
    information = dir(artifactPath);
    assert(~isempty(information) && information.bytes == record.bytes ...
        && strcmpi(oi_sha256_file(artifactPath), record.sha256), ...
        "test_comparison_uncertainty:ArtifactBinding", "Artifact bytes and hash must match the manifest");
end
assert(~entry.rendering_evidence.visual_inspection_verified ...
    && ~entry.rendering_evidence.pdf_font_embedding_verified, ...
    "test_comparison_uncertainty:VerificationScope", "Array assertions are not visual or font verification");
clear figureCleanup baselineCleanup;
fprintf("MATLAB_COMPARISON_UNCERTAINTY_NATIVE_ASSERTIONS=passed\n");
fprintf("MATLAB_COMPARISON_UNCERTAINTY_VISUAL_VERIFIED=false\n");
fprintf("MATLAB_COMPARISON_UNCERTAINTY_MANIFEST=%s\n", manifestPath);
end

function [observations, models, options] = synthetic_inputs(theme)
observations = table(["C"; "A"; "B"; "D"; "E"; "F"; "G"], ...
    [3; 1; 2; 4; 5; NaN; 99], [4; 2; NaN; 100; 50; NaN; 0.4], ...
    ["good"; "good"; "suspect"; "good"; "bad"; "good"; "good"], ...
    'VariableNames', {'Key', 'Observation', 'Uncertainty', 'QC'});
models = table(["E"; "B"; "D"; "A"; "F"; "C"; "H"], ...
    [5.5; 2.5; NaN; 1.5; 6.5; 3.5; 100], repmat("good", 7, 1), ...
    'VariableNames', {'Key', 'Model', 'QC'});
observations.Properties.VariableUnits = ["1" "degC" "degC" "1"];
models.Properties.VariableUnits = ["1" "degC" "1"];
options = struct("PairingRule", "inner-key", "PairKeys", "Key", ...
    "ObservationVariable", "Observation", "ModelVariable", "Model", ...
    "ObservationQCVariable", "QC", "ModelQCVariable", "QC", ...
    "AcceptedQCValues", ["good" "suspect"], "SampleLabelVariable", "Key", ...
    "ObservationUncertaintyVariable", "Uncertainty", "UncertaintySides", "observation", ...
    "UncertaintyType", "standard-uncertainty", "UncertaintyUnit", "degC", ...
    "QuantityUnit", "degC", "Theme", theme, ...
    "Title", "Synthetic observation-only uncertainty");
end

function assert_observation_case(result, baseline, observations, models)
assert(isequal(result.ObservationPairIndices, (1:6)') ...
    && isequal(result.ModelPairIndices, [6; 4; 2; 3; 1; 5]), ...
    "test_comparison_uncertainty:PairOrder", "Inner-key pairing must preserve observation row order");
assert(isequal(result.FinitePairMask, logical([1; 1; 1; 0; 1; 0])) ...
    && isequal(result.QCAcceptedMask, logical([1; 1; 1; 1; 0; 1])) ...
    && isequal(result.PairedMask, logical([1; 1; 1; 0; 0; 0])) ...
    && result.ValidCount == 3 && result.MissingCount == 2 && result.QCRejectedCount == 1 ...
    && result.UnmatchedObservationCount == 1 && result.UnmatchedModelCount == 1, ...
    "test_comparison_uncertainty:Masks", "Missing uncertainty must not remove a finite accepted pair");
assert(isequaln(result.Metrics, baseline.Metrics) ...
    && isequaln(result.StratifiedMetrics, baseline.StratifiedMetrics) ...
    && isequal(result.PairedMask, baseline.PairedMask), ...
    "test_comparison_uncertainty:Statistics", "Observation uncertainty cannot change pair statistics");
assert(result.Metrics.PairedCount == 3 && result.Metrics.Bias == 0.5 ...
    && result.Metrics.MAE == 0.5 && abs(result.Metrics.RMSE - 0.5) <= eps(0.5), ...
    "test_comparison_uncertainty:ExpectedMetrics", "Synthetic residual statistics must match their inputs");
assert(numel(result.Scatter) == 1 && isgraphics(result.Scatter, "scatter") ...
    && isequal(result.Scatter.Parent, result.Axes) && string(result.Scatter.Visible) == "on" ...
    && isequaln(double(result.Scatter.XData(:)), [3; 1; 2]) ...
    && isequaln(double(result.Scatter.YData(:)), [3.5; 1.5; 2.5]), ...
    "test_comparison_uncertainty:NativeScatter", "Native scatter must retain the missing-U and suspect pair");
assert(string(result.UncertaintyType) == "standard-uncertainty" ...
    && string(result.UncertaintyUnit) == "degC" && isnan(result.ConfidenceLevel), ...
    "test_comparison_uncertainty:Definition", "Standard uncertainty is not SD, SEM or a confidence interval");
assert_observation_metadata(result, observations.Uncertainty(1:6), logical([1; 1; 0; 0; 0; 0]));
assert_horizontal_lines(result, [-1 7; -1 3], [3.5; 1.5]);
assert_limits(result, [-1; 7]);
assert(result.Limits(1) > -2 && result.Limits(2) < 8, ...
    "test_comparison_uncertainty:UnplottedLimits", "Unmatched, missing-model and rejected-QC U must not set limits");
assert(observations.Uncertainty(4) == 100 && isnan(models.Model(3)), ...
    "test_comparison_uncertainty:MissingModelInput", "The missing-model row must retain real observation U");
end

function assert_observation_metadata(result, expectedValues, expectedMask)
metadata = result.Uncertainty;
assert(string(metadata.Sides) == "observation" ...
    && string(metadata.Observation.Status) == "provided" ...
    && isequaln(metadata.Observation.Values, expectedValues) ...
    && string(metadata.Model.Status) == "not_provided" ...
    && isequal(fieldnames(metadata.Model), {'Status'}) ...
    && string(metadata.Representation) == "magnitude" ...
    && string(metadata.Display) == "horizontal-line-segments" ...
    && islogical(metadata.GraphicsMask) && isequal(metadata.GraphicsMask, expectedMask), ...
    "test_comparison_uncertainty:Metadata", ...
    "Result must retain observation U on missing-model rows and never fabricate model magnitudes");
titleHandle = result.Legend.Title;
titleLines = string(titleHandle.String);
assert(isgraphics(titleHandle) && string(result.Legend.Visible) == "on" ...
    && string(titleHandle.Visible) == "on" ...
    && isequal(titleLines(:), ...
        ["Horizontal: observation standard uncertainty (degC)"; "Model uncertainty not provided"]) ...
    && string(titleHandle.Interpreter) == "none", ...
    "test_comparison_uncertainty:NativeExplanation", ...
    "The native legend title must explicitly distinguish observed standard uncertainty from absent model U");
end

function assert_horizontal_lines(result, expectedX, expectedY)
handles = result.UncertaintyGraphics;
assert(numel(handles) == size(expectedX, 1) && all(isgraphics(handles(:), "line")), ...
    "test_comparison_uncertainty:NativeLines", "Observation uncertainty must use one native Line per segment");
assert(isempty(findall(result.Axes, "Type", "errorbar")) ...
    && numel(findall(result.Axes, "Type", "line")) == numel(handles) + 1, ...
    "test_comparison_uncertainty:NoVerticalError", "No ErrorBar, vertical segment or fake model-U line is allowed");
for segmentIndex = 1:numel(handles)
    assert(isequal(handles(segmentIndex).Parent, result.Axes) ...
        && string(handles(segmentIndex).Visible) == "on" ...
        && isequaln(double(handles(segmentIndex).XData(:)), expectedX(segmentIndex, :)') ...
        && isequaln(double(handles(segmentIndex).YData(:)), repmat(expectedY(segmentIndex), 2, 1)), ...
        "test_comparison_uncertainty:LineCoordinates", "Every native horizontal endpoint must match input U");
end
end

function assert_limits(result, endpoints)
assert(isequaln(double(result.Axes.XLim), result.Limits) ...
    && isequaln(double(result.Axes.YLim), result.Limits) ...
    && result.Limits(1) <= min(endpoints) && result.Limits(2) >= max(endpoints) ...
    && isequaln(double(result.OneToOne.XData), result.Limits) ...
    && isequaln(double(result.OneToOne.YData), result.Limits), ...
    "test_comparison_uncertainty:Limits", "Both native rulers and reference must include true error endpoints");
end

function test_qc_policy(observations, models, options)
options.AcceptedQCValues = "good";
[~, axesHandle, cleanup] = make_axes();
result = oi_plot_comparison(axesHandle, observations, models, options);
assert(result.ValidCount == 2 && result.QCRejectedCount == 2 ...
    && isequal(result.PairedMask, logical([1; 1; 0; 0; 0; 0])) ...
    && isequaln(double(result.Scatter.XData(:)), [3; 1]) ...
    && isequaln(double(result.Scatter.YData(:)), [3.5; 1.5]), ...
    "test_comparison_uncertainty:QCPolicy", "Only the explicit QC acceptance policy may reject suspect");
assert_horizontal_lines(result, [-1 7; -1 3], [3.5; 1.5]);
assert_observation_metadata(result, observations.Uncertainty(1:6), logical([1; 1; 0; 0; 0; 0]));
clear cleanup;
options.AcceptedQCValues = ["good" "suspect"];
models.QC(6) = "bad";
[~, axesHandle, modelCleanup] = make_axes();
result = oi_plot_comparison(axesHandle, observations, models, options);
assert(result.ValidCount == 2 && result.QCRejectedCount == 2 ...
    && isequal(result.PairedMask, logical([0; 1; 1; 0; 0; 0])) ...
    && isequaln(double(result.Scatter.XData(:)), [1; 2]) ...
    && isequaln(double(result.Scatter.YData(:)), [1.5; 2.5]), ...
    "test_comparison_uncertainty:ModelQC", "Explicit model QC must also control scatter and error segments");
assert_horizontal_lines(result, [-1 3], 1.5);
assert_observation_metadata(result, observations.Uncertainty(1:6), logical([0; 1; 0; 0; 0; 0]));
clear modelCleanup;
end

function test_missing_and_zero_uncertainty(theme)
options = struct("QuantityUnit", "degC", "Theme", theme, ...
    "ObservationUncertainty", [0; NaN; 0.5], "UncertaintySides", "observation", ...
    "UncertaintyType", "standard-uncertainty", "UncertaintyUnit", "degC");
[~, axesHandle, cleanup] = make_axes();
result = oi_plot_comparison(axesHandle, [1; 2; 3], [1.5; 2.5; 3.5], options);
assert(result.ValidCount == 3 && isequal(result.PairedMask, true(3, 1)) ...
    && isequaln(double(result.Scatter.XData(:)), [1; 2; 3]) ...
    && isequaln(double(result.Scatter.YData(:)), [1.5; 2.5; 3.5]), ...
    "test_comparison_uncertainty:MissingU", "NaN U means missing U, not a missing observation-model pair");
assert_horizontal_lines(result, [1 1; 2.5 3.5], [1.5; 3.5]);
assert_observation_metadata(result, [0; NaN; 0.5], logical([1; 0; 1]));
[~, missingAxes, missingCleanup] = make_axes();
options.ObservationUncertainty = NaN(3, 1);
missing = oi_plot_comparison(missingAxes, [1; 2; 3], [1.5; 2.5; 3.5], options);
assert(isequaln(missing.Metrics, result.Metrics) && isequal(missing.PairedMask, result.PairedMask), ...
    "test_comparison_uncertainty:AllMissingU", "Even all-missing observation U must leave finite pair statistics intact");
assert_horizontal_lines(missing, zeros(0, 2), zeros(0, 1));
assert_observation_metadata(missing, NaN(3, 1), false(3, 1));
clear missingCleanup cleanup;
end

function test_default_both(theme)
observations = [1; 2; 3; NaN];
models = [1.5; 2.5; 3.5; 4.5];
options = struct("QuantityUnit", "degC", "Theme", theme, ...
    "ObservationUncertainty", [0.25; NaN; 0.5; NaN], ...
    "ModelUncertainty", [0.75; 0.1; 1; NaN], ...
    "UncertaintyType", "standard-deviation", "UncertaintyUnit", "degC");
[~, axesHandle, cleanup] = make_axes();
result = oi_plot_comparison(axesHandle, observations, models, options);
assert(result.ValidCount == 2 && result.MissingCount == 1 ...
    && isequal(result.PairedMask, logical([1; 0; 1; 0])) ...
    && isequaln(double(result.Scatter.XData(:)), [1; 3]) ...
    && isequaln(double(result.Scatter.YData(:)), [1.5; 3.5]), ...
    "test_comparison_uncertainty:DefaultBoth", "Default both must retain complete-uncertainty pair exclusion");
expectedX = [0.75 1.25; 1 1; 2.5 3.5; 3 3];
expectedY = [1.5 1.5; 0.75 2.25; 3.5 3.5; 2.5 4.5];
lines = read_lines(result.UncertaintyGraphics);
assert(isequaln(lines.x, expectedX) && isequaln(lines.y, expectedY) ...
    && isempty(findall(axesHandle, "Type", "errorbar")) ...
    && numel(findall(axesHandle, "Type", "line")) == 5, ...
    "test_comparison_uncertainty:BothCoordinates", "Both-sided native lines must retain horizontal and vertical U");
assert_limits(result, [0.75; 4.5]);
assert(string(result.Uncertainty.Sides) == "both" ...
    && string(result.Uncertainty.Observation.Status) == "provided" ...
    && string(result.Uncertainty.Model.Status) == "provided" ...
    && isequaln(result.Uncertainty.Observation.Values, options.ObservationUncertainty) ...
    && isequaln(result.Uncertainty.Model.Values, options.ModelUncertainty) ...
    && string(result.Uncertainty.Representation) == "magnitude" ...
    && string(result.Uncertainty.Display) == "horizontal-and-vertical-line-segments" ...
    && isequal(result.Uncertainty.GraphicsMask, result.PairedMask), ...
    "test_comparison_uncertainty:BothMetadata", "Default both must retain both measured U arrays");
assert(~contains(strjoin(string(result.Legend.Title.String), " "), "not provided"), ...
    "test_comparison_uncertainty:BothExplanation", "Both-provided uncertainty must not claim the model side is absent");
[~, explicitAxes, explicitCleanup] = make_axes();
options.UncertaintySides = "both";
explicit = oi_plot_comparison(explicitAxes, observations, models, options);
assert(isequaln(explicit.Metrics, result.Metrics) ...
    && isequal(explicit.PairedMask, result.PairedMask) ...
    && isequaln(read_lines(explicit.UncertaintyGraphics), lines), ...
    "test_comparison_uncertainty:ExplicitBoth", "Explicit both must equal the old default");
clear explicitCleanup cleanup;
end

function test_negative_contracts(theme)
[~, axesHandle, cleanup] = make_axes();
options = struct("QuantityUnit", "degC", "Theme", theme, ...
    "ObservationUncertainty", [0.25; 0.5; 0.75], "UncertaintySides", "observation", ...
    "UncertaintyType", "standard-uncertainty", "UncertaintyUnit", "degC");
for invalidValue = [Inf -Inf -1]
    invalid = options;
    invalid.ObservationUncertainty(2) = invalidValue;
    must_throw(@() oi_plot_comparison(axesHandle, [1; 2; 3], [1.5; 2.5; 3.5], invalid), ...
        "UncertaintyValues");
    must_throw(@() oi_plot_comparison(axesHandle, [1; 2; 3], [1.5; NaN; 3.5], invalid), ...
        "UncertaintyValues");
end
modelInputs = {zeros(3, 1), NaN(3, 1), Inf(3, 1), -ones(3, 1), []};
for inputIndex = 1:numel(modelInputs)
    forgedModel = options;
    forgedModel.ModelUncertainty = modelInputs{inputIndex};
    must_throw(@() oi_plot_comparison(axesHandle, [1; 2; 3], [1.5; 2.5; 3.5], forgedModel), ...
        "UncertaintyValues");
end
for variableName = ["Uncertainty" ""]
    forgedModel = options;
    forgedModel.ModelUncertaintyVariable = variableName;
    must_throw(@() oi_plot_comparison(axesHandle, [1; 2; 3], [1.5; 2.5; 3.5], forgedModel), ...
        "UncertaintyValues");
end
missingObservationU = rmfield(options, "ObservationUncertainty");
must_throw(@() oi_plot_comparison(axesHandle, [1; 2; 3], [1.5; 2.5; 3.5], missingObservationU), ...
    "UncertaintyValues");
must_throw(@() oi_plot_comparison(axesHandle, [1; NaN; 3], [1.5; 2.5; 3.5], options), ...
    "UncertaintyValues");
implicit = rmfield(options, "UncertaintySides");
must_throw(@() oi_plot_comparison(axesHandle, [1; 2; 3], [1.5; 2.5; 3.5], implicit), ...
    "UncertaintyValues");
bothWithMissingModel = implicit;
bothWithMissingModel.ModelUncertainty = [0.25; 0.5; 0.75];
must_throw(@() oi_plot_comparison(axesHandle, [1; 2; 3], [1.5; NaN; 3.5], bothWithMissingModel), ...
    "UncertaintyValues");
wrongUnit = options;
wrongUnit.UncertaintyUnit = "K";
must_throw(@() oi_plot_comparison(axesHandle, [1; 2; 3], [1.5; 2.5; 3.5], wrongUnit), ...
    "UncertaintyUnit");
confidence = options;
confidence.ConfidenceLevel = 0.95;
must_throw(@() oi_plot_comparison(axesHandle, [1; 2; 3], [1.5; 2.5; 3.5], confidence), ...
    "ConfidenceLevel");
missingQCPolicy = options;
missingQCPolicy.ObservationQC = ["good"; "suspect"; "good"];
must_throw(@() oi_plot_comparison(axesHandle, [1; 2; 3], [1.5; 2.5; 3.5], missingQCPolicy), ...
    "QCPolicy");
clear cleanup;
end

function values = visible_text(axesHandle)
handles = findall(axesHandle, "Type", "text");
values = strings(0, 1);
for handleIndex = 1:numel(handles)
    if string(handles(handleIndex).Visible) == "on"
        value = strjoin(string(handles(handleIndex).String), " ");
        if strlength(value) > 0
            values(end + 1, 1) = value;
        end
    end
end
end

function lines = read_lines(handles)
assert(all(isgraphics(handles(:), "line")), "test_comparison_uncertainty:LineClass", ...
    "Uncertainty graphics must be native Line objects");
lines = struct("x", zeros(numel(handles), 2), "y", zeros(numel(handles), 2));
for handleIndex = 1:numel(handles)
    assert(numel(handles(handleIndex).XData) == 2 && numel(handles(handleIndex).YData) == 2, ...
        "test_comparison_uncertainty:LineShape", "Each Line must contain exactly two endpoints");
    lines.x(handleIndex, :) = double(handles(handleIndex).XData(:))';
    lines.y(handleIndex, :) = double(handles(handleIndex).YData(:))';
end
end

function [figureHandle, axesHandle, cleanup] = make_axes()
figureHandle = oi_figure(2400, 1500, "off");
figureHandle.Units = "inches";
figureHandle.Position(3:4) = [8 5];
figureHandle.PaperUnits = "inches";
figureHandle.PaperPosition = [0 0 8 5];
figureHandle.PaperSize = [8 5];
figureHandle.PaperPositionMode = "manual";
layoutHandle = tiledlayout(figureHandle, 1, 1, "TileSpacing", "compact", "Padding", "compact");
axesHandle = nexttile(layoutHandle);
cleanup = onCleanup(@() close_if_valid(figureHandle));
end

function must_throw(callback, identifierFragment)
try
    callback();
catch errorRecord
    assert(startsWith(string(errorRecord.identifier), "oi_plot_comparison:") ...
        && contains(string(errorRecord.identifier), identifierFragment), ...
        "test_comparison_uncertainty:WrongFailure", "Unexpected rejection: %s: %s", ...
        errorRecord.identifier, errorRecord.message);
    return;
end
error("test_comparison_uncertainty:MissingRejection", ...
    "Expected oi_plot_comparison rejection containing %s", identifierFragment);
end

function close_if_valid(figureHandle)
if isgraphics(figureHandle, "figure")
    close(figureHandle);
end
end
