function test_asset_adversarial_contracts()
%TEST_ASSET_ADVERSARIAL_CONTRACTS Attack every native ocean asset contract.
assetDirectory = fullfile(fileparts(mfilename("fullpath")), "..", "assets");
addpath(assetDirectory);
theme = oi_ocean_theme();
cjkLabel = string(char([hex2dec("6D77") hex2dec("6E29")]));

assert(oi_require_text(cjkLabel, "test:CJK", "CJK text required") == cjkLabel, ...
    "Chinese scientific text was not preserved");
must_throw(@() oi_require_text(42, "test:TextType", "text required"), "TextType");
must_throw(@() oi_require_text("   ", "test:BlankText", "text required"), "BlankText");

[figureHandle, axesHandle] = make_axes();
figureCleanup = onCleanup(@() close_if_valid(figureHandle));
must_throw(@() oi_plot_profile(axesHandle, [0; 10], [1; 2], ...
    struct("QuantityLabel", "   ", "QuantityUnit", "degC", ...
    "DepthUnit", "m", "VerticalReference", "sea surface", ...
    "Theme", theme)), "Units");
hold(axesHandle, "on");
profileResult = oi_plot_profile(axesHandle, [0; 10; 20], [1; NaN; 2], ...
    struct("QuantityLabel", cjkLabel, "QuantityUnit", "degC", ...
    "DepthUnit", "m", "VerticalReference", "sea surface", ...
    "SeriesLabels", cjkLabel, "Title", cjkLabel, "Theme", theme));
assert(profileResult.ValidCount == 2 && profileResult.MissingCount == 1 ...
    && isnan(profileResult.Lines(1).XData(2)) && ishold(axesHandle), ...
    "Profile did not preserve its NaN line break or caller hold state");
clear figureCleanup;
close_if_valid(figureHandle);

[figureHandle, axesHandle] = make_axes();
figureCleanup = onCleanup(@() close_if_valid(figureHandle));
seriesTime = datetime(2024, 1, 1, [0 1], 0, 0, "TimeZone", "UTC")';
seriesTable = timetable(seriesTime, [1; 2], [0.1; 0.1], ["good"; "suspect"], ...
    'VariableNames', ["Value" "Uncertainty" "QCFlag"]);
seriesTable.Properties.VariableUnits = {'degC', 'degC', '1'};
must_throw(@() oi_plot_time_series(axesHandle, seriesTable, struct( ...
    "ValueVariables", "Value", "QCVariables", "QCFlag", ...
    "UncertaintyVariables", "Uncertainty", ...
    "UncertaintyType", "standard-deviation", "UncertaintyUnits", "degC", ...
    "Theme", theme)), "AcceptedQCValues");
overflowTable = timetable(seriesTime, [realmax; realmax], [realmax; realmax], ...
    'VariableNames', ["Value" "Uncertainty"]);
overflowTable.Properties.VariableUnits = {'degC', 'degC'};
must_throw(@() oi_plot_time_series(axesHandle, overflowTable, struct( ...
    "ValueVariables", "Value", "UncertaintyVariables", "Uncertainty", ...
    "UncertaintyType", "instrument-accuracy", "UncertaintyUnits", "degC", ...
    "Theme", theme)), "UncertaintyValues");
assert(~ishold(axesHandle), ...
    "Rejected time-series metadata changed the caller hold state");
clear figureCleanup;
close_if_valid(figureHandle);

[figureHandle, axesHandle] = make_axes();
figureCleanup = onCleanup(@() close_if_valid(figureHandle));
must_throw(@() oi_plot_section(axesHandle, [0 1], [0; 1], ones(2), ...
    struct("ColorLimits", [0 1+1i], "DistanceUnit", "km", ...
    "DepthUnit", "m", "QuantityLabel", "Temperature", ...
    "QuantityUnit", "degC", "Theme", theme)), "ColorLimits");
clear figureCleanup;
close_if_valid(figureHandle);

[figureHandle, axesHandle] = make_axes();
figureCleanup = onCleanup(@() close_if_valid(figureHandle));
timeValues = datetime(2024, 1, 1, 0:2, 0, 0, "TimeZone", "UTC")';
must_throw(@() oi_plot_hovmoller(axesHandle, timeValues, [0; 10], ...
    ones(2, 3), struct("TimeZone", "UTC", "DepthUnit", " ", ...
    "QuantityLabel", "Temperature", "QuantityUnit", "degC", ...
    "ColorLimits", [0 2], "Theme", theme)), "Units");
clear figureCleanup;
close_if_valid(figureHandle);

[figureHandle, axesHandle] = make_axes();
figureCleanup = onCleanup(@() close_if_valid(figureHandle));
tsOptions = struct("SalinityUnit", "PSU", "TemperatureUnit", "degC", ...
    "ColorLabel", "Depth", "ColorUnit", "m", "ColorLimits", [0 20], ...
    "DensityValues", [25 26; 26 27], "DensitySalinity", [34 35], ...
    "DensityTemperature", [5 10], "DensityLevels", [26 25], ...
    "Theme", theme);
must_throw(@() oi_plot_ts_diagram(axesHandle, [34; 35], [5; 10], ...
    [0; 10], tsOptions), "DensityLevels");
assert(~ishold(axesHandle), ...
    "Rejected T-S density metadata changed the caller hold state");
clear figureCleanup;
close_if_valid(figureHandle);

[figureHandle, axesHandle] = make_axes();
figureCleanup = onCleanup(@() close_if_valid(figureHandle));
spectrumOptions = struct("FrequencyUnit", "Hz", "PeriodUnit", "s", ...
    "DensityUnit", "degC^2/Hz", "WindowDescription", "Hann", ...
    "DetrendDescription", "linear", "SegmentDescription", "two", ...
    "LowerBound", [1; 1+1i], "UpperBound", [3; 3], ...
    "BoundType", "confidence-interval", "ConfidenceLevel", 0.95, ...
    "Theme", theme);
must_throw(@() oi_plot_spectrum(axesHandle, [1; 2], [2; 2], ...
    spectrumOptions), "Bounds");
clear figureCleanup;
close_if_valid(figureHandle);

invalidFigure = oi_figure(320, 240, "off");
invalidCleanup = onCleanup(@() close_if_valid(invalidFigure));
roseOptions = struct("DirectionConvention", "from", "DirectionUnit", "degree", ...
    "Normalization", "count", "Theme", theme);
must_throw(@() oi_plot_direction_rose(invalidFigure, [0; 90], roseOptions), ...
    "InvalidAxes");
clear invalidCleanup;
close_if_valid(invalidFigure);
[figureHandle, axesHandle] = make_axes();
figureCleanup = onCleanup(@() close_if_valid(figureHandle));
roseOptions.Weights = ["1"; "2"];
must_throw(@() oi_plot_direction_rose(axesHandle, [0; 90], roseOptions), "Weights");
roseOptions = rmfield(roseOptions, "Weights");
roseResult = oi_plot_direction_rose(axesHandle, [-360; 0; 360; 720; NaN], ...
    roseOptions);
assert(roseResult.ValidCount == 4 && roseResult.MissingCount == 1 ...
    && roseResult.BinValues(1) == 4, ...
    "Direction wrapping or missing counts changed at the degree boundary");
clear figureCleanup;
close_if_valid(figureHandle);

[figureHandle, axesHandle] = make_axes();
figureCleanup = onCleanup(@() close_if_valid(figureHandle));
vectorOptions = struct("XUnit", "km", "YUnit", "km", ...
    "VectorUnit", "m/s", "ComponentFrame", "eastward/northward", ...
    "XLabel", "East", "YLabel", "North", "Stride", "2", "Theme", theme);
must_throw(@() oi_plot_vector_field(axesHandle, [0 1], [0; 1], ...
    ones(2), ones(2), vectorOptions), "Stride");
clear figureCleanup;
close_if_valid(figureHandle);

[figureHandle, axesHandle] = make_axes();
figureCleanup = onCleanup(@() close_if_valid(figureHandle));
comparisonOptions = struct("QuantityUnit", "degC", ...
    "ObservationLabel", "Observation", "ModelLabel", "Model", "Theme", theme);
must_throw(@() oi_plot_comparison(axesHandle, [-realmax; realmax], ...
    [realmax; -realmax], comparisonOptions), "MetricOverflow");
comparisonResult = oi_plot_comparison(axesHandle, [-1e200; 0; 1e200], ...
    [-0.9e200; 0.1e200; 0.9e200], comparisonOptions);
assert(all(isfinite([comparisonResult.Metrics.Bias ...
    comparisonResult.Metrics.MAE comparisonResult.Metrics.RMSE])) ...
    && all(isfinite(comparisonResult.Limits)), ...
    "Finite extreme comparison data produced nonfinite metrics or limits");
clear figureCleanup;
close_if_valid(figureHandle);

singleTable = table(datetime(2024, 1, 1, "TimeZone", "UTC"), 1, ...
    "obs-1", "Station A", "good", ...
    'VariableNames', ["Time" "Value" "ObservationID" "Station" "QCFlag"]);
figureCount = numel(findall(groot, "Type", "figure"));
must_throw(@() interactive_timeseries_native_template(singleTable, string(tempdir), ...
    "Interactive", false, "Export", false, "ValueLabel", "Temperature", ...
    "ValueUnit", "degC"), "file stem");
assert(numel(findall(groot, "Type", "figure")) == figureCount, ...
    "Rejected output_base leaked a graphics handle");
must_throw(@() interactive_timeseries_native_template(singleTable, "unused", ...
    "Interactive", false, "Export", false, "ValueLabel", "Temperature", ...
    "ValueUnit", "degC", "SecondaryValueLabel", "Salinity", ...
    "SecondaryValueUnit", "PSU"), "metadata must be omitted");

fprintf("MATLAB_ASSET_ADVERSARIAL_CASES=passed\n");
fprintf("MATLAB_ASSET_BILINGUAL_CONTRACT=passed\n");
end

function [figureHandle, axesHandle] = make_axes()
figureHandle = oi_figure(640, 480, "off");
axesHandle = axes("Parent", figureHandle);
end

function must_throw(callback, expectedText)
thrown = false;
try
    callback();
catch errorRecord
    thrown = true;
    assert(contains(string(errorRecord.identifier), expectedText) ...
        || contains(string(errorRecord.message), expectedText), ...
        "Unexpected MATLAB error: %s", errorRecord.message);
end
assert(thrown, "Expected MATLAB contract rejection containing %s", expectedText);
end

function close_if_valid(figureHandle)
if ~isempty(figureHandle) && isgraphics(figureHandle)
    close(figureHandle);
end
end
