function test_direction_rose_export(outputDirectory)
arguments
    outputDirectory (1,1) string
end
assetDirectory = fullfile(fileparts(fileparts(mfilename("fullpath"))), "assets");
addpath(assetDirectory);
assert(~isfolder(outputDirectory) && ~isfile(outputDirectory), ...
    "test_direction_rose_export:FreshOutput", "Output directory must be new");
mkdir(outputDirectory);
theme = oi_ocean_theme();
test_reused_polar_axes(theme);
caseNames = ["weighted-percent", "converted-count", "zero-weight"];
records = cell(numel(caseNames), 1);
for caseIndex = 1:numel(caseNames)
    figureHandle = oi_figure(2400, 1500, "off");
    cleanupFigure = onCleanup(@() close_if_valid(figureHandle));
    figureHandle.Units = "inches";
    figureHandle.Position(3:4) = [8 5];
    if caseIndex == 2
        layoutHandle = tiledlayout(figureHandle, 1, 1, ...
            "Padding", "loose", "TileSpacing", "compact");
        axesHandle = nexttile(layoutHandle);
    else
        axesHandle = axes("Parent", figureHandle, "Units", "normalized", ...
            "PositionConstraint", "outerposition", "OuterPosition", [0.04 0.04 0.92 0.92]);
    end
    [directions, options, expected] = case_data(caseIndex, theme);
    originalDirections = directions;
    originalWeights = options.Weights;
    result = oi_plot_direction_rose(axesHandle, directions, options);
    histogramHandle = result.Histogram;
    assert_native_data(result, expected);
    assert(isequaln(directions, originalDirections) && isequaln(options.Weights, originalWeights), ...
        "test_direction_rose_export:InputMutation", "Original samples must remain unchanged");
    if caseIndex == 2
        assert(~isgraphics(axesHandle) && result.Axes.Layout.Tile == 1, ...
            "test_direction_rose_export:Tile", "Polar axes must keep the requested tile");
    else
        assert(isgraphics(axesHandle), "test_direction_rose_export:CallerAxes", ...
            "The conventional caller axes must remain valid");
        oi_apply_axes(axesHandle, theme);
    end
    assert(all(result.Axes.RTick > 0) && result.Axes.RLim(1) == 0 ...
        && result.Axes.RLim(2) >= max(expected.values) ...
        && string(result.Axes.RGrid) == "on", ...
        "test_direction_rose_export:ZeroRadiusGrid", ...
        "Only the degenerate zero-radius tick must be omitted, not zero data or positive grids");
    entry = oi_export_figure(figureHandle, outputDirectory, caseNames(caseIndex), ...
        2400, 1500, 300, "Title", options.Title, ...
        "Source", "public synthetic direction rose regression; not ocean observations", ...
        "Theme", theme.Name, "ExportSVG", true);
    assert(isequal(result.Histogram, histogramHandle), ...
        "test_direction_rose_export:HistogramIdentity", "Export must preserve the native Histogram");
    assert_native_data(result, expected);
    assert(all(result.Axes.RTick > 0) && result.Axes.RLim(1) == 0, ...
        "test_direction_rose_export:ExportRadialScale", "Export must not restore the zero-radius grid");
    directionLabel = "Direction " + expected.display_convention ...
        + " (degree; clockwise from true north)";
    titleHandle = result.Axes.Title;
    assert(isgraphics(titleHandle, "text") && string(titleHandle.Visible) == "on" ...
        && any(string(titleHandle.String) == directionLabel) ...
        && string(titleHandle.FontName) == theme.FontName ...
        && titleHandle.FontSize == theme.TitleSize, ...
        "test_direction_rose_export:NativeLabel", "Complete direction text must be natively visible");
    labels = getappdata(result.Axes, "OI_AxisLabels");
    assert(labels.xlabel == directionLabel && labels.ylabel == expected.radial_unit, ...
        "test_direction_rose_export:LabelBinding", "Manifest labels must agree with native text");
    titleBounds = oi_text_bounds(titleHandle, figureHandle);
    assert(all(titleBounds(1:2) >= 0) && all(titleBounds(1:2) + titleBounds(3:4) <= 1), ...
        "test_direction_rose_export:LabelBounds", "Rendered direction title must fit the figure");
    assert(any(contains(string({entry.text_objects.string}), directionLabel)), ...
        "test_direction_rose_export:TextEvidence", "Measured text evidence must include the visible direction label");
    oi_write_manifest(fullfile(outputDirectory, caseNames(caseIndex) + "-figures.json"), entry);
    records{caseIndex} = struct("case_id", caseNames(caseIndex), "data_source", "synthetic", ...
        "native_array_assertions_passed", true, "visual_verified", false, ...
        "bin_counts", result.Histogram.BinCounts, "bin_edges", result.Histogram.BinEdges, ...
        "valid_mask", result.ValidMask, "calm_mask", result.CalmMask, ...
        "sample_counts", result.SampleCounts, "weight_sums", result.WeightSums, ...
        "displayed_directions", result.DisplayedDirectionsDegrees, ...
        "radial_limits", result.Axes.RLim, "radial_ticks", result.Axes.RTick, ...
        "title", string(titleHandle.String), "title_bounds", titleBounds);
    clear cleanupFigure;
end
fileHandle = fopen(fullfile(outputDirectory, "native-results.json"), "w", "n", "UTF-8");
assert(fileHandle >= 0, "test_direction_rose_export:Write", "Cannot create native evidence");
cleanupFile = onCleanup(@() fclose(fileHandle));
fprintf(fileHandle, "%s\n", jsonencode(records));
clear cleanupFile;
fprintf("MATLAB_DIRECTION_ROSE_EXPORT=passed_synthetic_native_arrays_only\n");
end

function test_reused_polar_axes(theme)
figureHandle = oi_figure(2400, 1500, "off");
cleanupFigure = onCleanup(@() close_if_valid(figureHandle));
axesHandle = polaraxes("Parent", figureHandle);
directions = [0; 90; NaN];
options = struct("DirectionConvention", "from", "DirectionUnit", "degree", ...
    "Normalization", "weight", "Weights", [1; 2; NaN], "Theme", theme);
small = oi_plot_direction_rose(axesHandle, directions, options);
smallTicks = small.Axes.RTick;
options.Weights = [1000; 2000; NaN];
large = oi_plot_direction_rose(axesHandle, directions, options);
largeTicks = large.Axes.RTick;
assert(isequal(large.Axes, axesHandle) && ~isgraphics(small.Histogram) ...
    && all(largeTicks > 0) && max(largeTicks) > 100 * max(smallTicks) ...
    && large.Histogram.BinCounts(1) == 1000 && large.Histogram.BinCounts(5) == 2000, ...
    "test_direction_rose_export:ReusedScale", "Reused PolarAxes must regenerate ticks for larger data");
options.Weights = [1; 2; NaN];
restored = oi_plot_direction_rose(axesHandle, directions, options);
assert(isequal(restored.Axes, axesHandle) && ~isgraphics(large.Histogram) ...
    && all(restored.Axes.RTick > 0) && max(restored.Axes.RTick) < max(largeTicks) / 100 ...
    && restored.Histogram.BinCounts(1) == 1 && restored.Histogram.BinCounts(5) == 2 ...
    && restored.ValidCount == 2 && restored.MissingCount == 1, ...
    "test_direction_rose_export:RestoredScale", "Reused PolarAxes must regenerate ticks for smaller data");
clear cleanupFigure;
end

function [directions, options, expected] = case_data(caseIndex, theme)
options = struct("DirectionConvention", "from", "DirectionUnit", "degree", ...
    "Normalization", "percent", "MissingPolicy", "preserve", "Theme", theme, ...
    "Title", "Synthetic directional rose", "BinCount", 16);
if caseIndex == 1
    directions = [0; 45; 90; 135; 180; 225; 270; 315; NaN];
    options.Weights = [1; 2; 1; 3; 2; 1; 2; 1; NaN];
    counts = zeros(16, 1);
    counts(1:2:end) = 1;
    weightSums = zeros(16, 1);
    weightSums(1:2:end) = options.Weights(1:8);
    values = 100 * weightSums / 13;
    displayConvention = "from";
    displayed = directions;
    radialUnit = "percent";
elseif caseIndex == 2
    directions = [-360; 0; 11.25; 348.75; 360; 720; NaN];
    options.Weights = ones(size(directions));
    options.DisplayConvention = "to";
    options.Normalization = "count";
    options.DirectionUnit = "degree clockwise from true north";
    counts = zeros(16, 1);
    counts(9:10) = [5; 1];
    weightSums = counts;
    values = counts;
    displayConvention = "to";
    displayed = [180; 180; 191.25; 168.75; 180; 180; NaN];
    radialUnit = "sample count";
else
    directions = [0; 90; 180; NaN];
    options.Weights = [0; 0; 0; NaN];
    options.Normalization = "weight";
    counts = zeros(16, 1);
    counts([1 5 9]) = 1;
    weightSums = zeros(16, 1);
    values = weightSums;
    displayConvention = "from";
    displayed = directions;
    radialUnit = "weight sum";
end
expected = struct("counts", counts, "weight_sums", weightSums, "values", values, ...
    "valid_mask", isfinite(directions) & isfinite(options.Weights), ...
    "display_convention", displayConvention, "displayed", displayed, ...
    "radial_unit", radialUnit, "direction_unit", options.DirectionUnit);
end

function assert_native_data(result, expected)
assert(isa(result.Histogram, "matlab.graphics.chart.primitive.Histogram") ...
    && isequal(result.Histogram.Parent, result.Axes) ...
    && string(result.Histogram.DisplayStyle) == "bar" ...
    && result.Histogram.LineWidth == 0.6 ...
    && isequal(result.Histogram.EdgeColor, [1 1 1]), ...
    "test_direction_rose_export:NativeHistogram", "The native Histogram API must be preserved");
assert(isequaln(result.BinValues, expected.values) ...
    && isequaln(result.Histogram.BinCounts(:), expected.values) ...
    && isequaln(result.Histogram.Values(:), expected.values) ...
    && isequaln(result.SampleCounts, expected.counts) ...
    && isequaln(result.WeightSums, expected.weight_sums) ...
    && isequaln(result.BinCentersDegrees, 0:22.5:337.5) ...
    && isequaln(result.BinEdgesDegrees, ((0:16) - 0.5) * 22.5) ...
    && isequaln(result.Histogram.BinEdges, deg2rad(result.BinEdgesDegrees)), ...
    "test_direction_rose_export:BinData", "Counts, weights, zero bins and all boundaries must remain exact");
assert(isequaln(result.ValidMask, expected.valid_mask) ...
    && result.ValidCount == sum(expected.valid_mask) && result.MissingCount == 1 ...
    && ~any(result.CalmMask) && result.CalmCount == 0 ...
    && result.DirectionalCount == sum(expected.valid_mask) ...
    && isequaln(result.DisplayedDirectionsDegrees, expected.displayed) ...
    && result.DirectionUnit == expected.direction_unit ...
    && result.DisplayConvention == expected.display_convention ...
    && string(result.Axes.ThetaZeroLocation) == "top" ...
    && string(result.Axes.ThetaDir) == "clockwise" ...
    && isequal(result.Axes.ThetaTick, 0:45:315), ...
    "test_direction_rose_export:Semantics", "Missing, calm, units and bearing semantics must remain exact");
end

function close_if_valid(figureHandle)
if isgraphics(figureHandle)
    close(figureHandle);
end
end
