function evidence = test_generated_plot_router(outputRoot)
arguments
    outputRoot (1,1) string
end
assert(~exist('OCTAVE_VERSION', 'builtin'), ...
    "test_generated_plot_router:MatlabRequired", "MATLAB is required");
assert(isfolder(outputRoot), "test_generated_plot_router:MissingRoot", ...
    "Node generation requires an existing CI output root");
outputRoot = canonical_path(outputRoot);
generatedRoot = fullfile(outputRoot, "generated-router");
sourceDirectory = fullfile(generatedRoot, "source");
evidencePath = fullfile(generatedRoot, "generated-router-evidence.json");
assert(~isfile(evidencePath), "test_generated_plot_router:Reuse", ...
    "Generated router evidence must not be overwritten");
testsDirectory = fileparts(mfilename("fullpath"));
assetDirectory = canonical_path(fullfile(testsDirectory, "..", "assets"));
originalPath = path;
pathCleanup = onCleanup(@() path(originalPath));
addpath(assetDirectory, sourceDirectory, "-begin");
catalogRecord = file_evidence(generatedRoot, "catalog.json");
catalog = jsondecode(fileread(fullfile(generatedRoot, "catalog.json")));
actualRelease = release_name(version('-release'));
assert(catalog.schema_version == 1 && string(catalog.scope) == "two-route-smoke" ...
    && string(catalog.target_release) == actualRelease ...
    && canonical_path(catalog.output_root) == outputRoot ...
    && canonical_path(catalog.asset_directory) == assetDirectory ...
    && string(catalog.source_directory) == "source" ...
    && string(catalog.runtime_status) == "not-run" ...
    && ~catalog.execution_verified && ~catalog.visual_inspection_verified ...
    && ~catalog.desktop_interaction_verified, ...
    "test_generated_plot_router:Catalog", "Catalog release, paths or generation status mismatch");
verify_file(generatedRoot, catalog.inputs, "source/inputs.json");
inputs = jsondecode(fileread(fullfile(sourceDirectory, "inputs.json")));
fixtureTable = fixture_table(inputs);
expectedValid = sum(isfinite(fixtureTable.Value));
expectedMissing = sum(isnan(fixtureTable.Value));
assert(expectedValid == 5 && expectedMissing == 1, ...
    "test_generated_plot_router:FixtureCounts", "The six-row fixture must retain one NaN");
assert(numel(catalog.cases) == 2 ...
    && isequal(string({catalog.cases.id})', ["static"; "interactive"]), ...
    "test_generated_plot_router:Cases", "Exactly the static and interactive smoke cases are required");
for caseIndex = 1:2
    caseInfo = catalog.cases(caseIndex);
    caseId = string(caseInfo.id);
    functionName = "generated_router_" + caseId;
    parameters = ["sampleTime"; "sampleValue"; "sampleQC"];
    if caseId == "interactive"
        parameters = ["sampleTime"; "sampleValue"; "sampleID"; "sampleStation"; "sampleQC"];
        assert(string(caseInfo.request.interactionEnvironment) == "headless", ...
            "Interactive smoke must explicitly select the headless fallback");
    end
    assert(string(caseInfo.function_name) == functionName ...
        && isequal(string(caseInfo.parameters(:)), parameters) ...
        && string(caseInfo.output_directory) == caseId ...
        && string(caseInfo.request.outputDirectory) == caseId ...
        && string(caseInfo.request.functionName) == functionName ...
        && string(caseInfo.request.figureId) == "router_" + caseId ...
        && string(caseInfo.request.targetRelease) == actualRelease ...
        && canonical_path(caseInfo.request.assetDirectory) == assetDirectory, ...
        "test_generated_plot_router:CaseContract", "Fixed function, arguments, release or output directory changed");
    verify_file(generatedRoot, caseInfo.script, "source/" + functionName + ".m");
    caseDirectory = fullfile(generatedRoot, caseId);
    assert(isfolder(caseDirectory), "Missing fresh case output directory");
    contents = dir(caseDirectory);
    assert(all(ismember(string({contents.name}), ["." ".."])), ...
        "test_generated_plot_router:Reuse", "Case output must be empty before execution");
end
clear generated_router_static generated_router_interactive;
rehash;
for caseIndex = 1:2
    functionName = string(catalog.cases(caseIndex).function_name);
    assert(canonical_path(which(char(functionName))) ...
        == canonical_path(fullfile(sourceDirectory, functionName + ".m")), ...
        "test_generated_plot_router:FunctionPath", "Generated function is shadowed on the MATLAB path");
end
originalDirectory = pwd;
directoryCleanup = onCleanup(@() cd(originalDirectory));
cd(generatedRoot);
caseEvidence = struct([]);
for caseIndex = 1:2
    caseInfo = catalog.cases(caseIndex);
    if string(caseInfo.id) == "static"
        result = generated_router_static(fixtureTable.Time, fixtureTable.Value, fixtureTable.QCFlag);
    else
        result = generated_router_interactive(fixtureTable.Time, fixtureTable.Value, ...
            fixtureTable.ObservationID, fixtureTable.Station, fixtureTable.QCFlag);
    end
    caseEvidence(caseIndex) = audit_result(generatedRoot, caseInfo, result, ...
        actualRelease, fixtureTable, expectedValid, expectedMissing);
end
verify_file(generatedRoot, catalogRecord, "catalog.json");
verify_file(generatedRoot, catalog.inputs, "source/inputs.json");
for caseIndex = 1:2
    verify_file(generatedRoot, catalog.cases(caseIndex).script, ...
        "source/" + string(catalog.cases(caseIndex).function_name) + ".m");
    verify_file(generatedRoot, caseEvidence(caseIndex).manifest, ...
        string(catalog.cases(caseIndex).id) + "/figures.json");
    for format = ["png" "pdf" "svg"]
        verify_file(generatedRoot, caseEvidence(caseIndex).artifacts.(format), ...
            string(catalog.cases(caseIndex).id) + "/router_" ...
            + string(catalog.cases(caseIndex).id) + "." + format);
    end
end
evidence = struct("schema_version", 1, "scope", "two-route-smoke", ...
    "status", "passed", "execution_verified", true, "matlab_release", actualRelease, ...
    "matlab_version", string(version), "executed_cases", numel(caseEvidence), ...
    "visual_inspection_verified", false, "desktop_interaction_verified", false, ...
    "catalog", catalogRecord, "inputs", catalog.inputs, "cases", caseEvidence);
assert(~isfile(evidencePath), "Evidence destination is no longer fresh");
fileHandle = fopen(char(evidencePath), "w", "n", "UTF-8");
assert(fileHandle >= 0, "Cannot write generated router execution evidence");
fileCleanup = onCleanup(@() fclose(fileHandle));
fprintf(fileHandle, "%s\n", jsonencode(evidence));
clear fileCleanup directoryCleanup pathCleanup;
fprintf("MATLAB_GENERATED_ROUTER_RUNTIME=passed\nMATLAB_GENERATED_ROUTER_CASES=%d\n", numel(caseEvidence));
end

function fixtureTable = fixture_table(inputs)
assert(inputs.schema_version == 1 && inputs.synthetic ...
    && string(inputs.time_zone) == "UTC" && string(inputs.value_unit) == "degC" ...
    && string(inputs.missing_encoding) == "JSON null represents NaN", ...
    "test_generated_plot_router:Inputs", "Synthetic inputs must declare UTC, degC and NaN encoding");
sampleTime = datetime(string(inputs.Time(:)), "InputFormat", ...
    "yyyy-MM-dd'T'HH:mm:ss'Z'", "TimeZone", "UTC");
sampleValue = double(inputs.Value(:));
sampleID = string(inputs.ObservationID(:));
sampleStation = string(inputs.Station(:));
sampleQC = string(inputs.QCFlag(:));
fixtureTable = table(sampleTime, sampleValue, sampleID, sampleStation, sampleQC, ...
    'VariableNames', {'Time', 'Value', 'ObservationID', 'Station', 'QCFlag'});
fixtureTable.Properties.VariableUnits = {'datetime', 'degC', '1', '1', '1'};
assert(height(fixtureTable) == 6 && all(diff(sampleTime) > seconds(0)) ...
    && ~any(isnat(sampleTime)) && ~any(isinf(sampleValue)) ...
    && numel(unique(sampleID)) == 6 ...
    && all(strlength(sampleID) > 0) && all(strlength(sampleStation) > 0) ...
    && all(ismember(sampleQC, ["good" "missing" "suspect" "bad"])), ...
    "test_generated_plot_router:Inputs", "Fixture rows, IDs, station, QC or time order changed");
end

function record = audit_result(root, caseInfo, result, actualRelease, fixtureTable, validCount, missingCount)
caseId = string(caseInfo.id);
assert(string(result.route) == "time-series" && string(result.helper) == string(caseInfo.helper) ...
    && result.valid_count == validCount && result.missing_count == missingCount, ...
    "test_generated_plot_router:Counts", "Generated return value changed route or missing-value counts");
assert(string(result.qc.status) == "present" && string(result.qc.action) == "preserve" ...
    && result.qc.accepted_count == sum(fixtureTable.QCFlag == "good") ...
    && result.qc.suspect_count == sum(ismember(fixtureTable.QCFlag, ["missing" "suspect"])) ...
    && result.qc.rejected_count == sum(fixtureTable.QCFlag == "bad"), ...
    "test_generated_plot_router:QC", "Generated return value must preserve every QC class");
assert(string(result.runtime.target_release) == actualRelease ...
    && release_name(result.runtime.actual_release) == actualRelease ...
    && release_name(result.runtime.matlab_release) == actualRelease ...
    && ~result.runtime.octave_substitution && ~result.runtime.desktop_available ...
    && result.runtime.headless_static_export && string(result.runtime.figure_visible) == "off", ...
    "test_generated_plot_router:Runtime", "Actual execution must match the requested MATLAB headless release");
assert(~result.interaction.enabled && ~result.interaction.desktop_available ...
    && ~result.interaction.runtime_activation_requested && ~result.interaction.interaction_verified ...
    && result.interaction.headless.verified, ...
    "test_generated_plot_router:Interaction", "Headless smoke must not claim desktop interaction");
if caseId == "interactive"
    assert(result.interaction.requested && result.interaction.static_fallback_used ...
        && string(result.interaction.status) == "static-fallback-not-interactive", ...
        "Interactive smoke did not execute its headless fallback");
else
    assert(~result.interaction.requested && ~result.interaction.static_fallback_used);
end
manifestRecord = file_evidence(root, caseId + "/figures.json");
manifest = jsondecode(fileread(fullfile(root, manifestRecord.file)));
assert(manifest.execution_verified && result.manifest.execution_verified ...
    && string(manifest.runtime_status) == "ready" && string(result.manifest.runtime_status) == "ready" ...
    && manifest.runtime.execution_verified && string(manifest.runtime.engine) == "MATLAB" ...
    && string(manifest.artifact_validation.status) == "passed" ...
    && release_name(manifest.matlab_release) == actualRelease ...
    && ~manifest.visual_inspection.verified && ~result.manifest.visual_inspection.verified ...
    && ~manifest.runtime.visual_inspection.verified && numel(manifest.figures) == 1, ...
    "test_generated_plot_router:Manifest", "Generated manifest must report actual execution without visual claims");
entry = manifest.figures;
assert(string(entry.id) == "router_" + caseId ...
    && string(entry.title) == string(caseInfo.request.title) ...
    && isequaln(entry.exports, jsondecode(jsonencode(result.exports))) ...
    && isequaln(entry.runtime, jsondecode(jsonencode(result.runtime))) ...
    && entry.scientific_data_contract.missing.valid_count == validCount ...
    && entry.scientific_data_contract.missing.missing_count == missingCount ...
    && entry.scientific_data_contract.missing.total_count == height(fixtureTable) ...
    && string(entry.scientific_data_contract.units.value) == "degC", ...
    "test_generated_plot_router:ManifestEvidence", "Manifest identity, counts or returned evidence differs from disk");
rendering = entry.rendering_evidence;
assert(rendering.bounds_audited && rendering.clipped_count == 0 ...
    && rendering.text_overlap_count == 0 && all(rendering.normalized_margins >= 0) ...
    && rendering.physical_dimensions_verified && rendering.png_embedded_dpi_verified ...
    && ~rendering.visual_inspection_verified ...
    && ~entry.publication.typography.glyphs_verified ...
    && ~rendering.cjk_font_evidence.glyph_rendering_verified, ...
    "test_generated_plot_router:Layout", "Strict export geometry must pass without invented glyph verification");
fontCandidates = ["WenQuanYi Zen Hei" "Noto Sans CJK SC"];
availableFonts = string(listfonts);
fontAvailable = false(size(fontCandidates));
for candidateIndex = 1:numel(fontCandidates)
    fontAvailable(candidateIndex) = oi_font_available(fontCandidates(candidateIndex), availableFonts);
end
fontIndex = find(fontAvailable, 1);
assert(~isempty(fontIndex) ...
    && strcmpi(entry.publication.typography.selected_font, fontCandidates(fontIndex)) ...
    && all(strcmpi(string(entry.publication.typography.selected_fonts), fontCandidates(fontIndex))), ...
    "test_generated_plot_router:Font", "Actual font must respect WenQuanYi then Noto preference");
assert(isequal(sort(string(fieldnames(entry.exports))), sort(["png"; "pdf"; "svg"])), ...
    "Exactly PNG, PDF and SVG must be exported");
artifacts = struct();
for format = ["png" "pdf" "svg"]
    exportRecord = entry.exports.(format);
    expectedFile = "router_" + caseId + "." + format;
    verify_file(fullfile(root, caseId), exportRecord, expectedFile);
    assert(any(string(exportRecord.export_api) == ["print" "exportgraphics"]) ...
        && string(exportRecord.export_api) == string(result.runtime.export_api.(format)) ...
        && abs(exportRecord.physical_width_in - 8) < 1e-10 ...
        && abs(exportRecord.physical_height_in - 5) < 1e-10, ...
        "Per-format API or physical export dimensions are inconsistent");
    artifacts.(format) = file_evidence(root, caseId + "/" + expectedFile);
end
audit_dimensions(fullfile(root, caseId), entry.exports);
record = struct("id", caseId, "function_name", string(caseInfo.function_name), ...
    "script", caseInfo.script, "valid_count", result.valid_count, ...
    "missing_count", result.missing_count, "qc", result.qc, "runtime", result.runtime, ...
    "interaction", result.interaction, "selected_font", string(entry.publication.typography.selected_font), ...
    "rendering_evidence", rendering, "exports", entry.exports, ...
    "manifest", manifestRecord, "artifacts", artifacts);
end

function audit_dimensions(directory, exports)
pngInfo = imfinfo(fullfile(directory, exports.png.file));
[dpiX, dpiY] = png_physical_dpi(fullfile(directory, exports.png.file));
assert(pngInfo.Width == 2400 && pngInfo.Height == 1500 ...
    && exports.png.width == pngInfo.Width && exports.png.height == pngInfo.Height ...
    && exports.png.dpi == 300 && abs(dpiX - 300) < 0.1 && abs(dpiY - 300) < 0.1 ...
    && abs(dpiX - exports.png.embedded_dpi_x) < 1e-9 ...
    && abs(dpiY - exports.png.embedded_dpi_y) < 1e-9, ...
    "test_generated_plot_router:PNG", "PNG must measure 2400x1500 at 300 DPI");
pdfBytes = oi_read_file_prefix(fullfile(directory, exports.pdf.file), exports.pdf.bytes);
pdfText = char(pdfBytes');
boxes = regexp(pdfText, '/MediaBox\s*\[\s*([-+\d.]+)\s+([-+\d.]+)\s+([-+\d.]+)\s+([-+\d.]+)\s*\]', 'tokens');
pageCount = numel(regexp(pdfText, '/Type\s*/Page(?!s)', 'match'));
assert(~isempty(boxes) && exports.pdf.width == 576 && exports.pdf.height == 360 ...
    && pageCount == 1 && exports.pdf.pages == pageCount, ...
    "test_generated_plot_router:PDF", "PDF must report an 8x5 inch MediaBox");
for boxIndex = 1:numel(boxes)
    bounds = str2double(boxes{boxIndex});
    dimensions = abs(bounds(3:4) - bounds(1:2));
    assert(all(abs(dimensions - [576 360]) < 0.01) ...
        && isequal(round(dimensions, 6), [exports.pdf.width exports.pdf.height]), ...
        "test_generated_plot_router:PDF", "Actual PDF MediaBox differs from 8x5 inches");
end
document = xmlread(char(fullfile(directory, exports.svg.file)));
root = document.getDocumentElement();
viewBox = sscanf(char(replace(string(char(root.getAttribute('viewBox'))), ",", " ")), '%f')';
assert(svg_pixel_length(root, "width") == 2400 ...
    && svg_pixel_length(root, "height") == 1500 ...
    && exports.svg.width == 2400 && exports.svg.height == 1500 ...
    && abs(str2double(char(root.getAttribute('data-physical-width-in'))) - 8) < 1e-10 ...
    && abs(str2double(char(root.getAttribute('data-physical-height-in'))) - 5) < 1e-10 ...
    && numel(viewBox) == 4 && all(isfinite(viewBox)) && all(viewBox(3:4) > 0) ...
    && abs(viewBox(3) / viewBox(4) - 8 / 5) < 1e-6 ...
    && all(abs(viewBox(3:4) - [exports.svg.viewbox_width exports.svg.viewbox_height]) < 1e-10), ...
    "test_generated_plot_router:SVG", "Actual SVG geometry must match evidence while preserving native viewBox units");
end

function [dpiX, dpiY] = png_physical_dpi(filePath)
fileHandle = fopen(filePath, "rb");
assert(fileHandle >= 0, "test_generated_plot_router:PNG", "Cannot inspect PNG metadata: %s", filePath);
cleanup = onCleanup(@() fclose(fileHandle));
signature = fread(fileHandle, 8, "*uint8")';
assert(isequal(signature, uint8([137 80 78 71 13 10 26 10])), ...
    "test_generated_plot_router:PNG", "PNG signature is invalid");
dpiX = NaN;
dpiY = NaN;
physicalChunkSeen = false;
while true
    chunkLength = fread(fileHandle, 1, "uint32", 0, "ieee-be");
    assert(~isempty(chunkLength), "test_generated_plot_router:PNG", "PNG ended before image data");
    chunkType = char(fread(fileHandle, 4, "*uint8")');
    chunkData = fread(fileHandle, double(chunkLength), "*uint8")';
    chunkCrc = fread(fileHandle, 4, "*uint8");
    assert(numel(chunkType) == 4 && numel(chunkData) == double(chunkLength) ...
        && numel(chunkCrc) == 4, "test_generated_plot_router:PNG", "PNG contains a truncated chunk");
    if strcmp(chunkType, 'pHYs')
        assert(~physicalChunkSeen && chunkLength == 9 && chunkData(9) == 1, ...
            "test_generated_plot_router:PNG", "PNG physical-resolution metadata is invalid");
        physicalChunkSeen = true;
        pixelsPerMeterX = typecast(uint8(chunkData(1:4)), "uint32");
        pixelsPerMeterY = typecast(uint8(chunkData(5:8)), "uint32");
        [~, ~, endian] = computer;
        if endian == 'L'
            pixelsPerMeterX = swapbytes(pixelsPerMeterX);
            pixelsPerMeterY = swapbytes(pixelsPerMeterY);
        end
        dpiX = double(pixelsPerMeterX) * 0.0254;
        dpiY = double(pixelsPerMeterY) * 0.0254;
    elseif strcmp(chunkType, 'IDAT') || strcmp(chunkType, 'IEND')
        break;
    end
end
clear cleanup;
end

function value = svg_pixel_length(root, attributeName)
attribute = strtrim(string(char(root.getAttribute(char(attributeName)))));
numberPattern = "[+]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][+-]?\d+)?";
token = regexp(char(attribute), char("^(" + numberPattern + ")px$"), "tokens", "once");
assert(~isempty(token), "test_generated_plot_router:SVG", "SVG %s must use a px length", attributeName);
value = str2double(token{1});
assert(isfinite(value) && value > 0, "test_generated_plot_router:SVG", ...
    "SVG pixel dimensions must be finite and positive");
end

function verify_file(root, recorded, expectedFile)
assert(string(recorded.file) == expectedFile, ...
    "test_generated_plot_router:EvidencePath", "Unexpected evidence path");
actual = file_evidence(root, expectedFile);
assert(actual.bytes == recorded.bytes, ...
    "test_generated_plot_router:ByteMismatch", "Evidence byte count mismatch: %s", expectedFile);
assert(strcmpi(actual.sha256, recorded.sha256), ...
    "test_generated_plot_router:HashMismatch", "Evidence SHA-256 mismatch: %s", expectedFile);
end

function record = file_evidence(root, relativeFile)
filePath = fullfile(root, relativeFile);
assert(isfile(filePath), "test_generated_plot_router:MissingFile", "Missing file: %s", filePath);
fileInfo = dir(filePath);
assert(isscalar(fileInfo) && fileInfo.bytes > 0, "Evidence file must be nonempty");
record = struct("file", relativeFile, "bytes", fileInfo.bytes, "sha256", oi_sha256_file(filePath));
end

function value = canonical_path(value)
if usejava("jvm")
    value = string(char(java.io.File(char(value)).getCanonicalPath()));
    return;
end
[status, attributes] = fileattrib(char(value));
assert(status, "test_generated_plot_router:PathResolutionFailed", ...
    "Canonical path resolution failed without the MATLAB JVM: %s", value);
value = string(attributes.Name);
end

function value = release_name(value)
value = "R" + erase(string(value), "R");
end
