function entries = test_comparison_statistics_layout(outputRoot)
if nargin == 0
    outputRoot = string(tempname);
    mkdir(outputRoot);
end
outputRoot = string(outputRoot);
assert(isfolder(outputRoot), "test_comparison_statistics_layout:MissingRoot", ...
    "Output root must already exist");
outputDirectory = fullfile(outputRoot, "comparison-statistics-layout");
assert(~isfolder(outputDirectory) && ~isfile(outputDirectory), ...
    "test_comparison_statistics_layout:Reuse", "Comparison layout output must be fresh");
mkdir(outputDirectory);
assetDirectory = fullfile(fileparts(mfilename("fullpath")), "..", "assets");
addpath(assetDirectory);
observations = table(["A"; "B"; "C"; "D"; "E"; "F"; "G"], ...
    [0; 2; 5; 4; 10; 6; 7], repmat("good", 7, 1), ...
    'VariableNames', {'Key', 'Observation', 'QC'});
models = table(["A"; "B"; "C"; "D"; "E"; "F"; "H"], ...
    [0; 9; 5; NaN; 10; 6.5; 8], ...
    ["good"; "good"; "good"; "good"; "good"; "bad"; "good"], ...
    'VariableNames', {'Key', 'Model', 'QC'});
originalObservations = observations;
originalModels = models;
entries = struct([]);
caseNames = ["plain" "tiled-publication" "tiled-override"];
for caseIndex = 1:numel(caseNames)
    theme = oi_ocean_theme();
    if caseIndex == 3
        theme.AxesColor = [0.93 0.97 0.94];
        theme.FontSize = 12;
    end
    figureHandle = oi_figure(2400, 1500, "off");
    cleanupFigure = onCleanup(@() close_if_valid(figureHandle));
    exportSize = [2400 1500 300];
    if caseIndex == 2
        exportSize = [1200 675 180];
    end
    pageSize = exportSize(1:2) / exportSize(3);
    figureHandle.Units = "inches";
    figureHandle.Position(3:4) = pageSize;
    figureHandle.PaperUnits = "inches";
    figureHandle.PaperPosition = [0 0 pageSize];
    figureHandle.PaperSize = pageSize;
    figureHandle.PaperPositionMode = "manual";
    if caseIndex == 1
        axesHandle = axes("Parent", figureHandle, "Units", "normalized", ...
            "PositionConstraint", "outerposition", "OuterPosition", [0.04 0.04 0.92 0.92]);
    else
        layoutHandle = tiledlayout(figureHandle, 1, 1, ...
            "TileSpacing", "compact", "Padding", "compact");
        axesHandle = nexttile(layoutHandle);
    end
    originalParent = axesHandle.Parent;
    options = struct("PairingRule", "inner-key", "PairKeys", "Key", ...
        "ObservationVariable", "Observation", "ModelVariable", "Model", ...
        "ObservationQCVariable", "QC", "ModelQCVariable", "QC", ...
        "AcceptedQCValues", "good", "QuantityUnit", "degC", ...
        "Theme", theme, "Title", "Comparison statistics layout");
    expectedLegendLocation = "southoutside";
    if caseIndex == 3
        options.LegendLocation = "eastoutside";
        expectedLegendLocation = options.LegendLocation;
    end
    figureId = "comparison-statistics-" + caseNames(caseIndex);
    result = oi_plot_comparison(axesHandle, observations, models, options);
    metricHandle = find_metrics(axesHandle);
    assert_statistics(result, metricHandle);
    assert_presentation(result, axesHandle, originalParent, metricHandle, ...
        options.Title, theme, expectedLegendLocation, ...
        fullfile(outputDirectory, figureId + "-created-properties.json"));
    axesHandle.FontSize = theme.FontSize + 2;
    oi_apply_axes(axesHandle, theme);
    assert_presentation(result, axesHandle, originalParent, metricHandle, ...
        options.Title, theme, expectedLegendLocation, ...
        fullfile(outputDirectory, figureId + "-restyled-properties.json"));
    probePath = fullfile(outputDirectory, figureId + "-before-export.png");
    print(figureHandle, char(probePath), "-dpng", char("-r" + string(exportSize(3))));
    probeInfo = imfinfo(probePath);
    assert(probeInfo.Width == exportSize(1) && probeInfo.Height == exportSize(2), ...
        "Layout probe must render at the unchanged final physical size");
    assert_layout(result, metricHandle, figureHandle, ...
        fullfile(outputDirectory, figureId + "-before-export-geometry.json"));
    entry = oi_export_figure(figureHandle, outputDirectory, figureId, ...
        exportSize(1), exportSize(2), exportSize(3), ...
        "Title", options.Title, "Source", "synthetic comparison statistics regression", ...
        "Theme", theme.Name, "ExportSVG", true);
    assert(entry.rendering_evidence.clipped_count == 0 ...
        && entry.rendering_evidence.text_overlap_count == 0 ...
        && all(entry.rendering_evidence.normalized_margins >= 0), ...
        "Strict layout evidence must remain valid");
    assert_statistics(result, metricHandle);
    assert_presentation(result, axesHandle, originalParent, metricHandle, ...
        options.Title, theme, expectedLegendLocation, ...
        fullfile(outputDirectory, figureId + "-exported-properties.json"));
    assert_layout(result, metricHandle, figureHandle, ...
        fullfile(outputDirectory, figureId + "-exported-geometry.json"));
    assert_text_evidence(entry, axesHandle.Title, metricHandle);
    dataPixels = region_pixels(fullfile(outputDirectory, entry.exports.png.file), ...
        graphics_bounds(axesHandle, figureHandle), exportSize(1:2));
    assert(count_color(dataPixels, theme.LineColors(1, :)) > 0 ...
        && count_color(dataPixels, [0 0 0]) > 0, ...
        "test_comparison_statistics_layout:MissingDataPixels", ...
        "Exported data region must retain scatter markers and the 1:1 reference line");
    test_overlay_rejection(result, metricHandle, figureHandle, outputDirectory, ...
        figureId, theme, exportSize(3));
    assert_statistics(result, metricHandle);
    assert(isequaln(observations, originalObservations) && isequaln(models, originalModels), ...
        "Layout must not change the input observations or model values");
    if caseIndex == 1
        entries = entry;
    else
        entries(caseIndex) = entry;
    end
    clear cleanupFigure;
end
[~, entryOrder] = sort(string({entries.id}));
entries = entries(entryOrder);
oi_write_manifest(fullfile(outputDirectory, "figures.json"), entries);
fprintf("MATLAB_COMPARISON_STATISTICS_LAYOUT=passed\n");
fprintf("MATLAB_COMPARISON_STATISTICS_OUTPUT=%s\n", outputDirectory);
end

function assert_presentation(result, axesHandle, originalParent, metricHandle, titleText, theme, legendLocation, diagnosticPath)
handleChecks = struct("same_axes", isequal(result.Axes, axesHandle), ...
    "same_parent", isequal(axesHandle.Parent, originalParent), ...
    "native_legend", isgraphics(result.Legend, "legend"), ...
    "legend_location", string(result.Legend.Location) == legendLocation);
subtitleChecks = struct("native_subtitle", isequal(metricHandle, axesHandle.Subtitle), ...
    "separate_from_title", ~isequal(metricHandle, axesHandle.Title), ...
    "title_string", isequal(string(axesHandle.Title.String), titleText), ...
    "title_font_size", axesHandle.Title.FontSize == theme.TitleSize, ...
    "statistics_font_size", metricHandle.FontSize == theme.FontSize, ...
    "statistics_font_units", string(metricHandle.FontUnits) == "points", ...
    "statistics_color", isequal(metricHandle.Color, theme.TextColor), ...
    "statistics_visible", string(metricHandle.Visible) == "on", ...
    "statistics_background", isequal(string(metricHandle.BackgroundColor), "none"));
diagnostics = struct("release", version('-release'), ...
    "handle_conditions", handleChecks, "subtitle_conditions", subtitleChecks, ...
    "axes_class", class(axesHandle), "parent_class", class(axesHandle.Parent), ...
    "statistics_class", class(metricHandle), "subtitle_class", class(axesHandle.Subtitle), ...
    "title_string", string(axesHandle.Title.String), "expected_title", titleText, ...
    "title_font_size", axesHandle.Title.FontSize, "expected_title_font_size", theme.TitleSize, ...
    "statistics_font_size", metricHandle.FontSize, "expected_statistics_font_size", theme.FontSize, ...
    "statistics_font_units", string(metricHandle.FontUnits), ...
    "statistics_color", metricHandle.Color, "expected_statistics_color", theme.TextColor, ...
    "statistics_visible", string(metricHandle.Visible), ...
    "statistics_background", metricHandle.BackgroundColor, ...
    "legend_location", string(result.Legend.Location), "expected_legend_location", legendLocation, ...
    "axes_font_size", axesHandle.FontSize, "title_font_size_multiplier", axesHandle.TitleFontSizeMultiplier);
diagnostics.statistics_string = string(metricHandle.String);
write_diagnostics(diagnosticPath, diagnostics);
assert(all(structfun(@(condition) condition, handleChecks)), ...
    "test_comparison_statistics_layout:Handles", ...
    "Native axes and legend contracts failed: %s", jsonencode(diagnostics));
assert(all(structfun(@(condition) condition, subtitleChecks)), ...
    "test_comparison_statistics_layout:NativeSubtitle", ...
    "Native subtitle properties failed: %s", jsonencode(diagnostics));
assert(numel(findall(ancestor(axesHandle, "figure"), "Type", "axes")) == 1, ...
    "Statistics must not replace the data axes or introduce artificial coordinate axes");
end

function assert_layout(result, metricHandle, figureHandle, diagnosticPath)
metricBounds = oi_text_bounds(metricHandle, figureHandle);
dataBounds = graphics_bounds(result.Axes, figureHandle);
titleBounds = oi_text_bounds(result.Axes.Title, figureHandle);
legendBounds = graphics_bounds(result.Legend, figureHandle);
xlabelBounds = oi_text_bounds(result.Axes.XLabel, figureHandle);
ylabelBounds = oi_text_bounds(result.Axes.YLabel, figureHandle);
diagnostics = struct("release", version('-release'), "statistics", metricBounds, ...
    "data", dataBounds, "title", titleBounds, "legend", legendBounds, ...
    "xlabel", xlabelBounds, "ylabel", ylabelBounds, ...
    "figure_pixels", double(getpixelposition(figureHandle)), ...
    "axes_pixels", double(getpixelposition(result.Axes, true)));
write_diagnostics(diagnosticPath, diagnostics);
assert(all(metricBounds(1:2) >= 0) && all(metricBounds(1:2) + metricBounds(3:4) <= 1), ...
    "test_comparison_statistics_layout:ClippedStatistics", ...
    "All seven statistics items must remain inside the physical canvas");
assert_no_overlap(metricBounds, dataBounds, "DataOverlap");
assert(metricBounds(2) >= dataBounds(2) + dataBounds(4), ...
    "test_comparison_statistics_layout:StatisticsRegion", ...
    "Native subtitle must reserve space above the complete data rectangle");
assert_no_overlap(metricBounds, titleBounds, "TitleOverlap");
assert_no_overlap(metricBounds, legendBounds, "LegendOverlap");
assert_no_overlap(metricBounds, xlabelBounds, "XLabelOverlap");
assert_no_overlap(metricBounds, ylabelBounds, "YLabelOverlap");
fprintf("MATLAB_COMPARISON_STATISTICS_GEOMETRY=%s\n", jsonencode(diagnostics));
end

function write_diagnostics(filePath, diagnostics)
assert(~isfile(filePath), "test_comparison_statistics_layout:StaleDiagnostics", ...
    "Refusing to overwrite layout diagnostics");
[fileIdentifier, message] = fopen(filePath, "w");
assert(fileIdentifier >= 0, "test_comparison_statistics_layout:DiagnosticsFile", "%s", message);
fileCleanup = onCleanup(@() fclose(fileIdentifier));
fprintf(fileIdentifier, "%s\n", jsonencode(diagnostics));
clear fileCleanup;
end

function assert_no_overlap(firstBounds, secondBounds, identifier)
overlap = min(firstBounds(1:2) + firstBounds(3:4), secondBounds(1:2) + secondBounds(3:4)) ...
    - max(firstBounds(1:2), secondBounds(1:2));
assert(~all(overlap > 0), "test_comparison_statistics_layout:" + identifier, ...
    "Statistics overlap another region: statistics=%s, other=%s", ...
    mat2str(firstBounds, 17), mat2str(secondBounds, 17));
end

function assert_text_evidence(entry, titleHandle, metricHandle)
roles = string({entry.text_objects.role});
assert(nnz(roles == "title") == 1 && nnz(roles == "subtitle") == 1, ...
    "test_comparison_statistics_layout:TextEvidence", ...
    "Strict exporter must measure the native title and statistics subtitle separately");
titleEvidence = entry.text_objects(roles == "title");
metricEvidence = entry.text_objects(roles == "subtitle");
assert(string(titleEvidence.string) == strjoin(string(titleHandle.String), " ") ...
    && string(metricEvidence.string) == strjoin(string(metricHandle.String), " ") ...
    && metricEvidence.font_size == metricHandle.FontSize ...
    && ~titleEvidence.clipped && ~metricEvidence.clipped, ...
    "Title and complete statistics must remain in measured export evidence at their actual fonts");
end

function test_overlay_rejection(result, metricHandle, figureHandle, outputDirectory, figureId, theme, dpi)
backgrounds = {"none", result.Axes.Color};
for backgroundIndex = 1:numel(backgrounds)
    overlayHandle = text(result.Axes, 5, 5, metricHandle.String, ...
        "HorizontalAlignment", "center", "VerticalAlignment", "middle", ...
        "Interpreter", "none", "FontUnits", "points", "FontName", theme.FontName, ...
        "FontSize", theme.FontSize, "Color", theme.TextColor, ...
        "BackgroundColor", backgrounds{backgroundIndex}, "Margin", 4);
    overlayCleanup = onCleanup(@() delete(overlayHandle));
    negativePath = fullfile(outputDirectory, figureId + "-overlay-negative-" ...
        + string(backgroundIndex) + ".png");
    print(figureHandle, char(negativePath), "-dpng", char("-r" + string(dpi)));
    overlayBounds = oi_text_bounds(overlayHandle, figureHandle);
    dataBounds = graphics_bounds(result.Axes, figureHandle);
    assert_throws(@() assert_no_overlap(overlayBounds, dataBounds, "DataOverlap"), ...
        "test_comparison_statistics_layout:DataOverlap");
    clear overlayCleanup;
end
assert(isequal(find_metrics(result.Axes), metricHandle), ...
    "Overlay negatives must leave exactly one native statistics block");
end

function assert_throws(callback, identifier)
try
    callback();
catch errorDetails
    assert(string(errorDetails.identifier) == identifier, ...
        "Unexpected negative-test failure: %s", errorDetails.identifier);
    return;
end
error("test_comparison_statistics_layout:MissingError", ...
    "Expected overlapping statistics to fail with %s", identifier);
end

function metricHandle = find_metrics(axesHandle)
textHandles = findall(axesHandle, "Type", "text");
matches = false(size(textHandles));
for textIndex = 1:numel(textHandles)
    value = strjoin(string(textHandles(textIndex).String), newline);
    matches(textIndex) = contains(value, "Missing/QC rejected =") ...
        && contains(value, "Unmatched obs/model =");
end
assert(nnz(matches) == 1, "One complete statistics block must remain present");
metricHandle = textHandles(matches);
end

function assert_statistics(result, metricHandle)
assert(result.ValidCount == 4 && result.MissingCount == 1 && result.QCRejectedCount == 1 ...
    && result.UnmatchedObservationCount == 1 && result.UnmatchedModelCount == 1 ...
    && isequal(result.PairedMask, [true; true; true; false; true; false]), ...
    "Pairing, missing values, QC rejection and unmatched rows must remain unchanged");
assert(result.Metrics.PairedCount == 4 && abs(result.Metrics.Bias - 1.75) < 1e-12 ...
    && abs(result.Metrics.MAE - 1.75) < 1e-12 && abs(result.Metrics.RMSE - 3.5) < 1e-12, ...
    "Layout must preserve the paired statistics");
correlation = corrcoef([0; 2; 5; 10], [0; 9; 5; 10]);
assert(abs(result.Metrics.Correlation - correlation(1, 2)) < 1e-12);
expectedItems = ["N = 4"; "Bias = 1.75 degC"; "MAE = 1.75 degC"; ...
    "RMSE = 3.5 degC"; "r = " + compose("%.3f", correlation(1, 2)); ...
    "Missing/QC rejected = 1/1"; "Unmatched obs/model = 1/1"];
actualLines = string(metricHandle.String);
actualItems = split(strjoin(actualLines, "; "), "; ");
assert(numel(actualLines) == 3 && isequal(actualItems(:), expectedItems), ...
    "All seven unchanged statistics items must remain visible in three native layout rows");
assert(numel(result.Scatter) == 1 ...
    && isequal(result.Scatter.XData(:), [0; 2; 5; 10]) ...
    && isequal(result.Scatter.YData(:), [0; 9; 5; 10]) ...
    && string(result.Scatter.Visible) == "on" ...
    && isequal(result.OneToOne.XData, result.Limits) ...
    && isequal(result.OneToOne.YData, result.Limits) ...
    && string(result.OneToOne.Visible) == "on", ...
    "Statistics layout must not move or remove data or the 1:1 reference line");
assert(isequal(result.Limits, [-0.5 10.5]) ...
    && isequal(result.Axes.XLim, result.Limits) && isequal(result.Axes.YLim, result.Limits) ...
    && isequal(result.Axes.DataAspectRatio, [1 1 1]), ...
    "Layout must not extend scientific limits to invent empty data space or distort agreement");
end

function bounds = graphics_bounds(graphicsHandle, figureHandle)
figurePixels = double(getpixelposition(figureHandle));
objectPixels = double(getpixelposition(graphicsHandle, true));
bounds = [(objectPixels(1:2) - 1) ./ figurePixels(3:4), ...
    objectPixels(3:4) ./ figurePixels(3:4)];
assert(all(isfinite(bounds)) && all(bounds(3:4) > 0), ...
    "Graphics must have finite positive measured bounds");
end

function pixels = region_pixels(filePath, bounds, exportSize)
[imageData, colorMap] = imread(filePath);
width = exportSize(1);
height = exportSize(2);
assert(size(imageData, 1) == height && size(imageData, 2) == width, ...
    "Raster checks require the unchanged requested export dimensions");
if isempty(colorMap)
    pixels = double(imageData);
    if isinteger(imageData)
        pixels = pixels / double(intmax(class(imageData)));
    end
else
    indices = double(imageData);
    if isinteger(imageData)
        indices = indices + 1;
    end
    pixels = reshape(colorMap(indices(:), :), [size(imageData, 1) size(imageData, 2) 3]);
end
columns = (ceil(bounds(1) * width) + 1):floor((bounds(1) + bounds(3)) * width);
rows = (ceil((1 - bounds(2) - bounds(4)) * height) + 1):floor((1 - bounds(2)) * height);
assert(~isempty(rows) && ~isempty(columns) && rows(1) >= 1 && rows(end) <= height ...
    && columns(1) >= 1 && columns(end) <= width, "Data pixel region must be inside the canvas");
pixels = pixels(rows, columns, :);
end

function count = count_color(pixels, color)
distance = max(abs(pixels - reshape(color, 1, 1, 3)), [], 3);
count = nnz(distance <= 2 / 255);
end

function close_if_valid(figureHandle)
if isgraphics(figureHandle)
    close(figureHandle);
end
end
