function [figureHandle, result] = astra_comparison_trial(fixturePath)
%ASTRA_COMPARISON_TRIAL Construct the synthetic paired comparison in MATLAB.
% Caller supplies the repository assets on the MATLAB path and owns the
% returned invisible figure. No files are written; construction errors rethrow.
arguments
    fixturePath (1,1) string
end

assert(~verLessThan('matlab', '9.10'), ...
    'astra_comparison_trial:UnsupportedRelease', 'MATLAB R2021a or newer is required.');
assert(license('test', 'MATLAB') && ~isempty(which('figure')), ...
    'astra_comparison_trial:RuntimeUnavailable', 'MATLAB base graphics must be available.');
helpers = ["oi_figure", "oi_plot_comparison", "oi_font_available"];
for index = 1:numel(helpers)
    assert(~isempty(which(char(helpers(index)))), ...
        'astra_comparison_trial:MissingHelper', ...
        'Add the repository assets to the MATLAB path: %s', helpers(index));
end
assert(isfile(fixturePath), 'astra_comparison_trial:MissingInput', ...
    'The supplied fixturePath must identify an existing JSON file.');
fixtureText = fileread(fixturePath);
fixture = jsondecode(fixtureText);
assert(isstruct(fixture) && isscalar(fixture) ...
    && all(isfield(fixture, {'schema_version','kind','synthetic','title','contract','records'})), ...
    'astra_comparison_trial:InvalidFixture', 'Expected the paired-record fixture object.');
assert(fixture.schema_version == 1 && string(fixture.kind) == "paired_records" ...
    && islogical(fixture.synthetic) && isequal(fixture.synthetic, true), ...
    'astra_comparison_trial:InvalidFixture', 'This trial requires the synthetic paired-record schema.');
assert(ischar(fixture.title) && isrow(fixture.title) && ~isempty(strtrim(fixture.title)), ...
    'astra_comparison_trial:InvalidFixture', 'The original fixture title must be nonempty text.');
contract = fixture.contract;
requiredContract = {'time_zone','depth_direction','observation_unit','model_unit', ...
    'uncertainty_type','uncertainty_unit','missing_policy','qc_policy','stable_id_field'};
assert(isstruct(contract) && isscalar(contract) && all(isfield(contract, requiredContract)), ...
    'astra_comparison_trial:ScientificContract', 'Required scientific metadata are missing.');
assert(string(contract.time_zone) == "UTC" ...
    && string(contract.depth_direction) == "positive_down" ...
    && string(contract.observation_unit) == "degC" ...
    && string(contract.model_unit) == "degC" ...
    && string(contract.uncertainty_unit) == "degC" ...
    && string(contract.uncertainty_type) == "standard_uncertainty" ...
    && string(contract.missing_policy) == "preserve" ...
    && string(contract.qc_policy) == "preserve" ...
    && string(contract.stable_id_field) == "id", ...
    'astra_comparison_trial:ScientificContract', 'Unsupported or conflicting fixture semantics.');

records = fixture.records;
requiredFields = {'id','time','depth_m','observation_degC','model_degC','uncertainty_degC','qc'};
assert(isstruct(records) && iscolumn(records) && ~isempty(records) ...
    && all(isfield(records, requiredFields)), ...
    'astra_comparison_trial:InvalidRecords', 'Expected a nonempty column of complete record objects.');
recordCount = numel(records);
ids = strings(recordCount, 1);
timeText = strings(recordCount, 1);
qc = strings(recordCount, 1);
observations = NaN(recordCount, 1);
modelValues = NaN(recordCount, 1);
observationUncertainty = NaN(recordCount, 1);
depth = NaN(recordCount, 1);
for sourceRow = 1:recordCount
    row = records(sourceRow);
    ids(sourceRow) = record_text(row.id);
    timeText(sourceRow) = record_text(row.time);
    qc(sourceRow) = record_text(row.qc);
    observations(sourceRow) = record_number(row.observation_degC, true);
    modelValues(sourceRow) = record_number(row.model_degC, true);
    observationUncertainty(sourceRow) = record_number(row.uncertainty_degC, true);
    depth(sourceRow) = record_number(row.depth_m, false);
end
assert(numel(unique(ids)) == recordCount && all(depth >= 0), ...
    'astra_comparison_trial:InvalidMetadata', 'IDs must be unique and depths nonnegative.');
assert(all(ismember(qc, ["good", "suspect", "missing"])) ...
    && all(observationUncertainty(~isnan(observationUncertainty)) >= 0), ...
    'astra_comparison_trial:InvalidQuality', 'Unknown QC flag or negative standard uncertainty.');
assert(all((qc == "missing") == isnan(observations)) ...
    && ~any(isnan(observations) & ~isnan(observationUncertainty)), ...
    'astra_comparison_trial:InvalidQuality', 'Observation missingness, QC and uncertainty disagree.');
timeFormat = "yyyy-MM-dd'T'HH:mm:ss'Z'";
time = datetime(timeText, 'InputFormat', timeFormat, 'TimeZone', contract.time_zone);
time.Format = timeFormat;
assert(all(~isnat(time)) && all(string(time) == timeText) ...
    && all(diff(time) >= seconds(0)), ...
    'astra_comparison_trial:InvalidTime', 'Preserve the nondecreasing, full-second UTC record times.');
% Repeated times are distinct depth records; pairing uses original rows and IDs.
recordMetadata = struct('ID', ids, 'Time', time, 'Depth', depth, ...
    'DepthUnit', "m", 'DepthDirection', string(contract.depth_direction));
scientificDataContract = struct('shape', size(records), ...
    'dimensionOrder', ["record", "singleton"], 'observationDimension', "record", ...
    'dataType', "struct", 'numericDataType', "double", ...
    'variables', ["observation_degC", "model_degC", "uncertainty_degC"], ...
    'units', ["degC", "degC", "degC"], 'quantity', "synthetic temperature", ...
    'unitConversion', "none", 'sourceContract', contract);
scientificDataContract.coordinates = struct('Time', time, 'TimeZone', "UTC", ...
    'TimeOrder', "source order; nondecreasing; repeated times at distinct depths", ...
    'Depth', depth, 'DepthType', "depth", 'DepthUnit', "m", ...
    'DepthDirection', "positive_down", 'DepthReference', "not provided; metadata only", ...
    'HorizontalCoordinates', "not provided");
scientificDataContract.missing = struct('status', "present", ...
    'representation', "JSON null to MATLAB NaN, row by row", ...
    'ObservationMask', isnan(observations), 'ModelMask', isnan(modelValues), ...
    'UncertaintyMask', isnan(observationUncertainty));
scientificDataContract.qc = struct('status', "present", 'variable', "qc", ...
    'alignmentDimension', "record", 'flags', qc, ...
    'meanings', "good: accepted; suspect: retained, not certified good; missing: unavailable", ...
    'SuspectMask', qc == "suspect", 'MissingMask', qc == "missing", ...
    'InvalidMask', false(recordCount, 1), 'ModelStatus', "not_provided");
scientificDataContract.uncertainty = struct('status', "present", ...
    'variable', "uncertainty_degC", 'type', "standard-uncertainty", ...
    'unit', "degC", 'alignmentDimension', "record", 'ModelStatus', "not_provided");

figureHandle = oi_figure(1000, 850, "off");
try
    figureHandle.Units = 'inches';
    figureHandle.Position(3:4) = [10, 8.5];
    figureHandle.Name = fixture.title;
    figureHandle.NumberTitle = 'off';
    theme = getappdata(figureHandle, 'OI_OceanTheme');
    % Match theme selection's availability policy; rendering still needs verification.
    assert(oi_font_available(theme.FontName), ...
        'astra_comparison_trial:FontUnavailable', 'The selected font must satisfy the repository availability policy.');
    axesHandle = axes('Parent', figureHandle, 'Units', 'normalized', ...
        'OuterPosition', [0.04, 0.04, 0.92, 0.92], ...
        'PositionConstraint', 'outerposition', 'FontUnits', 'points');
    options = struct('QuantityUnit', string(contract.observation_unit), ...
        'ObservationLabel', "Observation temperature", 'ModelLabel', "Model temperature", ...
        'Title', fixture.title, 'Theme', theme, 'LegendLocation', "southoutside", ...
        'MissingPolicy', string(contract.missing_policy), ...
        'RecordMetadata', recordMetadata, 'SampleLabels', ids, ...
        'ObservationQC', qc, 'AcceptedQCValues', ["good", "suspect"], ...
        'UncertaintySides', "observation", 'ObservationUncertainty', observationUncertainty, ...
        'UncertaintyType', "standard-uncertainty", ...
        'UncertaintyUnit', string(contract.uncertainty_unit));
    setappdata(figureHandle, 'ASTRA_FixtureJSON', fixtureText);
    setappdata(figureHandle, 'requireScientificContract', true);
    setappdata(figureHandle, 'scientific_data_contract', scientificDataContract);
    result = oi_plot_comparison(axesHandle, observations, modelValues, options);
    drawnow;
catch constructionError
    if isgraphics(figureHandle, 'figure')
        delete(figureHandle);
    end
    rethrow(constructionError);
end
end

function value = record_number(raw, allowMissing)
% jsondecode can represent a null scalar as [] or NaN; retain its source row.
if isnumeric(raw) && isreal(raw) && (isempty(raw) || (isscalar(raw) && isnan(raw)))
    assert(allowMissing, 'astra_comparison_trial:InvalidNumber', ...
        'This coordinate must not be missing.');
    value = NaN;
    return;
end
assert(isnumeric(raw) && isreal(raw) && isscalar(raw) && isfinite(raw), ...
    'astra_comparison_trial:InvalidNumber', 'Expected a finite real scalar or declared null.');
value = double(raw);
end

function value = record_text(raw)
assert(ischar(raw) && isrow(raw) && ~isempty(strtrim(raw)), ...
    'astra_comparison_trial:InvalidText', 'Expected nonblank record text.');
value = string(raw);
end
